### ISSUE TITLE
Failed to join room on invite over federation.

### ISSUE THREAD

**Issue by neilisfragile** [matrix-org/dendrite#1023]
I tried to invite @neilj:dendrite.neilalexander.dev into a private room from my matrix.org account (@neilj:matrix.org) at approx 11:50 BST 20200512

The invite appeared on the client but on trying to join I received the following.

<img width="798" alt="Screenshot 2020-05-12 at 11 55 22" src="https://user-images.githubusercontent.com/451032/81676788-44bcc700-9448-11ea-8522-3c207917fdbc.png">

**Comment by neilalexander** [comment]
Relevant logs:
```
May 12 10:54:53 photon-machine docker-compose[129624]: dendrite_monolith | time="2020-05-12T10:54:53.226166983Z" level=info msg="Incoming request" func="RequestWithLogging\n\t" file=" [/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:122]" req.id=3nA2prDd4XQr req.method=POST req.path="/_matrix/client/r0/join/!zVpPeWAObqutioiNzB:jki.re"
May 12 10:54:53 photon-machine docker-compose[129624]: dendrite_monolith | time="2020-05-12T10:54:53.243313261Z" level=error msg="processRoomEvent.checkAuthEvents failed for event" func="processRoomEvent\n\t" file=" [/build/roomserver/internal/input_events.go:57]" auth_event_ids="[$VnU0XEK6VPvVIF2dYia3VEM4geCQ/crydE3oMUbkgzg $35+fT1q6wSJ5sasnSGkrqKNZGiKQ58UFpxylvRnyMVI $VwZY3if3+/rKgEzJMyjVaDeQFs0xLzph6sGjHEzLn2E]" error="eventauth: \"@neilj:dendrite.neilalexander.dev\" is not allowed to change their membership from \"leave\" to \"join\"" event_id="$WIaybN6lQsDZJEiGE1Jc/PTW8YGXk7Iu4U0vi2fAxcE"
May 12 10:54:53 photon-machine docker-compose[129624]: dendrite_monolith | time="2020-05-12T10:54:53.243499261Z" level=info msg="Responding (170 bytes)" func="respond\n\t" file=" [/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:170]" code=400 req.id=3nA2prDd4XQr req.method=POST req.path="/_matrix/client/r0/join/!zVpPeWAObqutioiNzB:jki.re"
```

**Comment by Half-Shot** [comment]
I did a bit of sleuthing out of curiosity:

It looks like dendrite believes the room is local, becaue it's trying to checkAuthEvents before it tries any sort of federated join (https://github.com/matrix-org/dendrite/blob/9b1b095b495a5cd4a6494bc309dd8c4e92d8661f/roomserver/internal/perform_join.go#L140-L143).

Dendrite isn't actually joined to !zVpPeWAObqutioiNzB:jki.re though from what I can see, so it's probably missing room state, which is probably what causes the error.

**Comment by neilalexander** [comment]
@Half-Shot You're half-right (no pun intended!) — the issue is that my Dendrite *was* once joined to that room and the room state hasn't been updated to reflect the new invite state. So the problem is sorta two-fold:

1. The room state should have been updated to reflect the new `invite` member event (but for some reason wasn't);
2. The perform API should try to be a bit more intelligent in this instance.

**Comment by Half-Shot** [comment]
Ahhh, this sounds about right. On first invite, Dendrite isn't joined to the room so does the federation API calls as usual and all is well. But on the second invite, Dendrite expects it's own state to be up to date but since there aren't any users in the room, it won't have gotten any transactions from other homeservers to update it's own internal state.

I guess you could either do a federated join if no users are joined to the room, or as you said, just insert the state into the room when you get an invite.

**Comment by Half-Shot** [comment]
Synapse appears to do the first option (of joining over federation if it has no members in the room):

- https://github.com/matrix-org/synapse/blob/master/synapse/handlers/room_member.py#L427-L456
- https://github.com/matrix-org/synapse/blob/master/synapse/handlers/room_member.py#L842-L863

**Comment by neilalexander** [comment]
I think what we're probably going to have to do is to consult the invites table first to see if we're responding to an invite and do a federated join special case.

I've [inspected my view of the room state](https://github.com/matrix-org/dendrite/wiki/Useful-Database-Queries#get-current-room-state) and it doesn't show the invite in the membership event (as expected it still shows `leave`). I suppose the difficulty is that if we try and update the room state with a new invite after a period of being out of the room then we are into the realm of caring about `auth_events` etc from our period away from the room.

**Comment by Half-Shot** [comment]
> I suppose the difficulty is that if we try and update the room state with a new invite after a period of being out of the room then we are into the realm of caring about auth_events etc from our period away from the room.

Yep, that's what I'm afraid of. And you can't just ask for missing events, because you're not in the room *yet*.
