### ISSUE TITLE
Request pools need some rethinking

### ISSUE THREAD

**Issue by neilalexander** [matrix-org/dendrite#1078]
Up until now, it’s been rather binary if a sync request returns straight away or if we wait for the time specified in the request. This has worked because of the limited feature support in the sync API.

Now that we’re starting to add more things into the mix, like send-to-device messages and account data, we need to rethink the logic of the request pools so that we can more intelligently decide when to return. We will also need this for things like push rules, presence, device lists and one-time keys to work properly.

The notifiers are a bit clunky and we don’t really have any escape hatch mechanism to start a task at the beginning of the sync and let it interrupt and return faster, so some work is needed here to remodel it into something better.

**Comment by Kegsay** [comment]
Did your refactor fix this?

**Comment by neilalexander** [comment]
Yes, should have done.
