### ISSUE TITLE
p2p dendrite may fail to talk full mesh due to libp2p limiting the number of accessible peers?

### ISSUE THREAD

**Issue by ara4n** [matrix-org/dendrite#1085]
I don't have much to back this up, but we seem to be having more splitbrains than expected. I'm wondering if libp2p limits the number of adjacent peers you can peer with (by default), so that if you have (say) 40 nodes on the network, you can only actually talk to a max of 10 at a time?  (Which would be fine if the other peers could route transitively to other peers, but that's not hooked up)?

Alternatively, the splitbrains may be due to the rz server getting completely overloaded.

**Comment by ara4n** [comment]
also, the fact that the 'connected peers' and 'discovered peers' counters are untrustworthy doesn't help understand what's going on.

**Comment by Kegsay** [comment]
https://github.com/matrix-org/go-http-js-libp2p/blob/master/js/browser-bundle.js#L91 may help, but I never seem to be connected to that many. My logs:
```
Connected peers:  50  Discovered peers:  2126  Found providers:  [ ... ] (20)
```
So there probably is a config option somewhere to increase this, but the extra load this will add would be disasterous given #1086

**Comment by ara4n** [comment]
So if you're only connected to 20, will it silently fail if it tries to talk to any of the rest?

**Comment by Kegsay** [comment]
I don't know. Peer discovery should still work in that if you give it a peer ID it should still find a path, but the public room list will be very inconsistent (as it will depend which 20 peers it speaks to).
