### ISSUE TITLE
Investigate signature error joining Matrix HQ

### ISSUE THREAD

**Issue by neilalexander** [matrix-org/dendrite#1132]
Trying to join Matrix HQ resulted in a signature error:

`joinCtx.CheckSendJoinResponse: respSendJoin: Bad signature from "michel-slm.name" with ID "ed25519:0"`

Need to investigate why that is, as apparently Synapse isn’t unhappy with it.

**Comment by Kegsay** [comment]
@neilalexander is this resolved?

**Comment by neilalexander** [comment]
I tried to join HQ today and was unable to. Not sure if it's the same issue - I'll try it again tomorrow.

**Comment by neilalexander** [comment]
This should be fixed by matrix-org/gomatrixserverlib#213.
