### ISSUE TITLE
how to setup and run p2p version

### ISSUE THREAD

**Issue by bitcard** [matrix-org/dendrite#1175]
does the p2p version based  on libp2p? is there a guide to setup and run p2p version? thanks.

**Comment by Kegsay** [comment]
https://github.com/matrix-org/dendrite/blob/master/build/docker/DendriteJS.Dockerfile

It hasn't been tested recently so it may require additional database configuration options.

**Comment by bitcard** [comment]
> https://github.com/matrix-org/dendrite/blob/master/build/docker/DendriteJS.Dockerfile
> 
> It hasn't been tested recently so it may require additional database configuration options.

thanks for your reply. 

this solution seem to run dendrite in browser.

because of there are many kind of client, like mobile, IoT etc,  I think some of client is difficult to run dendrite, so I hope dendrite run dendrite homeserver with p2p mode, the client connect to p2p homeserver.

**Comment by Kegsay** [comment]
We're not there yet. The closest will be Neil's work on a Yggdrasil demo which will then hopefully work on both mobile and web. All of these things are experiments though, rather than an official maintained thing. It will be a long time before we actually settle on a p2p approach we want to use for Matrix.

**Comment by bitcard** [comment]
> Yggdrasil demo

thank you, I will try the Yggdrasil demo.

**Comment by Kegsay** [comment]
FYI that demo is still in active development, but I think @neilalexander has got it mostly there.

**Comment by maverick74** [comment]
@Kegsay sorry for bringing this bug back from the dead but i didn't wanted to open a new one:

is there a (meta) bug (or something else) somewhere where we can follow the developments of a p2p matrix?
I ask this because i don't find as much info as i would like to on the matrix blog...

Tks
