### ISSUE TITLE
how to config Riot client url with dendrite-demo-libp2p?

### ISSUE THREAD

**Issue by bitcard** [matrix-org/dendrite#1184]
I want run dendrite homeserver with p2p mode,  if I understant is ok, the p2p homeserver connect each other, like IPFS. the Riot or other client can connect to dendrite-demo-libp2p(may be Riot client need to upgrade to support connect to dendrite-demo-libp2), so that users don't need to trust a particular server in order use matrix.

I  run bin/dendrite-demo-libp2p
```
Our node ID: 12D3KooWS3FqnDv4g5X7vs98Ykrkd9GhuzcmP4zHXwUcJfaSw2MH
Our addresses: [/ip6/::1/tcp/62355 /ip6/240e:82:b00:aa9c:180e:8624:d3cc:e28d/tcp/62355 /ip6/240e:82:b00:aa9c:35fa:bb60:4105:c371/tcp/62355 /ip4/127.0.0.1/tcp/62354 /ip4/192.168.1.175/tcp/62354]
Running in libp2p federation mode
Warning: Federation with non-libp2p homeservers will not work in this mode yet!
INFO[2020-07-05T18:55:29.030522000Z] [/Users/go/dendrite/cmd/dendrite-demo-libp2p/main.go:206] func1
	 Listening on :8080                           
INFO[2020-07-05T18:55:29.030527000Z] [/Users/go/dendrite/cmd/dendrite-demo-libp2p/main.go:212] func2
	 Listening on libp2p host ID 12D3KooWS3FqnDv4g5X7vs98Ykrkd9GhuzcmP4zHXwUcJfaSw2MH 
```
it seem the p2p homeserver go live. how to config the Riot client to connect it?  

I also compile the project: https://github.com/matrix-org/libp2p-proxy.  what's relationship dendrite-demo-libp2p and libp2p-proxy, they can work together?  or dendrite-monolith-server and libp2p-proxy work together?

because of there are many kind of client, like mobile, IoT etc, I think some of client is difficult to run dendrite, so I hope dendrite run with p2p mode,  all kind of client connect to p2p dendrite homeserver.

thanks.

**Comment by neilalexander** [comment]
In your output, the salient line is:
```
INFO[2020-07-05T18:55:29.030522000Z] [/Users/go/dendrite/cmd/dendrite-demo-libp2p/main.go:206] func1
Listening on :8080
```
... which is telling you to point your Riot client to your local machine on port 8080, e.g. `http://localhost:8080` as the homeserver URL. You can then register an account normally.

If you want to specify a different port to listen on, you can give the `-port 12345` option when starting `dendrite-demo-libp2p`. 

Note that, right now, the libp2p demo is currently only able to talk to other instances of the libp2p demo on the same network. If you want global reachability across a wider network then you might want to look at `dendrite-demo-yggdrasil` instead (giving a [peer URI](https://publicpeers.neilalexander.dev/) to the `-peer` command line option) or instead look at `dendritejs` and the [p2p.riot.im](https://p2p.riot.im) demo.

**Comment by bitcard** [comment]
> In your output, the salient line is:
> 
> ```
> INFO[2020-07-05T18:55:29.030522000Z] [/Users/go/dendrite/cmd/dendrite-demo-libp2p/main.go:206] func1
> Listening on :8080
> ```
> 
> ... which is telling you to point your Riot client to your local machine on port 8080, e.g. `http://localhost:8080` as the homeserver URL. You can then register an account normally.
> 
> If you want to specify a different port to listen on, you can give the `-port 12345` option when starting `dendrite-demo-libp2p`.
> 
> Note that, right now, the libp2p demo is currently only able to talk to other instances of the libp2p demo on the same network. If you want global reachability across a wider network then you might want to look at `dendrite-demo-yggdrasil` instead (giving a [peer URI](https://publicpeers.neilalexander.dev/) to the `-peer` command line option) or instead look at `dendritejs` and the [p2p.riot.im](https://p2p.riot.im) demo.

thank you for reply so quickly, I will try the dendrite-demo-yggdrasil and dendritejs
