### ISSUE TITLE
I found the lecture video about p2p matrix: https://av.tib.eu/media/47310

### ISSUE THREAD

**Issue by bitcard** [matrix-org/dendrite#1195]
in the video, Experiment 2: the cmd/dendrite-demo-libp2p seems can run successfully. is there a document to guide compile  and run it?  thanks.

**Comment by neilalexander** [comment]
It still works, install Go 1.13 and run `go run ./cmd/dendrite-demo-libp2p` from the root of the Dendrite repository.

**Comment by bitcard** [comment]
> It still works, install Go 1.13 and run `go run ./cmd/dendrite-demo-libp2p` from the root of the Dendrite repository.

thanks for your reply so quickly. 

after run ./cmd/dendrite-demo-libp2p, then how to config Riot web to chat? does use ios and android can use it chat?

**Comment by neilalexander** [comment]
The default is to listen on port 8080, so just configure Riot to use `http://localhost:8080` as the homeserver. You can then register and create an account as normal. 

Be aware that this demo only works on a local network - you’d need the demo running on another machine to see it in action. If you want to try something that works over the Internet then try `dendrite-demo-yggdrasil` instead or the in-browser libp2p demo at https://p2p.riot.im/.

**Comment by bitcard** [comment]
> The default is to listen on port 8080, so just configure Riot to use `http://localhost:8080` as the homeserver. You can then register and create an account as normal.
> 
> Be aware that this demo only works on a local network - you’d need the demo running on another machine to see it in action. If you want to try something that works over the Internet then try `dendrite-demo-yggdrasil` instead or the in-browser libp2p demo at https://p2p.riot.im/.

thank you, I will try it with another machine and dendrite-demo-yggdrasil.
