### ISSUE TITLE
Components should all go via federationsender for outbound federation calls

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/dendrite#1211]
Rather than doubling the API surface and having proxy functions in `federationsender` for all `FederationClient` functions, just:
- Make FederationClient an interface in GMSL
- Make federationsender implement that interface in its interface (which does proxy calls and stats/metrics)
- components use the FederationClient interface if they just want a dumb proxy, else the FS function if they need a bit more magic e.g `PerformJoin` does a bunch of extra work.

**Comment by neilalexander** [comment]
Some justifications for this are:

- tracking statistics/backoff, blacklisting
- having a single place where we can drop requests in order to satisfy server ACLs
- allowing us to put the `federationapi` and `federationsender` into a DMZ in a secure deployment
- P2P protocol stuff in one place

**Comment by Kegsay** [comment]
The groundwork for this was done in https://github.com/matrix-org/dendrite/pull/1284 - just need to add any missing functions which are needed on an ad-hoc basis. This issue is resolved.
