### ISSUE TITLE
Internal API optimisations

### ISSUE THREAD

**Issue by neilalexander** [matrix-org/dendrite#1260]
In polylith mode we're likely to make a lot of HTTP requests between components, especially as we add more functionality. We should examine, at some point in the future, if we can optimise these.

Some things to consider:

- Aggressive reuse of HTTP connections (and/or HTTP/2?)
- QUIC?
- Some faster encoding than JSON?

**Comment by neilalexander** [comment]
https://github.com/json-iterator/go#benchmark might be interesting to look at for JSON encoding/decoding performance.

**Comment by Kegsay** [comment]
I'd like to also track the number of internal calls we make e.g via prometheus, so we can quickly spot code paths which can be optimised.

**Comment by kegsay** [comment]
Internal APIs are dead. Long live monolith!
