### ISSUE TITLE
Implement whois

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/dendrite#1306]
Spec: https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-r0-admin-whois-userid
Sytests:
```
    × /whois
```

**Comment by DavidSpenler** [comment]
I can work on this

**Comment by MadLittleMods** [comment]
It looks like https://github.com/matrix-org/dendrite/pull/1573 is merged now so closing this issue.
