### ISSUE TITLE
Fix issues around /roomId/members

### ISSUE THREAD

**Issue by kegsay** [matrix-org/dendrite#1308]
Spec: https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-r0-rooms-roomid-members
Sytests:
```
    × Can get rooms/{roomId}/members at a given point
    × Can filter rooms/{roomId}/members
```

**Comment by Grotax** [comment]
So I investigated the first API endpoint.
I guessed that
https://github.com/matrix-org/dendrite/blob/master/clientapi/routing/memberships.go#L60
needs to be extended with an "At" and passing it though from the client request.
So I ended up at 
https://github.com/Grotax/dendrite/blob/master/roomserver/storage/interface.go#L129

But I guess then the At would need to be implemented for each DB implementation.

I think it makes sense to only query the data in the DB we actually need but I'm not a 100% sure.
So I'm just gonna leave this here for now.

**Comment by akhil-dh1** [comment]
@Kegsay @Grotax I would like to work on this issue. I am new to Matrix and I am not familiar with its codebase. It would be great if anyone could provide me some pointers on how to begin fixing this issue.

**Comment by alam0rt** [comment]
@kegsay  - been also taking a look at this, quite new to Matrix (codebase wise).

Looking at how `GetMembershipEventNIDsForRoom()` is implemented, I'm not really sure how to take the provided `at` and filter events using it.

Forgive the horror within https://github.com/matrix-org/dendrite/pull/2041, but any pointers would be great. Keen to implement.

**Comment by kegsay** [comment]
Still failing as of today.

**Comment by ShadowJonathan** [comment]
And as of today, while converting the test to complement

**Comment by S7evinK** [comment]
Implemented as of https://github.com/matrix-org/dendrite/pull/2827
