### ISSUE TITLE
Fix failing room state endpoints (setting state twice)

### ISSUE THREAD

**Issue by kegsay** [matrix-org/dendrite#1329]
Sytests:
```
    × Setting state twice is idempotent
```

**Comment by MadLittleMods** [comment]
Looks related to https://github.com/matrix-org/dendrite/issues/1311

**Comment by piyushsingariya** [comment]
Is this issue still open? Can I have a look over this?

**Comment by MadLittleMods** [comment]
Go for it @piyushsingariya!

**Comment by piyushsingariya** [comment]
@MadLittleMods Can you explain to me a bit about this issue? as I am new and having a hard time understanding Dendrite's issues and its codebase. It would be helpful if you could guide me.
Thanks in advance :)

**Comment by keremgocen** [comment]
hey @piyushsingariya were you able to progress on this one? I can try to help if you need any or I'm also happy to take a look myself, looking for a #good-first-issue to get myself familiarised with this dendrite.

**Comment by piyushsingariya** [comment]
yeah go ahead @keremgocen , I'm not focusing on this.

**Comment by keremgocen** [comment]
I'm looking at this and left a comment [here](https://github.com/matrix-org/dendrite/pull/1539/files#r667537781). It's not obvious to me what should be the fix;
- should I look at https://github.com/matrix-org/dendrite/blob/master/clientapi/routing/joinroom.go and check if the user is already joined somehow
- or it's about the event being returned and the new event returned must have a different id here https://github.com/matrix-org/dendrite/blob/master/clientapi/routing/sendevent.go

Not sure how the 2nd event ends up having the same id, when I look at the failing test code here: https://github.com/matrix-org/sytest/blob/master/tests/30rooms/01state.pl#L287

Any guidance would be helpful as this is my first issue, thanks.

**Comment by Tert0** [comment]
I get
```
Test 137 Setting state twice is idempotent... EXPECTED FAIL
```
as output for SyTests.

Does that mean that it works?

**Comment by kegsay** [comment]
No, you need it to be `... OK`

**Comment by ParthGala2k** [comment]
Hello, I plan to apply to matrix for the dendrite project as part of GSoC this year and was looking to familiarise myself with the codebase.
If no one is looking at this issue, is it okay if I have a go at it ?

**Comment by kegsay** [comment]
Still failing as of today: `2022-05-20T11:37:09.7789547Z     Test 594 outliers whose auth_events are in a different room are correctly rejected... EXPECTED FAIL`

**Comment by kegsay** [comment]
Still failing as of today: `2022-05-20T11:38:39.9370342Z     ❌ Setting state twice is idempotent`

**Comment by S7evinK** [comment]
Fixed in https://github.com/matrix-org/dendrite/pull/2512
