### ISSUE TITLE
Fix failing ban tests

### ISSUE THREAD

**Issue by kegsay** [matrix-org/dendrite#1331]
Sytests:
```
    × Remote banned user is kicked and may not rejoin until unbanned
```

**Comment by oliverpool** [comment]
```
× Remote banned user is kicked and may not rejoin until unbanned
```
Probably a sytest issue (see https://github.com/matrix-org/sytest/issues/940)

**Comment by DavidSpenler** [comment]
I can work on this.

**Comment by gavinr** [comment]
Should this be closed since #1884 was merged?

**Comment by kegsay** [comment]
`Remote banned user is kicked and may not rejoin until unbanned` still fails, so will update this issue.

**Comment by kegsay** [comment]
`2022-05-20T11:33:34.4785334Z     Test 181 Remote banned user is kicked and may not rejoin until unbanned... OK` - it's fixed!
