### ISSUE TITLE
Fix /joined_members failing sytest

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/dendrite#1332]
```
    × /joined_members return joined members
```

**Comment by Half-Shot** [comment]
I'd like to have a go at this one, where can I find the logs for the failing test so I can investigate it?

**Comment by Kegsay** [comment]
Any CI build will do, e.g https://buildkite.com/matrix-dot-org/dendrite/builds/3127#084c4023-62e8-4bce-8520-e948926ddc0d/634-962 - download the artifacts to find logs. `results.tap` contains perl logs (look for `not ok 269`) and the logs will likely be in `server-0/dendrite-logs/Monolith.log`
