### ISSUE TITLE
Redo notifier and streams

### ISSUE THREAD

**Issue by kegsay** [matrix-org/dendrite#1356]
This code has grown organically which makes it hellish to work with. We want:
 - common functions for working with streams (diffs, catchup, filtering, tokens)
 - notifier which works with that interface

Look into pure Go pubsub impls?

**Comment by kegsay** [comment]
@neilalexander I think you did this refactor?

**Comment by neilalexander** [comment]
Yes, this was done in my gargantuan sync API change.
