### ISSUE TITLE
media_api.max_file_size_bytes = 0 (unlimited) actually truncates uploads to 0 bytes

### ISSUE THREAD

**Issue by Francesco149** [matrix-org/dendrite#1361]
it seems like there's no check here https://github.com/matrix-org/dendrite/blob/3802efe3011cde7df7b10cf5e8b6763d518e1089/mediaapi/routing/upload.go#L150 or in `WriteTempFile` to handle `max_file_size_bytes = 0` as unlimited. therefore uploads get truncated to 0 bytes

**Comment by neilalexander** [comment]
Thanks for reporting this!
