### ISSUE TITLE
Backfill isn't trying other servers

### ISSUE THREAD

**Issue by HenrikSolver** [matrix-org/dendrite#1371]
I see some problems with backfill. I might misunderstand how this works, but this is what I see. At some point when I scrolling backwards in a room, my HS tries to fetch older messages from other servers. In this case it tries to use a server that is not available.

INFO[2020-08-29T10:21:21.340837471Z] [github.com/matrix-org/dendrite@/roomserver/internal/perform_backfill.go:71] StateIDsBeforeEvent
Requesting /state_ids at event event_id="$5Bly/LJXa74VWDJywwjbgA2Q5Sj4V3UXbhpQ/FkiTRU"
WARN[2020-08-29T10:21:21.478792541Z] [github.com/matrix-org/gomatrixserverlib@v0.0.0-20200817100842-9d02141812f2/client.go:140] RoundTrip
Error sending request to https://im.leptonics.com:8448/_matrix/federation/v1/state_ids/%21yjVgJUsMLYLAONsoii:jki.re?event_id=%245Bly%2FLJXa74VWDJywwjbgA2Q5Sj4V3UXbhpQ%2FFkiTRU: dial tcp 78.47.111.199:8448: connect: connection refused context=missing out.req.ID=02RqAb1Bs4hE out.req.method=GET out.req.uri="matrix://im.leptonics.com/_matrix/federation/v1/state_ids/%21yjVgJUsMLYLAONsoii:jki.re?event_id=%245Bly%2FLJXa74VWDJywwjbgA2Q5Sj4V3UXbhpQ%2FFkiTRU"

The problem I see is that my HS does not try another server to get events from, instead it contacts (or try to) this im.leptronics.com over and over again.

**Comment by neilalexander** [comment]
The event `$5Bly/LJXa74VWDJywwjbgA2Q5Sj4V3UXbhpQ/FkiTRU` in question was:
```
{
  "origin_server_ts" : 1597399700715,
  "prev_state" : [

  ],
  "type" : "m.room.message",
  "origin" : "matrix.org",
  "signatures" : {
    "matrix.org" : {
      "ed25519:a_RXGa" : "KpGsPTGjiwB6SHL2lcQHtSkwQ+trgWt15KIOUocbURH9H0nawyZtD1NePKmnhSSEAQ4EG\/XERcXLGs1LUhimCg"
    }
  },
  "hashes" : {
    "sha256" : "Us9TK\/gz0c09bpGcig8dWIfc38uJDkbxdysXAB6mqK8"
  },
  "depth" : 12066,
  "content" : {
    "format" : "org.matrix.custom.html",
    "formatted_body" : "<pre><code>not ok 604 Local device key changes get to remote servers\n# Started: 2020-08-14 09:58:34.161\n# Ended: 2020-08-14 09:58:44.274\n# Timed out waiting for test at .\/run-tests.pl line 759.\n# 0.099895: Registered new user @anon-20200814_094732-693:localhost:8800\n<\/code><\/pre>\n<p>thank you sytest, much informative of what you were waiting on..<\/p>\n",
    "body" : "```\nnot ok 604 Local device key changes get to remote servers\n# Started: 2020-08-14 09:58:34.161\n# Ended: 2020-08-14 09:58:44.274\n# Timed out waiting for test at .\/run-tests.pl line 759.\n# 0.099895: Registered new user @anon-20200814_094732-693:localhost:8800\n```\nthank you sytest, much informative of what you were waiting on..",
    "msgtype" : "m.text"
  },
  "auth_events" : [
    "$5KvOJ83oMmOi7liBk9DqR5A1Guago2BQ8hwG0G+celU",
    "$5jwZKnDj53thkkjnuHGH06X0CXiy7X9B+uHGC97sGeg",
    "$90T3TME4RFrCBwFJxPrmZ4MA9nPptN3pug+ZlXayV9I"
  ],
  "sender" : "@kegan:matrix.org",
  "unsigned" : {
    "age_ts" : 1597399700715
  },
  "prev_events" : [
    "$EnbMAGzy3XZaEaRh4O+wd\/9B87PsNaLzYO9xXK9WQkI"
  ],
  "room_id" : "!yjVgJUsMLYLAONsoii:jki.re"
}
```
