### ISSUE TITLE
"If user leaves room, remote user changes device and rejoins we see update in /sync and /keys/changes" is flakey

### ISSUE THREAD

**Issue by kegsay** [matrix-org/dendrite#1406]
On all builds:
 - https://buildkite.com/matrix-dot-org/dendrite/builds/3042#f80dcbd7-d853-4975-b36d-dfa2c595874a postgres/http
 - https://buildkite.com/matrix-dot-org/dendrite/builds/3036#3ceaa1b7-8660-4c20-8599-d2042c0d9fa5 postgres/http
 - https://buildkite.com/matrix-dot-org/dendrite/builds/3033#8fb8ab0d-7257-46c2-92c5-b80f9c1109a4 postgres and sqlite both http

**Comment by S7evinK** [comment]
I think this one is fine now.
