### ISSUE TITLE
Unable to join room with polylith

### ISSUE THREAD

**Issue by S7evinK** [matrix-org/dendrite#1422]
**Describe the bug**
Joining `#dendrite-dev:matrix.org` (on 913020e4) results in `Failed to join room - Unknown message` using Element Web.

**To Reproduce**
1. Try to join `#dendrite-dev:matrix.org`

**Expected behavior**
Successfully join the room

**Screenshots**
![2020-09-11_210446](https://user-images.githubusercontent.com/2353100/92964572-a16ed380-f474-11ea-9166-04918ba825b1.png)
![2020-09-11_210629](https://user-images.githubusercontent.com/2353100/92964588-a895e180-f474-11ea-8a43-92ff2c34ba48.png)

**Additional context**
Polylith with Kafka and PostgreSQL in Kubernetes with Traefik as the proxy for incoming external requests (eg federation or clients). Kafka was setup using the `bitnami/kafka` Helm Chart. Internal requests are sent inside Kubernetes using cluster services.

Federation works, tested with an account on matrix.org and on my synapse server.

**Configuration**
Changed `internal_api.listen` for every component to "any" (`http://:PORT`) and `internal_api.connect` to the DNS name (port unchanged) i used in the Kubernetes service.

Traefik rules (definitely needs work.. maybe already the problem?):
```
  - match: Host(`dendrite.s3cr3t.me`) && (Path(`/_matrix/client/r0/sync`) || Path(`/_matrix/client/r0/rooms/{roomid:.*}/messages`) || Path(`/_matrix/client/r0/user/{userid:.*}/filter`) || PathPrefix(`/_matrix/client/r0/user/{userid:.*}/filter/{filterid:.*}`) || Path(`/_matrix/client/r0/keys/changes`) )
=> sync_api

  - match: Host(`dendrite.s3cr3t.me`) && (PathPrefix(`/_matrix/client/r0`) || Path(`/_matrix/client/versions`))
=> client_api

  - match: Host(`dendrite.s3cr3t.me`) && (PathPrefix(`/_matrix/federation`) || PathPrefix(`/_matrix/key/v2`))
=> federation_api
```

**Logs**
[ServerKeyAPI.log](https://github.com/matrix-org/dendrite/files/5211171/ServerKeyAPI.log)
[FederationSender.log](https://github.com/matrix-org/dendrite/files/5211173/FederationSender.log)
[FederationAPI.log](https://github.com/matrix-org/dendrite/files/5211187/FederationAPI.log)

(the other logs didn't look suspicious)

**Comment by wirke** [comment]
You probably have the same problem as me - https://github.com/matrix-org/dendrite/issues/1418

**Comment by neilalexander** [comment]
Can you please attach the roomserver log? The only error lines appear to be `context cancelled`, which implies that the HTTP request from the roomserver to the federation sender and/or server key API was cancelled/killed for some reason.

**Comment by S7evinK** [comment]
I thought i did that.
A new full set of logs:
[UserAPI.log](https://github.com/matrix-org/dendrite/files/5232923/UserAPI.log)
[SyncAPI.log](https://github.com/matrix-org/dendrite/files/5232924/SyncAPI.log)
[RoomServerAPI.log](https://github.com/matrix-org/dendrite/files/5232925/RoomServerAPI.log)
[MediaAPI.log](https://github.com/matrix-org/dendrite/files/5232926/MediaAPI.log)
[KeyServer.log](https://github.com/matrix-org/dendrite/files/5232927/KeyServer.log)
[FederationSender.log](https://github.com/matrix-org/dendrite/files/5232928/FederationSender.log)
[FederationAPI.log](https://github.com/matrix-org/dendrite/files/5232929/FederationAPI.log)
[EDUServerAPI.log](https://github.com/matrix-org/dendrite/files/5232930/EDUServerAPI.log)
[ClientAPI.log](https://github.com/matrix-org/dendrite/files/5232931/ClientAPI.log)
[AppServiceAPI.log](https://github.com/matrix-org/dendrite/files/5232932/AppServiceAPI.log)
[ServerKeyAPI.log](https://github.com/matrix-org/dendrite/files/5232933/ServerKeyAPI.log)

**Comment by neilalexander** [comment]
So it looks like the problem in polylith mode is that the internal HTTP clients are set with a 30 second timeout - anything that takes longer than that will time out, causing the `context cancelled`. I will look into fixing that today.

**Comment by neilalexander** [comment]
I think this is probably fixed already, please reopen if it isn't.
