### ISSUE TITLE
Add smart /health endpoint that checks if dependent services available

### ISSUE THREAD

**Issue by S7evinK** [matrix-org/dendrite#1429]
**Is your feature request related to a problem? Please describe.**
Adding a `/health` endpoint allows orchestration tools to see if a component is healthy and "restart" the process, if needed.

**Describe the solution you'd like**
Ping the database connection and/or other components required to run a specific component.

**Comment by Kegsay** [comment]
You can use `/_matrix/client/versions` for this for now. This is still relevant in polylith deployments though which don't have this. I _think_ if metrics are enabled you can hit prometheus but obviously it doesn't actually mean that the service is ready for connections yet.

**Comment by MadLittleMods** [comment]
We're tracking a dumb `/health` endpoint that returns 200 OK in https://github.com/matrix-org/dendrite/issues/1668. We can use this as a follow-up to make something smarter.

For reference with Gitter, we have a dumb `/health_check` and another smart `/health_check/full` like this issue is after, [`server/api/index.js#L36-50`](https://gitlab.com/gitterHQ/webapp/-/blob/5abd9cdd6cf2ca7da62f4fd320f67aee1d38b94c/server/api/index.js#L36-50)

**Comment by whatlimits** [comment]
[](https://help.twitter.com/en/rules-and-policies/twitter-username-squatting)

**Comment by S7evinK** [comment]
https://github.com/alexliesenfeld/health

Might be worth a look for this.

**Comment by matslarson** [comment]
👍 for this, even if it's just a dumb `200 OK`. I have a Helm chart for a polylith deployment in k8s almost ready to go, but the hangup is that there's no way for the ingress loadbalancer to healthcheck the components. Using `/metrics` as a hack doesn't really work either, not only is it not really indicative of whether the service is ready, but it requires auth that can't be passed in a path and listens on the internal port while the loadbalancer would be checking the external port for service availability.

**Comment by MadLittleMods** [comment]
This was added in https://github.com/matrix-org/dendrite/pull/2303 and available in Dendrite 0.7.0 (2022-03-25).

> Healthcheck endpoints are now available at:
>  - `/_dendrite/monitor/up`, which will return 200 when Dendrite is ready to accept requests
>  - `/_dendrite/monitor/health`, which will return 200 if healthy and 503 if degraded for some reason
>
> *-- https://github.com/matrix-org/dendrite/blob/main/CHANGES.md#dendrite-070-2022-03-25*
