### ISSUE TITLE
Rename 'rewrite state' as 'override state'

### ISSUE THREAD

**Issue by ara4n** [matrix-org/dendrite#1430]
I got very confused by 'rewrite state', given that it implies that we are mutating an existing state snapshot because we've discovered it's wrong - whereas in practice it seems to just be creating a new immutable state snapshot for a room after a gap in the DAG.  Before it gets too baked in, can we consider a better name?  Or am I Confused?

**Comment by Kegsay** [comment]
Something like `CompleteStateSnapshot bool` would be better I think as that accurately represents what that flag means.

**Comment by Kegsay** [comment]
We don't have this field anymore.
