### ISSUE TITLE
Please implement POST /_matrix/key/v2/query endpoint

### ISSUE THREAD

**Issue by grinapo** [matrix-org/dendrite#1435]
**Is your feature request related to a problem? Please describe.**
Missing endpoint causes *lot* of breaking when a matrix server use it exlusively. 

**Describe the solution you'd like**
API implemented. 

**Details**
This endpoint shall be superior to `GET /_matrix/key/v2/server/{keyId}` and would serve the better good if it’d be implemented. :-)

**Comment by neilalexander** [comment]
I've started to add some support for these endpoints in #1436. It's not complete yet but, with any luck, it might just be enough to get Construct to talk to Dendrite in the meantime.
