### ISSUE TITLE
Official Docker ARM support

### ISSUE THREAD

**Issue by TR-SLimey** [matrix-org/dendrite#1494]
**Description:**

As per [this](https://matrix.to/#/!yomrOFwgFXzmeMAbzX:matrix.org/$wg35DVErw_BQ6bYne5SikHvr5IkmmpuXtMudcVNZwVY?via=an-atom-in.space&via=matrix.org&via=matrix.anukul.com.np) message, I would like to suggest official support for the Docker image on ARM

**Comment by c-x-berger** [comment]
I'm tooting my own horn here, but #1716 should help here.  
It's something like step (-1), but it's a step.

**Comment by TR-SLimey** [comment]
I actually already submitted a PR to build multi-architecture images using GitHub actions (#1613) :P

However, that works only in GitHub actions, and isn't much good when just cross-compiling the binaries (in my PR, I cross-compile them within the image, kind of sidestepping the issue), so I'd say your PR is still quite helpful. Thanks!

**Comment by c-x-berger** [comment]
I think we can close this now, since #1613 is merged and the images have been published!

**Comment by TR-SLimey** [comment]
Indeed we can. Thanks for the reminder :D
