### ISSUE TITLE
[query] Migration plan from Synapse to Dendrite

### ISSUE THREAD

**Issue by kwill** [matrix-org/dendrite#150]
**User story:** I am a Synapse service provider with many active users. When Dendrite is released I want to migrate my service to Dendrite, because it will be a superior solution.

**Query:** Is there (going to be) a migration plan for Synapse instances wanting to move to Dendrite? Are there any Synapse configuration options I can set today that will make that future migration faster/easier/feasible?

(This query is primarily about the service provider, not about self-hosted homeservers. I guess it is worth considering that users may be connecting to my instance with their own homeservers.)

**Comment by krombel** [comment]
@ara4n Wrote on 20. April 2017 [in #dendrite:matrix.org](https://matrix.to/#/!lnjwXgUmVSYdxgrvmo:matrix.org/$14927230491195146TMsWZ:matrix.org)
"we will absolutely provide migration."

I hopes it answers your question :slightly_smiling_face:

**Comment by Kegsay** [comment]
The important migration point is the data: Synapse and Dendrite store Matrix data in different ways. We have a vested interest in providing migration tools given that matrix.org currently runs on Synapse, and we will absolutely be moving to Dendrite when it's ready. So yes, there will be a plan. I don't know if there are any pre-emptive steps you can do, but we run Synapse on PostgreSQL, so if we write some migration scripts or something I imagine we'll be targeting PostgreSQL initially.

**Comment by kwill** [comment]
Thanks!

**Comment by KenMacD** [comment]
#1705 appears to track this issue.
