### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by Dreamsorcerer** [matrix-org/dendrite#1507]
Would be great to have a debian package, and install instructions for that.

**Comment by kegsay** [comment]
This won't happen in the short or medium term. When Dendrite is no longer beta you can expect packages, but until then you'll have to make do with Docker images I'm afraid. Closing this.

**Comment by Dreamsorcerer** [comment]
Judging by sytest results it's looking like dendrite is getting close. Any chance we'll get the deb packages in the next couple of months?
