### ISSUE TITLE
Issue fetching old signing key

### ISSUE THREAD

**Issue by aditsachde** [matrix-org/dendrite#1508]
### Background information

- **Dendrite version or git SHA**: 0.1.0
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: Yes
- **`go version`**: Default version in docker container

### Description

I had a synapse server at matrix.sachde.xyz which used the signing key seen [here](https://matrix.org/_matrix/key/v2/query/aditsachde.com/ed25519:a_AMlB). I switched to a dendrite server at dendrite.sachde.xyz, and when joining a room that I previously participated in, the join fails, because signature validation fails, as dendrite fails to retrieve the key. 

I have the old key, but synapse used a different format. Dendrite tries to fetch the key directly but fails. It should fall back to the perspective key server, as the key does exist on matrix.org

### Steps to reproduce

- Join and leave room on a synapse server.
- Deploy a dendrite server on the same domain.
- Try to join the room again, without specifiying the old key in the dendrite config.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->
```
time="2020-10-09T22:44:19.854957496Z" level=info msg="Checking event signatures for 1352 events of room state" func="Check\n\t" file=" [github.com/matrix-org/gomatrixserverlib@v0.0.0-20201006143701-222e7423a5e3/federationtypes.go:409]" context=missing
time="2020-10-09T22:44:19.994178749Z" level=info msg="Fetching 85 key(s)" func="handleFetcherKeys\n\t" file=" [github.com/matrix-org/dendrite@/signingkeyserver/internal/api.go:208]" fetcher_name="perspective server matrix.org"
time="2020-10-09T22:44:20.426154563Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [github.com/matrix-org/dendrite@/signingkeyserver/internal/api.go:208]" fetcher_name=DirectKeyFetcher
time="2020-10-09T22:44:20.859211577Z" level=warning msg="Failed to retrieve key \"ed25519:a_AMlB\" for server \"aditsachde.com\"" func="FetchKeys\n\t" file=" [github.com/matrix-org/dendrite@/signingkeyserver/internal/api.go:100]"
time="2020-10-09T22:44:22.124874626Z" level=error msg="Signature validation failed for event \"$sldiDbYkqSCO4kChaKxEV53k_3ApbmfoHKcXZTYQ5xA\"" func="Check\n\t" file=" [github.com/matrix-org/gomatrixserverlib@v0.0.0-20201006143701-222e7423a5e3/federationtypes.go:422]" error="gomatrixserverlib: could not download key for \"aditsachde.com\""
time="2020-10-09T22:44:22.125160231Z" level=error msg="Signature validation failed for event \"$R9jAG__bwHbfbDOwVYzmJEtwgxSJsNBaGPvL7qKQXmM\"" func="Check\n\t" file=" [github.com/matrix-org/gomatrixserverlib@v0.0.0-20201006143701-222e7423a5e3/federationtypes.go:422]" error="gomatrixserverlib: could not download key for \"aditsachde.com\""
time="2020-10-09T22:44:22.126519815Z" level=error msg="Signature validation failed for event \"$3a-1ST4-bXgMi92wUc6ykdyda0_3YIpYtv19DJneO6M\"" func="Check\n\t" file=" [github.com/matrix-org/gomatrixserverlib@v0.0.0-20201006143701-222e7423a5e3/federationtypes.go:422]" error="gomatrixserverlib: could not download key for \"aditsachde.com\""
time="2020-10-09T22:44:22.126755763Z" level=error msg="Signature validation failed for event \"$czklLAyHGhac7PUe6ZeNRu4RJJpxLorV7yG3JADw1Bg\"" func="Check\n\t" file=" [github.com/matrix-org/gomatrixserverlib@v0.0.0-20201006143701-222e7423a5e3/federationtypes.go:422]" error="gomatrixserverlib: could not download key for \"aditsachde.com\""
time="2020-10-09T22:44:22.127213174Z" level=error msg="Signature validation failed for event \"$7MLXbC5BQTfXAd7jCK0o-5jOme2y-wiCjEH7QcG67jk\"" func="Check\n\t" file=" [github.com/matrix-org/gomatrixserverlib@v0.0.0-20201006143701-222e7423a5e3/federationtypes.go:422]" error="gomatrixserverlib: could not download key for \"aditsachde.com\""
time="2020-10-09T22:44:22.373829351Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [github.com/matrix-org/dendrite@/signingkeyserver/internal/api.go:208]" fetcher_name="perspective server matrix.org"
time="2020-10-09T22:44:22.553586216Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [github.com/matrix-org/dendrite@/signingkeyserver/internal/api.go:208]" fetcher_name=DirectKeyFetcher
time="2020-10-09T22:44:22.725315318Z" level=warning msg="Failed to retrieve key \"ed25519:a_AMlB\" for server \"aditsachde.com\"" func="FetchKeys\n\t" file=" [github.com/matrix-org/dendrite@/signingkeyserver/internal/api.go:100]"
time="2020-10-09T22:44:23.122100456Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [github.com/matrix-org/dendrite@/signingkeyserver/internal/api.go:208]" fetcher_name="perspective server matrix.org"
time="2020-10-09T22:44:23.519444005Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [github.com/matrix-org/dendrite@/signingkeyserver/internal/api.go:208]" fetcher_name=DirectKeyFetcher
time="2020-10-09T22:44:23.716133723Z" level=warning msg="Failed to retrieve key \"ed25519:a_AMlB\" for server \"aditsachde.com\"" func="FetchKeys\n\t" file=" [github.com/matrix-org/dendrite@/signingkeyserver/internal/api.go:100]"
time="2020-10-09T22:44:24.085826595Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [github.com/matrix-org/dendrite@/signingkeyserver/internal/api.go:208]" fetcher_name="perspective server matrix.org"
time="2020-10-09T22:44:24.463617789Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [github.com/matrix-org/dendrite@/signingkeyserver/internal/api.go:208]" fetcher_name=DirectKeyFetcher
time="2020-10-09T22:44:24.643868748Z" level=warning msg="Failed to retrieve key \"ed25519:a_AMlB\" for server \"aditsachde.com\"" func="FetchKeys\n\t" file=" [github.com/matrix-org/dendrite@/signingkeyserver/internal/api.go:100]"
time="2020-10-09T22:44:24.854554213Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [github.com/matrix-org/dendrite@/signingkeyserver/internal/api.go:208]" fetcher_name="perspective server matrix.org"
time="2020-10-09T22:44:25.047330406Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [github.com/matrix-org/dendrite@/signingkeyserver/internal/api.go:208]" fetcher_name=DirectKeyFetcher
time="2020-10-09T22:44:25.213302132Z" level=warning msg="Failed to retrieve key \"ed25519:a_AMlB\" for server \"aditsachde.com\"" func="FetchKeys\n\t" file=" [github.com/matrix-org/dendrite@/signingkeyserver/internal/api.go:100]"
time="2020-10-09T22:44:25.415893469Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [github.com/matrix-org/dendrite@/signingkeyserver/internal/api.go:208]" fetcher_name="perspective server matrix.org"
time="2020-10-09T22:44:25.599599710Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [github.com/matrix-org/dendrite@/signingkeyserver/internal/api.go:208]" fetcher_name=DirectKeyFetcher
time="2020-10-09T22:44:25.764842917Z" level=warning msg="Failed to retrieve key \"ed25519:a_AMlB\" for server \"aditsachde.com\"" func="FetchKeys\n\t" file=" [github.com/matrix-org/dendrite@/signingkeyserver/internal/api.go:100]"
time="2020-10-09T22:44:25.817379931Z" level=error msg="Failed to process room join response" func="func1\n\t" file=" [github.com/matrix-org/dendrite@/federationsender/internal/perform.go:228]" error="respSendJoin: gomatrixserverlib: event with ID \"$7MLXbC5BQTfXAd7jCK0o-5jOme2y-wiCjEH7QcG67jk\" is not allowed by its auth events: gomatrixserverlib: event with ID \"$7MLXbC5BQTfXAd7jCK0o-5jOme2y-wiCjEH7QcG67jk\" is not allowed by its auth_events: eventauth: sender \"@adit:aditsachde.com\" is not in the room" room_id="!yomrOFwgFXzmeMAbzX:matrix.org" user_id="@adit:aditsachde.com"
```

**Comment by aditsachde** [comment]
Fixed this issue by converting my old synapse key using the following format. The equal sign after the key_data is important.

```
ed25519 handle key_data
```

```
-----BEGIN MATRIX PRIVATE KEY-----
Key-ID: ed25519:handle

key_data=
-----END MATRIX PRIVATE KEY-----
```

However, I don't think this solves the underlying issue that dendrite does not correctly fall back to fetching the key from the perspective key server. I tried my best to look through the code and see whats wrong, but I don't know go well enough to properly debug it.

**Comment by neilalexander** [comment]
I've created a PR to address this, although if you still have any old signing keys from your domain name, you should ideally configure them as `old_private_keys` in your config so that they are still available for other HSes to request directly from you. In this case you also wouldn't need to fetch the keys over federation.

**Comment by jakehemmerle** [comment]
Make sure your key is formatted exactly as above:
`*KEY DATA HERE*=`
not
`key_data=*KEY DATA HERE*`
or you might also spend 30 minutes trying to figure out why dendrite keeps saying `keyBlock is nil` 😃
