### ISSUE TITLE
opt-in anonymous metric reporting

### ISSUE THREAD

**Issue by ara4n** [matrix-org/dendrite#1509]
in terms of justifying dendrite dev funding, it's critical we track how many people are actually using it, as best we can. we should implement the same optional phone-home stats reporting as synapse has

**Comment by rumpelsepp** [comment]
As long as the collected data is publicly available (e.g. syncthing [does this](https://data.syncthing.net/)) I would enable it.

**Comment by S7evinK** [comment]
Currently missing: Total rooms, message count to be added in #2748

**Comment by kegsay** [comment]
This was done.
