### ISSUE TITLE
Registration restrictions and app service namespace restrictions are also applied to app services

### ISSUE THREAD

**Issue by phol** [matrix-org/dendrite#1518]
### Background information

- **Dendrite version or git SHA**: v0.1.0
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **`go version`**: go version go1.15.2 linux/amd64

### Description

I am experimenting with Dendrite and was trying out to set up the [mautrix-whatsapp](https://github.com/tulir/mautrix-whatsapp) bridge.

It requires an exclusive namespace, but when `exclusive: true` is enabled in its registration file, it errors with

```log
[ERROR] Failed to connect to homeserver: failed to ensure registered: failed to POST /_matrix/client/r0/register: M_EXCLUSIVE (HTTP 400): This username is reserved by an application service.. Retrying in 10 seconds...
```

Setting `exclusive: false` remediates that issue, however, disabling registration in dendrite also causes errors:

```log
[ERROR] Failed to connect to homeserver: failed to ensure registered: failed to POST /_matrix/client/r0/register: 403 403 Forbidden
```

After setting `exclusive: false` and `registration_disabled: false` and dropping and recreating the bridge, it does register as can be viewed in the Dendrite logs:

```log
Oct 13 11:29:02 dendrite dendrite-monolith-server[23628]: time="2020-10-13T09:29:02.818448029Z" level=info msg="Processing registration request" func="Register\n\t" file=" [/root/dendrite/clientapi/routing/register.go:507]" auth.type="" req.id=eAmml6MbH2Mm req.method=POST req.path=/_matrix/client/r0/register session_id="" username=whatsappbot
```

I can also invite it into rooms, but it doesn't respond to commands. I've not figured out what the cause of that last issue is yet but I'm suspecting this might have to do with notifications not being implemented yet, making it irrelevant for this specific issue.

### Steps to reproduce

- Install Dendrite
- Install Mautrix WhatsApp and try to register it in the app services section in dendrite.yaml.
- Restart Dendrite, start Mautrix Whatsapp
- Watch the logs.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by Limvot** [comment]
I believe I'm running into this with mautrix-telegram as well.
