### ISSUE TITLE
Downloading pictures from federated Synapse instance fails

### ISSUE THREAD

**Issue by darkgallium** [matrix-org/dendrite#1525]
### Background information

- **Dendrite version or git SHA**: 286dd408ae623b218f9c5a97d53f174c0ea19cc2
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: SQLite3
- **Running in Docker?**:  No
- **`go version`**: go1.15.2 linux/arm

### Description

When sending pictures from a federated synapse instance onto a public room of my dendrite server, the picture doesn't show up and when clicking on it we get the following JSON error :
```json
{"errcode":"M_NOT_FOUND","error":"Failed to download: error querying the database.: invalid response from remote server: strconv.ParseInt: parsing \"\": invalid syntax"}
```

### Some clues

Problem seems to be located at the following line : https://github.com/matrix-org/dendrite/blob/e3c2b081c7c197cad931d6525931dc9e960b93c3/mediaapi/routing/download.go#L696 

The header `Content-Length` seems to be missing from the HTTP response provided by the Synapse instance. Note that the problem doesn't appear with several other instances behind reverse proxies, which is not the case of the one I'm mentioning. 

Since the problem did not appear between instances of Synapse, I looked at Synapse's way of downloading pictures from federated instances and it effectively doesn't appear to use the `Content-Length` header to deduce file size (see https://github.com/matrix-org/synapse/blob/v1.21.0/synapse/rest/media/v1/media_repository.py#L332 and https://github.com/matrix-org/synapse/blob/1c262431f9bf768d106bf79a568479fa5a0784a1/synapse/http/matrixfederationclient.py#L939)

Should I report this problem in the Synapse repo as well?
I can possibly come up with a PR, just need some advice on what should be done.

Thanks for your help :)

**Comment by superboum** [comment]
To add some context, this problem appeared to @darkgallium as we use [Traefik v1](https://traefik.io/) as a reverse proxy in front of our synapse instance. Traefik defaults to dynamically compressing all contents, including medias, if the client says it supports compression. When Traefik dynamically compress content, the `content-length` header is not sent. So, maybe Dendrite should not rely on this header or stop sending an header that says it supports compression? As a quick fix, I am aware that we can simply configure Traefik to stop doing compression on our medias even if supported by the client.
