### ISSUE TITLE
Events shown in wrong order 

### ISSUE THREAD

**Issue by 0bsessive** [matrix-org/dendrite#1547]
### Background information

- **Dendrite version or git SHA**: 0.2rc
- **Monolith or Polylith?**: monolith 
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: no
- **`go version`**: 1.15

got a room on dendrite federated to matrix.org. events are shown in the order of Thursday, Saturday and then Friday seen from matrix.org 🤔

**Comment by neilalexander** [comment]
I'll keep this open for now since, strictly speaking, the ordering issue isn't really fixed.

**Comment by kegsay** [comment]
A lot of work was done in this area to improve this, but out of order events are a long standing issue with how `/sync` works in Matrix. Either way, not an issue to keep open.
