### ISSUE TITLE
Some rooms keep backfilling regardless of history visibility

### ISSUE THREAD

**Issue by Pestdoktor** [matrix-org/dendrite#1559]
### Background information

- v0.20.1
- monolith
- postgres
- docker

### Description

Backfill should only work until reaching own join https://github.com/matrix-org/dendrite/blob/59428cdde3ed3f30f01b886c641e6dd1f313c294/syncapi/routing/messages.go#L264-L266

Some rooms keep responding to `GET /_matrix/client/r0/rooms/{roomId}/messages` after that

### Steps to reproduce

- join !bEWtlqtDwCLFIAKAcv:matrix.org or !jxlRxnrZCsjpjDubDX:matrix.org
- scroll back indefinitely

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by Pestdoktor** [comment]
just confirmed this on a fresh deployment
[Monolith.log](https://github.com/matrix-org/dendrite/files/5439104/Monolith.log)

**Comment by S7evinK** [comment]
Should hopefully be solved by https://github.com/matrix-org/dendrite/pull/2511
