### ISSUE TITLE
Ignore unknown keys in appservice registration files

### ISSUE THREAD

**Issue by bodqhrohro** [matrix-org/dendrite#1567]
### Background information

- **Dendrite version or git SHA**: 0.2.1
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: SQlite3
- **Running in Docker?**: no
- **`go version`**: 1.15

### Steps to reproduce

- generate an Appservice config with [matrix-appservice-node](https://github.com/matrix-org/matrix-appservice-node)
- provide that config in Dendrite config
- run Dendrite

Which results in an error:
```
FATA[0000] Invalid config file: yaml: unmarshal errors:
  line 16: field de.sorunome.msc2409.push_ephemeral not found in type config.ApplicationService 
```
because the parser doesn't ignore unknown keys.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by claudemuller** [comment]
Hey @bodqhrohro - mind if I take a swing?

**Comment by bodqhrohro** [comment]
You're welcome :)

**Comment by tichnas** [comment]
Hi @claudemuller, are you still working on the issue?
If not, @bodqhrohro I'd love to work on this so can I please be assigned?

**Comment by bodqhrohro** [comment]
I don't assign anyone. Feel free to make a PR, then reviewers will decide whose solution is better ;)

**Comment by MadLittleMods** [comment]
Related to https://github.com/matrix-org/matrix-appservice-node/issues/33 which is now fixed so `matrix-appservice-node` will no longer set `de.sorunome.msc2409.push_ephemeral` to `undefined`

**Comment by irth** [comment]
The error originates here, when the registration file is unmarshaled:

https://github.com/matrix-org/dendrite/blob/3c419be6af2938170d2c04f56d8616c0129ca673/setup/config/config_appservice.go#L183

The only difference between `Unmarshal` and `UnmarshallStrict` is that `UnmarshallStrict` does not allow unknown keys and duplicate keys. [(docs)](https://pkg.go.dev/gopkg.in/yaml.v2#UnmarshalStrict)

Replacing this `UnmarshalStrict` with `Unmarshal` would fix this issue.

However, this brings another issue into mind - do we want to verify that the keys that we require are actually present? Or, are we doing that somewhere else?

**Comment by keremgocen** [comment]
@irth was there a conclusion about your comment? I'm happy to send a PR with that small change if that's still the solution you guys think is the best.

**Comment by alam0rt** [comment]
I was going to write up a simple PR to "fix" this, but personally `UnmarshallStrict` feels like a better user experience - i.e. if I had a  typo in my config I'd prefer to know at start up rather than spending ages working out why my config was being silently swallowed.

**Comment by irth** [comment]
Perhaps we might need to Unmarshal it to something less typed - map[string]interface{}, and then do the verification and fill the struct manually.
