### ISSUE TITLE
matrix client get image thumbnail 404 error.

### ISSUE THREAD

**Issue by bitcard** [matrix-org/dendrite#1574]
### Background information

- **Dendrite version or git SHA**: 0.2.1
- **Monolith or Polylith?**: monolith
- **SQLite3 or Postgres?**: sqlite3
- **Running in Docker?**: no
- **`go version`**: go1.14.4 darwin/amd64

### Description

matrix client get image thumbnail 404 error.

http://servername:8008/_matrix/media/v1/thumbnail/servername/da46bf4c52a22a1bccb96e42a49396dce7af3d8759b22e6eb03b865761b09655?width=648&height=710&method=scale

### Steps to reproduce

1, run riot android, upload image to server.
2, server create 4 files:
file
thumbnail-32x32-crop
thumbnail-96x96-crop
thumbnail-640x480-scale

3, another mobile device can't display this file, debug it, found get image 404

**Comment by Kegsay** [comment]
Have you checked that https://github.com/matrix-org/dendrite/blob/v0.2.1/dendrite-config.yaml#L220 exists and is writable by the dendrite process?

**Comment by 0bsessive** [comment]
can confirm. config option exists and is writable, not loading

**Comment by bitcard** [comment]
> Have you checked that https://github.com/matrix-org/dendrite/blob/v0.2.1/dendrite-config.yaml#L220 exists and is writable by the dendrite process?

yes, server write file is ok, the thumbnail was created.

**Comment by 0bsessive** [comment]
For some reason avatars of people and rooms do load in web element but not element iOS app

**Comment by fnwbr** [comment]
> For some reason avatars of people and rooms do load in web element but not element iOS app

I’m having the same issue. Did you ever find out why that’s the case?

**Comment by kegsay** [comment]
Please make a new issue if this is still a problem for you, and we will investigate this further.
