### ISSUE TITLE
"Couldn't verify signature on third-party invite" when trying to join a room

### ISSUE THREAD

**Issue by wlcx** [matrix-org/dendrite#1595]
### Background information

- **Dendrite version or git SHA**: 0.3.1
- **Monolith or Polylith?**: monolith 
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: yes, digest d6726a759
- **`go version`**: whatever is used in the docker image

### Description
When trying to join a specific room (#rust-embedded:matrix.org), dendrite fails to join the room, causing an error or endless spinner in element.

The crucial log line seems to be:
```
time="2020-11-23T18:52:53.710377271Z" level=error msg="Failed to process room join response" func="func1\n\t" file=" [github.com/matrix-org/dendrite/federationsender/internal/perform.go:243]" error="respSendJoin: gomatrixserverlib: event with ID \"$I0Kh3EivqPltZoXxPTBzYbTFMg4cFcnmUuXUWbNPLh0\" is not allowed by its auth events: gomatrixserverlib: event with ID \"$I0Kh3EivqPltZoXxPTBzYbTFMg4cFcnmUuXUWbNPLh0\" is not allowed by its auth_events: eventauth: Couldn't verify signature on third-party invite for @REDACTED:matrix.org" room_id="!BHcierreUuwCMxVqOf:matrix.org" user_id="@samw:hacksrus.uk"
```
I don't think any of the rest of the logs are relevant so I have omitted them, but please let me know if any additional output would be useful.

### Steps to reproduce

- Run a dendrite homeserver 
- Try to join #rust-embedded:matrix.org

**Comment by kegsay** [comment]
We should ignore/drop the event for a failed signature, even if this is a 3PID signature.

**Comment by kegsay** [comment]
We do now drop events which fail sig checks.
