### ISSUE TITLE
Invalid username on appservice user creation due to underscore

### ISSUE THREAD

**Issue by wlcx** [matrix-org/dendrite#1599]
### Background information

- **Dendrite version or git SHA**: 0.3.1
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: Yes
- **`go version`**: Docker version

### Description
When running the discord app service (https://github.com/Half-Shot/matrix-appservice-discord, v0.5.2), I get errors in the appservice's log regarding username registration:

```
discord-appsvc_1  | Nov-25 18:31:55.757 [UserSync] info: Creating new user @_discord_567871284180942858:hacksrus.uk
discord-appsvc_1  | Nov-25 18:31:55.772 [UserSync] error: Failed to update user's profile [M_INVALID_USERNAME: Username cannot start with a '_'] {
discord-appsvc_1  |   errcode: 'M_INVALID_USERNAME',
discord-appsvc_1  |   data: {
discord-appsvc_1  |     errcode: 'M_INVALID_USERNAME',
discord-appsvc_1  |     error: "Username cannot start with a '_'"
discord-appsvc_1  |   },
discord-appsvc_1  |   httpStatus: 400
discord-appsvc_1  | }
```

On discussion in #dendrite{,-dev}, it seems like is because dendrite calls `validateUsername` rather than `validateApplicationServiceUsername` : https://github.com/matrix-org/dendrite/blob/master/clientapi/routing/register.go#L484-L486

### Steps to reproduce

- Run the discord appservice bridged to a discord guild
- send a message in a channel, causing the app service to try to create a user

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by wlcx** [comment]
Somewhat related https://github.com/matrix-org/dendrite/issues/630

**Comment by Half-Shot** [comment]
Oh missed this, we're using #1784
