### ISSUE TITLE
Dendrite Checklist for feature parity with Synapse

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/dendrite#160]
https://docs.google.com/spreadsheets/d/1tkMNpIpPjvuDJWjPFbw_xzNzOHBA-Hp50Rkpcr43xTw

We're using that public spreadsheet to monitor progress.

**Comment by dali99** [comment]
I've subscribed to the spreadsheet via the alert system. But I haven't gotten an update since I subscribed.

Further looking points to issues like #280 being closed on the github issue tracker, but with ? on the spreadsheet.

So, I was wondering if this spreadsheet is still being updated

**Comment by anoadragon453** [comment]
@dali99 it is now :P
