### ISSUE TITLE
Move some packages from internal

### ISSUE THREAD

**Issue by azcorp-cloud** [matrix-org/dendrite#1600]
Hi folks! May i ask you move setup, config and mscs packages from internal? It restricts other golang developers import them and start all monolyth complex inside custom app.

**Comment by neilalexander** [comment]
Can I ask what your use-case is?

**Comment by azcorp-cloud** [comment]
First of all try it as small corp chat engine with many rooms and integration with AD. So I want run it with custom auth adapter and add http intercepter/middlware with some custom metrics. If all will be smooth try some perfomance tests, and use it on our public portal.
