### ISSUE TITLE
Too many max_open_conns in default docker dendrite.yaml

### ISSUE THREAD

**Issue by normen** [matrix-org/dendrite#1611]
(as talked about on #dendrite:matrix.org)

### Background information

- Dendrite 0.3.2 
- Monolith
- Postgres
- Docker
- go 1.15.1

### Description
The default dendrite.yaml uses a `max_open_conns` of 100 for each process. The default postgres instance only allows around 100 connections, causing dropped DB connections when theres a lot of requests.

### Steps to reproduce

- Install dendrite via docker-compose
- connect to a lot of large rooms on a different server

The memory and CPU load of dendrite grows to gigabytes and 100% load. After a while the db drops connections because of too many connections. When setting the max_connections for each process to 10 instead of 100 the server runs more smoothly with max 1-200 MB memory use and just a few CPU spikes.

**Comment by kondanta** [comment]
Same issue applies for bare metal as well. I have deployed Dendrite as a systemd service and was having roughly a gigabyte memory usage along with 100% CPU usage.

**Comment by neilalexander** [comment]
The `max_open_conns` in the sample config were fixed in 0.3.3 so that they total up to the default 100 connections, rather than being 100 connections each.

**Comment by RobinJ1995** [comment]
You might've forgotten to update [this one](https://github.com/matrix-org/dendrite/blob/master/build/docker/config/dendrite-config.yaml), I think :)

**Comment by neilalexander** [comment]
> You might've forgotten to update [this one](https://github.com/matrix-org/dendrite/blob/master/build/docker/config/dendrite-config.yaml), I think :)

Fixed in c55361c1, thanks for reminding me!
