### ISSUE TITLE
Same read receipts sent down /sync constantly

### ISSUE THREAD

**Issue by auscompgeek** [matrix-org/dendrite#1627]
### Background information

- dendrite.matrix.org
- **Dendrite version or git SHA**: 0.3.3+bad81c02
- **Monolith or Polylith?**: monolith

### Description

In a DM I just created, I keep receiving the same read receipts, for the exact same events, with the exact same event IDs, every few syncs.

### Steps to reproduce

- Create a room.
- Send some messages.
- Check the ephemeral events the client receives.

The read receipts should not be resent multiple times, but they are.

**Comment by neilalexander** [comment]
This should be fixed in `master` now, but `dendrite.matrix.org` won't be updated until tomorrow evening. Please reopen if it's still a problem then.
