### ISSUE TITLE
"Forgotten room messages cannot be paginated" flakey for Dendrite

### ISSUE THREAD

**Issue by S7evinK** [matrix-org/dendrite#1629]
**Describe the bug**
https://buildkite.com/matrix-dot-org/dendrite/builds/3776
https://buildkite.com/matrix-dot-org/dendrite/builds/3774
Two different CI runs for Dendrite.

As far as i can see, in that [test](https://github.com/matrix-org/sytest/blob/73fa9af701e48f010471ec02b96913030b94d019/tests/30rooms/31forget.pl#L3), there's a room created as `$creator`, message sent as `$creator` but messages are retrieved for `$user`.
I'm not sure if `$creator == $user` in that case, or at least should be, as the test passes from time to time.
(As I'm not so familiar with Perl, would
```perl
+ matrix_get_room_messages( $creator, $room_id, limit => 1 );
- matrix_get_room_messages( $user, $room_id, limit => 1 );
``` 
be sufficient?)

**Expected behavior**
Test always passes

**Comment by kegsay** [comment]
I have been tracking flakey tests recently. I haven't seen this as an issue. Closing for now.
