### ISSUE TITLE
"SendEvents failed" on sending a message in #dendrite:matrix.org

### ISSUE THREAD

**Issue by oleg-fiksel** [matrix-org/dendrite#1630]
### Background information

- **Dendrite version or git SHA**: 9c03b0a4fa38971dfe83bd135aefb3c482a18380
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: yes
- **`go version`**: golang:1.15-alpine

### Description

Can't send messages to the room `#dendrite:matrix.org`.
Getting the following error in the log:

```
time="2020-12-10T22:42:19.126748607Z" level=error msg="SendEvents failed" func="SendEvent\n\t" file=" [github.com/matrix-org/dendrite/clientapi/routing/sendevent.go:102]" error="InputRoomEventsResponse: r.calculateAndSetState: roomState.CalculateAndStoreStateBeforeEvent: v.calculateAndStoreStateAfterManyEvents: d.Writer.Do: d.StateBlockTable.BulkInsertStateData: context canceled" req.id=f3wkgs3tjyzv req.method=PUT req.path="/_matrix/client/r0/rooms/!yomrOFwgFXzmeMAbzX:matrix.org/send/m.room.message/m1607640109008.0" user_id="@oleg:dendrite01.fiksel.info"

```

### Steps to reproduce

- build docker container from git commit 9c03b0a4fa38971dfe83bd135aefb3c482a18380 using `./build/docker/images-build.sh`
- connect to Dendrite using https://app.element.io
- join #dendrite:matrix.org
- try to send a message

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by neilalexander** [comment]
Please try `2885eb0` or newer and reopen if this is still an issue.

**Comment by oleg-fiksel** [comment]
I can send messages again on 2885eb0! 🎉 
Thanks for fixing this @neilalexander ! ❤️
