### ISSUE TITLE
Empty Rooms that persist through cache clears

### ISSUE THREAD

**Issue by InfiniteWorldSoftware** [matrix-org/dendrite#1634]
I am using [dendrite.matrix.org](dendrite.matrix.org).

Steps to reproduce (note- I was using Element throughout this process):
- Leave a room.
- (Optional) Forget the room.

There is some variability as to whether these empty rooms show up or not. However, they generally show up after leaving a room or being kicked from a room.

What should happen is that rooms should either be moved to the historical section, or disappear entirely if forgotten. 

![image](https://user-images.githubusercontent.com/66080865/101960135-c0484780-3bd4-11eb-9c66-7b89aa9238cb.png)

**Comment by kegsay** [comment]
Without information on what dendrite.matrix.org was running at this time it's hard to say if this issue is resolved or not. Closing this issue for now: if it re-surfaces please re-open.
