### ISSUE TITLE
Mention that you can use a single Postgres database earlier in INSTALL.md

### ISSUE THREAD

**Issue by aaronraimist** [matrix-org/dendrite#1637]
By the time INSTALL.md mentions

> Dendrite supports running all components from the same database in PostgreSQL mode

people have probably already run the loop to create individual databases since that is higher up in the file. 

https://github.com/matrix-org/dendrite/blob/master/docs/INSTALL.md#postgresql-database-setup should mention that you can create just one database

**Comment by neilalexander** [comment]
Is that better?

**Comment by aaronraimist** [comment]
Looks much better thanks
