### ISSUE TITLE
Postgres version in docker-compose deps is ancient 👴

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/dendrite#1651]
https://github.com/matrix-org/dendrite/blob/9a1ef81fa2a87d30d98298bcd91557b55a6da5a4/build/docker/docker-compose.deps.yml#L6

I presume this is because Dendrite is tested against 9.6, however it feels like we should not be expecting folks to run super old versions of postgresql for production. I've been running against 13 for my production dendrite but I'd be interested to know what would be a good version to support.

**Comment by neilalexander** [comment]
I think we can reasonably upgrade this, not aware of any reason we shouldn't. I think dendrite.matrix.org is running against PGSQL 11.6? 

@Kegsay Any thoughts?

**Comment by Kegsay** [comment]
Nope, let's do it.
