### ISSUE TITLE
Add health check endpoint

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/dendrite#1668]
#### Description:

Add a health check (`/health`) endpoint that allows orchestration tools to see if a component is up and running.

#### Potential solutions

Add a dumb `/health` endpoint that just returns 200 OK.

As a follow-up, we can improve this to check that the processs is actually healthy and its dependent services(database, kafka) are available -> https://github.com/matrix-org/dendrite/issues/1429

**Comment by whatlimits** [comment]
[![Uploading 105648138...]](https://help.twitter.com/en/rules-and-policies/twitter-username-squatting)

**Comment by kegsay** [comment]
Dupe https://github.com/matrix-org/dendrite/issues/1429 - we don't need 2 open issues for this.
