### ISSUE TITLE
Mention unstable features in /_matrix/client/versions

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/dendrite#1696]
[Spec link](https://adoring-einstein-5ea514.netlify.app/client-server/#get_matrixclientversions)

Synapse currently does something like
```json
GET https://matrix.org/_matrix/client/versions
{
  "versions": [
    "r0.0.1",
    "r0.1.0",
    "r0.2.0",
    "r0.3.0",
    "r0.4.0",
    "r0.5.0",
    "r0.6.0"
  ],
  "unstable_features": {
    "org.matrix.label_based_filtering": true,
    "org.matrix.e2e_cross_signing": true,
    "org.matrix.msc2432": true,
    "uk.half-shot.msc2666": true,
    "io.element.e2ee_forced.public": false,
    "io.element.e2ee_forced.private": false,
    "io.element.e2ee_forced.trusted_private": false
  }
}
```

It would be good if we could get enabled MSCs listed in here so things like Cerulean could dynamically decide if the homeserver being used has enough support to work.

**Comment by Kegsay** [comment]
Is this part of the spec?

**Comment by Half-Shot** [comment]
Tis indeed https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-versions

**Comment by Kegsay** [comment]
Fab, let's do it!

**Comment by sumitks866** [comment]
Hi! I want to work on this issue. Can anyone explain how to proceed? I am new to Matrix.

**Comment by Half-Shot** [comment]
Awesome. On the understanding that you know some Go:

- The handler for the versions endpoint above can be found at https://github.com/matrix-org/dendrite/blob/be7d8595be0533207f8942b129c16f3844550712/clientapi/routing/routing.go#L65-L82
- You need to add support for the unstable_features key which is documented in https://adoring-einstein-5ea514.netlify.app/client-server/#get_matrixclientversions 
- To find out what keys should be mentioned, I believe the configuration has some "MSC" keys that will tell you what is enabled on Dendrite. Probably worth asking about tht when you've figured out the other bits.

**Comment by sumitks866** [comment]
I think only msc2836 is to be mentioned. I checked dendrite-config file and config_mscs.go file.

https://github.com/matrix-org/dendrite/blob/fa65c40bae3b02540446b4c600533a673853e2d0/dendrite-config.yaml#L256-L267

https://github.com/matrix-org/dendrite/blob/fa65c40bae3b02540446b4c600533a673853e2d0/setup/config/config_mscs.go#L6

Please guide me further. Also what are MSCs? Sorry if I am asking too much questions, I am a newcomer.

**Comment by Half-Shot** [comment]
No problem. It's worth having a skim through https://matrix.org/docs/spec/ which describes Matrix in more detail. MSCs are up and coming features for Matrix that haven't yet made it into the specification, and are considered extensions which homeservers may choose to implement (see https://matrix.org/docs/spec/proposals for details. 

MSC stands for Matrix Spec Change, so each proposal to change matrix ends up with it's own number.

>I think only msc2836 is to be mentioned. I checked dendrite-config file and config_mscs.go file.

Sounds good. Basically what we would expect to do here is for each enabled MSC in the config, you would add a `org.matrix.mscXXXX` to the `unstable_features` field. There are some like my own which are called "uk.half-shot.msc2666", but I think it's probably better that we get to that later.
