### ISSUE TITLE
Allow solid WebID as authentication

### ISSUE THREAD

**Issue by Sigmun** [matrix-org/dendrite#1699]
**Description:**

I think the best way to enable social login with no privacy trade-off is to use the solid specification process (https://github.com/solid/solid-spec#webid-profile-documents). Thanks to this authentication process, you even don't need to worry about p2p authentication process.

**Comment by Kegsay** [comment]
Please keep suggestions like this out of the issue tracker. When we get around to implementing social login we will investigate options which will include your suggestion, along with any other competing standards.
