### ISSUE TITLE
Dendrite keeps panicking with write room event failure.

### ISSUE THREAD

**Issue by n3vu0r** [matrix-org/dendrite#1701]
### Background information

- **Dendrite version or git SHA**: 0.3.5+ec1b0179
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **`go version`**: 1.14

### Description

Dendrite keeps panicking with write room event failure. It is not usable any more.

### Steps to reproduce

  - Leave Element open in browser.
  - Come back and see `Connectivity to the server has been lost.`.
  - Find that Dendrite exited with panic log message:

    ```
    time="2021-01-12T06:38:05.826652913Z" level=panic msg="roomserver output log: write room event failure" func="github.com/matrix-org/dendrite/federationsender/consumers.(*OutputRoomEventConsumer).onMessage" file="github.com/matrix-org/dendrite/federationsender/consumers/roomserver.go:109" add="[]" del="[]" error="mismatched last sent event ID: had \"**stripped**" in database got \"**stripped**" from room server" event="{\"auth_events\"...
    ```
  - Restarting Dendrite results directly in the same panic.

**Comment by neilalexander** [comment]
This is *probably* the result of a crash, but in any case, I'll look into how we can improve this.

In the meantime, you can repair your Dendrite install by modifying the database — go into the `federationsender_rooms` table, find the room with the "had X in database" event ID in the `last_event_id` column, and then replace it with the "got X from roomserver" event ID instead. Dendrite should then start normally.

**Comment by n3vu0r** [comment]
Thanks, I updated the `last_event_id`:

```sql
update federationsender_rooms set last_event_id = '**new**' where last_event_id = '**old**';
UPDATE 1
```

But strangely I cannot select it afterwards with the new ID. It must have vanished somehow. (Dendrite was not running.). Now I'm getting this error:

```
time="2021-01-12T10:24:35.906742294Z" level=panic msg="roomserver output log: write new event failure" func="github.com/matrix-org/dendrite/syncapi/consumers.(*OutputRoomEventConsumer).onNewRoomEvent" file="github.com/matrix-org/dendrite/syncapi/consumers/roomserver.go:180" add="[]" del="[]" error="d.Topology.InsertEventInTopology: pq: duplicate key value violates unique constraint \"syncapi_output_room_events_topology_pkey\"" event="{\"auth_events\"...
```

I deleted then both entries in `syncapi_output_room_events_topology` with old and new ID, (DELETE 1, respectively). But the error remains. It's not important for me to repair the database, it's one or two days old. But maybe this helps to understand the original cause?
