### ISSUE TITLE
reject group invite return server error

### ISSUE THREAD

**Issue by bitcard** [matrix-org/dendrite#1727]
### Background information

- **Dendrite version or git SHA**: 0.3.1
- **Monolith or Polylith?**:  Monolith, dendrite-demo-libp2p
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: no
- **`go version`**:  1.13

### Describe
accept invite is ok, but reject group invite get server error, debug server /leave request, got "dial to self attempted" because libp2p can't dial to self peer id.

### Steps to reproduce

- Invite from riot android, ant then reject this invite from another device.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by kegsay** [comment]
We generally plan on supporting the pinecone demos from now on - cc @neilalexander can we close this?

**Comment by neilalexander** [comment]
Yep.
