### ISSUE TITLE
Cannot reject invites over federation

### ISSUE THREAD

**Issue by InfiniteWorldSoftware** [matrix-org/dendrite#1743]
I'm on dendrite.matrix.org.

### Description
I cannot reject invites

### Steps to reproduce

- Invite a user on a server running Dendrite
- Revoke their invite
- They will not be able to reject the invite

Edit: after doing a bit more testing only invites over federation have this issue. Inviting/disinviting other users on dendrite.matrix.org (for example) works great.
Important: After doing a few more tests, it looks like revoking their invite is a necessary step in these tests (rejecting invites before having them revoked seems to work just fine)
<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by andir** [comment]
Yeah, I can confirm the same. I just setup a dendrite instance yesterday. Joined a (custom) IRC gateway and have two "status channel" invites open that I can't reject but they are still showing up in my active invites.
The message I am getting is `Failed to leave room "!cOdyQheypHfqXecCpX:server.org" through 1 server(s)`

**Comment by kegsay** [comment]
Related: https://github.com/matrix-org/dendrite/issues/1828 https://github.com/matrix-org/dendrite/issues/1727 https://github.com/matrix-org/dendrite/issues/1400 

Bizarrely though tests for this very thing pass :/

```
Test 169 Invited user can reject invite over federation... OK
Test 170 Invited user can reject invite over federation several times... OK
Test 171 Invited user can reject invite for empty room... OK
Test 172 Invited user can reject invite over federation for empty room... OK
```

**Comment by kegsay** [comment]
However, these tests do NOT pass:
```
not ok 5 (expected fail) Inbound federation can receive invite and reject when remote replies with a 403 # TODO expected fail
not ok 6 (expected fail) Inbound federation can receive invite and reject when remote replies with a 500 # TODO expected fail
not ok 7 (expected fail) Inbound federation can receive invite and reject when remote is unreachable # TODO expected fail
```
