### ISSUE TITLE
Cant Register Any New Accounts With "user_id or device_id mismatch"

### ISSUE THREAD

**Issue by Rayqan** [matrix-org/dendrite#1744]
For some background I'm running dendrite version 3.8 in docker with a traefik instance in front of it terminating ssl. I also have cloudflare in front of traefik proxying requests to it. 

The issue I'm facing is whenever I use nheko to attempt to register a new account on my dendrite instance I get an error "user_id or device_id mismatch users: @test:$MY_DOMAIN_NAME - @test:$MY_DOMAIN_NAME, devices: uIzNhBeP - yhxgIZ_M]]". Looking through the source [here](https://github.com/matrix-org/dendrite/blob/2bfab5f58b77002b1838b52f6edc369ea280ced7/keyserver/internal/internal.go#L475) seems like that error is from a mismatch with the parsed device id and the key's device id.

Thanks for any help.

**Comment by Kegsay** [comment]
This sounds like Nheko is getting confused what its device ID is. If they don't match, this error is returned. Can you try clearing any caches on Nheko and retrying?

**Comment by Rayqan** [comment]
Unfortunately it seems like the error persists even after clearing nheko's cache. However I seem to have been able to get it working with element-desktop. I would assume then that this would be considered a issue on nheko's side?

**Comment by Kegsay** [comment]
Indeed, it does seem that way. We do have integration tests to ensure things like we're using the right device ID for this endpoint, and they are passing: https://buildkite.com/matrix-dot-org/dendrite/builds/4468#93c36d97-79ed-42f0-a775-72d6c1715dba/696-1230 so I don't see there's much for us to do here I'm afraid.
