### ISSUE TITLE
Unable to join room

### ISSUE THREAD

**Issue by Danacus** [matrix-org/dendrite#1746]
### Background information

- **Dendrite version or git SHA**: 0.3.8
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: Docker
- **`go version`**: Not sure, the one from the Docker container I suppose

### Description

While I am able to join other rooms, I am unable to join one specific room. It might be related to roles and permissions.

### Steps to reproduce

I don't know how to reproduce this bug, but in case it's useful, this is what I did:
- Install the Postgres and Dendrite Docker containers on my Raspberry PI 4.
- Create a new user using the Element desktop app.
- Join several rooms on matrix.org without too much issues
- Try to join #Apocalyps-Survivors:matrix.org
- I am now stuck on "Joining room ..."

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

The following error message appears in the log of Dendrite:

```
dendrite_monolith_1  | time="2021-02-01T13:33:45.519619885Z" level=error msg="Failed to process room join response" func="func1\n\t" file=" [github.com/matrix-org/dendrite/federationsender/internal/perform.go:240]" error="gomatrixserverlib: event with ID \"$ntw7bQVfH3wycVTJ-oelecmM9ayMBVx_XJ3yVniUClw\" is not allowed by its auth events: gomatrixserverlib: event with ID \"$ntw7bQVfH3wycVTJ-oelecmM9ayMBVx_XJ3yVniUClw\" is not allowed by its auth_events: eventauth: sender with level 100 is not allowed to change user level from 100 to 50 because the old level is equal to or above the level of the sender" room_id="!QtNcUyGhnaNxVHfyfm:matrix.org" user_id="@daan:vanoverloop.xyz"
```

I'm not really sure why this is happening and whether it is even related to Dendrite. I can join other rooms just fine.

**Comment by Kegsay** [comment]
Probably a bad event somewhere, we'd need to investigate the send_join response.

**Comment by Danacus** [comment]
Feel free to let me know if there's any information/debug logs you want me to provide to investigate this issue.

**Comment by neilalexander** [comment]
This might already be fixed on the latest `master` — can you please try commit 369d3939fdf88546dfdaf8c185125c684c55e991 and let us know if it is still an issue?

**Comment by Danacus** [comment]
That does appear to have fixed it, thanks a lot!

**Comment by neilalexander** [comment]
Glad to hear it!
