### ISSUE TITLE
"unsigned.age" field missing from events

### ISSUE THREAD

**Issue by p-e-w** [matrix-org/dendrite#1754]
### Background information

- **Dendrite version or git SHA**: 0.3.9
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **`go version`**: 1.15

#### Synapse -> Synapse

```
{
  ...
  "origin_server_ts": 1612587703370,
  "unsigned": {
    "age": 4060
  }
}
```

#### Dendrite -> Synapse

The `age` field is missing:

```
{
  ...
  "origin_server_ts": 1612588027946,
  "unsigned": {}
}
```

#### Synapse -> Dendrite

A non-canonical `age_ts` field is present, which appears to always be equal to `origin_server_ts`:

```
{
  ...
  "origin_server_ts": 1612588032002,
  "unsigned": {
    "age_ts": 1612588032002
  }
}
```

### Why this matters

The entire `unsigned` field is explicitly marked as optional by the spec, but the `age` subfield is useful for breaking down latency measurements into more fine-grained metrics. This is done by [PingPong](https://github.com/p-e-w/pingpong), which currently cannot break down latencies when Dendrite is involved because of this issue.

**Comment by neilalexander** [comment]
We've decided to take no action on this at the moment and will revisit if more need arises.
