### ISSUE TITLE
SelectOneTimeKeys takes a significant amount of time

### ISSUE THREAD

**Issue by normen** [matrix-org/dendrite#1757]
### Background information

- **Dendrite version or git SHA**: 0.3.9
- **Monolith or Polylith?**: mono
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: yep
- **`go version`**: 1.15?

### Description
The dendrite instance - despite not being connected to other instances through rooms seems to spike the CPU and database access every 30 seconds. (60MB/s database internal traffic for a few sec) Apparently one-time keys take a significant amount of time. See attached profile.

[profile.zip](https://github.com/matrix-org/dendrite/files/5946905/profile.zip)

My dendrite instance ran for a while since 0.3.4, I nuked the db when this started around 0.3.8.

### Steps to reproduce

- run dendrite

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by neilalexander** [comment]
![Uploading Screenshot 2021-02-08 at 21.11.11.png…]()

**Comment by normen** [comment]
When setting up a backup for dendrite I noticed that the size of a _gzipped_ dump of the `dendrite_keyserver` db is about 80MB, by far the largest db of the bunch.

As said the server is basically empty atm - but federating.

**Comment by kegsay** [comment]
Closing this on the basis that #1851 has helped.
