### ISSUE TITLE
Auto-join room

### ISSUE THREAD

**Issue by danger89** [matrix-org/dendrite#1762]
**Description:**

In Synapse it's possible to auto join rooms, configured in the yml settings (as `auto_join_rooms`). Dendrite doesn't have this feature yet too bad.

This feature will allow homeserver owners to auto join new users to a predefined room on their server.

**Comment by danger89** [comment]
Are we synapse yet?

**Comment by Neboer** [comment]
Come on, this feature is very useful! It've been a long time, please someone add it to this great project.

**Comment by Neboer** [comment]
I've already implemented it and have opened a pull request  #2823 .

**Comment by S7evinK** [comment]
Implemented in https://github.com/matrix-org/dendrite/pull/2823
