### ISSUE TITLE
Limit complex rooms

### ISSUE THREAD

**Issue by danger89** [matrix-org/dendrite#1763]
**Description:**

If some reason Dendrite don't perform well on large and larger rooms. There is no way to limit the joins of complex room (by defining a `room_complexity` value) in Dendrite yml file.

This feature helps home servers owners to better control the usage/performance of the server.

**Comment by Half-Shot** [comment]
We should consider this carefully, room complexity is a synapse feature rather than a specced one which means we shouldn't rush to support it in favour of devising a spec.

**Comment by erkinalp** [comment]
MSC filed: https://github.com/matrix-org/matrix-doc/pull/3059

**Comment by kegsay** [comment]
We would rather just making joining rooms less expensive and faster.

**Comment by danger89** [comment]
As long as Dendrite still have impact on very large rooms. I can't provide my server to the public, without me having the opportunity to limit users to join too complex rooms.
