### ISSUE TITLE
Appservice not getting anything aside from invite events. 

### ISSUE THREAD

**Issue by w3bb** [matrix-org/dendrite#1771]
### Background information

- **0.3.10**
- **Monolith**
- **Postgres**
- **Using the Alpine package, no docker**
- **Go version N/A**

### Description

After setting up an appservice the appservice doesn't seem to receive any events aside from invite events.

### Steps to reproduce

- Install the Dendrite package on Alpine
- Set Dendrite up to work with icewind1991/mx-puppet-steam
- Profit

Dendrite should send all events

In both Dendrite and the appservice, you can see it sends events for room invites, but nothing seems to be logged about message events being sent to the appservice.

Relevant portion of appservice log: https://paste.sr.ht/~welt/c47a6c0ae1e835b739a77cd6e669dce76ac2f803
Appservice registration file: https://paste.sr.ht/~welt/10f98648a51c650dec852fd1e86a9e3095710c62

The only lines I can find with the verbatim name of the bot in the logs are relating to it being invited to said rooms, i.e.:

```msg="processing invite event" func="github.com/matrix-org/dendrite/roomserver/internal/perform.(*Inviter).PerformInvite" file="github.com/matrix-org/dendrite/roomserver/internal/perform/perform_invite.go:64" event_id="$<snip>" room_id="!<snip>:spiderden.net" room_info_exists=true room_version=6 target_user_id="@steampuppet.bot:spiderden.net"```

**Comment by w3bb** [comment]
It also doesn't seem to send events from federated users, although I'm not sure if that should be a separate issue.

**Comment by Half-Shot** [comment]
https://github.com/matrix-org/dendrite/pull/1680 needs to land

**Comment by Half-Shot** [comment]
#1680 has landed.
