### ISSUE TITLE
CORS headers omitted for some endpoints

### ISSUE THREAD

**Issue by nashley** [matrix-org/dendrite#1776]
### Background information

- **Dendrite version or git SHA**: `3069079e37510dbda59b2b272ce133ef81832d7b`
- **Monolith or Polylith?**: `monolith`
- **SQLite3 or Postgres?**: `sqlite`
- **Running in Docker?**: :x: (no)
- **`go version`**: `go1.16 linux/arm`
- Running behind `nginx`. [Config here](https://gist.github.com/nashley/fe55f3a9e58e3523c3a75ab70a58efdc).

### Description

`Access-Control-Allow-Headers` and `Access-Control-Allow-Methods` and `Access-Control-Allow-Origin` aren't specified for the following endpoints:
- `/_matrix/client/r0/joined_groups`
- `/_matrix/client/r0/create_group`
- `/_matrix/client/unstable/room_keys/version`
- `/_matrix/client/r0/pushers`
- `/_matrix/client/r0/publicised_groups`
- `/_matrix/client/r0/user/%40username%3Aserver.address/openid/request_token` (substitute `username` and `server.address`)
- `/_matrix/client/unstable/room_keys/version`
However, they are specified for seemingly every other endpoint. For example, creating & chatting in rooms works just fine.

### Steps to reproduce

- Open developer console's network tab
- Go to self-hosted `https://server.address/#/groups` and try to create a group

I'd expect the appropriate CORS headers to be returned for these endpoints like they are for the others. If that's not desired for some reason, I'd expect a documented explanation.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by neilalexander** [comment]
These endpoints aren't implemented yet. That's why there are no CORS headers returned for them.

**Comment by nashley** [comment]
Ah, I thought that might be the case.
Would it be useful if I submitted a PR to stub them out and return `501`s with the standard CORS headers?

**Comment by neilalexander** [comment]
I'm not sure if a 404 with CORS headers is any better than a 404 without CORS headers?

@Kegsay Any thoughts?

**Comment by Kegsay** [comment]
Please do not attach CORS headers for these endpoints. We have no plans to implement some of them.
