### ISSUE TITLE
Send 202 Accepted on /profile requests

### ISSUE THREAD

**Issue by ChurchOfTheSubgenius** [matrix-org/dendrite#1806]
### Background information

- **Dendrite version or git SHA**: latest master
- **Monolith or Polylith?**: monolith
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: no
- **`go version`**: go1.16

### Description

Updating display name or avatar in a busy Dendrite server with many rooms brings Dendrite to a stop. Dendrite hangs and stops logging when it reaches `SendEvents` on lines [#L172](https://github.com/matrix-org/dendrite/blob/af41f6d4549759afd7f52f780b40abe2834ab4c0/clientapi/routing/profile.go#L172) and [L289](https://github.com/matrix-org/dendrite/blob/af41f6d4549759afd7f52f780b40abe2834ab4c0/clientapi/routing/profile.go#L289) in `clientapi/routing/profile.go`.

### Steps to reproduce

- Update user avatar or display name
- Dendrite halts and needs to be killed/restarted

I can't tell exactly what's happening since Hummingbard's Dendrite logs are very noisy. Commenting out the `SendEvents` functions sets the user avatar and display name properly. I am guessing that `SendEvents` updates the updated profile data in room memberships. I suspect it may have something to do with rooms that no longer exist, either locally or federated.

I cannot reproduce this locally with a fresh Dendrite. Most likely there is a state resolution conflict somewhere, as @neilalexander pointed out to me a while back.

**Comment by kegsay** [comment]
These endpoints will block until all the membership events have been sent, see https://github.com/matrix-org/dendrite/blob/af41f6d4549759afd7f52f780b40abe2834ab4c0/roomserver/internal/input/input.go#L167 - as you are in many rooms this will take a long time. We could probably eagerly return 200 OK, and do something similar to joining rooms (we wait a bit then 202 Accepted it)

**Comment by neilalexander** [comment]
Profile updates are now sent asynchronously to the roomserver, so this endpoint shouldn't block anymore.
