### ISSUE TITLE
State blocks taking too much disk space

### ISSUE THREAD

**Issue by neilalexander** [matrix-org/dendrite#1807]
We're creating a lot of duplicate state snapshots/blocks and I don't think we are cleaning up old ones that are no longer referenced properly either.

We really need to refactor this and I suggest we do away with state blocks together, have the state snapshots be simply an ordered list of event NIDs in a single-column array, and then guarantee uniqueness on that to ensure snapshots are *really* deduplicated.

It's just too expensive to determine when a state block is referenced from multiple snapshots and we really aren't gaining enough in performance to justify it.

**Comment by neilalexander** [comment]
We should also add a room NID column to the state tables so that we can clean up rooms properly and fully implement forgotten rooms.

**Comment by kegsay** [comment]
https://github.com/matrix-org/dendrite/pull/1839 largely fixed this.
