### ISSUE TITLE
Repository takes forever to clone

### ISSUE THREAD

**Issue by turt2live** [matrix-org/dendrite#1808]
it's a 35mb repo for some reason - should recommending clones with `--depth=1`

**Comment by Kegsay** [comment]
Probably because in the past we had a /vendor directory which had all our dependencies in it.

**Comment by Kegsay** [comment]
There isn't much actionable here - we expect users to use a release/docker image and not clone the repo to build.

**Comment by turt2live** [comment]
@Kegsay the first line of https://github.com/matrix-org/dendrite#get-started is "clone the repo"

**Comment by turt2live** [comment]
well, kinda. I'd concede that there is an install link there, but the common install mechanism is:

1. Find the first header that says the thing you're trying to do
2. Copy/paste from the code block under that, or the list if there is none
3. Go back and read the text after it's all broken
