### ISSUE TITLE
RegExp blacklist filters for allowable user/room names

### ISSUE THREAD

**Issue by yaliqmadiq** [matrix-org/dendrite#1829]
**Description:**

It would be nice to have a configuration that blocks registration and local HS room creation where the names match a custom-defined set of regular expressions for unallowed names.

This would greatly help reduce trolling.

For instance, blocking names having variants of the N-word:

```
	re_nban = regexp.MustCompile(`(?m)(?i)N\s*[a-zA-Z0-9$&+,:;=?@#|'<>.^()%!-]\s(?i)(g)\s*[a-zA-Z0-9$&+,:;=?@#|'<>.^()%!-]\s((?i)(e|3)|(?i)(r)|(?i)(a|@|4)+(?i))\s*(?i)(r|t|)`)

```

Another option might also be to strip diacriticals before regexp parsing, like this:

```

func isMn(r rune) bool {
	return unicode.Is(unicode.Mn, r) // Mn: nonspacing marks
}

// StripDiacriticals is meant to get rid of Ed using extra Latin vowel sounds to get around word bans
func StripDiacriticals(input string) string {
	t := transform.Chain(norm.NFD, transform.RemoveFunc(isMn), norm.NFC)
	result, _, _ := transform.String(t, input)
	return result
}

```

**Comment by kegsay** [comment]
We don't have any plan to implement this. Generally speaking, trying to blacklist words is difficult and error-prone and ultimately not really worth it.

For reference, this is a good video on the topic: https://www.youtube.com/watch?v=CcZdwX4noCE
