### ISSUE TITLE
Foreign keys

### ISSUE THREAD

**Issue by iunof** [matrix-org/dendrite#1850]
Hi. I'm learning databases. As i understand foreign keys are the way to referential integrity in RDMS but there are no foreign keys in Dendrite. There are 15 tables in roomserver db but no foreign keys. I found several reasons why people do not use FKs:
- overhead on write because of checks
- easier migrations
I assume 'easier migrations'  is the reason? If i'm wrong could someone explain why Dendrite doesn't use FKs please ?

**Comment by kegsay** [comment]
Mostly this is because of overheads.
