### ISSUE TITLE
proposal: Integrate mediaapi with go-storage to allow store files on various storage service 

### ISSUE THREAD

**Issue by Xuanwo** [matrix-org/dendrite#1857]
## Background

[go-storage](https://github.com/aos-dev/go-storage) is an application-oriented unified storage layer for Golang which allows the user to connect various storage services with the same interface. For now, go-storage supports s3, gcs, azblob, oss, cos, and more supports are on the way: https://github.com/aos-dev/go-storage/issues/536.

mediaapi only supports the local path and makes it hard to scale.

## Proposal

So I propose to integrate mediaapi with go-storage to allow store files on various storage service.

NOTE: we still need a local cache as we need to calculate the sha256 hash of file.

## Implementations

- Replace mediaapi `fileutil` with go-storage.
- Add storage connection string like we did on database.

**Comment by kegsay** [comment]
We have no plans to do this at present. We might extend the mediaapi to support something like https://github.com/turt2live/matrix-media-repo/ but ultimately there are _plenty_ of options here. Dendrite needs to be able to work in embedded environments so a filesysytem backed storage will always be a requirement.
