### ISSUE TITLE
Implement login with email

### ISSUE THREAD

**Issue by PiotrKozimor** [matrix-org/dendrite#1858]
Support for `m.id.thirdparty` identifier type and `medium` field in identifier.
Specs: 
 - https://spec.matrix.org/unstable/client-server-api/#post_matrixclientr0login
 - https://spec.matrix.org/unstable/client-server-api/#identifier-types

Sytest:
`Can login with 3pid and password using m.login.password`

Questions:
 - How do we pass configuration? I suggest `email_login` field in `client_api`.
 - Shall Dendrite send verification emails on its own before enabling this feature?

**Comment by kegsay** [comment]
:S please don't make multiple issues for one issue - move it to https://github.com/matrix-org/dendrite/issues/1298 

> How do we pass configuration? I suggest email_login field in client_api.

sounds good.

> Shall Dendrite send verification emails on its own before enabling this feature?

To some degree it will have to send emails itself I think, what does Synapse do?
