### ISSUE TITLE
Can't reject invite of no-longer existing room

### ISSUE THREAD

**Issue by andir** [matrix-org/dendrite#1861]
### Background information

- **Dendrite version or git SHA**:  2948ffd78207e0fd354be9a3a637cfdaa3c5154a
- **Monolith or Polylith?**:  Monolith
- **SQLite3 or Postgres?**:  SQLite
- **Running in Docker?**:  No.
- **`go version`**: 1.15.10

### Description

Months ago I received several invites for conversations but by the time I saw them I could neither accept nor reject them anymore.

When trying to reject an invite I get:
> Failed to leave room "!IaGVtVRpgDwQuKawsw:xxx.xxxx" through 1 server(s)

When trying to accept any of them:
> You are not invited to this room.

Now I have 21 invites in my Element that I can neither accept nor reject.

### Steps to reproduce

I am not exactly sure how that goes but it might be reproducible by

- Invite a dendrite user from another instance into a chat
- Wait a while for the invite to arrive on the dendrite server
- Remove the channel from the origin server
- On the dendrite client try to join / reject the invite.

**Comment by LecrisUT** [comment]
This might be just an client/element error. Try clearing element's cache in `Settings->Help & About->Clear cache and reload`

**Comment by andir** [comment]
> This might be just an client/element error. Try clearing element's cache in `Settings->Help & About->Clear cache and reload`

I have that across multiple instances of clients (and platforms).

**Comment by LecrisUT** [comment]
I have had similar problems when I manually deleted rooms and that resolved it for me. Try it out and see if that resolves it.

**Comment by andir** [comment]
> I have had similar problems when I manually deleted rooms and that resolved it for me. Try it out and see if that resolves it.

How do you manually delete a channel that you can't see?

**Comment by LecrisUT** [comment]
By channel you mean a room? For synapse there is `synapse-admin`, but if the management API are compatible, you should be able to use it as well. There are other garbage collectors as well, and you can also manually `curl` the API. I personally prefer a VSCode extension to manually interface with some API.

**Comment by kegsay** [comment]
Dupe https://github.com/matrix-org/dendrite/issues/1743 - we're aware of this issue and will try to address this ASAP
