### ISSUE TITLE
Dendrite won't allow invitation rejections unless federation is turned on.

### ISSUE THREAD

**Issue by gleachkr** [matrix-org/dendrite#1873]
### Background information

- **Dendrite version or git SHA**: 2c9a390fa67aa80bd8cfffb02b20739d0b1807d8
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: sqlite3
- **Running in Docker?**: no
- **`go version`**: 1.16 linux/amd64

### Description

Dendrite won't allow invitation rejections unless federation is turned on.

### Steps to reproduce

- set `disable_federation: true` in dendrite.yaml.
- issue an invitation to a room.
- attempt to reject this invitation by accessing the relevant leave endpoint (I was doing this with the js-sdk).

The server then throws a 400 bad request, and the SDK gives the error "failed to leave room ... through 1 server(s)".

The following error appears in the systemd log:

```
Jun 12 16:41:24 dendrite-1 dendrite-monolith-server[465449]: time="2021-06-12T16:41:24.375703525Z" level=warning msg="r.federation.MakeLeave failed" func="PerformLeave\n\t" file=" [github.com/matrix-org/dendrite/federationsender/internal/perform.go:463]" error="Get \"matrix://populus.open-tower.com/_matrix/federation/v1/make_leave/ ETC
Jun 12 16:42:04 dendrite-1 dendrite-monolith-server[465449]: time="2021-06-12T16:42:04.752656729Z" level=warning msg="Outgoing request failed" func="DoHTTPRequest\n\t" file=" [github.com/matrix-org/gomatrixserverlib@v0.0.0-20210216163908-bab1f2be20d0/client.go:495]" error="Get \"matrix://populus.open-tower.com/_matrix/federation/v1/make_leave/ ETC
```

Switching `disable_federation` to false appears to resolve the problem. The problem only seems to arise when rejecting an invitation, not when leaving a room that has been joined, but it was completely reproducible under those conditions.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by kegsay** [comment]
Possibly related: https://github.com/matrix-org/dendrite/issues/1873

**Comment by kegsay** [comment]
@gleachkr please can you try this again on e80098e18630df4ff148c16f741dd72f33e2b1c8 - it should be fixed now.

**Comment by gleachkr** [comment]
Yes, seems to be fixed. Thanks!
