### ISSUE TITLE
Inviting to an unsupported room version return `M_BAD_JSON` instead of `M_UNSUPPORTED_ROOM_VERSION`

### ISSUE THREAD

**Issue by clokep** [matrix-org/dendrite#1878]
### Background information

This was tested against dendrite.matrix.org

- **Dendrite version or git SHA**: 
- **Monolith or Polylith?**: 
- **SQLite3 or Postgres?**: 
- **Running in Docker?**: 
- **`go version`**: 

### Description

Sending an invite to a Dendrite instance from a Synapse instance with an experimental room version fails (as expected), but uses the incorrect error code (`M_BAD_JSON` instead of `M_UNSUPPORTED_ROOM_VERSION`).

### Steps to reproduce

* Setup a Synapse (v1.36.0 should work)
* Create a room with an experimental room version (create a room, then upgrade it in Element Web with `/upgraderoom org.matrix.msc3083`)
* Invite a user on Dendrite
* The user will see an error:

![image](https://user-images.githubusercontent.com/2403652/122204723-5b2d2180-ce97-11eb-9d1d-e78c895e7587.png)

Dendrite returns `M_BAD_JSON`.

![image](https://user-images.githubusercontent.com/2403652/122204965-a0515380-ce97-11eb-81a8-d08867b78a18.png)

### Expected results

Dendrite returns an error like:

```
{"errcode":"M_UNSUPPORTED_ROOM_VERSION","error":"Homeserver does not support this room version"}
```

This helps client give an actionable response to the user.

**Comment by meenal06** [comment]
Hey @kegsay Can I work on this?
