### ISSUE TITLE
Account deactivation breaks after 1 deactivation until restart

### ISSUE THREAD

**Issue by 0x1a8510f2** [matrix-org/dendrite#1942]
### Background information

- **Dendrite version or git SHA**: 0.4.1
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: Yes
- **`go version`**: Whatever 0.4.1 was build with

### Description

After an account is deactivated, no more accounts can be deactivated until the server restarts. After restart, only one account can be deactivated again. When attempting to deactivate another account, the following appears in Element Web:

![image](https://user-images.githubusercontent.com/83190128/127015907-7b6c89ae-e02b-4ed5-9988-171ce0be7e12.png)

### Steps to reproduce

- create account on Dendrite
- deactivate said account while selecting "forget messages" (not sure if the last bit is relevant)
- create another account
- attempt to deactivate the second account and see screen as in screenshot below

There don't seem to be any relevant logs

**Comment by kegsay** [comment]
I think this is because this endpoint should be gated behind a `sudo` style "re-auth please" prompt, but Dendrite isn't asking for that on a subsequent go?

To check:
 - Both accounts created have different user IDs?
 - Did you use the same Element-Web browser session when making the 2nd account?

**Comment by 0x1a8510f2** [comment]
Both have different MXID localparts, but I did use the same browser session (if I understood correctly), that is, I deactivated one account which signed me out, then created another account from the same EW without reloading or anything.

**Comment by kegsay** [comment]
Does it work correctly if you use a different browser session for the 2nd account deactivation?

**Comment by 0x1a8510f2** [comment]
It doesn't seem to work correctly, no. I've opened EW in a private tab, deactivated the account, closed the private window, opened another private window and repeated the process to no avail.

**Comment by D4v1dH03** [comment]
I'm experiencing the same issue on `dendrite.matrix.org` homeserver and I cannot self deactivate my account.
