### ISSUE TITLE
Migration fails when using pgbouncer for postgres pooling

### ISSUE THREAD

**Issue by mkroman** [matrix-org/dendrite#1955]
### Background information

- **Dendrite version or git SHA**: Dendrite v0.4.1
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: PostgreSQL 13 with pgbouncer
- **Running in Docker?**: Kubernetes + containerd with the dendrite-monolith docker image
- **`go version`**: [1.15](https://github.com/matrix-org/dendrite/blob/v0.4.1/build/docker/Dockerfile.monolith#L1)

### Description

When running Dendrite where the services are using postgresql as the database, but the database is pooled behind [pgbouncer](https://www.pgbouncer.org/), the migration fails:

```
INFO[2021-08-03T05:22:56.143343205Z] [base.go:113] NewBaseDendrite
	 Dendrite version 0.4.1
PANI[2021-08-03T05:22:56.150902850Z] [base.go:286] CreateAccountsDB
	 failed to connect to accounts db              error="pq: prepared statement \"1\" already exists"
panic: (*logrus.Entry) 0xc0003d84d0

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc0003d8460, 0x0, 0xc0003e2120, 0x20)
	github.com/sirupsen/logrus@v1.8.1/entry.go:259 +0x2e5
github.com/sirupsen/logrus.(*Entry).Log(0xc0003d8460, 0x0, 0xc0002f5cd8, 0x1, 0x1)
	github.com/sirupsen/logrus@v1.8.1/entry.go:293 +0x86
github.com/sirupsen/logrus.(*Entry).Logf(0xc0003d8460, 0x0, 0x12711ce, 0x20, 0x0, 0x0, 0x0)
	github.com/sirupsen/logrus@v1.8.1/entry.go:338 +0xe5
github.com/sirupsen/logrus.(*Entry).Panicf(...)
	github.com/sirupsen/logrus@v1.8.1/entry.go:376
github.com/matrix-org/dendrite/setup.(*BaseDendrite).CreateAccountsDB(0xc00017f200, 0x125446d, 0x8)
	github.com/matrix-org/dendrite/setup/base.go:286 +0x105
main.main()
	github.com/matrix-org/dendrite/cmd/dendrite-monolith-server/main.go:76 +0x197
```

pgbouncer [does not support prepared statements](https://www.pgbouncer.org/faq.html#how-to-use-prepared-statements-with-transaction-pooling), so it will have to be disabled in the client.

The `pq` module has solved this with the connection parameter `binary_parameters=true` as [described here](https://blog.bullgare.com/2019/06/pgbouncer-and-prepared-statements/#Solution_-_using_binary_parameters_query_mode), but this does not change the behavior in Dendrite.

I believe this is because Dendrite depends on goose v2.7.0 which in turn depends on [`pq` v1.1](https://github.com/pressly/goose/commit/37648a7ab31947b6f8ed2db9a8d1f74df9c559bf), which is already very old.

There's a [v3 working branch](https://github.com/pressly/goose/tree/go-modules) that adds support for go modules and has updated `pq` to `v1.10.2`. This might solve it, but I haven't tested it.

### Steps to reproduce

- Run Dendrite monolith with postgres
- Connect to the database via pgbouncer instead of directly

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by S7evinK** [comment]
Closing this, as we recently removed goose as the migration tool.
If this is still an issue with Dendrite v0.9.0, we can reopen this.
