### ISSUE TITLE
Deleting a multimedia message in an E2EE room works, but the deleted message is "unable to be decrypted"

### ISSUE THREAD

**Issue by 9p4** [matrix-org/dendrite#1966]
### Background information

- **Dendrite version or git SHA**: 0.4.1
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **`go version`**: `go version go1.15.2 linux/amd64`

### Description

Deleting a multimedia message in an E2EE room appears to succeed, but then it returns an error when viewing the message again: `** Unable to decrypt: Unknown encryption algorithm "undefined". **`

### Steps to reproduce

- Create an E2EE room
- Send an image
- Delete the image
- Reopen the client to see the error message

I expected to see "This message was deleted"

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by kegsay** [comment]
What client were you running for this?

**Comment by 9p4** [comment]
Element Desktop (I forget the version as this was a while back).

I checked again just now and it seems like the issue isn't there anymore. I'll reopen this if it comes back.
