### ISSUE TITLE
M_ROOM_IN_USE is not used

### ISSUE THREAD

**Issue by nivekuil** [matrix-org/dendrite#1971]
Dendrite doesn't return the error code, only a string. How synapse does it: https://github.com/matrix-org/synapse/blob/d0b294ad974c05621426369a00be6bf05c4af997/synapse/handlers/room.py#L660 

mx-puppet-bridge needs this error code https://github.com/Sorunome/mx-puppet-bridge/blob/b85e37f6e7f4848442aa5901d7df869bf33fa3db/src/roomsyncroniser.ts#L286

**Comment by neilalexander** [comment]
Fixed by #1972, thanks for contributing it!
