### ISSUE TITLE
Cannot join mx-slack bridge room with more than 2 members : "CheckAuthEvents failed for event"

### ISSUE THREAD

**Issue by Notmarrco** [matrix-org/dendrite#1975]
Hello,

### Background information

- **Dendrite version or git SHA**:  0.4.1
- **Monolith or Polylith?**:  Monolyth
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: no
- **`go version`**: 1.15.9 (buster backports)

### Description

I have a slack bridge, but dendrite refuse that I join some channels.

### Steps to reproduce

- installing dendrite and slack bridge with sorunome mx-puppet-slack
- linking to a slack workspace
- listrooms for the slack bridge
- trying to access to rooms (by clicking on the listrooms result) yield a "user is not allowed to change their membership from leave to join" error

For some rooms/channel it works though but I cannot find why : some are private some are public, and it doesn't seem to affect my authorization to join or not. (fwiw I am admin of the workspace) 

First I thought it was a bridge error but it's dendrite that refuse me to join the rooms. Sorry if I'm mistaken.

(edit : not related) ~On a side note, I saw in the github issues that there was a problem with federated rooms with the same error. I have tested my federated status with the matrix federation tester, and all seems good. However when I try to invite someone from my other dendrite (I have 2 , to test federation) the room is created, the user is invited, but it cannot accept the invitation ("fail to join the room" with "unkown error"). So it may be a bad configuration from me, or because one server can do ipv4 only and the other ipv6+ipv4.~

Is there more info that I can provide ? I have no idea where / what to look for.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

```
time="2021-08-13T10:36:11.739578496Z" level=error msg="helpers.CheckAuthEvents failed for event, rejecting event" func="github.com/matrix-org/dendrite/roomserver/internal/input.(*Inputer).processRoomEvent" file="/opt/dendrite/roomserver/internal/input/input_events.go:106" auth_event_ids="[$FC9SthiWVNSL4H1QSE4o0XQBXBGfAMcHeEMp7kLRn_s $aSkhwXnolPYpuWMs4d_Tjh8CoLVRv9pMnunUmgjiHSU $l9CIiUDrLfOQMr1L8INspFY9Hc5GJUW3BYXE0ksfjpE]" error="eventauth: \"@myuser:mydomain.fr\" is not allowed to change their membership from \"leave\" to \"join\"" event_id="$8SxnJU6XZM8NpwXuAWF2btfRnUOFtVDYCQsA988xUbY"
time="2021-08-13T10:36:11.741465877Z" level=info msg="Error authing soft-failed event" func="github.com/matrix-org/dendrite/roomserver/internal/input.(*Inputer).processRoomEvent" file="/opt/dendrite/roomserver/internal/input/input_events.go:120" error="eventauth: \"@myuser:mydomain.fr\" is not allowed to change their membership from \"leave\" to \"join\"" event_id="$8SxnJU6XZM8NpwXuAWF2btfRnUOFtVDYCQsA988xUbY" room="!FcZUHCcUaHycxdDe:mydomain.fr" type=m.room.member
time="2021-08-13T10:36:11.750148536Z" level=debug msg="Stored rejected event" func="github.com/matrix-org/dendrite/roomserver/internal/input.(*Inputer).processRoomEvent" file="/opt/dendrite/roomserver/internal/input/input_events.go:189" event_id="$8SxnJU6XZM8NpwXuAWF2btfRnUOFtVDYCQsA988xUbY" room="!FcZUHCcUaHycxdDe:mydomain.fr" sender="@myuser:mydomain.fr" soft_fail=true type=m.room.member
```
### EDIT

Found out that the issue seems to be when joining slack channels with more than 2 members (>= 3). I opened an issue in the mx-slack github but since it seems to be working with synapse, it's possible that it's a dendrite issue.

Thank you

**Comment by kegsay** [comment]
I think this is due to `/createRoom`'s default public|private room value. Dendrite follows the spec:

<img width="927" alt="Screenshot 2022-01-21 at 10 19 29" src="https://user-images.githubusercontent.com/7190048/150510240-5986b8e4-3d4f-4213-b930-8b38c2bd5730.png">

Whereas synapse does not. https://github.com/matrix-org/synapse/issues/11498 - This could cause a problem if the bridge is calling this endpoint without an explicit `visibility` and the behaviour will vary between server implementations. Please re-open this if you have relevant logs to show that the bridge is in fact sending `visibility`.
