### ISSUE TITLE
Build failed on Windows (logrus/syslog)

### ISSUE THREAD

**Issue by NikitaPuzyryov** [matrix-org/dendrite#1980]
### Background information

- **Dendrite version or git SHA**: master (329c9e6) (bisected to 1bee1ae)
- **Monolith or Polylith?**: Monolith or Pinecone demo (the ones I tried)
- **SQLite3 or Postgres?**: -
- **Running in Docker?**: -
- **`go version`**: go1.17 windows/amd64

### Description

The following error is thrown when trying to build Dendrite on Windows 10:
```
> go build .\cmd\dendrite-demo-pinecone
package github.com/matrix-org/dendrite/cmd/dendrite-demo-pinecone
        imports github.com/matrix-org/dendrite/appservice
        imports github.com/matrix-org/dendrite/appservice/api
        imports github.com/matrix-org/dendrite/userapi/storage/accounts
        imports github.com/matrix-org/dendrite/internal
        imports github.com/sirupsen/logrus/hooks/syslog: build constraints exclude all Go files in <snip>\go\pkg\mod\github.com\sirupsen\logrus@v1.8.1\hooks\syslog
```

**Comment by alexfca** [comment]
We received the same error when attempting to compile/run the latest (0.5.0) version on Windows as well.
Just flagging so I am notified of any updates, and thanks @NikitaPuzyryov for logging
