### ISSUE TITLE
Unable to remove old sessions

### ISSUE THREAD

**Issue by alistair23** [matrix-org/dendrite#1984]
### Background information

- **Dendrite version or git SHA**: 329c9e671c763ce3f7adc8c734246eb53b47df94
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **`go version`**: 1.15.6

### Description

When using Element I see a list of devices in my profile.

Some of the devices match what I see under `Where you’re logged in` in the Security and Privacy section. I can change the name, verify them and they work correctly.

There are also some devices that aren't listed under `Where you’re logged in`. These are old devices that are no longer used. They are unverified (as I can't verify them) and there is no way to remove them or change the names.

### Steps to reproduce

- Compare the list in Element's `Where you’re logged in` the the user profile.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by neilalexander** [comment]
This happened I suppose because the user API's device list and the key server's device list got out of sync. The `Where you're logged in` section will be reporting keys from the user API, but the device list in the user profile will be reporting keys from the key server.

I think this bug is actually already fixed by the introduction of the `PerformDeleteKeys` API on the key server in #1979, as the user API will now tell the key server to delete keys when deleting a device.

We will need to think about how to clean up stale entries from before the fix.

**Comment by alistair23** [comment]
Any update on this? Even being able to manually fix it would work

**Comment by alistair23** [comment]
Any ideas?

**Comment by kegsay** [comment]
@alistair23 can you try this on latest master please - https://github.com/matrix-org/dendrite/commit/2c581377a5f6b243300445947fd0fd38a919873d

I cannot reproduce this issue by doing the following:
 - Sign in on Element-Web
 - Sign in on Element-Web again in incognito tab.
 - Verify 2 devices present on `Where you're signed in`
 - Verify 2 devices present on list of devices for my user (by clicking the user in a member list in a room).
 - Logout of incognito session by hitting the Logout button.
 - Verify 1 device present on `Where you're signed in`
 - Verify 1 device present on list of devices for my user (by clicking the user in a member list in a room).

Versions:
```
Element version: 869b271f72f9-react-869b271f72f9-js-869b271f72f9
Olm version: 3.2.8
```

**Comment by alistair23** [comment]
So I don't think you can get into this state anymore as @neilalexander pointed out, it has been fixed. The problem is that for people who had sessions before the fix, there is no way to cleanup the old sessions.

I'm guessing that some SQL commands would work or resetting all sessions, but I have no idea how to do either.

**Comment by alistair23** [comment]
This seems to be fixed with https://github.com/matrix-org/dendrite/pull/2186

**Comment by kegsay** [comment]
That is probably because that PR logged out all active sessions.
