### ISSUE TITLE
Dendrite puts Element into a loop that floods requests, when a user's attempt to register fails because username already exists. Synapse doesn't.

### ISSUE THREAD

**Issue by techmindful** [matrix-org/dendrite#1999]
### Background information

- **Dendrite version or git SHA**: 
commit 329c9e671c763ce3f7adc8c734246eb53b47df94
- **Monolith or Polylith?**: 
Monolith
- **SQLite3 or Postgres?**: 
SQLite3
- **Running in Docker?**: 
No
- **`go version`**: 
go1.17 linux/amd64

### Description

*This may look like an Element issue, but it doesn't happen if I use Synapse (Debian pre-built package from Apt, version 1.41.1+buster1). So I decided to post it here.*

After building and running Dendrite, I followed the steps [here](https://github.com/techmindful/element-web#setting-up-a-dev-environment) to start working on Element locally. If I try to register with a username that already exists, the browser's developer console gets flooded with:
```
POST http://localhost:8008/_matrix/client/r0/register 429 (Too Many Requests)
Active flow => {"stages":["m.login.dummy"]}
Next stage: m.login.dummy
```
Sometimes the 429 is replaced with 400.
Element seems to constantly loop back to [this line of code](https://github.com/matrix-org/matrix-js-sdk/blob/37736184a0eb8c78fb1b88b7952f803a91ef6cbf/src/interactive-auth.ts#L540). 

### Steps to reproduce

- Follow the steps [here](https://github.com/matrix-org/dendrite#get-started) to build and run Dendrite.
- Follow the steps [here](https://github.com/vector-im/element-web#setting-up-a-dev-environment) to build and run Element. At the time of writing:
  - `matrix-js-sdk` is at commit 3c36be9839091bf63a4850f4babed0c976d48c0e
  - `matrix-react-sdk` is at commit 7a083946866e9f28917cc90c65c51f8cc3ad01d8
  - `element-web` is at commit b73e2fc27ddab856958ae3c5f27f5821bf3d939f.
- Register a user with Element. Then try to register another user with the same username. The browser's developer console will be flooded.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

Here's the log from Dendrite:
```
INFO[2021-09-02T08:22:41.805652685Z] [base.go:113] NewBaseDendrite                                                                                                           
         Dendrite version 0.5.0-rc1+329c9e67                                                                                                                                 
INFO[2021-09-02T08:22:41.806983568Z] [signingkeyserver.go:103] NewInternalAPI                                                                                                
         Enabled perspective key fetcher               num_public_keys=2 server_name=matrix.org                                                                              
INFO[2021-09-02T08:22:41.819530029Z] [base.go:429] func2                                                                                                                     
         Starting external Monolith listener on :8008                                                                                                                        
INFO[2021-09-02T08:22:41.819557285Z] [base.go:429] func2                                                                                                                     
         Starting external Monolith listener on :8448                                                                                                                        
INFO[2021-09-02T08:22:55.948568850Z] [register.go:523] Register                                                                                                              
         Processing registration request               auth.type="" req.id=vPFcV9fCzRLV req.method=POST req.path=/_matrix/client/r0/register session_id="" username=test0    
INFO[2021-09-02T08:22:55.963175774Z] [register.go:523] Register                                                                                                              
         Processing registration request               auth.type=m.login.dummy req.id=hV7XVH20DKXA req.method=POST req.path=/_matrix/client/r0/register session_id=dPJfOTuSm8
mCCawZqx5EX6Ra username=test0                                                                                                                                                
INFO[2021-09-02T08:22:56.028506904Z] [register.go:523] Register                                                                                                              
         Processing registration request               auth.type=m.login.dummy req.id=4eBO5kyAwTQe req.method=POST req.path=/_matrix/client/r0/register session_id=dPJfOTuSm8
mCCawZqx5EX6Ra username=test0                                                                                                                                                
INFO[2021-09-02T08:22:56.110464955Z] [register.go:523] Register                                                                                                              
         Processing registration request               auth.type=m.login.dummy req.id=UogiwYCpKflz req.method=POST req.path=/_matrix/client/r0/register session_id=dPJfOTuSm8
mCCawZqx5EX6Ra username=test0
...
```
The rest of the logs are all repetitions of the last line.

**Comment by kegsay** [comment]
Cannot reproduce on:
```
Element version: 869b271f72f9-react-869b271f72f9-js-869b271f72f9
Olm version: 3.2.8
```
<img width="875" alt="Screenshot 2022-01-21 at 10 56 56" src="https://user-images.githubusercontent.com/7190048/150515605-f14e1587-ee41-4a67-b3c7-71c910d809f0.png">
