### ISSUE TITLE
Dendrite and Jocko

### ISSUE THREAD

**Issue by voxadam** [matrix-org/dendrite#200]
Is there any reason to think that Dendrite wouldn't work with Travis Jeffery's Go implementation of Kafka, [Jocko](https://github.com/travisjeffery/jocko), instead of Apache Kafka? Jocko is still a young project and is still missing some Kafka features but a single binary version of Kafka with no dependency on ZooKeeper has obvious appeal.

**Comment by NegativeMjark** [comment]
Jocko claims that it has protocol compatibility with kafka. I don't think we are doing anything particularly exotic when talking to kafka so I guess it should Just Work™ if we point the dendrite config at a Jocko installation.
