### ISSUE TITLE
Export selection of users to new server

### ISSUE THREAD

**Issue by joblogmans** [matrix-org/dendrite#2006]
Hi all,

I am considering setting up a Matrix home server at my fathers server until I get my own place. This raised the issue of exporting all the data of specific users to a completely new server (i.e. my own). In Synapse this is not possible, but adding this as a feature would really add to the decentralization of Matrix communication.

**Description:** Option to export selection of users to new server with all data.

**Advantages:**
- Easy start for new users as they can start with a VPS, a friends server or a public Dendrite server and then move on to their own server.
- Back-ups of personal data from public servers.
- Less dependency on specific servers as migrating specific users is relatively easy (or at least possible).

**Possible issues:** username might be an issue as the domain of the new server will be different.

**Example:**
Server 1: users: person1, person2, person3.
person1 and person2 build their own server and want their data on there.
Server 1 exports person1 & person2 which get imported into server 2 with all data available.
Server 1 continues as before but will no longer manage person1 and person2, but will still manage person3. Server 2 is now in charge of person1 and person2.

Not necessary in the short-term, but very nice feature for the long-term.

**Comment by kegsay** [comment]
Please add your comments and suggestions to https://github.com/matrix-org/matrix-doc/issues/915
