### ISSUE TITLE
sytest `Local device key changes appear in /keys/changes` flakes

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/dendrite#2007]
In https://github.com/matrix-org/sytest/pull/1129#issuecomment-913825396 we noticed that a specific sytest that would intermittently fail, but seemingly only for dendrite running _without_ full HTTP APIs.

 In that PR I wasn't modifying dendrite---just sytest's GHA config. It should have been fetching dendrite's master branch throughout. Not sure if there's a flakey test or a problem in dendrite? @anoadragon453  suggested I get it down in writing here. Happy to move it to sytest if we can confirm it's not a dendrite problem.

Some specific sytest runs:
- https://github.com/matrix-org/sytest/runs/3525244956
- https://github.com/matrix-org/sytest/runs/3524830553 
- https://github.com/matrix-org/sytest/runs/3527233610
- https://github.com/matrix-org/sytest/actions/runs/1215486987 (failing on sqlite)
- https://github.com/matrix-org/sytest/pull/1134/checks?check_run_id=3566373941 failing on sqlite no full http; postgres + full http

And also seen on buildkite:
- https://buildkite.com/matrix-dot-org/sytest/builds/1581#b1e10cd8-9a02-4e9f-911b-1d53571effca

### Background information

- **Dendrite version or git SHA**:  "Dendrite version 0.5.0"
- **Monolith or Polylith?**: monolith
- **SQLite3 or Postgres?**:  Postgres
- **Running in Docker?**: yes
- **`go version`**: unsure

**Comment by S7evinK** [comment]
Going to close this, haven't seen this one fail in quite some time.
Also removed the test from our blacklist, as we might not have seen any failures because of that. (I've checked several recent runs and didn't see it fail, though)
