### ISSUE TITLE
Dendrite does not implement MSC3375 (Room v9)

### ISSUE THREAD

**Issue by BratishkaErik** [matrix-org/dendrite#2010]
### Background information

- **Dendrite version or git SHA**: commit ba2f456e86b0cb06f95c28da09d84d5a997b3d7e
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **`go version`**: go1.17.2 linux/amd64

Logs:
M_INCOMPATIBLE_ROOM_VERSION: Your homeserver does not support the features required to interact with this room

**Comment by BratishkaErik** [comment]
I will test b4a007ecceafd2b93fee2e775b0a61283d4a3844

**Comment by neilalexander** [comment]
Joining v8 and v9 rooms should work as of v0.5.1.
