### ISSUE TITLE
clientapi KeyBackupVersion returning 500 instead of 404.

### ISSUE THREAD

**Issue by marcialvieira** [matrix-org/dendrite#2016]
### Background information

- **Dendrite version or git SHA**: 0.5.0
- **Monolith or Polylith?**: Polylith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: Docker (matrixdotorg/dendrite-polylith:latest)
- **`go version`**: go1.17

### Description

Attempting to "Set up Secure Backup" on the "Element Web Client", the `/_matrix/client/unstable/room_keys/version` request fail with `500 Internal Server Error` instead of 404, as you can see in the code.

https://github.com/matrix-org/dendrite/blob/master/clientapi/routing/key_backup.go#L96,L104

### Steps to reproduce

```
curl 'http://client_api:8071/_matrix/client/unstable/room_keys/version' -i  -H 'Connection: keep-alive'   -H 'accept: application/json'   -H 'DNT: 1'   -H 'Authorization: Bearer nAaBZBH_LCbcFHA0exTrTLILP3j50-AxWXLMl4vUGI4'   -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36'   -H 'Sec-GPC: 1'   -H 'Sec-Fetch-Site: same-origin'   -H 'Sec-Fetch-Mode: cors'   -H 'Sec-Fetch-Dest: empty'   -H 'Accept-Language: en-US,en;q=0.9,pt-BR;q=0.8,pt;q=0.7'   -H 'Cookie: ph_phc_Jzsm6DTm6V2705zeU5dcNvQDlonOR68XvX2sh1sEOHO_posthog=%7B%22distinct_id%22%3A%2217c1429fd3183d-0b60d59a2fc38e-192b1d0f-1ea7ee-17c1429fd3298a%22%2C%22%24device_id%22%3A%2217c1429fd2d6f6-0639b2633da76-192b1d0f-1ea7ee-17c1429fd2e937%22%2C%22appVersion%22%3A%22v1.8.5%22%2C%22appPlatform%22%3A%22Web%20Platform%22%2C%22%24session_recording_enabled%22%3Afalse%2C%22%24active_feature_flags%22%3A%5B%5D%7D'   --compressed
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Content-Type: application/json
Date: Tue, 05 Oct 2021 18:04:09 GMT
Content-Length: 100

{"message":"QueryKeyBackup: Internal API: 404 from http://user_api:7781/api/userapi/queryKeyBackup"}
```
<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by Agorise** [comment]
Yep, the first time I try to logout, it ops up that modal that asks me to save my keys, but then I accept that and the spinner just spins and spins. It won't let me see or save my mnemonic etc. 
 
Also, I have noticed that in the settings screen, it won't save my personal settings either (like dark theme, my email and phone number, etc).  
 
Please see attached screenshots: 
![image (1)](https://user-images.githubusercontent.com/31280836/136081436-d23371ea-7ff7-426d-9bf7-36a2e3009b7a.png)
![image](https://user-images.githubusercontent.com/31280836/136081442-e8aee43e-06d2-4f45-b9a1-9b07145f3b7f.png)

**Comment by kegsay** [comment]
@S7evinK can you confirm the fix here?

**Comment by S7evinK** [comment]
Yep, all good now.
