### ISSUE TITLE
Failed to get server ACLs for room \"!enSliztFdoJNZxcBir:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !enSliztFdoJNZxcBir:matrix.womo.site doesn't exist"

### ISSUE THREAD

**Issue by yswtrue** [matrix-org/dendrite#2027]
### Background information

- **Dendrite version or git SHA**:  v0.5.0
- **Monolith or Polylith?**:  Polylith
- **SQLite3 or Postgres?**:  Postgres
- **Running in Docker?**:  Yes
- **`go version`**:  k8s v1.21.2-eks-06eac09 with containerd://1.4.6

### Description

I have deployed a dendrite and a Synapse server for federation comminute, when I restart dendrite room server, room server get this log.

### Steps to reproduce

- run a Synapse server
- run a dendrite server
- direct chat with each other
- restart dendrite server

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->
```
time="2021-10-22T08:09:22.303637151Z" level=error msg="Failed to get server ACLs for room \"!VbEIdMjVcWNOulmcde:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !VbEIdMjVcWNOulmcde:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.314690238Z" level=error msg="Failed to get server ACLs for room \"!ZcOaUQDyMfpXDzkfAS:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !ZcOaUQDyMfpXDzkfAS:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.323678961Z" level=error msg="Failed to get server ACLs for room \"!VENIotSqXvZSycYkgX:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !VENIotSqXvZSycYkgX:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.333505722Z" level=error msg="Failed to get server ACLs for room \"!yhDJOgvXPQovbmdbLI:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !yhDJOgvXPQovbmdbLI:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.343613155Z" level=error msg="Failed to get server ACLs for room \"!lKwHAbBwjvpidVPBmx:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !lKwHAbBwjvpidVPBmx:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.351537508Z" level=error msg="Failed to get server ACLs for room \"!TWZaMNmxxVEvbfsUPo:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !TWZaMNmxxVEvbfsUPo:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.362373689Z" level=error msg="Failed to get server ACLs for room \"!VSqtnfVPcKTNcFwaMg:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !VSqtnfVPcKTNcFwaMg:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.371585522Z" level=error msg="Failed to get server ACLs for room \"!BQdbupUgVvKaOTlZRt:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !BQdbupUgVvKaOTlZRt:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.380887434Z" level=error msg="Failed to get server ACLs for room \"!VVYnMRcGKmQPNTQQZY:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !VVYnMRcGKmQPNTQQZY:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.391003873Z" level=error msg="Failed to get server ACLs for room \"!eDmrWyAPDZchjQyKSm:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !eDmrWyAPDZchjQyKSm:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.400777414Z" level=error msg="Failed to get server ACLs for room \"!zvzPYquoHEZraZEhXh:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !zvzPYquoHEZraZEhXh:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.410798616Z" level=error msg="Failed to get server ACLs for room \"!MnHWJCzRnHKcxikIap:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !MnHWJCzRnHKcxikIap:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.420425506Z" level=error msg="Failed to get server ACLs for room \"!YiaHhOcqhKIBgZMXBx:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !YiaHhOcqhKIBgZMXBx:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.430022424Z" level=error msg="Failed to get server ACLs for room \"!ldOrauRugZpouNiKkG:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !ldOrauRugZpouNiKkG:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.439498657Z" level=error msg="Failed to get server ACLs for room \"!exYSeVZAybFLuBtXTH:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !exYSeVZAybFLuBtXTH:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.448763976Z" level=error msg="Failed to get server ACLs for room \"!rFCfaJBBTsjAdzWYLC:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !rFCfaJBBTsjAdzWYLC:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.458587646Z" level=error msg="Failed to get server ACLs for room \"!OmVrOPWmJIrzRXfHYw:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !OmVrOPWmJIrzRXfHYw:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.468355283Z" level=error msg="Failed to get server ACLs for room \"!xQDSHLwOGwiSllMmtM:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !xQDSHLwOGwiSllMmtM:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.478947814Z" level=error msg="Failed to get server ACLs for room \"!wSYtYDRRVqDBydXDUk:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !wSYtYDRRVqDBydXDUk:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.487979749Z" level=error msg="Failed to get server ACLs for room \"!HvVGvmWydqHNqqKRML:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !HvVGvmWydqHNqqKRML:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.498413393Z" level=error msg="Failed to get server ACLs for room \"!KmfYZkyFWJjbCebByZ:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !KmfYZkyFWJjbCebByZ:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.507457474Z" level=error msg="Failed to get server ACLs for room \"!bGJyOkqhRHPmEzjpVa:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !bGJyOkqhRHPmEzjpVa:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.517342819Z" level=error msg="Failed to get server ACLs for room \"!mjrsjrKKdzcaQtHCbb:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !mjrsjrKKdzcaQtHCbb:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.526892062Z" level=error msg="Failed to get server ACLs for room \"!qLSuUhyQYxueFroSHQ:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !qLSuUhyQYxueFroSHQ:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.555356820Z" level=error msg="Failed to get server ACLs for room \"!IlCnYikWcmLjohvmmk:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !IlCnYikWcmLjohvmmk:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.555956715Z" level=error msg="Failed to get server ACLs for room \"!rKoVAcSMbcceXWbZEE:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !rKoVAcSMbcceXWbZEE:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.556496700Z" level=error msg="Failed to get server ACLs for room \"!NsWIrBCoubXnybHmXN:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !NsWIrBCoubXnybHmXN:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.563847862Z" level=error msg="Failed to get server ACLs for room \"!frojOjDCaGBeZGIZQY:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !frojOjDCaGBeZGIZQY:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.573493671Z" level=error msg="Failed to get server ACLs for room \"!UTqHGSpMLxDONvSvIA:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !UTqHGSpMLxDONvSvIA:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.583855937Z" level=error msg="Failed to get server ACLs for room \"!TeIrHWIVriwmAnTEuE:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !TeIrHWIVriwmAnTEuE:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.593487277Z" level=error msg="Failed to get server ACLs for room \"!YRQMLAAsLNrutJCrOM:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !YRQMLAAsLNrutJCrOM:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.603213726Z" level=error msg="Failed to get server ACLs for room \"!pmIJYbGVktLrAVqQEh:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !pmIJYbGVktLrAVqQEh:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.613137898Z" level=error msg="Failed to get server ACLs for room \"!QeuWninRJDyhgPzmbK:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !QeuWninRJDyhgPzmbK:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.626609722Z" level=error msg="Failed to get server ACLs for room \"!BQGazpqDyIptlilieS:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !BQGazpqDyIptlilieS:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.637138576Z" level=error msg="Failed to get server ACLs for room \"!UvxWYZERggjnLsjdRd:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !UvxWYZERggjnLsjdRd:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.645665588Z" level=error msg="Failed to get server ACLs for room \"!KSbrJgPGYvLCUpQkpR:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !KSbrJgPGYvLCUpQkpR:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.655187481Z" level=error msg="Failed to get server ACLs for room \"!uOUxeZFPJutVEayFMV:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !uOUxeZFPJutVEayFMV:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.664749042Z" level=error msg="Failed to get server ACLs for room \"!dgmkqFzKgRfDzKFejK:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !dgmkqFzKgRfDzKFejK:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.674735401Z" level=error msg="Failed to get server ACLs for room \"!xXzFfLZxoIBUWuJaZj:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !xXzFfLZxoIBUWuJaZj:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.684311569Z" level=error msg="Failed to get server ACLs for room \"!ifxNkpPdpzYpbhvMCA:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !ifxNkpPdpzYpbhvMCA:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.693946063Z" level=error msg="Failed to get server ACLs for room \"!LhRnIwsrFgreOQTgsp:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !LhRnIwsrFgreOQTgsp:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.703952170Z" level=error msg="Failed to get server ACLs for room \"!sokoOSWfuyCNjSvHJv:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !sokoOSWfuyCNjSvHJv:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.712845051Z" level=error msg="Failed to get server ACLs for room \"!QTXLPEkPaBOaCYHsOp:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !QTXLPEkPaBOaCYHsOp:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.724058737Z" level=error msg="Failed to get server ACLs for room \"!ixIYGoRAsSosKTAlLK:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !ixIYGoRAsSosKTAlLK:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.734005747Z" level=error msg="Failed to get server ACLs for room \"!lQFvjEBNSLmgmSMuCy:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !lQFvjEBNSLmgmSMuCy:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.743230483Z" level=error msg="Failed to get server ACLs for room \"!MVxBjSgGmyYQXEiiJp:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !MVxBjSgGmyYQXEiiJp:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.753612223Z" level=error msg="Failed to get server ACLs for room \"!qruovFOpCdwwUEXMMt:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !qruovFOpCdwwUEXMMt:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.763922619Z" level=error msg="Failed to get server ACLs for room \"!ZYtSSWomxqVFfCvNZb:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !ZYtSSWomxqVFfCvNZb:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.773656901Z" level=error msg="Failed to get server ACLs for room \"!tDKMwIWjwbnVLgNtxP:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !tDKMwIWjwbnVLgNtxP:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.783184385Z" level=error msg="Failed to get server ACLs for room \"!jyjbvOssvQxLKOJMQd:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !jyjbvOssvQxLKOJMQd:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.793424280Z" level=error msg="Failed to get server ACLs for room \"!iZKboDCnZHVXqMLDqH:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !iZKboDCnZHVXqMLDqH:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.803057693Z" level=error msg="Failed to get server ACLs for room \"!ksbUMFSqebiGyjthls:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !ksbUMFSqebiGyjthls:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.812365414Z" level=error msg="Failed to get server ACLs for room \"!ZHZDRlXSuMouRwgdeW:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !ZHZDRlXSuMouRwgdeW:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.822190981Z" level=error msg="Failed to get server ACLs for room \"!NhvCgPaVxzfdMekIYI:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !NhvCgPaVxzfdMekIYI:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.832296044Z" level=error msg="Failed to get server ACLs for room \"!ytulNfBMMgpBoUAQPI:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !ytulNfBMMgpBoUAQPI:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.842998750Z" level=error msg="Failed to get server ACLs for room \"!qumWGLERaXthFKzFPk:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !qumWGLERaXthFKzFPk:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.853027550Z" level=error msg="Failed to get server ACLs for room \"!bjsAsryuQTutaaqZXx:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !bjsAsryuQTutaaqZXx:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.862825905Z" level=error msg="Failed to get server ACLs for room \"!BdNOMPacfbUBnipZnr:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !BdNOMPacfbUBnipZnr:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.873676015Z" level=error msg="Failed to get server ACLs for room \"!sJSCeWUOStwceTckbE:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !sJSCeWUOStwceTckbE:matrix.womo.site doesn't exist"
time="2021-10-22T08:09:22.885409275Z" level=error msg="Failed to get server ACLs for room \"!RDCyNNRQaFlIZkxsug:matrix.womo.site\"" func="NewServerACLs\n\t" file=" [acls.go:60]" error="room !RDCyNNRQaFlIZkxsug:matrix.womo.site doesn't exist"

```
here is the logs, and room server not start to listen.

**Comment by Notmarrco** [comment]
I had the same error but in another context.

Dendrite was running fine, then I stopped it, stopped the bridges and stopped postgres. Then I moved the postgresql data files to another disk, changed postgres config and restarted all services. 
After that I began to have the same errors as @yswtrue , but I could see that the db was fine, dendrite didn't complain for the db, and it did start.
Reverting to using db in its first location did remove the errors.

**Comment by kegsay** [comment]
This implies that rooms in the rooms table https://github.com/matrix-org/dendrite/blob/802f1c96f804f7a146e4e12e25b20c980a6af870/roomserver/storage/shared/storage.go#L1020 are not present in... the rooms table.

The error is coming from https://github.com/matrix-org/dendrite/blob/master/roomserver/storage/shared/storage.go#L846

The notable thing here is the presence of `IsStub` - https://github.com/matrix-org/dendrite/blob/2c581377a5f6b243300445947fd0fd38a919873d/roomserver/storage/postgres/rooms_table.go#L155 - stub rooms can happen when you're invited to a room but not yet accepted it. We shouldn't be failing `GetStateEvent` calls for that.
