### ISSUE TITLE
Element Client returns "malformed json" on creating an account

### ISSUE THREAD

**Issue by xx1182** [matrix-org/dendrite#2040]
### Background information

- **Dendrite version or git SHA**: last one, like 5 minutes ago
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: SQLite3
- **Running in Docker?**:  NO
- **`go version`**:  1.17

### Description

I've even run the federation tester and it says success... i don't know if the server is unable to create accounts, or something else.

### Steps to reproduce

- Get your favourite client
- Try to register an account
- Not SUCCESS!!!

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by kegsay** [comment]
Without any logs or pastes of the HTTP request/responses being performed, it's hard to provide any feedback or help.

I suspect "malformed JSON" means that you're actually receiving HTML instead, which is usually caused by a reverse proxy sitting between the client and the server.

**Comment by spaetz** [comment]
I just created a user, using the latest master revision, using sqlite3 and no docker, using go 1.15 with Element Web and it worked just fine. So this works in principle, and without more specific logs, I guess nothing can be done about this.
