### ISSUE TITLE
Kubernetes support

### ISSUE THREAD

**Issue by samip5** [matrix-org/dendrite#2043]
**Description:** I would like to request kubernetes support, which would mean manifests and/or Helm chart for the applicaiton.

https://kubernetes.io/docs/reference/glossary/?all=true#term-manifest
https://kubernetes.io/blog/2016/10/helm-charts-making-it-simple-to-package-and-deploy-apps-on-kubernetes/

**Comment by S7evinK** [comment]
Unofficial: https://github.com/S7evinK/dendrite-helm

Have a look at the `values.yaml` and the `dendrite-config.yaml` in this repo for the configuration, as I didn't document anything yet. (e.g.: you need to create the database(s) manually as of now)
I also recommend to deploy a monolith, as there are some issues with polylith. (monolith is **not** tested by myself though; polylith doesn't support scaling yet)

**Comment by samip5** [comment]
This is being worked on: https://github.com/k8s-at-home/charts/pull/1319

**Comment by kegsay** [comment]
We have no intention to maintain an official k8s helm chart whilst Dendrite is still in beta. It adds more stuff for us to maintain which slows iteration speed.
