### ISSUE TITLE
Not able to join public rooms since the server takes an indefinite time updating keys from the database

### ISSUE THREAD

**Issue by ghost** [matrix-org/dendrite#2050]
### Background information

- **Dendrite version or git SHA**: 0.5.1
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: Docker
- **`go version`**: 1.15

### Description
Not able to join public rooms since the server takes an indefinite time updating keys from the database.

### Steps to reproduce

- Run dendrite 0.5.1 with Monolith Mode in Docker. (with Postgres)
- Register a user and Login 
- Try to join any public rooms in `matrix.org` server
- The loading indicator will spin indefinitely which results in an error saying "There was an error joining the room"

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->
### Logs
```
dendrite-monolith | time="2021-11-18T08:29:21.854223980Z" level=info msg="Updated 1 of 1 key(s) in database (0 keys remaining)" func="handleFetcherKeys\n\t" file=" [api.go:262]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:21.863259143Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [api.go:208]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:22.123432710Z" level=info msg="Updated 1 of 1 key(s) in database (0 keys remaining)" func="handleFetcherKeys\n\t" file=" [api.go:262]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:22.182853859Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [api.go:208]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:22.382436397Z" level=info msg="Updated 1 of 1 key(s) in database (0 keys remaining)" func="handleFetcherKeys\n\t" file=" [api.go:262]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:22.431352672Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [api.go:208]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:22.648018493Z" level=info msg="Updated 1 of 1 key(s) in database (0 keys remaining)" func="handleFetcherKeys\n\t" file=" [api.go:262]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:22.652874327Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [api.go:208]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:22.851101861Z" level=info msg="Updated 1 of 1 key(s) in database (0 keys remaining)" func="handleFetcherKeys\n\t" file=" [api.go:262]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:22.856745090Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [api.go:208]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:23.132106145Z" level=info msg="Updated 1 of 1 key(s) in database (0 keys remaining)" func="handleFetcherKeys\n\t" file=" [api.go:262]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:23.151483675Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [api.go:208]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:23.419098981Z" level=info msg="Updated 1 of 1 key(s) in database (0 keys remaining)" func="handleFetcherKeys\n\t" file=" [api.go:262]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:23.424127850Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [api.go:208]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:23.632810164Z" level=info msg="Updated 1 of 1 key(s) in database (0 keys remaining)" func="handleFetcherKeys\n\t" file=" [api.go:262]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:23.652157984Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [api.go:208]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:24.031565538Z" level=info msg="Updated 1 of 1 key(s) in database (0 keys remaining)" func="handleFetcherKeys\n\t" file=" [api.go:262]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:24.041711323Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [api.go:208]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:24.290927870Z" level=info msg="Updated 1 of 1 key(s) in database (0 keys remaining)" func="handleFetcherKeys\n\t" file=" [api.go:262]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:24.321592155Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [api.go:208]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:24.573160865Z" level=info msg="Updated 1 of 1 key(s) in database (0 keys remaining)" func="handleFetcherKeys\n\t" file=" [api.go:262]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:24.640853309Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [api.go:208]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:24.837103443Z" level=info msg="Updated 1 of 1 key(s) in database (0 keys remaining)" func="handleFetcherKeys\n\t" file=" [api.go:262]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:24.842792231Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [api.go:208]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:25.046377118Z" level=info msg="Updated 1 of 1 key(s) in database (0 keys remaining)" func="handleFetcherKeys\n\t" file=" [api.go:262]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:25.093278498Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [api.go:208]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:25.299780674Z" level=info msg="Updated 1 of 1 key(s) in database (0 keys remaining)" func="handleFetcherKeys\n\t" file=" [api.go:262]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:25.314166393Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [api.go:208]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:25.524949905Z" level=info msg="Updated 1 of 1 key(s) in database (0 keys remaining)" func="handleFetcherKeys\n\t" file=" [api.go:262]" fetcher_name="perspective server matrix.org"
dendrite-monolith | time="2021-11-18T08:29:25.527754303Z" level=info msg="Fetching 1 key(s)" func="handleFetcherKeys\n\t" file=" [api.go:208]" fetcher_name="perspective server matrix.org"
```

**Comment by kegsay** [comment]
Without further context here it's difficult to know how dendrite ended up in this failure mode. It sounds like it might be a failure in matrix.org's perspective server but it's hard to know for sure.

**Comment by S7evinK** [comment]
Closing this, as it's unlikely to get more context from a (now) deleted user.
