### ISSUE TITLE
Postgres Version?

### ISSUE THREAD

**Issue by benyanke** [matrix-org/dendrite#2052]
I see that in the docker compose deployment, it specifies Postgres v 11.

https://github.com/matrix-org/dendrite/blob/master/build/docker/docker-compose.deps.yml#L6

This is an aging version of postgres, and before long will be out of support.

https://www.postgresql.org/support/versioning/

Is this actually required, or is this something that can be brought to version 14?

**Comment by neilalexander** [comment]
Version 11 is the lowest version that we support. Newer versions will work fine.
