### ISSUE TITLE
log file contains "level=warning" while config option needs "level: warn"

### ISSUE THREAD

**Issue by spaetz** [matrix-org/dendrite#2053]
### Background information

- Dendrite 0.5.1
- Monolith
- go 1.15

### Description

dendrite.yaml [takes](https://github.com/matrix-org/dendrite/blob/6e93531e9412a16d39567e141c98b538a7e1e739/dendrite-config.yaml#L394):
```
logging:
- type: file
  level: **warn**
```
however, the log file prints log entries of the format:
`time="2021-11-22T11:06:52.657618474Z" level=**warning**`

This inconsistency makes it very hard to know what the right value is to put into the config file. Especially as the default [config file](https://github.com/matrix-org/dendrite/blob/master/dendrite-config.yaml) does not list the possible logging levels anymore (they [used to be (line 132)](https://github.com/matrix-org/dendrite/commit/58c10c6d546da27e1df2ebd4353f073e3cc2a286?diff=unified#diff-dd8f3ef0612a76237776fb6e881714815b66b0c693ecd41d90213631c0dc4366) in the original for that file but seemed to have gotten removed...)

It would be nice to
a) either have a list of possible values in the config file and/or
b) to make the output error level consistent with the configured one.

Thanks for dendrite :-)

**Comment by kegsay** [comment]
https://github.com/matrix-org/dendrite/pull/2101
