### ISSUE TITLE
Allow to set debug level for dendrite STDERR logging

### ISSUE THREAD

**Issue by spaetz** [matrix-org/dendrite#2054]
**Description:**

Currently
```
logging:
 level: XXX
```
allows to set the logging level for the log file in addition to the log output sent to STDERR. However, the log level of STDERR can't be influenced somehow. Given that journalctl/systemd sucks in all STDERR logs, it would be awesome to have a possibility to influence the verboseness of STDERR. This could be one of:

- -q, -qq, -v, --v command line options to impact STDERR logging
- using the same verboseness as defined in the `logging:` section (although I see the charme of possibly having two different log levels(
- introducing a new `logging: stderr_level:` variable
- ...

**Comment by MFAshby** [comment]
Logging in dendrite is using [logrus](https://github.com/Sirupsen/logrus).

As far as I can see, there's not really a way to configure the default logger separately from log hooks that route logs to either file or syslog. If you happen to set the logging level to `debug` for any of the hooks, the debug logging will also appear in stderr, which might be enough for debugging your issue.

A better solution might be: disable the 'standard' logging and explicitly add a hook to route logs to stdout/stderr with the appropriate level. That way, logging to stdout/err can be handled the same way as all other logging.
