### ISSUE TITLE
.well-known not found in docker monolith

### ISSUE THREAD

**Issue by fcwoknhenuxdfiyv** [matrix-org/dendrite#2063]
### Background information

- **Dendrite version or git SHA**:  0.5.1
- **Monolith or Polylith?**: monolith
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: yes
- **`go version`**: n/a

### Description

Calls are returning `404 page not found`

### Steps to reproduce

- from inside the container, run `curl localhost:8008/.well-known/matrix/server`

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by S7evinK** [comment]
Did you specify a `well_known_server_name` in the config? The handler is only added if the value is not an empty string.
https://github.com/matrix-org/dendrite/blob/83b9cb4d79123ec89e18a46d5202e74a9e9305b8/dendrite-config.yaml#L57-L59

**Comment by fcwoknhenuxdfiyv** [comment]
hi @S7evinK , apologies for not answering sooner, I just found the notification email in my spam folder.

Yes, I do have that setting configured.

**Comment by fcwoknhenuxdfiyv** [comment]
Okay, I just entered the container and it's not set. Something went wrong with the docker setup. I'll close this and reopen if the problem persists.
