### ISSUE TITLE
Dendrite incorrectly accepts `m.room.canonical_alias` for aliases that were never set

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/dendrite#2068]
### Background information

- **Dendrite version or git SHA**: 83b9cb4d79123ec89e18a46d5202e74a9e9305b8
- **Running in Docker?**: yes

This was found while running Complement, so build information from [this Dockerfile](https://github.com/matrix-org/complement/blob/277e25800c9b51f5dc0fb5d89430cf99d817267d/dockerfiles/Dendrite.Dockerfile) also applies.

### Description

Found in complement while implementing `m.room.canonical_alias rejects missing aliases`, this currently passes;

```go
			roomID := alice.CreateRoom(t, map[string]interface{}{})

			roomAlias := "#alias:hs1"

			res := setCanonicalAlias(t, alice, roomID, roomAlias, nil)

			must.MatchResponse(t, res, match.HTTPResponse{
				StatusCode: 200,
				JSON: []match.JSON{
					match.JSONKeyPresent("event_id"),
				},
			})
```

while this snippet fails in Synapse, because synapse (and sytest) expect that the alias be set via the `/directory/room/` endpoint first.

**Comment by S7evinK** [comment]
Fixed in #2236, Complement is happy with all currently skipped tests.
