### ISSUE TITLE
Dendrite accepts bogus `m.room.canonical_alias` state event

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/dendrite#2069]
### Background information

- **Dendrite version or git SHA**: 83b9cb4d79123ec89e18a46d5202e74a9e9305b8
- **Running in Docker?**: yes

This was found while running Complement, so build information from [this Dockerfile](https://github.com/matrix-org/complement/blob/277e25800c9b51f5dc0fb5d89430cf99d817267d/dockerfiles/Dendrite.Dockerfile) also applies.

### Description

Found while working on a complement test, the following snippet succeeds on synapse;

```go
			roomID := alice.CreateRoom(t, map[string]interface{}{})

			roomAlias := "%alias:hs1"

			res := setCanonicalAlias(t, alice, roomID, roomAlias, nil)

			must.MatchResponse(t, res, match.HTTPResponse{
				StatusCode: 400,
				JSON: []match.JSON{
					match.JSONKeyEqual("errcode", "M_INVALID_PARAM"),
				},
			})
```

However, on dendrite, the last HTTP call **succeeds with `200`**. Dendrite is not correctly validating the room alias before putting it in the room graph.

**Comment by S7evinK** [comment]
Fixed in #2236
