### ISSUE TITLE
Dendrite requesting nonstop since it was asked to join an invaild room

### ISSUE THREAD

**Issue by goodspeed34** [matrix-org/dendrite#2077]
### Background information

- **Dendrite version or git SHA**: 0.5.1+a47b12dc
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: Nope
- **`go version`**: go1.17 openbsd/amd64

### Description

Dendrite was persistent to join an invalid chat room

### Steps to reproduce

- Enter an invalid matrix ID for dendrite to join (Something like @invalid:nonexist.com)
- Get a message showing the user's not exist
- Lookup the log and see the behaviour.

```
level=error msg="Failed to query device keys for some users" func="github.com/matrix-org/dendrite/keyserver/internal.(*DeviceListUpdater).processServer" file="github.com/matrix-org/dendrite/keyserver/internal/device_list_update.go:401" content=missing failed=1 server_name=*****.*** total=1 wait=8h0m0s
```

This request keeps showing and nonstop.

**Comment by kegsay** [comment]
Can't reproduce this. I just get profile lookup failures.

**Comment by kegsay** [comment]
Please open a new issue if you can reproduce this on the latest version.
