### ISSUE TITLE
NGINX Monolith sample config

### ISSUE THREAD

**Issue by idi-moe** [matrix-org/dendrite#2078]
https://github.com/matrix-org/dendrite/blob/a47b12dc7d692e0ddd4aaa0801dafc9bb462aad9/docs/nginx/monolith-sample.conf#L26

Should "monolith" in this line not be "localhost"? I changed mine during install.

**Comment by Forchapeatl** [comment]
Thank you for bringing this up.

**Comment by kegsay** [comment]
https://github.com/matrix-org/dendrite/pull/2087
