### ISSUE TITLE
nats branch: Default generated logging path is fatal.

### ISSUE THREAD

**Issue by gedw99** [matrix-org/dendrite#2081]
This is for NATS branch...

@neilalexander 

The generated dendrite config has the logging as **path: /var/log/dendrite**

On Mac, "path: /var/log/dendrite" fails with 
```

FATA[2021-12-31T12:41:14.996493000Z] [log.go:127] setupFileHook
         Couldn't create directory /var/log/dendrite: "mkdir /var/log/dendrite: permission denied" 

```

**path: ./var/log/dendrite** is better for default perhaps as there is no need for SUDO magic needed ?

**Comment by Forchapeatl** [comment]
Please ensure your go version is above 1.15

**Comment by gedw99** [comment]
> Please ensure your go version is above 1.15

go version go1.17.5 darwin/amd64

**Comment by neilalexander** [comment]
> The generated dendrite config has the logging as path: /var/log/dendrite

How did you generate the config? The sample `dendrite-config.yaml` in the repository is intended as a sample. It's fully expected that you will need to adjust it to suit your environment.

**Comment by gedw99** [comment]
using the tool.


> > The generated dendrite config has the logging as path: /var/log/dendrite
> 
> How did you generate the config?

Yes using the tool.

> The sample `dendrite-config.yaml` in the repository is intended as a sample. It's fully expected that you will need to adjust it to suit your environment.

yes i know. just wanted to highlight the inconsistency because the paths in the config used the pattern whereby no sudo was needed.

**Comment by kegsay** [comment]
It's not great that the default config refers to locations that may not exist or may not be accessible. However, it's also not great to shove everything into the current working directory as that can change depending on where you run the binary. Referring to a location that will produce an error feels better than silently accepting a suboptimal path, so I think the current behaviour is acceptable. Closing.
