### ISSUE TITLE
bzr is needed as a dependency to build Dendrite with build.sh but it is not documented

### ISSUE THREAD

**Issue by nicobao** [matrix-org/dendrite#2090]
### Background information

- **Dendrite version or git SHA**:  16035b97
- **Monolith or Polylith?**: building
- **SQLite3 or Postgres?**: N/A
- **Running in Docker?**: N/A
- **`go version`**: 1.16.13

### Description

On running `./build.sh`, I get the error:

```
get "launchpad.net/gocheck": found meta tag vcs.metaImport{Prefix:"launchpad.net/gocheck", VCS:"bzr", RepoRoot:"https://launchpad.net/~niemeyer/gocheck/trunk"} at //launchpad.net/gocheck?go-get=1
get "launchpad.net/xmlpath": found meta tag vcs.metaImport{Prefix:"launchpad.net/xmlpath", VCS:"bzr", RepoRoot:"https://launchpad.net/~niemeyer/xmlpath/trunk"} at //launchpad.net/xmlpath?go-get=1
go: github.com/juju/testing@v0.0.0-20210324180055-18c50b0c2098 requires
	github.com/juju/utils/v2@v2.0.0-20200923005554-4646bfea2ef1 requires
	launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: unrecognized import path "launchpad.net/gocheck": GOVCS disallows using bzr for public launchpad.net/gocheck; see 'go help vcs'
```

It happens because this `juju` dependency relies on the `bzr` VCS tool: http://wiki.bazaar.canonical.com and I didn't have `bzr` installed on my computer.

### Steps to reproduce

- clone the repository
- install go
- do not have bzr installed, just git
- run `./build.sh`

I'd have expected either that the README mention this `bzr` dependency, which isn't an usual VCS tool to have installed on one's computer OR that the `build.sh` script downloads it for me.

I suggest that we keep it simple and add a mention of this dependency on the README file.
I am not familiar much with the `go` ecosystem so it took me some time to figure it out, which I suppose would happen for other newcomers.

**Comment by spaetz** [comment]
which, on my debian-based box, I use build.sh all the time and I don't have bzr installed for sure.

**Comment by nicobao** [comment]
Does it install `github.com/juju/testing` as well? If yes, does it use `bzr`?

**Comment by kegsay** [comment]
@nicobao please can you tell me the output to `go env`. I'm particularly interested in `GOVCS`.

**Comment by RayyanAnsari** [comment]
on fedora, i had to install the `breezy` package (fork of bazaar), then run
`GOVCS='*:all' ./build.sh`

**Comment by neilalexander** [comment]
If you are using a `GOPROXY` then the actual VCS tools are often not needed since the proxy will take care of it for us. That said, we do have a really messy dependency graph right now (in part due to the P2P demos and the upgrade tests) so we should do something about that.

**Comment by kegsay** [comment]
Closing as won't fix effectively, this is a weird Go quirk with the OPs distro.
