### ISSUE TITLE
502 Error when attempting to set avatar

### ISSUE THREAD

**Issue by LennyMcLennington** [matrix-org/dendrite#2107]
### Background information

- **Dendrite version or git SHA**: a47b12dc7d692e0ddd4aaa0801dafc9bb462aad9
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Posgres (I did psql --version and got `psql (PostgreSQL) 14.1 (Debian 14.1-4)`, I think that is the postgres version)
- **Running in Docker?**: No
- **`go version`**: go version go1.17.5 linux/amd64
- **Client used (if applicable)**: app.element.io version 1.9.9 and SchildiChat Desktop version 1.9.7-sc.1

### Description

 - **What** is the problem: When I attempt to set my avatar it hangs for around 30 seconds, gives a 502 error, and the avatar remains unchanged.
 - **Who** is affected: To my knowledge I only know of it happening with my account on my homeserver, I have asked someone else on my homeserver to check whether this issue also occurs for him and will update when I get a response.
 - **How** is this bug manifesting: I get an error in the Monolith.log file (shown below), and after this happens I get "Connectivity to the server has been lost" on the Element client no matter what I do (restarting Element does not help), and 502 errors on a lot of requests, and all this only gets fixed when I restart the homeserver manually. After restarting, I don't get any 502 errors or persistent connectivity errors like that until I attempt to set my avatar again.
 - **When** did this first appear: This happened the first time I attempted to set my avatar. Someone else on my home server had successfully set his avatar a while ago but I only tried to set it today and found this issue.

### Steps to reproduce

- Attempt to set an avatar

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->
The avatar is not set, the request gets a 502 error and I get this line in the Monolith.log;
```
time="2022-01-24T00:41:19.758764169Z" level=error msg="QueryRoomsForUser failed" func=github.com/matrix-org/dendrite/clientapi/routing.SetAvatarURL file="github.com/matrix-org/dendrite/clientapi/routing/profile.go:147" error="GetRoomsByMembership: cannot map user ID to state key NID: context canceled" req.id=qxPUhlmXtLNC req.method=PUT req.path="/_matrix/client/r0/profile/@lenny:polymc.org/avatar_url" user_id="@lenny:polymc.org"
```

**Comment by kegsay** [comment]
`context cancelled` means the client gave up. Setting profile names / pictures scales with the number of rooms the account is joined to because 1 event must be sent for every room the account is joined to. How many rooms is this account joined to?

**Comment by LennyMcLennington** [comment]
> How many rooms is this account joined to?

It was joned to 8 rooms and 3 spaces, but now I have left two of the spaces so now it's in 1 space and 6 rooms and now it works. It's something to do with one of those rooms that I left then, I guess. Is there some sort of admin API I could use to force join myself to those rooms to see which one it is or am I stuck outside of those rooms now that I've left them?

**Comment by neilalexander** [comment]
This shouldn't happen anymore now that the profile updates are sent asynchronously, but please reopen if this is still an issue in 0.8.1.
