### ISSUE TITLE
Event unmarshalling should be delayed as far as possible in HTTP mode

### ISSUE THREAD

**Issue by neilalexander** [matrix-org/dendrite#2112]
We currently have a whole bunch of structs in Dendrite and in GMSL where we refer to `Event` or `HeaderedEvent` and these are often implicitly being marshalled/unmarshalled to/from JSON when we strictly don't need the events at that moment in time. This often also gets complicated because of the room version needing to be known too. We should defer unmarshalling as far as possible by passing around `RawJSON` across API boundaries.

**Comment by neilalexander** [comment]
@kegsay Do we consider this done now with the `EventJSON` stuff?

**Comment by kegsay** [comment]
Yep.
