### ISSUE TITLE
Current sync server needs to be rewritten to support different streams

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/dendrite#212]
Currently its a hack to just support messages. While things like account data can be hacked on top, we probably want to fix it sooner rather than later.

See: https://github.com/matrix-org/dendrite/issues/211

**Comment by NegativeMjark** [comment]
The sync server now happily supports multiple streams by using a shared postgres sequence to generate IDs. This will have scaling issues if we need to run multiple sync server instances, but that is tracked by  #211 for now.
