### ISSUE TITLE
DM rooms are displayed as normal rooms

### ISSUE THREAD

**Issue by kegsay** [matrix-org/dendrite#2121]
> New 1:1 chat initiate by my synapse server to dentrite shows up under rooms not under person on the dendrite element clienrt

> I see the same. Invite from dendrite homeserver to matrix.org sows up as person, but from matrix.org to homeserver shows up in rooms on the homeserver, both element clients

Could be a few things:
 - Account data isn't sent to clients
 - `is_direct` hints aren't making it across federation
 
Ref: https://spec.matrix.org/v1.1/client-server-api/#direct-messaging

**Comment by zeeZ** [comment]
That second quote is me, running v0.5.1.

**Comment by kegsay** [comment]
We now have complement tests to assert that:
 - Account data IS sent to clients
 - `is_direct` hints ARE making it across federation

Without further logs I cannot help more on this one. Additional Qs:
 - Does this consistently happen with all new DM rooms?
 - Does it happen when you DM users on the same homeserver?

**Comment by S7evinK** [comment]
As far as my testing goes, this only happens when a user is invited over federation. As soon as the invite is accepted, the DM appears as a normal room in Element Web (and probably other clients)
