### ISSUE TITLE
"superfluous response.WriteHeader" spam in logs

### ISSUE THREAD

**Issue by 0x1a8510f2** [matrix-org/dendrite#2123]
### Background information

- **Dendrite version or git SHA**: 0.6.0
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: Yes
- **`go version`**: official Docker build version
- **Client used (if applicable)**: N/A

### Description

During (as far as I can tell) normal operation, the following spam appears in the logs:
![image](https://user-images.githubusercontent.com/83190128/151629856-2b67343e-6934-47c1-9e1b-6b9fa0b66fad.png)

### Steps to reproduce

As reported by @S7evinK, switching rooms in Element Web appears to trigger the spam, likely among others.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by S7evinK** [comment]
I can reproduce this, by e.g. switching rooms in Element Web (1.9.10-rc.2)

**Comment by S7evinK** [comment]
Probably got it, verifying now. :)

**Comment by 0x1a8510f2** [comment]
That was quick. Thanks! :D

**Comment by 0x1a8510f2** [comment]
Looks like this has been fixed now so I'll close the issue.
