### ISSUE TITLE
Unable to join new rooms 

### ISSUE THREAD

**Issue by thefirstofthe300** [matrix-org/dendrite#2124]
### Background information

- **Dendrite version or git SHA**: v0.6.0
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: Yes

### Description

 - **What** is the problem: Unable to join rooms
 - **Who** is affected: My server user
 - **How** is this bug manifesting: Server silently fails to join a new room
 - **When** did this first appear: On first install

I am spinning up a Dendrite server for the first time on this particular domain (I've spun one up before elsewhere but that was before I knew what I was doing). AFAICT, I have everything configured correctly for federation. I booted up the server and attempted to join the #dendrite:matrix.org room. The server silently fails to join and seems to end the join process with the following error:

```
time="2022-01-29T01:41:36.452380454Z" level=error msg="Failed to send room join response to roomserver" error="InputRoomEventsResponse: r.checkForMissingAuthEvents: event.VerifyEventSignatures: gomatrixserverlib: key with ID \"ed25519:a_rRAI\" for \"satterfield.us\" not valid at 1611291871075" room_id="!yomrOFwgFXzmeMAbzX:matrix.org" user_id="@firstofth300:dendrite.seymour.family"
```

**Comment by zeeZ** [comment]
Creating and joining a local room also fails.

```
time="2022-01-30T11:42:58.079457540Z" level=info msg="Creating new room" req.id=Kbdv9oeXamzo req.method=POST req.path=/_matrix/client/r0/createRoom roomID="!MQmRYYmMhAl4QkJS:rinjes.me" roomVersion=6 userID="@christian:rinjes.me" user_id="@christian:rinjes.me"
```

Then nothing happens. publicRooms says `num_joined_members` is 1, and trying to join it again yields `{"errcode":"M_GUEST_ACCESS_FORBIDDEN","error":"Guest access not implemented"}` on `initialSync`

**Comment by thefirstofthe300** [comment]
@zeeZ Your report reminds me a bit of #1882. Not sure if it's related.

**Comment by owski** [comment]
I am experiencing the same issue. I am unable to join #dendrite:matrix.org (or, seemingly any room with more than a few hundred users) on v0.6.0. Running on 2 CPU / 4 GB Ram box, SSD, Postgres DB.

I attempted to leave #dendrite:matrix.org up overnight to join and it's stuck on "Joining room ..."

**Comment by neilalexander** [comment]
Is this still a problem in v0.6.5?

**Comment by neilalexander** [comment]
Closing as stale, please reopen if still a problem in 0.8.1.
