### ISSUE TITLE
federationsender_queues stop moving shortly after restart

### ISSUE THREAD

**Issue by zeeZ** [matrix-org/dendrite#2125]
### Background information

- **Dendrite version or git SHA**: 0.6.0
- **Monolith or Polylith?**:  Monolith
- **SQLite3 or Postgres?**:  Postgres 12.8.0
- **Running in Docker?**: Yes (matrixdotorg/dendrite-monolith@sha256:b6c02bbca4806d8edf6c5944da5bbd9d99e64f8f2f78997464bf8c98bce8ea72)

This server has a single user and the sole joined room is #dendrite:matrix.org.

### Description

 - **What** is the problem: federationsender_queue_edus and federationsender_queue_pdus stop moving
 - **Who** is affected: Federation
 - **How** is this bug manifesting: After a restart row counts drop, then soon after do not change anymore
 - **When** did this first appear: update from 0.5.1 to 0.6.0

I was told to open this issue ;), though I assume it's related to the overall "federation no longer working" problem with 0.6.0.

[dendrite.log](https://github.com/matrix-org/dendrite/files/7964032/dendrite.log)
[dendrite2.log](https://github.com/matrix-org/dendrite/files/7964033/dendrite2.log)
![image](https://user-images.githubusercontent.com/715896/151667688-b43ad2f3-8252-4baf-88c7-f6d9c59a9b6f.png)

The bumps in the graph are after a server restart (16:17 and 16:32).

**Comment by neilalexander** [comment]
Is this still happening on Dendrite 0.6.5?

**Comment by S7evinK** [comment]
Is this still happening on the latest release?

**Comment by kegsay** [comment]
Closing as no user feedback.
