### ISSUE TITLE
Error "failed to send EDU" and "Federation disabled" when federation is disabled in config

### ISSUE THREAD

**Issue by travbid** [matrix-org/dendrite#2128]
### Background information

- **Dendrite version or git SHA**: v0.6.0
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: no
- **`go version`**: go1.17 linux/amd64
- **Client used (if applicable)**: n/a

### Description

 - **What** is the problem:
With `disable_federation: true` dendrite repeatedly logs errors: "failed to send EDU" and "Federation disabled". I don't believe this should be an error when federation is explicitly disabled.
 - **Who** is affected:
People who run dendrite server v0.6.0 with `disable_federation: true`
 - **How** is this bug manifesting:
The logs quickly filled up with these same error message repeated until my machine ran out of disk space:
 ```
time="2022-01-29T23:44:09.428897577Z" level=info msg="Sending send-to-device message into \"matrix.mydomain.xyz\" destination queue" func="github.com/matrix-org/dendrite/federationapi/consumers.(*OutputEDUConsumer).onSendToDeviceEvent.func1" file="github.com/matrix-org/dendrite/federationapi/consumers/eduserver.go:129"
time="2022-01-29T23:44:09.429044995Z" level=error msg="failed to send EDU" func="github.com/matrix-org/dendrite/federationapi/consumers.(*OutputEDUConsumer).onSendToDeviceEvent.func1" file="github.com/matrix-org/dendrite/federationapi/consumers/eduserver.go:131" error="Federation disabled"
time="2022-01-29T23:44:09.429275925Z" level=info msg="Sending send-to-device message into \"matrix.mydomain.xyz\" destination queue" func="github.com/matrix-org/dendrite/federationapi/consumers.(*OutputEDUConsumer).onSendToDeviceEvent.func1" file="github.com/matrix-org/dendrite/federationapi/consumers/eduserver.go:129"
time="2022-01-29T23:44:09.429413561Z" level=error msg="failed to send EDU" func="github.com/matrix-org/dendrite/federationapi/consumers.(*OutputEDUConsumer).onSendToDeviceEvent.func1" file="github.com/matrix-org/dendrite/federationapi/consumers/eduserver.go:131" error="Federation disabled"
```
 - **When** did this first appear:
After upgrading to v0.6.0

### Steps to reproduce

- `go build`
- `cp dendrite-config.yaml dendrite.yaml`
- Set `server_name` and `connection_string`s
- Set `disable_federation: true`
- `./bin/dendrite-monolith-server --config=dendrite.yaml --tls-cert=server.crt --tls-key=server.key`

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by neilalexander** [comment]
Related: #2127.

**Comment by timmc** [comment]
On v0.6.3 these are the lines I'm still getting:

```
# cat /srv/commdata/stg_matrix/dendrite/logs/Monolith.log | sed 's/^time="[^"]*" //' | sort | uniq -c
 405036 level=error msg="failed to send EDU" func="github.com/matrix-org/dendrite/federationapi/consumers.(*OutputEDUConsumer).onSendToDeviceEvent" file="github.com/matrix-org/dendrite/federationapi/consumers/eduserver.go:139" error="Federation disabled"
 107809 level=error msg="failed to send EDU" func="github.com/matrix-org/dendrite/federationapi/consumers.(*OutputEDUConsumer).onTypingEvent" file="github.com/matrix-org/dendrite/federationapi/consumers/eduserver.go:191" error="Federation disabled"
...
```
(140 MB in 2 minutes!)

**Comment by timmc** [comment]
Great! As of that PR, my non-federated server seems stable. :-)
