### ISSUE TITLE
m.room.power_levels event missing from some rooms

### ISSUE THREAD

**Issue by bones-was-here** [matrix-org/dendrite#2129]
### Background information

- **Dendrite version or git SHA**: 0.6
- **Monolith or Polylith?**: monolith
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: no
- **`go version`**: 1.17.6
- **Client used (if applicable)**: Element

### Description

 - **What** is the problem: lack of any m.room.power_levels event in a specific public room (v6)
 - **Who** is affected: user accounts on the dendrite homeserver
 - **How** is this bug manifesting: No power levels or permissions can be viewed or changed with accounts on the dendrite homeserver, but with a matrix.org account the room looks normal.
 - **When** did this first appear: after the 0.5.1 -> 0.6 upgrade

When I load the room in question I don't see any errors logged, not even a warn.  
There's a lot of `superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:65)` but that happens for every room.  
Haven't found any relevant errors in Element either.

### Steps to reproduce

I haven't found a way to reproduce this, apart from join this specific room with an account on its homeserver.  
The room is the only one with some users banned, but I tried creating a new room (on the same homeserver), joining it with a matrix.org account, banning that account - but no issue found.

Possibly something in the database was lost during the upgrade?

Edit2: the room's federation is not broken, other events are federating (in both directions).  
Can we reset something to make it get the power levels from matrix.org?

**Comment by neilalexander** [comment]
This feels a lot like it is probably the same failure mode causing #2082 — the client should be sent a state event but it isn't for some reason. It's possible that this is either due to the roomserver output sending an incorrect state delta, or the sync API is messing up somewhere.

**Comment by bones-was-here** [comment]
I did another test to see if the m.room.power_levels event content was somehow unparsable for dendrite by copying it (from matrix.org side) to a new room (created with dendrite, like the now-broken room was originally) but it applied successfully and can now be read and changed from dendrite, so the event content doesn't seem to be the issue.  

Then with this test room I tried banning (from dendrite side) my matrix.org account, which succeeded.  I then unbanned and invited that account (from dendrite) but that account is no longer able to join, when accepting the invite element says "Cannot join user who was banned".  In dendrite the membership is "invite" but I guess matrix.org still thinks membership is "ban" ?

**Comment by bones-was-here** [comment]
This appears to have been fixed by #2154 :)

**Comment by bones-was-here** [comment]
This bug can still occur with 0.8.4.  

I have a very small room with 3 homeservers participating, 2x dendrite 0.8.4 and matrix.org.  Conspicuously, both of the dendrite servers have mysteriously lost the power levels event, and matrix.org still has correct power levels.  This happened recently without making any change to any settings stored in the power levels event.  It's a v6 room originally created and configured by dendrite.

**Comment by bones-was-here** [comment]
This is happening again with 2eae8dc4

downloadState doesn't help because nobody is allowed to send any event.

**Comment by bones-was-here** [comment]
This seems to be reproducible currently when joining our space with a dendrite (not the main one that created the room).
With 0.12.0:
- Leave space (was already in it, with no power levels event)
- purgeRoom (successfully delete space)
- Join space (fails)

With a734b112c6577a23b87c6b54c50fb2e9a629cf2b:
- purgeRoom (fails, nothing to delete)
- Join space (succeeds, is able to backfill the timeline)
- observe there's no power levels event, but matrix.org does still have it

**Comment by bones-was-here** [comment]
Interestingly the above dendrite has now (next day) acquired a correct-looking power levels event.  If receiving another event prompted it, it looks to have been... someone changing their profile pic? xD  
An older dendrite (0.12.0) still lacks it. I've upgraded it to a734b112c6577a23b87c6b54c50fb2e9a629cf2b also, will report back if it regains power levels too.

**Comment by bones-was-here** [comment]
Is it possible to prioritise the power levels event in some way? The dendrite that did eventually get it didn't get it until the next day, which seems like it could cause valid events to be rejected.

**Comment by bones-was-here** [comment]
Pretty sure this is fixed since #3133, or at least I haven't seen it happen again.
