### ISSUE TITLE
Combined logs

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/dendrite#214]
Given a request is going to cause work on multiple components, we should look into how we want to do logging. Specifically whether we want to stuff them all into a single "stream", rather than having each instance logging to a separate file.

**Comment by babolivier** [comment]
FTR in the case of a single "stream" I opened https://github.com/matrix-org/dendrite/pull/198 which prefix logs emitted from a component (excluding the ones emitted from https://github.com/matrix-org/util atm) with the component's name to help differentiate similar log outputs from different components.

**Comment by NegativeMjark** [comment]
Is the idea here to make the components log over the network to some sort of logging central server? If so I suspect that all we need is to pick an appropriate logrus hook from https://github.com/sirupsen/logrus#hooks

**Comment by erikjohnston** [comment]
Quite possibly, or shoving stuff in elastic search, or whatever. I think the important thing is to be able to see all logs for a single request across all components. Though we should probably also keep per component logs so that its easy to diagnose component specific issues.

**Comment by Kegsay** [comment]
Closing this: we landed open tracing and in general the answer to "use a central log store" is not a dendrite issue but an ops issue.
