### ISSUE TITLE
Feature request: add hcaptcha for register, login form

### ISSUE THREAD

**Issue by cnmade** [matrix-org/dendrite#2157]
**Description:**

Hcaptcha service is alternative for reCaptcha.

It is free and strong enough. like to see it be supported. can be used to prevent bots for register and login .

**Comment by kegsay** [comment]
We already support reCaptcha which is good enough to prevent simple bots.

**Comment by kegsay** [comment]
We have no plans to add this, and will be relying on OIDC servers for additional captcha providers when we migrate to that form of reg/login.
