### ISSUE TITLE
Feature Request: lock user create room permission

### ISSUE THREAD

**Issue by cnmade** [matrix-org/dendrite#2158]
**Description:**

As a private matrix server owner, we do not want to gave the ability to user , they can not create new chat room while they just sign up to our matrix server.

I suggest provided an option.

Let admin decide, if public user can create chat room or not.

If turn off.
Only admin user , who create the matrix server, can create new chat room.

This can be helpful to prevent abuse usage .

**Comment by kegsay** [comment]
We're not interested in this feature right now.

**Comment by Domoel** [comment]
That would be great! Especially because admins in rooms created by other users are currently not admins but only members which is really a bummer.
