### ISSUE TITLE
Roomserver can deadlock due to multiple txns

### ISSUE THREAD

**Issue by kegsay** [matrix-org/dendrite#2173]
When the roomserver processes events, it requires _two_ connections as it makes _two_ transactions (annoyingly). One to process the event and then another for the latest events / membership updater. This was always known to be a wart but this can explode spectacularly on large/busy servers. This has been present since Day One in Dendrite.

In one scenario, the `max_open_conns` was set to `10` for the roomserver. However, the server was very busy such that >10 events in different rooms arrived at once, causing all 10 connections to be obtained. These connections could not complete because they then required a 2nd connection for the latest events / membership updater, which it could never get, hence it deadlocks.

This can manifest in metrics with `dendrite_roomserver_input_backpressure` being present and not changing even for a newly created room(!).

The workaround for now is to increase the connection count, but this merely delays the problem....

We need to guarantee that we only use a single in-flight txn when processing an event to ensure we cannot deadlock.

**Comment by neilalexander** [comment]
Fixed by #2178.
