### ISSUE TITLE
Sending E2EE messages dendrite -> matrix.org randomly fails to provide keys

### ISSUE THREAD

**Issue by bones-was-here** [matrix-org/dendrite#2184]
### Background information

- **Dendrite version or git SHA**: 5106cc807cf22a95420b24f6bfdd5c9ac8aa06de
- **Monolith or Polylith?**: monolith
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: no
- **`go version`**: 1.17.6
- **Client used (if applicable)**: element android, fluffychat android, element desktop/web, nheko

### Description

 - **What** is the problem: "sometimes" the message recipient is not sent keys to decrypt
 - **Who** is affected: recipients of E2EE messages sent by dendrite users
 - **How** is this bug manifesting: recipient sees only a notice that a message could not be decrypted, but from the dendrite user's perspective, all the messages are readable in all clients
 - **When** did this first appear: not sure this has ever been reliable, sometimes it works fine for a long period, other times it randomly fails even though it's the same session sending the messages (and that client has not been restarted since the last time it was working)

### Steps to reproduce

"Recently" I've noticed a new issue where clients will constantly spam the server with key related requests.  
I had reliability issues with sending E2EE messages before that, but now element in firefox and element desktop and nheko are constantly making key related requests in an endless loop.  I don't know how to open a debug output in android but the CPU load on the phone from running Element is continuous and the network never idles when it's open.

### Describe how what happens differs from what you expected.

E2EE should reliably work (and if it can't work there should be an error printed somewhere, not a silent failure that gives the impression the message was sent successfully).

**Comment by r3k2** [comment]
I am seen a similar problem, most likely the same as @bones-was-here I have tested this between my test account on matrix.org and my personal and main account on hispagatos.org. I can read what my matrix.org account writes to me on a 1:1 but when I write  from hispagatos.org account on the other side I get a "message could not be decrypted" and sometimes other similar ones on the matrix.org side. This is noticeable specially on some rooms we host between people on diverse matrix servers, they have been complaining that they can't see any of the people's msg's that come from our dendrite server.
cheers.

**Comment by kegsay** [comment]
So this could be either:
 - Dendrite isn't telling clients about all the devices for a user, so the client never encrypts messages for the matrix.org device.
 - Dendrite isn't receiving the device list updates from matrix.org over federation for some reason, e.g https://github.com/matrix-org/dendrite/issues/1601

**Comment by bones-was-here** [comment]
```
du -hs jetstream/\$G/streams/*
40K     jetstream/$G/streams/DendriteInputRoomEvent
40K     jetstream/$G/streams/DendriteOutputClientData
2.5G    jetstream/$G/streams/DendriteOutputKeyChangeEvent
492K    jetstream/$G/streams/DendriteOutputReceiptEvent
56K     jetstream/$G/streams/DendriteOutputRoomEvent
56K     jetstream/$G/streams/DendriteOutputSendToDeviceEvent
```

**Comment by bones-was-here** [comment]
I think it is encrypting, just with no way for the client to decrypt and no way for the sender to know there was a problem.  I reproduced it just now:
```
Decrypted event source

{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.bad.encrypted",
    "body": "** Unable to decrypt: The sender's device has not sent us the keys for this message. **"
  }
}

Original event source

{
  "content": {
    "algorithm": "m.megolm.v1.aes-sha2",
    "ciphertext": "AwgAEpABuR7Y8lZdqVRhQb2/JkXfenfEZn8XmM79aFkgs8Dy/ylf3LpwZWrQfXZFoIMQGfdyStK7bMG7fUSW2L5GII/Fn2U0tB4vLBheYKBRbRL9Tz+HkzjcXjss7gevFq5sM0e8/IxLPEoYZj7krxGyqzLXkMoFCmtdSHdHmB4o9f22rCfgWclhVsp932V/IRp9nZpJFTr00D/PUXbzUq5fs0rFQf+36GiDRfLn+B7ugbke2gEiWPugL/y1Itlfc5/B/i9URWEcLnukj+E6pWtNr8HpHcqLbbVE0dAB",
    "device_id": "8FJwtH0g",
    "sender_key": "nIaJ1o5X4U1aS5wvqKoC/dFDuv6W6l88M8LcovFhEHY",
    "session_id": "f9RYKueJkaczcLEk09ChFg7SFhhAVUv/5VcJAcjAdeU"
  },
  "origin_server_ts": 1645196307027,
  "sender": "@bones_was_here:xonotic.org",
  "type": "m.room.encrypted",
  "unsigned": {},
  "event_id": "$dc0YYjwa-JrOQ-JeIkl-HemImYs0Xiay4wQIl2HvB1I",
  "room_id": "!F9SctfHbpoz7GzEu:xonotic.org"
}
```

**Comment by bones-was-here** [comment]
The growth rate of stream "DendriteOutputKeyChangeEvent" is currently averaging about 125 messages per minute.

**Comment by r3k2** [comment]
in our case, I had reports of people on small instances getting our keys and eventually been able to read msgs from users on our server like around 9-10 have reported this, but  on matrix.org people never can see any of the msg any one on our server post and we have a bunch of people using dendrite daily.

**Comment by bones-was-here** [comment]
As mentioned in chat, the spam mentioned in OP looks like this (in element 1.10.4 in firefox or element desktop)
```
OPTIONS /_matrix/client/r0/sync?filter=1&timeout=30000&since=s174818_110_193336_6191_171832_174803_9514990
GET     /_matrix/client/r0/sync?filter=1&timeout=30000&since=s174818_110_193336_6191_171832_174803_9514990
OPTIONS /_matrix/client/r0/sync?filter=1&timeout=30000&since=s174818_110_193336_6191_171832_174803_9514994
GET     /_matrix/client/r0/sync?filter=1&timeout=30000&since=s174818_110_193336_6191_171832_174803_9514994
OPTIONS /_matrix/client/r0/sync?filter=1&timeout=30000&since=s174818_110_193336_6191_171832_174803_9514998
GET     /_matrix/client/r0/sync?filter=1&timeout=30000&since=s174818_110_193336_6191_171832_174803_9514998
```
It continues like that at several requests per second whenever the client(s) are open, with the same behaviour in all new sessions.  
This has been happening with dendrite since about 0.6 including 0.6.4 and doesn't happen when logged into matrix.org.

**Comment by bones-was-here** [comment]
0.6.4 E2EE DM update: no change.  With fresh sessions element web is sending un-decryptable messages, element android is sending decryptable messages.  Same procedure in both: log in, paste in my e2ee key, successfully restore all keys from backup, sessions show as verified in both clients, all e2ee message history is readable.

**Comment by bones-was-here** [comment]
And possibly some leftover issue from the OTK cleanup #2208
`level=error msg="internal.DeviceListCatchup failed" device_id=0kTVEoUO error="Failed to query OTK counts: context canceled" limit=20 req.id=muHaIF1euT2u req.method=GET req.path=/_matrix/client/r0/sync since=s175549_422_194996_6224_171832_175561_9597270 timeout=30s user_id="@bones_was_here:xonotic.org"`

**Comment by bones-was-here** [comment]
I changed log level to debug and the homeserver is printing `level=debug msg="QueryKeyChanges request off=11272428,to=11272430 response off=11272430 uids=[@user:server]" context=missing` at up to 10 per second, which seems like it could be related to (at least some of) the CPU load in #2181 and the steadily growing `DendriteOutputKeyChangeEvent` in jetstream.  

Currently it's the same two users in all the messages, I know both of them and am confident they're not attacking the homeserver :) One is on matrix.org, the other is on a personal homeserver that also runs synapse.

**Comment by bones-was-here** [comment]
It seems to be Nheko clients causing the QueryKeyChanges spam, and Nheko spams the server much faster than my Element client does.  But the fact that both clients are spamming the server (with sync requests) suggests they expect something that Dendrite isn't providing.

**Comment by bones-was-here** [comment]
The spamming is fixed by #2233 but at 8dfc958dddc5f7125633f9b5cf55371ab35ceb6c I still send undecryptable E2EE messages from some sessions to some users (for other users, the same session's E2EE messages are decrypted).

**Comment by neilalexander** [comment]
Is this still the case on 0.7.0 or `main`?

**Comment by r3k2** [comment]
@neilalexander I will ask my users later on our private channel see if they still had it, Myself last week someone from matrix told me he can't read me. I do git pull and ./build.sh daily so not sure which version it was, but tonight I will try to log in with my test account on matrix.org and ask my users and report back. thanks

**Comment by r3k2** [comment]
@neilalexander they say is better but it happens at times, and I just remembed to reply here because I logged into my test account and I just replicated it again today 
![still-matrix-issues](https://user-images.githubusercontent.com/5316229/162477303-b4fd3916-8e3c-4f5c-b1f7-d1e041ae158b.png)

**Comment by bones-was-here** [comment]
There seems to be a pattern to the inability of matrix.org users to decrypt messages sent from Element Web on Dendrite.

If I have not started Element Android (eg rebooted phone) recipient gets:  
`** Unable to decrypt: The sender's device has not sent us the keys for this message. **`  
And this is permanent (those messages will have to be re-sent).

If I have started it but it's not currently running (eg phone in sleep) recipient gets:
`** Unable to decrypt: Error: OLM.UNKNOWN_MESSAGE_INDEX **`  
And these will tend to become readable when I start up Element Android and view the room in question.

If I keep the phone plugged in with Android dev options set to always keep the screen awake, and I keep Element as the foreground app (just idling at the room list), E2EE works in Element Web.

**Comment by Mic92** [comment]
I can confirm this issue still with dendrite 0.8.8. I can also confirm that it not only happens with element but also with https://github.com/poljar/weechat-matrix which is based on `matrix-nio`

**Comment by jittygitty** [comment]
I've had unable to decrypt errors with both participants using Android client and connected to "same" Dendrite server. I've just upgraded to latest dendrite via pull request, still can't get the keys.
https://github.com/matrix-org/dendrite/issues/2436
https://github.com/vector-im/element-web/issues/19748

**Comment by timaeos** [comment]
Just a quick update:
I updated to the latest [commit](https://github.com/matrix-org/dendrite/commit/7bfc3074d10b2cd91b37290e39d3882119853107)
After some work clearing out old devices and redoing the device verification on the dendrite server, I'm now only having this problem intermittently in the opposite direction (i.e. dendrite -> matrix e2ee sends keys but matrix -> dendrite doesn't).

**Comment by 5trongthany** [comment]
I discussed the issue with a user in the Dendrite chat and was told to run some DB commands that "Instructs Dendrite to re-new the device lists/keys of the given user, so hopefully your client now received a device_list.changed entry for that user and encrypts messages successfully to that user"

I ran these commands on my postgres server, which seems to have resolved the issue for now:
`SELECT * FROM keyserver_stale_device_lists WHERE user_id = 'MATRIX_USER_ID';`
UPDATE keyserver_stale_device_lists SET is_stale = true WHERE user_id = 'MATRIX_USER_ID';

this seems to have helped with the issue. I am not sure how this could be worked into fixing the main issue, but thought it relevant.

**Comment by timaeos** [comment]
@S7evinK appears to be working on making an e

> I discussed the issue with a user in the Dendrite chat and was told to run some DB commands that "Instructs Dendrite to re-new the device lists/keys of the given user, so hopefully your client now received a device_list.changed entry for that user and encrypts messages successfully to that user"
> 
> I ran these commands on my postgres server, which seems to have resolved the issue for now: `SELECT * FROM keyserver_stale_device_lists WHERE user_id = 'MATRIX_USER_ID';` UPDATE keyserver_stale_device_lists SET is_stale = true WHERE user_id = 'MATRIX_USER_ID';
> 
> this seems to have helped with the issue. I am not sure how this could be worked into fixing the main issue, but thought it relevant.

@S7evinK appears to be working on an admin endpoint to streamline this procedure without requiring a dendrite server reboot (#2746 ) and messing around in the db.

The most recent commits that deal with parsing commit `e1bf709` appears to have helped with e2ee as well. If anyone is still showing this problem, please try updating to the latest commit

**Comment by S7evinK** [comment]
With a recent change `/members`, is this still happening? Is it better/worse?

**Comment by bones-was-here** [comment]
e2ee no longer works at all for me, in rooms where it did previously work, even between 2 users of the same dendrite instance.

**Comment by neilalexander** [comment]
> e2ee no longer works at all for me, in rooms where it did previously work, even between 2 users of the same dendrite instance.

Which commit are you on? We've been hearing the opposite overall from most users, that things have improved dramatically since 0.10.6 and the latest `main` commits.

**Comment by bones-was-here** [comment]
0.10.6 currently.  It got worse some time around 0.8.x or 0.9.x (rooms that used to work most of the time started breaking, the workaround of having all clients open simultaneously no longer helped) and currently seems broken all the time.  Very old messages from when it used to work can still be decrypted.

The messages that were sent before the invited user joined are visible now (after the usual clear cache & reload dance) so DM works better in that regard, but those also can't be decrypted if e2ee is enabled.

**Comment by bones-was-here** [comment]
Not sure if relevant to /members but on 0.10.6 when joining a DM via an invite, i still hit the incorrect users counting issue #2514 (it showed a total of 0 people but correctly listed 2).  Most rooms have correct member counts but our main room member count still shows an extra 12 users compared to synapse (even on the dendrite that originally created the room).

**Comment by bones-was-here** [comment]
I havn't seen any e2ee failures on 0.10.7 yet :)

**Comment by bones-was-here** [comment]
Just had an e2ee failure when another user of the same dendrite instance switched from element web to element android I could not decrypt the messages he sent from Android, and after re-syncing the android client he could no longer decrypt my messages.  He's using cross signing whereas I paste in the backup key whenever I log in to a client, so possibly cross signing is flakey.

**Comment by bones-was-here** [comment]
He reckons it works (for a while) if he's able to have both clients active at the same time.

**Comment by dvergeylen** [comment]
I am having the same issue. I can provide logs if that can help 🙂

**Comment by alnmy** [comment]
Having the same issue.
