### ISSUE TITLE
Can't connect to the dendrite room

### ISSUE THREAD

**Issue by SSamDav** [matrix-org/dendrite#2206]
### Background information

I'm running a docker compose with the following images:

- postgres:14
- matrixdotorg/dendrite-monolith:latest
- nats:latest

### Description

 - **What** I can't send a message to the dendrite room.
 - **Who** Me:
 - **How** is this bug manifesting:
  - `time="2022-02-20T15:01:46.948653531Z" level=error msg="QueryCurrentState: could not query membership for user" error="storage: state NIDs missing from the database (0 != 1)" [req.id](http://req.id/)=MxQjbarjeqF8 req.method=PUT req.path="/_matrix/client/r0/rooms/!yomrOFwgFXzmeMAbzX:[matrix.org/typing/@ssamdav:matrix.bongole.xyz](http://matrix.org/typing/@ssamdav:matrix.bongole.xyz)" user_id="[@ssamdav:matrix.bongole.xyz](https://matrix.to/#/@ssamdav:matrix.bongole.xyz)" `

**Comment by kegsay** [comment]
In order to send an event in a room Dendrite needs to get the current state of the room to attach things like auth events to the new event. This error message indicates dendrite cannot get the state of the room.

**Comment by SSamDav** [comment]
What should I do?

**Comment by neilalexander** [comment]
Just to be clear, your client is showing you the room but when you try to send a message or a typing notification, you see these errors?

The state NID error indicates that Dendrite doesn’t think you are joined to the room — the state NID that it’s looking for is your own membership event.

In some cases, you can issue another `/join` command from within Element to try to prompt the server to rejoin the room, but it’s a pretty bad bug if you still manage to see a room you aren’t fully joined to.

**Comment by SSamDav** [comment]
When I try to join the room I get this error:
```
time="2022-02-21T00:01:03.511389603Z" level=info msg="User requested to room join" room_id="#dendrite:matrix.org" servers="[]" user_id="@ssamdav:matrix.bongole.xyz"
time="2022-02-21T00:01:03.628886067Z" level=error msg="Failed to join room" error="error joining local room: \"QueryLatestEventsAndState: storage: state NIDs missing from the database (0 != 1)\"" room_id="#dendrite:matrix.org" servers="[]" user_id="@ssamdav:matrix.bongole.xyz"
time="2022-02-21T00:01:06.626713610Z" level=error msg="QueryCurrentState: could not query membership for user" error="storage: state NIDs missing from the database (0 != 1)" req.id=y29Gh8xuUj7U req.method=POST req.path="/_matrix/client/r0/rooms/!yomrOFwgFXzmeMAbzX:matrix.org/read_markers" user_id="@ssamdav:matrix.bongole.xyz"
time="2022-02-21T00:01:07.143057319Z" level=error msg="QueryCurrentState: could not query membership for user" error="storage: state NIDs missing from the database (0 != 1)" req.id=3JX8jCxwrztY req.method=POST req.path="/_matrix/client/r0/rooms/!yomrOFwgFXzmeMAbzX:matrix.org/read_markers" user_id="@ssamdav:matrix.bongole.xyz"
```

**Comment by SSamDav** [comment]
I also can't leave the room.

**Comment by neilalexander** [comment]
Can you please try commit https://github.com/matrix-org/dendrite/pull/2210/commits/bb2043d1cf2cf5bc1c64818418492c49ea9179b3 from #2210 and then try to re-join the room?

**Comment by neilalexander** [comment]
Glad to hear it!
