### ISSUE TITLE
Signing in from a new session does not sync room information

### ISSUE THREAD

**Issue by alistair23** [matrix-org/dendrite#2222]
### Background information

- **Dendrite version or git SHA**:  0.6.4
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **`go version`**: go version go1.17.3 linux/amd64
- **Client used (if applicable)**: Element Web

### Description

 - **What** is the problem: Signing in from a new session does not sync room information
 - **Who** is affected: Clients on my server
 - **How** is this bug manifesting: When I login
 - **When** did this first appear: Sometime after switching to jetstream

I have been having issues related to https://github.com/matrix-org/dendrite/issues/2181 but this is different again. When logging onto new sessions it all appears to work correctly but the room information is not sync correctly. The rooms show up in Element as "Empty Room", I can't see any previous messages, it seems like even the fact the room was encrypted is lost.

Existing clients seem to be fine though

### Steps to reproduce

- Login from a new device with Element
- Verify session with security key
- Look at the users rooms, all rooms are listed as "Empty Room" and the faviroute and low priority status is lost. There are also no previous messages.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by neilalexander** [comment]
Is this still true on the latest `main` commit? I haven’t been able to reproduce this at all on either of the Dendrite servers that I use so far.

**Comment by alistair23** [comment]
Still seems to be a problem, it seems very related to https://github.com/matrix-org/dendrite/issues/2150 though

**Comment by neilalexander** [comment]
I can't understand what's happening here. Can you increase your log level to `debug` and see if anything useful comes up when syncing your clients?

**Comment by alistair23** [comment]
After updating to 0.6.5 and deleting the jetstream directory it seems to be fixed, so I'm going to close this
