### ISSUE TITLE
Loading thumbnails takes a very long time

### ISSUE THREAD

**Issue by 0x1a8510f2** [matrix-org/dendrite#2243]
### Background information

- **Dendrite version or git SHA**: e46a61c49e5a0116b5df3df34a95cf5b8c811a8d built via images-build.sh
- **Monolith or Polylith?**: Mono
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: Yes
- **`go version`**: Not sure but likely not relevant
- **Client used (if applicable)**: Element Web/Android

### Description

 - **What** is the problem: Thumbnails regularly fail to load for a long time. This includes user avatars, room avatars and images in the timeline. Fetching the images themselves appears to work fine, because saving a broken image from the timeline produces a regular image with no delay. Only thumbnail generation appears to be affected.
 - **Who** is affected: Users on the dendrite instance
 - **How** is this bug manifesting: Images in timeline are blank, room and user avatars fallback to the placeholder.
 - **When** did this first appear: A few versions back, not sure when exactly. Didn't take note at the time because I put it down to poor internet connection.

### Steps to reproduce

- Sign in to account on Dendrite instance on Element Web
- Switch between spaces and notice that some of the room thumbnails fail to appear when switching back or when clearing cache and reloading

These steps are likely not complete, but I'm not sure what else is relevant. It has crossed my mind that I have some rooms whose icons are unfetchable as they're stored on servers which are now dead. Not sure if that is relevant at all.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by neilalexander** [comment]
This happens on dendrite.matrix.org too.
