### ISSUE TITLE
Migration from SQLite to Postgres

### ISSUE THREAD

**Issue by Semisol** [matrix-org/dendrite#2276]
**Description:** A script to migrate data from SQLite to Postgres

This would, to the extent that is possible, attempt to copy data from SQLite to Postgres so that the database engine can be switched.

**Comment by neilalexander** [comment]
This requires a bit of thought, because the database schemas across the two engines aren't exactly the same. We have different value formats for anything array-based and we have no sequences in SQLite so have had to workaround in other ways.

**Comment by DanielHons** [comment]
I think dendrite would not need to take care for this. https://pgloader.readthedocs.io/en/latest/ref/sqlite.html should do this well.

**Comment by plamenh** [comment]
You should check out this one:

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/importing-synapse-sqlite.md
