### ISSUE TITLE
Migration issues

### ISSUE THREAD

**Issue by ratsclub** [matrix-org/dendrite#2308]
I'm having some issues while migrating my [NixOS](https://nixos.org) server to another one with a bigger hard drive.

### Background information

- **Dendrite version or git SHA**: 0.7.0
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **`go version`**: 1.17.7
- **Client used (if applicable)**: Element

### Description

 - **What** is the problem: I can't send messages to rooms I'm already in "`user does not belong to room`" error
 - **Who** is affected: Every registered user
 - **How** is this bug manifesting: I can see it on Element's console log on the browser
 - **When** did this first appear: When I started the new server

### Steps to reproduce

- `pg_dump dendrite -U dendrite -h localhost -F c  --data-only > dendrite.dump` on the old server
- `pg_restore -U dendrite -h localhost -d dendrite dendrite.dump` on the new server
- Log in on https://app.element.io and see that your rooms and DMs are loaded
- Send a message and get "`user does not belong to room`" on console

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by neilalexander** [comment]
`--data-only` probably means that you dropped the sequences. Those are important.

**Comment by ratsclub** [comment]
@neilalexander You hit the nail! Thanks!
