### ISSUE TITLE
Adding users via Element for Android causes "sql: no rows in result set"

### ISSUE THREAD

**Issue by ddevault** [matrix-org/dendrite#2325]
### Background information

- **Dendrite version or git SHA**: 
- **Monolith or Polylith?**: 0.5.1
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **`go version`**: 1.17.4
- **Client used (if applicable)**: Element for Android

### Description

 - **What** is the problem: Attempting to add users for direct messages fails
 - **Who** is affected: Me
 - **How** is this bug manifesting: `"java.lang.RuntimeException: HTTP 500: {"message": "rsAPI.QueryKnownUsers: sql: no rows in result set"}`
 - **When** did this first appear: During the initial configuration of my instance

### Steps to reproduce

- Install dendrite on an Alpine Linux 3.15 server
- Configure with postgres or sqlite (reproducible with both)
- Configure reverse proxy from nginx
- Create initial user account
- Start up dendrite and log in with Element
- Start DM and enter any user details

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by spaetz** [comment]
0.5.1 is rater outdated and A LOT has changed since the current 0,7 release of dendrite. Perhaps upgrading to a current version will make the issue go away.

**Comment by ddevault** [comment]
It is reproducible on Dendrite 0.7.0.

**Comment by neilalexander** [comment]
Is this a monolith deployment or a polylith deployment?

**Comment by ddevault** [comment]
Monolith.

**Comment by neilalexander** [comment]
I suspect this is already actually fixed on `main` (as a part of the work I did in #2311). Any chance you can try the latest commit?

**Comment by neilalexander** [comment]
Please update the issue when you can.

**Comment by tombh** [comment]
I think I'm suffering from this as well. And notably I'm using Arch's AUR [dendrite-git](https://aur.archlinux.org/packages/dendrite-git), so I'm on the latest commit. The logs are full of:

`level=error msg="syncDB.GetFilter failed" func=github.com/matrix-org/dendrite/syncapi/sync.newSyncRequest file="github.com/matrix-org/dendrite/syncapi/sync/request.go:64" error="sql: no rows in result set"`

I registered with Element Web and I'm connecting with the [gomuks](https://github.com/tulir/gomuks) client. However, I don't get these errors when logging in with Element Web, so maybe this is a gomuks issue.

I should say that I'm a confused as to what `dendrite-create-account` is for, I added an account with it but I can't login with it. Are those accounts different from the ones I create through Element Web?

**Comment by kegsay** [comment]
Element Android must be doing something strange given we have integration tests for setting up DMs. I'll see if I can repro this next week.

**Comment by S7evinK** [comment]
@tombh How did you create the account using `create-account`?
Also, I think the problems you mentioned are unrelated to this issue, do you mind creating a new issue for this? :)

**Comment by tombh** [comment]
I've created new issues for each problem: #2349 and #2350 :)

**Comment by kegsay** [comment]
Closing as OP hasn't provided feedback.
