### ISSUE TITLE
Read receipt in DM triggers notification sound on Element Desktop

### ISSUE THREAD

**Issue by 0x1a8510f2** [matrix-org/dendrite#2353]
### Background information

- **Dendrite version or git SHA**: 0.8.1
- **Monolith or Polylith?**: Mono
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: Yes
- **`go version`**: n/a
- **Client used (if applicable)**: Element Desktop

### Description

 - **What** is the problem: Receiving a read receipt triggers a notification sound; this is not the case with Synapse
 - **Who** is affected: Element Desktop/Dendrite users
 - **How** is this bug manifesting: Sound plays when read receipt is received
 - **When** did this first appear: IIRC after the notifications support merge

### Steps to reproduce

- Start Element Desktop
- Send a message to another user
- Wait for user to open message
- Notice sound when read receipt goes through

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by neilalexander** [comment]
Probably a problem with the push rules. Maybe this:
```
      "room": [
        {
          "actions": [
            "notify",
            {
              "set_tweak": "sound",
              "value": "default"
            }
          ],
          "default": false,
          "enabled": true
        }
      ],
```

**Comment by baalajimaestro** [comment]
Hi, I have the same problem, but I am clueless on how to update the push rules, can you help me with it?

**Comment by Charadon** [comment]
I also have this problem. It's very annoying to hear the notification sound only to find there's nothing there. How do you modify push rules?

**Comment by neilalexander** [comment]
This is really strange and I cannot reproduce it. Dendrite doesn't handle EDUs in the notification code at all, so all I can assume is that there's something odd in the push rules and/or Element Web.

You can try nuking the push rules for your account and letting Dendrite regenerate them, i.e. something like this on the user API database, to see if that helps:
```
DELETE FROM account_data WHERE localpart = 'neilalexander' AND type = 'm.push_rules';
```

**Comment by Charadon** [comment]
> This is really strange and I cannot reproduce it. Dendrite doesn't handle EDUs in the notification code at all, so all I can assume is that there's something odd in the push rules and/or Element Web.
> 
> You can try nuking the push rules for your account and letting Dendrite regenerate them, i.e. something like this on the user API database, to see if that helps:
> 
> ```
> DELETE FROM account_data WHERE localpart = 'neilalexander' AND type = 'm.push_rules';
> ```

Unfortunately, that did not fix it. I should also mention that this is a fresh dendrite install

**Comment by baalajimaestro** [comment]
> This is really strange and I cannot reproduce it. Dendrite doesn't handle EDUs in the notification code at all, so all I can assume is that there's something odd in the push rules and/or Element Web.
> 
> You can try nuking the push rules for your account and letting Dendrite regenerate them, i.e. something like this on the user API database, to see if that helps:
> 
> ```
> DELETE FROM account_data WHERE localpart = 'neilalexander' AND type = 'm.push_rules';
> ```

This did fix it mostly. but there are some notifications from groups, where normal text, without a mention, or a keyword, gets triggered as message type notice, and triggers a notification on element/fluffychat. I have tried to debug this, but to not much avail. The message that becomes a notice, is seemingly very random.

**Comment by Charadon** [comment]
> This did fix it mostly. but there are some notifications from groups, where normal text, without a mention, or a keyword, gets triggered as message type notice, and triggers a notification on element/fluffychat. I have tried to debug this, but to not much avail. The message that becomes a notice, is seemingly very random.

Which database did you run that command on? Because for me, it didn't do anything.
