### ISSUE TITLE
History not fetched from other servers when (re)joining room

### ISSUE THREAD

**Issue by bones-was-here** [matrix-org/dendrite#2387]
### Background information

- **Dendrite version or git SHA**: 54ff4cf690918886c7e7a59a65ccff970c3aa1fc
- **Monolith or Polylith?**: monolith
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: no
- **`go version`**: 1.17.9
- **Client used (if applicable)**: element web

### Description

 - **What** is the problem: if a homeserver has had no users in a room for some time and re-joins it, the missing events are not fetched from remote servers
 - **Who** is affected: potentially any user of a homserver that has been out of a room it previously was in
 - **How** is this bug manifesting: when the user re-joins the room, no warns or errors are logged, and the fetched events are all retrieved locally (so in Element the user can see only very old messages, from when the server previously participated in the room)
 - **When** did this first appear: may have always been like this

After re-joining the room, if a user on a different homeserver posts a message, the re-joined user does not see it.  

If the re-joined user posts a message in a problematic room, this can trigger sudden fetching of events - not just in the room where the message was posted, but also in other rooms that are in the same state of missing recent events.  Not all history is loaded however, and it logs:
`level=warning msg="Stored rejected event" context=missing error="missingState.processEventWithMissingState: t.lookupState (backwards extremity): t.lookupStateAfterEvent: t.lookupStateBeforeEvent: contents=`
`level=warning msg="Roomserver failed to process async event" error="missingState.processEventWithMissingState: t.lookupState (backwards extremity): t.lookupStateAfterEvent: t.lookupStateBeforeEvent: contents=`
`level=warning msg="failed to get state after ... context=missing error="storage: event IDs missing from the database (0 != 1)"`

### Steps to reproduce

- create a room, invite user(s) from a different homeserver
- leave the room with all user(s) on the homeserver that created the room
- rejoin with the user that originally created the room, after "some time" and many messages

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by bones-was-here** [comment]
This seems related to the broken state I see for #dendrite:matrix.org

I tried to join this room with earlier versions of dendrite which never succeeded, so after a while I would give up and leave the room.

Now this room causes lots of warns/errors of the above types, and although the state has gradually improved, there are still some matrix.org users whose messages are not received on this dendrite instance.

**Comment by nakoo** [comment]
I have suffered the similar issue. I overlooked that I have to leave the room before deleting the dendrite server. Now if I join the room used on old dendrite server, I'm getting so much db and connections errors that I couldn't neither join the room nor fetch the data from newers.

I think this issue could be reproducable by:

- join the large room that needs more connection (like #matrix:matrix.org) 
- delete dendrite db
- rejoin the same room with same username

**Comment by bones-was-here** [comment]
This can also happen when joining a room the server has never participated in, and which contains some problematic old state events.

I tried to join `#dendrite-alerts:matrix.org` with Dendrite 0.8.8 which succeeded, but several days later no history from before my join event has loaded - not even the release announcements sent from matrix.org.  While the chat view is open in Element Web, Dendrite will repeatedly try to retrieve state events in a seemingly endless loop.  I'm not sure if it's iterating or randomly selecting servers to try, but it seems to be stuck on 3 missing events it can't retrieve from anywhere.

It logs things like this (the exact errors are different depending which server it's trying to fetch events from)
```
level=warning msg="Failed to request keys from fetcher" error="gomatrixserverlib: unable to lookup server keys: Post \"matrix://matrix.org/_matrix/key/v2/query\": context canceled" fetcher="perspective server matrix.org" req.id=kQsoYBQ7ijjM req.method=GET req.path=/_matrix/federation/v1/query/profile
level=error msg="Failed to fetch key for server" error="Post \"matrix://nfld.uk/_matrix/key/v2/query\": context canceled" fetcher=DirectKeyFetcher req.id=kQsoYBQ7ijjM req.method=GET req.path=/_matrix/federation/v1/query/profile
level=warning msg="Failed to retrieve any keys" fetcher=DirectKeyFetcher req.id=kQsoYBQ7ijjM req.method=GET req.path=/_matrix/federation/v1/query/profile
level=info msg="Error authenticating request" error="context canceled" req.id=kQsoYBQ7ijjM req.method=GET req.path=/_matrix/federation/v1/query/profile
level=info msg="backfilled 96 events" room_id="!UBhRLVEYYvUWnsljRs:matrix.org"
level=info msg="Fetching 3 missing state events (from 5 possible servers)" context=missing
```

```
level=warning msg="failed to get event from server" context=missing error="contents=[60 104 116 109 108 62 10 60 104 101 97 100 62 60 116 105 116 108 101 62 53 48 50 32 66 97 100 32 71 97 116 101 119 97 121 60 47 116 105 116 108 101 62 60 47 104 101 97 100 62 10 60 98 111 100 121 62 10 60 99 101 110 116 101 114 62 60 104 49 62 53 48 50 32 66 97 100 32 71 97 116 101 119 97 121 60 47 104 49 62 60 47 99 101 110 116 101 114 62 10 60 104 114 62 60 99 101 110 116 101 114 62 110 103 105 110 120 47 49 46 49 56 46 48 32 40 85 98 117 110 116 117 41 60 47 99 101 110 116 101 114 62 10 60 115 99 114 105 112 116 32 100 101 102 101 114 32 115 114 99 61 34 104 116 116 112 115 58 47 47 115 116 97 116 105 99 46 99 108 111 117 100 102 108 97 114 101 105 110 115 105 103 104 116 115 46 99 111 109 47 98 101 97 99 111 110 46 109 105 110 46 106 115 47 118 54 53 50 101 97 99 101 49 54 57 50 97 52 48 99 102 97 51 55 54 51 100 102 54 54 57 100 55 52 51 57 99 49 54 51 57 48 55 57 55 49 55 49 57 52 34 32 105 110 116 101 103 114 105 116 121 61 34 115 104 97 53 49 50 45 71 105 55 120 112 74 82 56 116 83 107 114 112 70 55 97 111 114 100 80 90 81 108 87 50 68 76 116 122 85 108 90 99 117 109 83 56 100 77 81 106 119 68 72 69 110 119 57 73 55 90 76 121 105 79 106 47 54 116 90 83 116 82 66 71 116 71 103 78 54 99 101 78 54 99 77 72 56 122 55 101 116 80 71 108 119 61 61 34 32 100 97 116 97 45 99 102 45 98 101 97 99 111 110 61 39 123 34 114 97 121 73 100 34 58 34 55 49 56 100 53 51 101 53 53 102 53 53 57 50 57 99 34 44 34 118 101 114 115 105 111 110 34 58 34 50 48 50 49 46 49 50 46 48 34 44 34 114 34 58 49 44 34 116 111 107 101 110 34 58 34 50 50 56 54 100 48 56 53 50 50 97 52 52 99 98 101 98 51 57 97 49 98 52 52 99 48 102 49 49 50 53 100 34 44 34 115 105 34 58 49 48 48 125 39 32 99 114 111 115 115 111 114 105 103 105 110 61 34 97 110 111 110 121 109 111 117 115 34 62 60 47 115 99 114 105 112 116 62 10 60 47 98 111 100 121 62 10 60 47 104 116 109 108 62 10] msg=Failed to GET JSON (hostname \"matrix.myl.moe\" path \"/_matrix/federation/v1/event/$BLXvAdiPVVLfxY-lW3GuJ8TunKU3QPb6MDCxJzHHInE\"): <html>\n<head><title>502 Bad Gateway</title></head>\n<body>\n<center><h1>502 Bad Gateway</h1></center>\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\n<script defer src=\"https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194\" integrity=\"sha512-Gi7xpJR8tSkrpF7aordPZQlW2DLtzUlZcumS8dMQjwDHEnw9I7ZLyiOj/6tZStRBGtGgN6ceN6cMH8z7etPGlw==\" data-cf-beacon='{\"rayId\":\"718d53e55f55929c\",\"version\":\"2021.12.0\",\"r\":1,\"token\":\"2286d08522a44cbeb39a1b44c0f1125d\",\"si\":100}' crossorigin=\"anonymous\"></script>\n</body>\n</html>\n code=502 wrapped=" event_id="$BLXvAdiPVVLfxY-lW3GuJ8TunKU3QPb6MDCxJzHHInE" server=matrix.myl.moe
level=info msg="Persisting 0 new events" context=missing
level=error msg="backfillViaFederation: failed to get state entries for event" error="storage: state event IDs missing from the database (989 != 992)" event_id="$-3qaskHl7ZIhob9U89npOFgI6GDNHIYGwrSgRjEck-o"
level=error msg="mreq.retrieveEvents failed" error="PerformBackfill failed: storage: state event IDs missing from the database (989 != 992)" req.id=B23r733XuSQu req.method=GET req.path="/_matrix/client/r0/rooms/!UBhRLVEYYvUWnsljRs:matrix.org/messages" user_id="@bones_was_here:xonotic.org"
```

It has the matrix.org key_perspectives config from dendrite-sample.monolith.yaml.

**Comment by nakoo** [comment]
> This can also happen when joining a room the server has never participated in, and which contains some problematic old state events.
> 
> I tried to join `#dendrite-alerts:matrix.org` with Dendrite 0.8.8 which succeeded, but several days later no history from before my join event has loaded - not even the release announcements sent from matrix.org. While the chat view is open in Element Web, Dendrite will repeatedly try to retrieve state events in a seemingly endless loop. I'm not sure if it's iterating or randomly selecting servers to try, but it seems to be stuck on 3 missing events it can't retrieve from anywhere.
> 
> It logs things like this (the exact errors are different depending which server it's trying to fetch events from)
> 
> ```
> level=warning msg="Failed to request keys from fetcher" error="gomatrixserverlib: unable to lookup server keys: Post \"matrix://matrix.org/_matrix/key/v2/query\": context canceled" fetcher="perspective server matrix.org" req.id=kQsoYBQ7ijjM req.method=GET req.path=/_matrix/federation/v1/query/profile
> level=error msg="Failed to fetch key for server" error="Post \"matrix://nfld.uk/_matrix/key/v2/query\": context canceled" fetcher=DirectKeyFetcher req.id=kQsoYBQ7ijjM req.method=GET req.path=/_matrix/federation/v1/query/profile
> level=warning msg="Failed to retrieve any keys" fetcher=DirectKeyFetcher req.id=kQsoYBQ7ijjM req.method=GET req.path=/_matrix/federation/v1/query/profile
> level=info msg="Error authenticating request" error="context canceled" req.id=kQsoYBQ7ijjM req.method=GET req.path=/_matrix/federation/v1/query/profile
> level=info msg="backfilled 96 events" room_id="!UBhRLVEYYvUWnsljRs:matrix.org"
> level=info msg="Fetching 3 missing state events (from 5 possible servers)" context=missing
> ```
> 
>  ```
> level=warning msg="failed to get event from server" context=missing error="contents=[60 104 116 109 108 62 10 60 104 101 97 100 62 60 116 105 116 108 101 62 53 48 50 32 66 97 100 32 71 97 116 101 119 97 121 60 47 116 105 116 108 101 62 60 47 104 101 97 100 62 10 60 98 111 100 121 62 10 60 99 101 110 116 101 114 62 60 104 49 62 53 48 50 32 66 97 100 32 71 97 116 101 119 97 121 60 47 104 49 62 60 47 99 101 110 116 101 114 62 10 60 104 114 62 60 99 101 110 116 101 114 62 110 103 105 110 120 47 49 46 49 56 46 48 32 40 85 98 117 110 116 117 41 60 47 99 101 110 116 101 114 62 10 60 115 99 114 105 112 116 32 100 101 102 101 114 32 115 114 99 61 34 104 116 116 112 115 58 47 47 115 116 97 116 105 99 46 99 108 111 117 100 102 108 97 114 101 105 110 115 105 103 104 116 115 46 99 111 109 47 98 101 97 99 111 110 46 109 105 110 46 106 115 47 118 54 53 50 101 97 99 101 49 54 57 50 97 52 48 99 102 97 51 55 54 51 100 102 54 54 57 100 55 52 51 57 99 49 54 51 57 48 55 57 55 49 55 49 57 52 34 32 105 110 116 101 103 114 105 116 121 61 34 115 104 97 53 49 50 45 71 105 55 120 112 74 82 56 116 83 107 114 112 70 55 97 111 114 100 80 90 81 108 87 50 68 76 116 122 85 108 90 99 117 109 83 56 100 77 81 106 119 68 72 69 110 119 57 73 55 90 76 121 105 79 106 47 54 116 90 83 116 82 66 71 116 71 103 78 54 99 101 78 54 99 77 72 56 122 55 101 116 80 71 108 119 61 61 34 32 100 97 116 97 45 99 102 45 98 101 97 99 111 110 61 39 123 34 114 97 121 73 100 34 58 34 55 49 56 100 53 51 101 53 53 102 53 53 57 50 57 99 34 44 34 118 101 114 115 105 111 110 34 58 34 50 48 50 49 46 49 50 46 48 34 44 34 114 34 58 49 44 34 116 111 107 101 110 34 58 34 50 50 56 54 100 48 56 53 50 50 97 52 52 99 98 101 98 51 57 97 49 98 52 52 99 48 102 49 49 50 53 100 34 44 34 115 105 34 58 49 48 48 125 39 32 99 114 111 115 115 111 114 105 103 105 110 61 34 97 110 111 110 121 109 111 117 115 34 62 60 47 115 99 114 105 112 116 62 10 60 47 98 111 100 121 62 10 60 47 104 116 109 108 62 10] msg=Failed to GET JSON (hostname \"matrix.myl.moe\" path \"/_matrix/federation/v1/event/$BLXvAdiPVVLfxY-lW3GuJ8TunKU3QPb6MDCxJzHHInE\"): <html>\n<head><title>502 Bad Gateway</title></head>\n<body>\n<center><h1>502 Bad Gateway</h1></center>\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\n<script defer src=\"https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194\" integrity=\"sha512-Gi7xpJR8tSkrpF7aordPZQlW2DLtzUlZcumS8dMQjwDHEnw9I7ZLyiOj/6tZStRBGtGgN6ceN6cMH8z7etPGlw==\" data-cf-beacon='{\"rayId\":\"718d53e55f55929c\",\"version\":\"2021.12.0\",\"r\":1,\"token\":\"2286d08522a44cbeb39a1b44c0f1125d\",\"si\":100}' crossorigin=\"anonymous\"></script>\n</body>\n</html>\n code=502 wrapped=" event_id="$BLXvAdiPVVLfxY-lW3GuJ8TunKU3QPb6MDCxJzHHInE" server=matrix.myl.moe
> level=info msg="Persisting 0 new events" context=missing
> level=error msg="backfillViaFederation: failed to get state entries for event" error="storage: state event IDs missing from the database (989 != 992)" event_id="$-3qaskHl7ZIhob9U89npOFgI6GDNHIYGwrSgRjEck-o"
> level=error msg="mreq.retrieveEvents failed" error="PerformBackfill failed: storage: state event IDs missing from the database (989 != 992)" req.id=B23r733XuSQu req.method=GET req.path="/_matrix/client/r0/rooms/!UBhRLVEYYvUWnsljRs:matrix.org/messages" user_id="@bones_was_here:xonotic.org"
> ```
> 
> It has the matrix.org key_perspectives config from dendrite-sample.monolith.yaml.

Yeah, it still happens to me too.
