### ISSUE TITLE
Very heavy resource usage, unable to stop participating in old version of #dendrite:matrix.org

### ISSUE THREAD

**Issue by bones-was-here** [matrix-org/dendrite#2396]
### Background information

- **Dendrite version or git SHA**: 0.8.2
- **Monolith or Polylith?**: monolith
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: no
- **`go version`**: 1.17.9
- **Client used (if applicable)**: element web

### Description

 - **What** is the problem: dendrite is using excessive CPU, RAM, DB storage to participate in an obsolete room
 - **Who** is affected:
 - **How** is this bug manifesting:
 - **When** did this first appear: after the spam attack on the previous room, it appeared to recover and gradually reduce in resource usage, but then regressed.

### Steps to reproduce

There don't seem to be any steps to _not_ reproduce this problem on my instance.

Restarting dendrite, leaving the old room, rejoining the old room, telling dendrite to forget the room, have no effect.  When it starts up it goes back to printing the usual kinds of messages for that room.

Related to #2176

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->



```
level=warning msg="failed to get state after $XtzFNTwrI1aXtMrRLkfqRUHgPrp3V8gF1QbDHasl3yw locally" context=missing error="storage: missing state for event NID 199698" room_id="!yomrOFwgFXzmeMAbzX:matrix.org"
level=error msg="Error checking if allowed to see event" error="roomState.LoadStateAtEvent: LoadStateAtEvent.SnapshotNIDFromEventID($Hf4uaSjyxnBAVWuZv49jRSyQSHxl_gVH7KEPS9ctfwk) returned 0 NID, was this event stored?" event_id="$Hf4uaSjyxnBAVWuZv49jRSyQSHxl_gVH7KEPS9ctfwk" req.id=isLed3TPKNSo req.method=POST req.path="/_matrix/federation/v1/get_missing_events/!yomrOFwgFXzmeMAbzX:matrix.org" server=matrix.blacksword.games
level=warning msg="Couldn't validate signature of event \"$ZEDC7EHXMgwzIbrieNi0w-S15VBfAoikf7M3uCrb7Jc\" from /event" context=missing error="gomatrixserverlib: key with ID \"ed25519:a_WRob\" for \"hispagatos.org\" not valid at 1578677304783"
level=error msg="failed to query device keys for some users" context=missing failed=1 server_name=dogyap.xyz total=1 wait=8h0m0s
level=info msg=DeviceListUpdater.Update context=missing deleted=true device_id=RICOMLMKBM display_name="" prev_ids="[]" prev_ids_exist=false stream_id=327927 user_id="@spambot36p32dtwsj:imeyer.io"
```

**Comment by neilalexander** [comment]
Can you please take a CPU profile so we can work out exactly what it's doing?

https://github.com/matrix-org/dendrite/blob/main/docs/PROFILING.md

**Comment by bones-was-here** [comment]
[profile.gz](https://github.com/matrix-org/dendrite/files/8581796/profile.gz)
This is 64 seconds taken shortly after startup (waited for the first "Cleaning old notifications"), memory usage is not too bad yet

**Comment by bones-was-here** [comment]
As others have mentioned in chat, (outgoing) bandwidth usage is far above what would be expected for this instance

**Comment by bones-was-here** [comment]
Presence is disabled (incoming and outgoing)

**Comment by neilalexander** [comment]
Can you please give #2398 a try and see if that improves things?

**Comment by bones-was-here** [comment]
#2398 is a big improvement for CPU, RAM, and outgoing bandwidth.  

- I was back in the old room at the time of compiling and restarting
- Waited for the first "Cleaning old notifications"
- Observed the heavy resource usage
- Left the old room
- Resource usage decreased rapidly, postgres was busy for a bit and then the server looked much happier :)

**Comment by neilalexander** [comment]
Great, I'll merge it!
