### ISSUE TITLE
max_file_size_bytes = 0 counts as limited file size

### ISSUE THREAD

**Issue by nakoo** [matrix-org/dendrite#2408]
### Background information

- **Dendrite version or git SHA**: 0.8.2
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: Yes
- **`go version`**: -
- **Client used (if applicable)**: Element Web

### Description

 - **What** is the problem:
When `max_file_size_bytes` to `0`, uploading file doesn't count as unlimited as intended. Fetching file from other servers counts as unlimited.

 - **Who** is affected: -
 - **How** is this bug manifesting:
 
![2022-04-30_12-33](https://user-images.githubusercontent.com/4975021/166107140-4d834b21-ec22-4621-8a9c-914f89c7f7f1.png)
 - **When** did this first appear:
Set `max_file_size_bytes` to `0` in `dendrite.yaml` config file

### Steps to reproduce

- Set `max_file_size_bytes` to `0` in `dendrite.yaml` config file
- Restart the server
- Try to upload the file

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by spaetz** [comment]
Is that not rather a client issue? The spec says:

`m.upload.size 	integer 	The maximum size an upload can be in bytes. Clients SHOULD use this as a guide when uploading content. If not listed or null, the size limit should be treated as unknown`.

**Comment by nakoo** [comment]
> Is that not rather a client issue? The spec says:
> 
> `m.upload.size integer The maximum size an upload can be in bytes. Clients SHOULD use this as a guide when uploading content. If not listed or null, the size limit should be treated as unknown`.
> 
> Or does 'null' not include zero in this case?

It seems `checkPositive` function doesn't check 0.
We need to set like `-1` for unlimited.

https://github.com/matrix-org/dendrite/blob/a84f50f4fb0963e15b6aca60f658bed45b779127/setup/config/config_mediaapi.go#L64

https://github.com/matrix-org/dendrite/blob/a84f50f4fb0963e15b6aca60f658bed45b779127/setup/config/config.go#L383-L387

We need to document this part correctly as I mentioned. (same with `build/docker/config/dendrite.yaml`)

https://github.com/matrix-org/dendrite/blob/bfa344e83191c49bdc9917ab7a8ec31b93c202e9/dendrite-config.yaml#L261-L264
