### ISSUE TITLE
msg="GetUserDevices returned unknown error type" context=missing error="json: cannot unmarshal object into Go struct field RespUserDeviceKeys.devices.keys.device_id of type string" 

### ISSUE THREAD

**Issue by myxor** [matrix-org/dendrite#2426]
### Background information

- **Dendrite version or git SHA**:  `matrixdotorg/dendrite-monolith:main` docker image, hash: `f1bc07e2783f`
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**:  Postgresql
- **Running in Docker?**:  Yes
- **`go version`**: from docker image
- **Client used (if applicable)**:

### Description

 - **What** is the problem:
The following warning/error messages are spamming my log multiple times per second:

> time="2022-05-05T12:54:07.346604659Z" level=warning msg="GetUserDevices returned unknown error type" context=missing error="json: cannot unmarshal object into Go struct field RespUserDeviceKeys.devices.keys.device_id of type string" server_name=matrix.org user_id="@XXX:matrix.org"
> time="2022-05-05T12:54:07.943592081Z" level=error msg="failed to query device keys for some users" context=missing failed=1 server_name=matrix.org total=2 wait=1h0m0s
> time="2022-05-05T12:54:07.948765651Z" level=info msg=DeviceListUpdater.Update context=missing deleted=false device_id=NNNVMNSXXS display_name="" prev_ids="[3575163522]" prev_ids_exist=false stream_id=3575165145 user_id="XXX:matrix.org"
> time="2022-05-05T12:54:08.382876302Z" level=warning msg="GetUserDevices returned unknown error type" context=missing error="json: cannot unmarshal object into Go struct field RespUserDeviceKeys.devices.keys.device_id of type string" server_name=matrix.org user_id="XXX:matrix.org"
> time="2022-05-05T12:54:09.058492531Z" level=error msg="failed to query device keys for some users" context=missing failed=1 server_name=matrix.org total=2 wait=1h0m0s
> time="2022-05-05T12:54:09.060987150Z" level=info msg=DeviceListUpdater.Update context=missing deleted=false device_id=ZCETOZOAZA display_name="" prev_ids="[3575165145]" prev_ids_exist=false stream_id=3575169229 user_id="XXX:matrix.org"
> time="2022-05-05T12:54:09.966066901Z" level=warning msg="GetUserDevices returned unknown error type" context=missing error="json: cannot unmarshal object into Go struct field RespUserDeviceKeys.devices.keys.device_id of type string" server_name=matrix.org user_id="XXX:matrix.org"
> time="2022-05-05T12:54:10.562863944Z" level=error msg="failed to query device keys for some users" context=missing failed=1 server_name=matrix.org total=2 wait=1h0m0s
> time="2022-05-05T12:54:10.565991770Z" level=info msg=DeviceListUpdater.Update context=missing deleted=false device_id=EFHNLRSZAZ display_name="" prev_ids="[3575169229]" prev_ids_exist=false stream_id=3575182447 user_id="XXX:matrix.org"
> time="2022-05-05T12:54:10.801073946Z" level=warning msg="GetUserDevices returned unknown error type" context=missing error="json: cannot unmarshal object into Go struct field RespUserDeviceKeys.devices.keys.device_id of type string" server_name=matrix.org user_id="XXX:matrix.org"
> time="2022-05-05T12:54:11.461493749Z" level=error msg="failed to query device keys for some users" context=missing failed=1 server_name=matrix.org total=2 wait=1h0m0s
> time="2022-05-05T12:54:11.465462739Z" level=info msg=DeviceListUpdater.Update context=missing deleted=false device_id=OFBFQUSUQY display_name="" prev_ids="[3575182447]" prev_ids_exist=false stream_id=3575184069 user_id="XXX:matrix.org"
> 

Please note that i removed the user ids from the log

 - **Who** is affected:
 - **How** is this bug manifesting:
 - **When** did this first appear:
 Saw it today the first time

### Steps to reproduce

- don't know how to reproduce this but i can provide more logs if necessary

I have disable presence events in my config:

```
   # Configures the handling of presence events.
    presence:
      # Whether inbound presence events are allowed, e.g. receiving presence events from other servers
      enable_inbound: false
      # Whether outbound presence events are allowed, e.g. sending presence events to other servers
      enable_outbound: false
```

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by neilalexander** [comment]
This is a known issue at the moment where the device list updater isn't backing off properly when certain users or servers are dead. In this case, the user in question has genuinely invalid device keys (we've seen this in our logs too). I believe @kegsay is planning to work more on the device list updates.

**Comment by S7evinK** [comment]
Closing this for now, as with some recent changes to the device list updater this error message should be handled differently.
If you're still seeing this, feel free to re-open.
