### ISSUE TITLE
prometheus.Handler() is deprecated, figure out how to replace it

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/dendrite#243]

**Comment by t3chguy** [comment]
as far as I am aware this is just a straight s/`prometheus.Handler()`/`promhttp.Handler()`
that's how matrix-static's prom works anyway

**Comment by erikjohnston** [comment]
Ah, yes.

For the record: `prometheus.Handler` automatically includes a bunch of useful metrics (apparently), whereas `promhttp.Handler` doesn't. We can recreate a lot of it with the helper functions in `promhttp`, but we need to figure out what stats we want

**Comment by t3chguy** [comment]
I wonder if matrix-static is missing a load of useful metrics, I don't believe it is though when I checked locally

**Comment by Kegsay** [comment]
We use `promhttp` now.
