### ISSUE TITLE
Allow using self-signed certificates when connecting to external NATS

### ISSUE THREAD

**Issue by nahsi** [matrix-org/dendrite#2463]
If NATS configured to use TLS with self-signed certificates dendrite will panic with
```
time="2022-05-15T09:41:11.368171456Z" level=panic msg="Unable to connect to NATS" error="x509: certificate signed by unknown authority"
```

**Comment by neilalexander** [comment]
This should be easy enough to do — we just need to add something to the JetStream section of the Dendrite config that configures nats.go to pass through a [custom `tls.Config`](https://pkg.go.dev/github.com/nats-io/nats.go#Secure) with skip-verify enabled.
