### ISSUE TITLE
State of #dendrite:matrix.org is broken

### ISSUE THREAD

**Issue by bones-was-here** [matrix-org/dendrite#2465]
### Background information

- **Dendrite version or git SHA**: 0.8.5
- **Monolith or Polylith?**: monolith
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: no
- **`go version`**: 1.17.9
- **Client used (if applicable)**: Element web

### Description

 - **What** is the problem: Dendrite's view of the room differs hugely from matrix.org's view, to the point that it's unusable.  It considers the room to be invite-only, so it rejects the joins and messages of all users who joined after the room was (temporarily) invite only.  It considers @neilalexander:dendrite.matrix.org to not be in the room.
 - **Who** is affected:
 - **How** is this bug manifesting:
 - **When** did this first appear: it has never worked properly, but is worse than it used to be

### Steps to reproduce

Other Dendrite users have reported a similar problem in chat, including that other users on their homeserver cannot join the room.
Possibly related to #2129

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by neilalexander** [comment]
Please check your logs for any `eventauth:` entries for room ID `!RcWPWcZrMeBxOGaalX:matrix.org`. If there are things being rejected, those entries should reveal why.
