### ISSUE TITLE
Local room address is not shown in element (and cannot be removed/edited)

### ISSUE THREAD

**Issue by spaetz** [matrix-org/dendrite#2486]
### Background information

- **Dendrite version or git SHA**: main
- **Monolith or Polylith?**: mono
- **SQLite3 or Postgres?**: PG
- **Running in Docker?**:  NO
- **`go version`**: 1.18
- **Client used (if applicable)**: element web

### Description

If I add a local name on a "foreign room", e.g. #dendrite:matrix.org, I can close the room setting dialog. reopen it, and the dialog will show me "This room has no local addresses". However, it does exist (I can join the local room address). The problem manifested itself when the #dendrite room was upgraded, as apparently the local address was still pointing to the old room. So I could not set a local "#dendrite" alias to the new room version, as it was allegedly already in use. With not being able to see the local address, I can also not remove/delete it from the old room...

**Comment by neilalexander** [comment]
This seems to be an Element Web bug as it is trying to use an unstable aliases endpoint (which Dendrite doesn't/won't support) instead of the specced endpoint. I've created an issue.

**Comment by neilalexander** [comment]
This is fixed in Element Web/Desktop [v1.10.14](https://github.com/vector-im/element-web/releases/tag/v1.10.14).

**Comment by spaetz** [comment]
Can confirm as fixed! Local aliases are now showin. Thanks Neil
