### ISSUE TITLE
404 Response when viewing Space Summary when MSC2946 is enabled

### ISSUE THREAD

**Issue by timaeos** [matrix-org/dendrite#2491]
### Background information

- **Dendrite version or git SHA**:  commit ac4d0072cf5507d7de1504d16aa5c4ca8537eb26
- **Monolith or Polylith?**:  Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **`go version`**: 1.16.15
- **Client used (if applicable)**: Element (desktop)

### Description

 - **What** is the problem: Server receives a 404 Response when attempting to receive the hierarchy for spaces
 - **Who** is affected: Clients on my server when viewing Spaces Summaries
 - **How** is this bug manifesting: The homeserver is receiving 404 responses from the server as noted below and showing "Unknown Room" errors despite the room existing. Eventually the spaces summary shows the list of rooms and the rooms are able to be joined.
 - **When** did this first appear: noticed after upgrading to commit ac4d0072cf5507d7de1504d16aa5c4ca8537eb26 -- Could potentially have happened earlier.

### Steps to reproduce

- Join a space that has encrypted and restricted join v9 rooms
- View the Space Summary with MSC2946 enabled in the dendrite configuration
- Monitor logs for the dendrite server

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

I expect it to behave as noted in the spec https://spec.matrix.org/unstable/client-server-api/#discovering-rooms-within-spaces

GET /_matrix/client/v1/rooms/{roomId}/hierarchy

Added in v1.2

Paginates over the space tree in a depth-first manner to locate child rooms of a given space.

Where a child room is unknown to the local server, federation is used to fill in the details. The servers listed in the via array should be contacted to attempt to fill in missing rooms.

Only [m.space.child](https://spec.matrix.org/unstable/client-server-api/#mspacechild) state events of the room are considered. Invalid child rooms and parent events are not covered by this endpoint.

```
May 25 09:43:02 hermes dendrite-start.sh[445433]: time="2022-05-25T14:43:02.719665879Z" level=warning msg="failed to call MSC2946Spaces on server tchncs.de" error="contents=[123 34 101 114 114 99 111 100 101 34 58 34 77 95 85 78 75 78 79 87 78 34 44 34 101 114 114 111 114 34 58 34 85 110 107 110 111 119 110 32 114 111 111 109 58 32 33 118 108 108 107 101 65 88 71 120 67 66 98 85 103 106 82 66 113 58 116 99 104 110 99 115 46 100 101 34 125] msg=Failed to GET JSON (hostname \"tchncs.de\" path \"/_matrix/federation/unstable/org.matrix.msc2946/hierarchy/!vllkeAXGxCBbUgjRBq:tchncs.de\") code=404 wrapped=M_UNKNOWN: Unknown room: !vllkeAXGxCBbUgjRBq:tchncs.de" req.id=tEPpwFRzzXke req.method=GET req.path="/_matrix/client/v1/rooms/!sdGyoypKTYFXzEvrBf:tchncs.de/hierarchy" user_id="@timaeos:matrix.nexaeos.io"
```

**Comment by spaetz** [comment]
Err, the error log you posted indicates that
https://tchncs.de/_matrix/federation/unstable/org.matrix.msc2946/hierarchy/!vllkeAXGxCBbUgjRBq:tchncs.de
returns a 404, not dendrite.

**Comment by timaeos** [comment]
> Err, the error log you posted indicates that https://tchncs.de/_matrix/federation/unstable/org.matrix.msc2946/hierarchy/!vllkeAXGxCBbUgjRBq:tchncs.de returns a 404, not dendrite.

You're right, however I also checked again matrix.org spaces 
```
May 25 10:58:46 hermes dendrite-start.sh[445433]: time="2022-05-25T15:58:46.241467786Z" level=warning msg="failed to call MSC2946Spaces on server matrix.org" error="contents=[123 34 101 114 114 99 111 100 101 34 58 34 77 95 85 78 75 78 79 87 78 34 44 34 101 114 114 111 114 34 58 34 85 110 107 110 111 119 110 32 114 111 111 109 58 32 33 111 112 88 90 101 102 102 108 122 85 72 109 74 82 103 120 104 104 58 109 97 116 114 105 120 46 111 114 103 34 125] msg=Failed to GET JSON (hostname \"matrix.org\" path \"/_matrix/federation/unstable/org.matrix.msc2946/hierarchy/!opXZefflzUHmJRgxhh:matrix.org\") code=404 wrapped=M_UNKNOWN: Unknown room: !opXZefflzUHmJRgxhh:matrix.org" req.id=EQO7jXWzvybs req.method=GET req.path="/_matrix/client/v1/rooms/!ommCUnDJcfLyBxqKEq:matrix.org/hierarchy" user_id="@timaeos:matrix.nexaeos.io"
```
 and it returns the same 404. Do we believe that the normal Synapse doesn't implement the hierarchy call or that somehow the message to the other server is malformed in some way?

**Comment by timaeos** [comment]
Actually it looks like this might just be a synapse problem like you supposed:
https://github.com/matrix-org/synapse/pull/12858/commits
Should fix itself later hopefully
