### ISSUE TITLE
Allow other captcha Providers

### ISSUE THREAD

**Issue by mpldr** [matrix-org/dendrite#2493]
**Description:**

I'd rather not use reCaptcha for privacy reasons. Is there a way to configure other providers such as hCaptcha or – even better – serve a custom captcha.

**Comment by neilalexander** [comment]
#2415 does mention [patching in hCaptcha support](https://github.com/matrix-org/dendrite/issues/2415#issuecomment-1122058084), since seemingly the site-verify API is quite similar. I absolutely think this is a thing we can reasonably support.

**Comment by array-in-a-matrix** [comment]
hCaptcha is an option as of [Dendrite version 0.10.5](https://github.com/matrix-org/dendrite/releases/tag/v0.10.5). Having other options would be nice.

**Comment by kegsay** [comment]
We have no plans to add more captcha providers.
