### ISSUE TITLE
Make command line config flags available in the yaml config

### ISSUE THREAD

**Issue by lukehoersten** [matrix-org/dendrite#2494]
Please ensure all command line config flags are available in the yaml config. I'd like to use systemd with instances to load specific yaml configs to load all other parameters.

Things like http-bind-address require a custom command line instantiation instead of loading everything from the yaml config.

Specifically the following CLI flags:

  -api
  -api-bind-address string
  -http-bind-address string
  -https-bind-address string
  -really-enable-open-registration
  -tls-cert string
  -tls-key string

**Comment by kegsay** [comment]
We don't have plans to do this currently. We are actively trying to reduce our configuration API surface, and adding duplicate fields (YAML and CLI flags) adds extra complexity as you now need to worry about which takes precedence.

We aren't opposed to removing the CLI flags entirely, and solely having them configured via the config file, but this would be a breaking API change and require a lot of signalling to end-users to warn them of such a change.

Overall, the tradeoffs here just don't add up for us right now. We'll likely revisit this when we have more team members to focus on the overall server admin experience, but this isn't a priority for us right now. Sorry.
