### ISSUE TITLE
Audio or Video calling not working, but messaging is working

### ISSUE THREAD

**Issue by jittygitty** [matrix-org/dendrite#2495]
### Background information
This is RELATED to https://github.com/vector-im/element-android/issues/6160  and  https://github.com/vector-im/element-web/issues/22331

I should add that "VERIFICATION" does not work either, because probably it only sees ONE person when in fact messaging is working. I have a feeling the issue may be with DENDRITE and not with the clients. Perhaps related to the lack of "PRESENCE"? (presence is not enabled on dendrite)

So currently in Element Desktop or elsewhere I can not check the permissions (user/moderator/admin) of the other user, And again verification fails because the other person is unable to properly accept, they just get in a loop with "SKIP" or "Continue" and can't get out until they click "SKIP" since continue does not work.

Also when clicking audio or video on android app it says Can not place call with yourself...
On the DESKTOP app simply "nothing" happens when clicking the audio or video buttons.

I'm running Dendrite off github in monolith config with SQLite3 database. No docker.

### Steps to reproduce

- Install APP apk on Android
- Create User on Dendrite from commandline
- Tell user on Android App to sign into your dendrite home server with user/pass you give them
- In your Desktop Element app (latest), create a DM direct message room with them
- You see messaging works after they accept invite, all good
- You try to call them voice or video from Element Desktop app, but buttons do NOTHING
- The other person tries to click Audio or Video but gets message like: Can not place call with yourself.
- The other person (Android app user) sees only 1 Person listed in room settings instead of 2.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by jittygitty** [comment]
I WAS able to place a call from another Android App installation where the user was logged into matrix.org (Synapse) and was able to make a DM call to the same Element Desktop user that failed as per post above.

But on Android App installations using my DENDRITE homeserver, if I try initiate a call or video inside a DM direct message room I get popup error "You cannot place a call with yourself" and the phone and video icons are a bit shaded out not full green color.

**Comment by jittygitty** [comment]
From yet a different Element Android app install connected again to my Dendrite homeserver, I can now message and also call the Desktop Element app user from a previously created chat, but I noticed that Notifications weren't working when messages from the android app weren't decrypted, only after I clicked inside Element Desktop app to "re-request" keys , did the messages get decrypted and notifications started working. Probably Notifications should still work even if message was delivered undecipherable encrypted?

So again this feels like two issues, sometimes room settings detects there's only "one" person in room when actually there are two and text messaging works, just not audio/video. And the other issue is that sometimes a user doesn't have the PERMISSIONS necessary to start a call in a DM room yet no error message is given.

**Comment by jittygitty** [comment]
Additional details provided in issue: https://github.com/vector-im/element-web/issues/22331

**Comment by jittygitty** [comment]
@neilalexander @spaetz Can you please take a look at the log snippet and thread at https://github.com/vector-im/element-web/issues/22331  because @turt2live closed my ticket there saying issue does not pertain to their web or desktop client code but to my "environment".

If that is the case, this can only mean that the issue is with my environment of "Dendrite or with Turn Server".

**Comment by turt2live** [comment]
(pinging people that aren't involved on a ticket is considered spam - please refrain from demanding attention from the team)

Per your Element Web issue, I cannot foresee this being actionable by the Dendrite team either. Your issue appears to be with your device or configuration, in which case the support rooms are best to validate that things are set up correctly.
