### ISSUE TITLE
Clear cache & reload breaks membership in rooms suggested by a Space in (only) Element Web

### ISSUE THREAD

**Issue by bones-was-here** [matrix-org/dendrite#2503]
### Background information

- **Dendrite version or git SHA**: 0.8.6
- **Monolith or Polylith?**: monolith
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: no
- **`go version`**: 1.17.9
- **Client used (if applicable)**: element web, element android

### Description

 - **What** is the problem: room membership changes and becomes inconsistent, seemingly at random, when updating and/or restarting
 - **Who** is affected: 
 - **How** is this bug manifesting: element web shows I am no longer in some rooms, and cannot access the room when trying to rejoin, but in element android I am still able to participate in the same rooms.  Additionally, the server reverts to participating in the old #dendrite room, requiring evacuateRoom to be used again.
 - **When** did this first appear: unknown

### Steps to reproduce

- update and/or restart dendrite, observe that membership has changed and is now inconsistent between clients
- clearing cache and/or re-logging has no effect

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

When trying to "re"-join the rooms in element web, dendrite will log a successful room join, but the spinner continues endlessly in element web, and when refreshing it's back to showing the room as not joined.  The options seem to be:  
- access the room using element android only
- leave the room using `curl` or element android, and re-join it

These are all public v6 rooms.

When the errors for the old #dendrite start being logged again, I check the state in element web and it shows I'm both in the room (listed in the user list) and not in the room (room is being previewed, with a button to join).  
When I do `GET /_dendrite/admin/evacuateRoom/!yomrOFwgFXzmeMAbzX:matrix.org`  
it returns `{"affected":["@bones_was_here:xonotic.org"]}`  
and on a second GET it returns the empty array (until the next time it reverts).

**Comment by bones-was-here** [comment]
This happened again with 1 room and no restart of dendrite.  As usual, element web became unable to access the room, cache clear & re-logging had no effect, but it was still working normally in element android.  Leaving and re-joining the room in Android fixed it for now.

**Comment by bones-was-here** [comment]
I'm wondering if this is somehow related to spaces summary, which is enabled on my homeservers.  So far I have only seen it happen with rooms that are members of a space and claim that space as their canonical parent.

**Comment by McSinyx** [comment]
Which curl command did you use to leave a room?  BTW I'm facing this on 0.8.5 with Element Web.  The issue emerges last week I think with two rooms affected.

**Comment by bones-was-here** [comment]
`curl -v 'https://example.com/_matrix/client/r0/rooms/!yomrOFwgFXzmeMAbzX:matrix.org/leave' -H 'Authorization: Bearer <your_access_token>' -d ''`

**Comment by McSinyx** [comment]
Thanks, it worked!

**Comment by bones-was-here** [comment]
Hmmm a new message dot and bold text appeared in element web for a room i'm "not in"

**Comment by bones-was-here** [comment]
A better workaround to restore access to the room in Element Web is to post a message to it using Element Android.

**Comment by bones-was-here** [comment]
I think this is fixed, as of 522bd2999f605258e95565c6d648d2f7ea001ea4 I can no longer reproduce it.

Element web was open (but not in use, on another screen) when suddenly over 9000 notifications for old messages appeared and most rooms and spaces disappeared from the sidebar.  A clear cache & reload fixed that, without the side effect of kicking me out of the same 3 rooms as usual.  It seems I can do clear cache & reload repeatedly without causing membership issues now.

**Comment by neilalexander** [comment]
Can you please just double-check that this is still true as of [07dd9bd](https://github.com/matrix-org/dendrite/commit/07dd9bd9954d0740664651bf9755a81c3ba2d011) before I cut a release?

**Comment by bones-was-here** [comment]
It appears to still be fixed.  Not sure if this has an issue but previously clear cache & reload would cause chat history to have @user:domain instead of display names in element web, that appears to be fixed also.
