### ISSUE TITLE
Do not Automatically Sign-Out users from clients if server all sudden loads wrong or empty database files

### ISSUE THREAD

**Issue by jittygitty** [matrix-org/dendrite#2510]
### Background information

- **Dendrite 0.8.6+b541f304**: 
- **Monolith**: 
- **SQLite3**: 
- **NO docker**: 
- **go 1.17.7**:
- **Applies to both Android and Desktop etc**:

### Description

 - **What** is the problem:
I had updated to 0.8.7+f41931b5 but for some reason I was no longer getting notifications in Desktop Client which always worked great, they were still working on Android. But after I reinstalled the Older Dendrite, I FORGOT to replace the empty git db files with my real sqlite databases and when I started the dendrite server that way, it KICKED Out , signed out my logged in users.... 

(related side-issues: After logging back in, my android user needed to be reverified, verification would not work (you're forced to cancel/skip since you never get the message/pic to verify or any way to accept verification on the android side) for it initiated from my desktop user, also parts of previous conversation was unreadable (just stuck at: "waiting for this message, this may take a while") to the android user while the desktop user could see it all, maybe since for the desktop I had a previously exported keys and was able to verify on re-login resign-in?  )
(Also, I tried to send over a file from desktop user to android user in the DM and i got Upload Error, "This file is too large to upload. The file size limit is 0 B but this file is 61.12 KB." yet dendrite.yaml had it set to 0 for no limit..)

Anyway I'm not sure if the dendrite SERVER "dictates" to the clients to log out. Even if so, likely the clients should be allowed to just wait it out and REFUSE to log themselves out, I think the CLIENT should decide whether they want to log themselves out or not. I would have chosen to stay logged in with the cached data until server was brought back online in "correct way" with the proper sqlite databases. I am NOT sure if Dendrite actually told clients to sign-out or if the clients themselves somehow chose to sign-out without asking the user for their "permission".

I'm not sure what's the possible consequences of being "logged out Unexpectedly" by the server if you didn't have "key backup/management" setup to backup remotely and you didn't export/save your keys anywhere before being automatically signed out unexpectedly. Is it possible to always "require" user confirmation for any "sign-out" etc?

If the Clients can perfectly well stay "logged-in/signed-in" during the time that a server is "completely down" or off and simply give a message that it can't connect to server, I see no reason why the client can't remain signed-in even if the server is temporarily misconfigured or missing its "databases" etc. I'd like to avoid any "automatic" sign-out.

 - **Who** is affected:
 All users logged in.
 - **How** is this bug manifesting:
 Users are all signed out 
 - **When** did this first appear:
 Perhaps this was always the behavior, I don't know.

### Steps to reproduce

- Start Dendrite server with empty fresh sqlite databases instead of your real ones
- See the logged in users being automatically kicked/signed-out of their clients.
- Users then deal with headaches of verifications not working right or not seeing full prior discussions etc

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by jittygitty** [comment]
@neilalexander Thanks for explaining, I guess anyone using custom client can then choose to pop-up a confirmation to user if to logout or if to stay in "offline" mode and try again later when server recovers etc.

**Comment by dvergeylen** [comment]
>If you have the wrong database configuration, Dendrite can no longer validate your existing client access tokens for incoming Client-Server API requests, as their validity is stored in the database.

Hi NeilAlexander, can you elaborate on this? I have a session that can't read messages since 0.10.5 ("Waiting for this message, this may take a while") and I would like to repair but I have no clue on how to do this. Is there something in the DB that could be remove that would trigger a new sync? (the session is verified, don't know if that changes anything?). Keep up the great work!!!
