### ISSUE TITLE
room upgrade went bad (missing room)

### ISSUE THREAD

**Issue by spaetz** [matrix-org/dendrite#2515]
### Background information

- **Dendrite version or git SHA**: 0.8.7
- **Monolith or Polylith?**:  mono
- **SQLite3 or Postgres?**:  PSQL
- **Running in Docker?**:  NO
- **`go version`**: 1.17
- **Client used (if applicable)**: element web

### Description
My admin user on my dendrite home server upgraded the v5 room #mobian:matrix.org ("!ThIzZNArdoSkaWndMq:matrix.org").
This is the tombstone event that got sent into the room. 
```
{
  "content": {
    "body": "This room has been replaced",
    "replacement_room": "!zcjeWiQpbl2vK5M8:sspaeth.de"
  },
  "origin_server_ts": 1654517709314,
  "sender": "@spaetz:sspaeth.de",
  "state_key": "",
  "type": "m.room.tombstone",
  "unsigned": {},
  "event_id": "$gxRUAcut-6iaUNfBe2xrV05ACVVnvlwWsynaeI3mafk",
  "room_id": "!ThIzZNArdoSkaWndMq:matrix.org"
}
```

However, the tombostone event did not propagate for quite a while and the new room apparently never got created. My postgres shows:
select * from roomserver_rooms WHERE room_id LIKE "%zcjeWiQp...
                                                          ^
```
select * from roomserver_rooms WHERE room_id LIKE '%zcjeWiQpbl2vK5M8%';
 room_nid | room_id | latest_event_nids | last_event_sent_nid | state_snapshot_nid | room_version 
----------+---------+-------------------+---------------------+--------------------+--------------
(0 rows)

```

everybody clicking on the "upgrade here" link gets an error saying: `Failed to join Failed to make_join via any server`.
I finally created another upgrade from the @matrix.debian.social user (running synapse) and that worked fine. However, we still have the tombstone event pointing to a nonexisting room, which is quite a bad user experience.

I had the log level set to warn, and after some digging I found a single line saying:
```

time="2022-06-06T12:15:09.978788111Z" level=error msg="Room upgrade failed" func="github.com/matrix-org/dendrite/roomserver/internal/perform.(*Upgrader).PerformRoomUpgrade" file="github.com/matrix-org/dendrite/roomserver/internal/perform/perform_upgrade.go:52" error="0 : gomatrixserverlib.Allowed failed"
```

**Comment by neilalexander** [comment]
I'm going to close this for now since a variety of fixes were made to room upgrades this week. Please yell if it needs reopening.
