### ISSUE TITLE
Seemingly pass the federation test but can't actually federate

### ISSUE THREAD

**Issue by tehradamant** [matrix-org/dendrite#2517]
### Background information

- **Dendrite version or git SHA**: 0.8.7
- **Monolith or Polylith?**: monolith
- **SQLite3 or Postgres?**: postgresql
- **Running in Docker?**: no
- **`go version`**:1.18.3
- **Client used (if applicable)**: element-desktop

### Description

Hello! I've tried to setup my own dendrite server but it doesn't actually work. It passes the federation tests if I understand it correctly ( https://federationtester.matrix.org/#suffocating.org ) but in practice nothing works properly. I managed to join some rooms and see some messages in them but sending anything doesn't reach the room most of the time or reaches it very slowly though my account can be seen in the room with another account I have on matrix.org. I also tried sending a message from matrix.org account to my denderite account without any success. I can see a notification and invite but no messages or accepting the invite errors out ("There was an error joining."). This shouldn't be a hardware issue as I've run matrix-synapse just fine (also I converted my synapse keys to dendrite keys like it says in the installation guide) on this very same VPS. I'm not sure which files would be the most relevant:
nginx configs:
https://pastebin.com/raw/UxKEinBr
https://pastebin.com/raw/6aA8Vskd
dendrite config:
https://pastebin.com/raw/8B073Z5M

Sorry if there are obvious error anywhere I'm kinda new to this server stuff and I also have been tweaking these files for hours trying to get it working without much success.

EDIT: also I've forgot to mention my VPS runs Arch Linux and uses systemd-networkd and systemd-resolved if that could have any relation to this issue

**Comment by spaetz** [comment]
I can reach your server just fine https://matrix.suffocating.org/_matrix/client/versions, so reachability is not a problem at the very least.
I got your server in my logs from yesterday:
time="2022-06-06T10:59:28.444108761Z" level=error msg="getProfile failed" func=github.com/matrix-org/dendrite/clientapi/routing.GetProfile file="github.com/matrix-org/dendrite/clientapi/routing/profile.go:52" error="Get \"matrix://suffocating.org/_matrix/federation/v1/query/profile?user_id=%40DELETED%3Asuffocating.org\": Invalid server name" req.id=V8DgoZ72YMCf req.method=GET req.path="/_matrix/client/r0/profile/@DELETED:suffocating.org"

**Comment by spaetz** [comment]
One more thing to try: You use both     server [::1]:8008; and localhost in your configs. Try with an explicit 127.0.0.1 to avoid an ipv4/iv6 impedance mismatch, I believe dendrite does not listen on ipv6 by default.

**Comment by tehradamant** [comment]
Okay so I put 127.0.0.1 everywhere and restarted dendrite and nginx and waited a few minutes. But seems to be no improvement or any kind of change, everything is still the same

**Comment by tehradamant** [comment]
I'm not 100% sure but it seems to be fixed for me somehow so I guess there's no point in keeping this issue open
