### ISSUE TITLE
Handle edge cases when rejecting invites over federation.

### ISSUE THREAD

**Issue by NegativeMjark** [matrix-org/dendrite#252]
The syncapi needs to handle the case where we reject an invite for a room the server is not a member of over federation.

Currently the syncapi detects when an invite has been rejected by waiting for a leave event in the roomserver output stream. However when we reject an invite for a room the server isn't a member of it doesn't have enough information to write an ordinary leave event as a ```OutputNewRoomEvent``` to the roomserver output stream. (It won't know the state of the room for example).

Instead it writes an ```OutputRetireInviteEvent``` to the output stream. The syncapi needs to listen for those messages and inform the clients that the invite event has been rejected using it.

**Comment by Kegsay** [comment]
@neilalexander didn't you fix this with the whole MembershipUpdate `Overwrite` stuff?

**Comment by Kegsay** [comment]
We do this now.
```go
func (s *OutputRoomEventConsumer) onRetireInviteEvent(
	ctx context.Context, msg api.OutputRetireInviteEvent,
) error {
	sp, err := s.db.RetireInviteEvent(ctx, msg.EventID)
	if err != nil {
		// panic rather than continue with an inconsistent database
		log.WithFields(log.Fields{
			"event_id":   msg.EventID,
			log.ErrorKey: err,
		}).Panicf("roomserver output log: remove invite failure")
		return nil
	}
	// Notify any active sync requests that the invite has been retired.
	// Invites share the same stream counter as PDUs
	s.notifier.OnNewEvent(nil, "", []string{msg.TargetUserID}, types.NewStreamToken(sp, 0, nil))
	return nil
}
```
