### ISSUE TITLE
Mjolnir crashes consistently

### ISSUE THREAD

**Issue by bones-was-here** [matrix-org/dendrite#2521]
### Background information

- **Dendrite version or git SHA**: c4df6d77231358f161e5243e62af6510258943a5
- **Monolith or Polylith?**: monolith
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: no
- **`go version`**: 1.17.11
- **Client used (if applicable)**: element web

### Description

 - **What** is the problem: when attempting to add a user to a banlist, mjolnir crashes, and immediately crashes with the same message on subsequent startups.
 - **Who** is affected:
 - **How** is this bug manifesting:
 - **When** did this first appear: it happens even with quite old versions, so it may never have worked on dendrite.

### Steps to reproduce

- !mjolnir list create bl banlist
- !mjolnir default bl
- !mjolnir ban user @badguy:example.com

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

```
/data/home/mjolnir/mjolnir.git/lib/models/BanList.js:289
                 event.unsigned.rule = rule;
                                     ^
TypeError: Cannot set properties of undefined (setting 'rule')
    at BanList.<anonymous> (/data/home/mjolnir/mjolnir.git/lib/models/BanList.js:289:37)
    at Generator.next (<anonymous>)
    at fulfilled (/data/home/mjolnir/mjolnir.git/lib/models/BanList.js:20:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

```
Error during startup:
TypeError: Cannot set properties of undefined (setting 'rule')
     at BanList.<anonymous> (/data/home/mjolnir/mjolnir.git/lib/models/BanList.js:289:37)
     at Generator.next (<anonymous>)
     at fulfilled (/data/home/mjolnir/mjolnir.git/lib/models/BanList.js:20:58)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by neilalexander** [comment]
I'm not at all familiar with Mjolnir but I'm going to hazard a guess that it's expecting the `"unsigned"` key to be populated somewhere and it isn't (probably because it's omitted if empty).

**Comment by bones-was-here** [comment]
The spec says unsigned is optional (to me that means omitting it is legal), so is this a spec compliance issue in mjolnir?  (also it should probably handle errors instead of crashing...)

**Comment by neilalexander** [comment]
> The spec says unsigned is optional (to me that means omitting it is legal)

Agreed!

> so is this a spec compliance issue in mjolnir? (also it should probably handle errors instead of crashing...)

Wouldn't surprise me to find that Mjolnir has never been tested against anything non-Synapse, so quite possibly.
