### ISSUE TITLE
Building 0.8.8 with GCCGO 1.16.5 fails on Slackware 15

### ISSUE THREAD

**Issue by R3belWithoutAPause** [matrix-org/dendrite#2539]
### Background information

- **Dendrite version or git SHA**: 0.8.8
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: SQLite3
- **Running in Docker?**: No
- **`go version`**: go version go1.16.5 gccgo (GCC) 11.2.0 linux/amd64
- **Client used (if applicable)**: Slackware64-15.0

### Description

 - **What** is the problem: Build fails trying to build dendrite 0.8.8 on Slackware 15
 - **Who** is affected: Server admin
 - **How** is this bug manifesting: various references to undefined names in minio/highwayhash
 - **When** did this first appear: Can't say because this is the first time trying to build Dendrite

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

The following errors are thrown almost immediately when trying to build dendrite:

```
github.com/minio/highwayhash
/root/go/pkg/mod/github.com/minio/highwayhash@v1.0.2/highwayhash.go:74:9: error: reference to undefined name ‘initialize’
   74 |         initialize(&state, key)
      |         ^
/root/go/pkg/mod/github.com/minio/highwayhash@v1.0.2/highwayhash.go:76:17: error: reference to undefined name ‘update’
   76 |                 update(&state, data[:n])
      |                 ^
/root/go/pkg/mod/github.com/minio/highwayhash@v1.0.2/highwayhash.go:85:9: error: reference to undefined name ‘finalize’
   85 |         finalize(hash[:], &state)
      |         ^
/root/go/pkg/mod/github.com/minio/highwayhash@v1.0.2/highwayhash.go:96:9: error: reference to undefined name ‘initialize’
   96 |         initialize(&state, key)
      |         ^
/root/go/pkg/mod/github.com/minio/highwayhash@v1.0.2/highwayhash.go:98:17: error: reference to undefined name ‘update’
   98 |                 update(&state, data[:n])
      |                 ^
/root/go/pkg/mod/github.com/minio/highwayhash@v1.0.2/highwayhash.go:107:9: error: reference to undefined name ‘finalize’
  107 |         finalize(hash[:], &state)
      |         ^
/root/go/pkg/mod/github.com/minio/highwayhash@v1.0.2/highwayhash.go:118:9: error: reference to undefined name ‘initialize’
  118 |         initialize(&state, key)
      |         ^
/root/go/pkg/mod/github.com/minio/highwayhash@v1.0.2/highwayhash.go:120:17: error: reference to undefined name ‘update’
  120 |                 update(&state, data[:n])
      |                 ^
/root/go/pkg/mod/github.com/minio/highwayhash@v1.0.2/highwayhash.go:129:9: error: reference to undefined name ‘finalize’
  129 |         finalize(hash[:], &state)
      |         ^
/root/go/pkg/mod/github.com/minio/highwayhash@v1.0.2/highwayhash.go:141:9: error: reference to undefined name ‘finalize’
  141 |         finalize(hash[:], &state)
      |         ^
/root/go/pkg/mod/github.com/minio/highwayhash@v1.0.2/highwayhash.go:159:9: error: reference to undefined name ‘initialize’
  159 |         initialize(&d.state, d.key[:])
      |         ^
/root/go/pkg/mod/github.com/minio/highwayhash@v1.0.2/highwayhash.go:172:17: error: reference to undefined name ‘update’
  172 |                 update(&d.state, d.buffer[:])
      |                 ^
/root/go/pkg/mod/github.com/minio/highwayhash@v1.0.2/highwayhash.go:177:17: error: reference to undefined name ‘update’
  177 |                 update(&d.state, p[:nn])
      |                 ^
/root/go/pkg/mod/github.com/minio/highwayhash@v1.0.2/highwayhash.go:192:9: error: reference to undefined name ‘finalize’
  192 |         finalize(hash[:d.size], &state)
      |         ^
/root/go/pkg/mod/github.com/minio/highwayhash@v1.0.2/highwayhash.go:224:9: error: reference to undefined name ‘update’
  224 |         update(state, block[:])
      |         ^
/root/go/pkg/mod/github.com/minio/highwayhash@v1.0.2/highwayhash_generic.go:107:17: error: reference to undefined name ‘update’
  107 |                 update(state, tmp[:])
```

Build command:

`go build -o $PKG/usr/bin/dendrite-monolith-server $TMP/$PRGNAM-$VERSION/$PRGNAM-$VERSION/cmd/dendrite-monolith-server`

Please let me know if you need any other information

**Comment by neilalexander** [comment]
We haven't really done any testing with the `gccgo` compiler — normally people use `gc` — but it looks to be that the problems you are seeing are in a dependency of the NATS Server:
```
~ go mod why github.com/minio/highwayhash
# github.com/minio/highwayhash
github.com/matrix-org/dendrite/setup/jetstream
github.com/nats-io/nats-server/v2/server
github.com/minio/highwayhash
```

**Comment by kegsay** [comment]
Please just use `gc`.
