### ISSUE TITLE
Track whether our server is in the room.

### ISSUE THREAD

**Issue by NegativeMjark** [matrix-org/dendrite#256]
For each room in the room server we need to know whether our server is still in the room.
Otherwise horrible things will happen if we try to rejoin a room the server has left.
The client API will use this information to tell whether a user can join the room locally or if it will need to contact another server. If this information is wrong it will try to rejoin locally using the stale room state.
We need to know this information in the roomserver to tell if our forward extremities are still valid, otherwise the roomserver will try to merge the stale state with the current state.

Implementing this could have some overlap with #215 

If we want to support vhosting then this should reflect whether *any* of the servers we are are in the room.

**Comment by Kegsay** [comment]
@neilalexander I think we do this pretty good now?

**Comment by neilalexander** [comment]
Yes, this is done.
