### ISSUE TITLE
JetStream can't start because of storage directory

### ISSUE THREAD

**Issue by thepra** [matrix-org/dendrite#2569]
### Background information

- **Dendrite version or git SHA**: 0.8.9
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **`go version`**: 2.34.1
- **Client used (if applicable)**:

### Description

 - **What** is the problem: 
Can't start JetStream on path `storage_path: /media/<redected>/hd/Dendrite/JetStream/` despite throughout the path I added the dendrite user with ACL:
[INF] Starting JetStream
[FTL] Can't start JetStream: storage directory is not a directory
 - **Who** is affected: JetStream

### Steps to reproduce

- compile and put in place all the configurations
- setup `dendrite.service`(thanks to the example configuration)
- `systemctl start dendrite.service` without success

Throughout the installation guide there're no instructions overall on setting up a user that runs the go build, and it quite many try and error to make the service not crash because there're no permissions for this or for that. Now I've hit this JetStream part for which I can't find a solution meanwhile that directory does exists the dendrite is saying otherwise...

What am I supposed to do?

**Comment by neilalexander** [comment]
Does `/media/<redacted>/hd/Dendrite/` exist as a folder?

Is `/media/<redacted>/hd/Dendrite/JetStream` actually a file and not a folder?
