### ISSUE TITLE
Can not initiate 1:1 call when room is created from element-desktop. However it works fine with matrix.org server

### ISSUE THREAD

**Issue by Juha-Park-TII** [matrix-org/dendrite#2582]
### Background information

- **Dendrite version or git SHA**: v0.8.9
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Posgres
- **Running in Docker?**: No
- **`go version`**: 1.18
- **Client used (if applicable)**: Element-desktop

### Description

 - **What** is the problem: Wrong status information of "People" in Room information
 - **Who** is affected: Person try to make 1:1 call.
 - **How** is this bug manifesting: When room is created from element-desktop, user in element-desktop can not initiate 1:1 call
 - **When** did this first appear: From the begging of element-desktop testing.

### Steps to reproduce

- Create 1:1 room from element-desktop
- Initiate 1:1 call
- If call cannot be initiated, check the "People" information. all of them are offline.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by jittygitty** [comment]
@Juha-Park-TII These call issues seem to have been FIXED finally in the latest version of Element-Desktop. Please update your Element Desktop and confirm if it fixed it for you also. Thanks.
(I had opened similar issue over at:  https://github.com/matrix-org/dendrite/issues/2499 )

**Comment by Juha-Park-TII** [comment]
It does not happen with latest element-desktop.
Thanks.
