### ISSUE TITLE
Rate limiting causes decryption errors in Element

### ISSUE THREAD

**Issue by boogewooge** [matrix-org/dendrite#2589]
### Background information

- **Dendrite version or git SHA**: 0.8.9
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **`go version`**: 1.18.4
- **Client used (if applicable)**: Element Web/Desktop

### Description

 - **What** is the problem: 

When the `rate_limiting` config block is left at default, viewing an encrypted room with a lot of media in Element tends to show some of the media as "Error decrypting image/video". 

Switching rooms resets which of the media are decrypted correctly. 

After clearing the cache, all media are decrypted correctly, switching rooms (sometimes >1 times) makes the issue resurface.

Original event sources always stay the same for all media. Decrypted event sources change depending on how the media event in question is currently behaving.

This does not happen on nheko or fluffychat.

The only errors in the dendrite logs were rate-limit triggers.

Disabling `rate_limiting` fixes the issue.

 - **Who** is affected: All our users we tested this with.
 
 - **How** is this bug manifesting: By viewing a room with a bunch of media in the recent timeline in Element Web/Desktop.
 
 - **When** did this first appear: Immediately on a fresh dendrite install. 

### Steps to reproduce

- (Optional: Fresh dendrite install)
- Leave `rate_limiting` config block on these defaults: https://github.com/matrix-org/dendrite/blob/main/dendrite-sample.monolith.yaml#L184=
- Create room
- Send some 10+ media files (images and videos) into the room
- In element (with `Show previews/thumbnails for images` turned on): switch to another room and then to the one where the media were posted (and are still in recent timeline). Maybe do this a couple times, but only rarely more than one switch was needed in our case.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by kegsay** [comment]
Great description, thank you! We just need to update the defaults to be a little more open.
