### ISSUE TITLE
All components require access to registration files

### ISSUE THREAD

**Issue by mibmo** [matrix-org/dendrite#2598]
**Description:**
When using a polylith deployment, every single component checks if the files specified in `app_service_api.config_files` exist; this requires that the config files be mounted for every single component. This is not friendly towards most deployment methods, and may be considered a bug.

I propose that only the `appservice` component checks for these files, since it's the only that ever interacts with them.

Here's an example of an error from one of the other components (here sync api) complaining about a missing registration file.
```css
time="2022-07-28T23:56:50Z" level=fatal msg="Invalid config file: open /etc/dendrite/appservices/discord-registration.yaml: no such file or directory"
```

**Comment by kegsay** [comment]
Most likely because the AS work was bundled with the Config, and since every component uses the Config, by proxy it uses the AS stuff. We should fix that: there's no reason for it to do so beyond it doing so historically.

**Comment by mibmo** [comment]
There are a few similar things for other components. (I'm assuming not every component needs access to the old signing keys / the TLS certs / matrix key?)

I'm struggling understanding Dendrite's architecture but would love to contribute this fix; could you point me to the correct place to look? (or just where to start my reading! :))

**Comment by S7evinK** [comment]
Closing this, now that polylith is deprecated/removed.
