### ISSUE TITLE
PAM authentication

### ISSUE THREAD

**Issue by Kobaxidze256** [matrix-org/dendrite#2622]
**Description:**

I want authentication with PAM. I want unix users to log into a newly generated account if that's necessary and use the service without registering.
I want to write a config file with PAM enabled, enable a systemd unit and be done with it. Can this be done?
What would user deletion do then? I'm unfamiliar with Matrix.

**Comment by kegsay** [comment]
We have no plans to implement or maintain this at this time. Sorry.
