### ISSUE TITLE
Failed to load list of rooms.

### ISSUE THREAD

**Issue by sqpp** [matrix-org/dendrite#2627]
### Background information

- **Dendrite version or git SHA**: Dendrite 0.9.1
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **go version**: go version go1.18.1 linux/arm64
- **Client used (if applicable)**: Element

### Description

 - **What** is the problem: Unable to see the room list.
 - **Who** is affected: Everyone in the server.
 - **How** is this bug manifesting: Getting "Failed to load list of rooms." when trying to discover rooms.
 - **When** did this first appear: From the beginning.

### Steps to reproduce
Not sure if this can be reproduced, I have enough free and usable RAM, as well as the load is perfectly fine. 

```
load average: 0.37, 0.23, 0.19
               total        used        free      shared  buff/cache   available
Mem:           7.6Gi       1.5Gi       196Mi       103Mi       6.0Gi       5.7Gi
Swap:             0B          0B          0B
```

Beside of that I am getting this error since the very beginning. The rooms are also public.

**Comment by neilalexander** [comment]
Do you see anything in the Dendrite logs when trying to request the public rooms list?

**Comment by weedoe** [comment]
I am having the same problem. It throws 404 errors when trying to load the room list in a Space. It is trying to access /hierarchy 

I also had the same problem with Conduit. No problems with Synapse.

**Comment by 9p4** [comment]
Have you enabled the spaces MSC in the config?

**Comment by zoenglinghou** [comment]
@neilalexander What key word should I search the log for? I tried greping the space name from the log but nothing shows up.

**Comment by cxr6548** [comment]
> @neilalexander What key word should I search the log for? I tried greping the space name from the log but nothing shows up.

I ran into this issue and some googling led me to the solution. Unfortunately I can't find the website with the answer I found in my browser history but in short: In your dendrite.yaml file search for `experimental MSCs` and see just below the line mentioning Spaces. Uncomment it.

**Comment by zoenglinghou** [comment]
@cxr6548 that did it for me. Thanks! I hope the feature is soon finalized.

**Comment by k4r4b3y** [comment]
Even after I uncomment that `mscs:` list, element android still says "It looks like your homeserver doesn't support Spaces yet", when I try to "Explore rooms" in a space. Here's my relevant lines of my config:
```
# Configuration for enabling experimental MSCs on this homeserver.
mscs:
  mscs:
    - msc2946
    - msc2836

```
Am I failing at proper indentation in this yaml file or something??
