### ISSUE TITLE
Notifications (sound and or Badges) not working on FluffyChat iOS Devices.

### ISSUE THREAD

**Issue by BobWs** [matrix-org/dendrite#2629]
### Background information

- **Dendrite version or git SHA**: 0.91
- **Monolith or Polylith?**: Monlith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: yes
- **`go version`**:
- **Client used (if applicable)**: Elements and FluffyChat (iOS)

### Description

 - **What** is the problem: Notifications not working on FluffyChat iOS devices. No sound, badges nothing if the app is in the background. One can only see new messages when you are active in the app. This is only affected by the FluffyChat app. Elements desktop (MacOS) is working fine, when the desktop app is in the background notification is working (sound and badges).
 - **Who** is affected:
 - **How** is this bug manifesting:
 - **When** did this first appear: Not sure, this is my first installation of Dendrite.

### Steps to reproduce

- list the steps
- that reproduce the bug
- using hyphens as bullet points

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by S7evinK** [comment]
In FluffyChat, do you see "Devices" listed in Settings -> Notifications? Sounds like FluffyChat didn't register for push notifications.

**Comment by BobWs** [comment]
> In FluffyChat, do you see "Devices" listed in Settings -> Notifications?

Yes, all the devices I use to login are listed there. Notifications settings are all enabled. I even tried to toggle the on/off notifications on both desktop app and iOS app. But it still isn’t working.

**Comment by FlyingStitchman** [comment]
Push notifications for me are working using dendrite 0.13.1 and Fluffychat 1.13.0 (ios 15.7.8).
Notifications do not seem to work for secondary accounts in Fluffychat, which might have been the reasoning for issue in the first place.

Anyways, this can probably be closed unless someone else has issues with Fluffychat using a primary account.
