### ISSUE TITLE
Error migrating from 0.8.9 to 0.9.1 : endless db migration loop

### ISSUE THREAD

**Issue by Notmarrco** [matrix-org/dendrite#2631]
### Background information

- **Dendrite version or git SHA**: 0.9.1
- **Monolith or Polylith?**: monolith
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: no
- **`go version`**: go version go1.18.4 linux/amd64
- **Client used (if applicable)**:

### Description

 - **What** is the problem: dendrite starts but is unreachable and logs the same actions over and over
 - **Who** is affected:
 - **How** is this bug manifesting: debug logs about migrating the db (see below)
 - **When** did this first appear: when wigrating from 0.8.9 to 0.9.1

### Steps to reproduce

- using 0.8.9 with a postgres connection for every service (not only one connection as possible now) 
- stop dendrite
- recompile dendrite 0.9.1
- start dendrite
- 
<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

example of the logs generated that loops over and over : 

```
time="2022-08-10T00:10:38.101331532Z" level=info msg=PerformDeviceCreation func="github.com/matrix-org/dendrite/userapi/internal.(*UserInternalAPI).PerformDeviceCreation" file="/opt/dendrite/userapi/internal/api.go:151" context=missing device_id=0xc003bb4d40 display_name=0xc003bb4d40 localpart=t0pI492jhLnPmwPB0rxTz8u_fUxE6wZpUTubCO-P1GPs7-G5TWNSyMDeEzDqPt9W
time="2022-08-10T00:10:38.161397009Z" level=info msg=PerformDeviceCreation func="github.com/matrix-org/dendrite/userapi/internal.(*UserInternalAPI).PerformDeviceCreation" file="/opt/dendrite/userapi/internal/api.go:151" context=missing device_id=0xc003d130c0 display_name=0xc003d130c0 localpart=sqPDcx88f3SCgDKPVpEden9G2aiK2V1X9dAMeZluTn79vI8HMOvO1MPYdxd0Sz6T
time="2022-08-10T00:10:38.176687216Z" level=info msg=PerformDeviceCreation func="github.com/matrix-org/dendrite/userapi/internal.(*UserInternalAPI).PerformDeviceCreation" file="/opt/dendrite/userapi/internal/api.go:151" context=missing device_id=0xc003d13340 display_name=0xc003d13340 localpart=DslqK9JGtpOFBwkL3cLo6JilKox4j8lM3HZCNalOyk8qLS-J8-6u5RLTt__2Ahje
time="2022-08-10T00:10:38.191943445Z" level=info msg=PerformDeviceCreation func="github.com/matrix-org/dendrite/userapi/internal.(*UserInternalAPI).PerformDeviceCreation" file="/opt/dendrite/userapi/internal/api.go:151" context=missing device_id=0xc003bb50c0 display_name=0xc003bb50c0 localpart=aYuBiREaMiQ5aeaxfQtwZ8v5k2OVOFy8YaTJ5ZApp7PRuVT1VZICgbpndFS7LBT7
time="2022-08-10T00:10:38.208153331Z" level=info msg=PerformDeviceCreation func="github.com/matrix-org/dendrite/userapi/internal.(*UserInternalAPI).PerformDeviceCreation" file="/opt/dendrite/userapi/internal/api.go:151" context=missing device_id=0xc003c6c340 display_name=0xc003c6c340 localpart=WKEXauQLpnxzJsBs8SKjw1jgvvGA2v8S
time="2022-08-10T00:10:38.223425274Z" level=info msg=PerformDeviceCreation func="github.com/matrix-org/dendrite/userapi/internal.(*UserInternalAPI).PerformDeviceCreation" file="/opt/dendrite/userapi/internal/api.go:151" context=missing device_id=0xc003d13640 display_name=0xc003d13640 localpart=_discordpuppet_bot
time="2022-08-10T00:10:38.239672776Z" level=info msg=PerformDeviceCreation func="github.com/matrix-org/dendrite/userapi/internal.(*UserInternalAPI).PerformDeviceCreation" file="/opt/dendrite/userapi/internal/api.go:151" context=missing device_id=0xc003bb51c0 display_name=0xc003bb51c0 localpart=_slackpuppet_bot
time="2022-08-10T00:10:38.255323243Z" level=info msg="Starting application service" func=github.com/matrix-org/dendrite/appservice/workers.worker file="/opt/dendrite/appservice/workers/transaction_scheduler.go:64" appservice=instagram
time="2022-08-10T00:10:38.256206704Z" level=info msg="Starting application service" func=github.com/matrix-org/dendrite/appservice/workers.worker file="/opt/dendrite/appservice/workers/transaction_scheduler.go:64" appservice=whatsapp
time="2022-08-10T00:10:38.279205168Z" level=debug msg="Setting DB connection limits" func=github.com/matrix-org/dendrite/internal/sqlutil.Open file="/opt/dendrite/internal/sqlutil/sqlutil.go:45" ConnMaxLifetime=-1s MaxIdleConns=2 MaxOpenConns=5 dataSourceName="postgres://localhost/dendrite_mediaapi"
time="2022-08-10T00:10:38.319762302Z" level=debug msg="Setting DB connection limits" func=github.com/matrix-org/dendrite/internal/sqlutil.Open file="/opt/dendrite/internal/sqlutil/sqlutil.go:45" ConnMaxLifetime=-1s MaxIdleConns=2 MaxOpenConns=5 dataSourceName="postgres://localhost/dendrite_syncapi"
time="2022-08-10T00:10:38.335492871Z" level=debug msg="Executing database migration 'syncapi: add history visibility column (output_room_events)'" func="github.com/matrix-org/dendrite/internal/sqlutil.(*Migrator).Up.func1" file="/opt/dendrite/internal/sqlutil/migrate.go:98"
time="2022-08-10T00:10:38.339843807Z" level=debug msg="Executing database migration 'syncapi: add history visibility column (current_room_state)'" func="github.com/matrix-org/dendrite/internal/sqlutil.(*Migrator).Up.func1" file="/opt/dendrite/internal/sqlutil/migrate.go:98"
time="2022-08-10T00:10:38.347533868Z" level=debug msg="Executing database migration 'syncapi: drop sent_by_token'" func="github.com/matrix-org/dendrite/internal/sqlutil.(*Migrator).Up.func1" file="/opt/dendrite/internal/sqlutil/migrate.go:98"
time="2022-08-10T00:10:38.350141297Z" level=debug msg="Executing database migration 'syncapi: fix sequences'" func="github.com/matrix-org/dendrite/internal/sqlutil.(*Migrator).Up.func1" file="/opt/dendrite/internal/sqlutil/migrate.go:98"
```

it seems that dendrite has to "performdevicecreation" and it doesn't succeed. That seems annoying, but what startle me is the neverending loop of "executing database migration"s.

**Comment by S7evinK** [comment]
`Executing database migration` is a little misplaced in the code, it's not getting executed if it already was.
Is there anything else in the logs/systemd? Like error/panics, I'm not seeing anything which would cause a crash.

**Comment by Notmarrco** [comment]
Well thanks for your answer. I didn't check the systemd logs, so I just exec "bin/dendrite-monolith" and in fact there was an error about a misconfigured MSC. I'm not sure how I did it but I managed to change a digit of an experimental MSC in the config. 🤦‍♂️ 
When corrected it works again !! 🎉
