### ISSUE TITLE
Server crash in user_interactive.go NewSession

### ISSUE THREAD

**Issue by tak-hntlabs** [matrix-org/dendrite#2634]
### Background information

- **Dendrite version or git SHA**: Dendrite main
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: SQLite3
- **Running in Docker?**: No
- **`go version`**: 1.18.4 darwin/amd64
- **Client used (if applicable)**:

### Description

 - **What** is the problem: Working on a feature branch. When running some tests that spin up multiple login sessions, the server crashes intermittently in user_interactive.go NewSession func.
 
 Exception has occurred: fatal error
"concurrent map writes"
Stack:
	 2  0x00000001051a91f8 in github.com/matrix-org/dendrite/clientapi/auth.(*UserInteractive).NewSession
	     at /Users/austinellis/hnt/harmony/servers/dendrite/clientapi/auth/user_interactive.go:209
	 3  0x00000001051a543c in github.com/matrix-org/dendrite/clientapi/auth.(*LoginTypePublicKey).LoginFromJSON
	     at /Users/austinellis/hnt/harmony/servers/dendrite/clientapi/auth/login_publickey.go:73
	 4  0x00000001051a49cc in github.com/matrix-org/dendrite/clientapi/auth.LoginFromJSONReader
	     at /Users/austinellis/hnt/harmony/servers/dendrite/clientapi/auth/login.go:91
	 5  0x00000001057f4640 in github.com/matrix-org/dendrite/clientapi/routing.Login
	     at /Users/austinellis/hnt/harmony/servers/dendrite/clientapi/routing/login.go:80
	 6  0x0000000105823d18 in github.com/matrix-org/dendrite/clientapi/routing.Setup.func45
	     at /Users/austinellis/hnt/harmony/servers/dendrite/clientapi/routing/routing.go:571
	 7  0x0000000104d85784 in github.com/matrix-org/util.(*jsonRequestHandlerWrapper).OnIncomingRequest
	     at /Users/austinellis/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20200807132607-55161520e1d4/json.go:79
	 8  0x0000000104d8639c in github.com/matrix-org/util.MakeJSONAPI.func1

 - **Who** is affected: High volume of clients attempting to login.
 - **How** is this bug manifesting: If there is a high volume of clients trying to login, this crash might happen.
 - **When** did this first appear: Observed during feature development when running tests that spin up multiple login sessions.

PR: https://github.com/matrix-org/dendrite/pull/2635

**Comment by neilalexander** [comment]
Fixed in #2635.
