### ISSUE TITLE
Move room alias stuff out of room server

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/dendrite#266]

**Comment by NegativeMjark** [comment]
This should just be a matter of moving the code, the alias code only interacts with the rest of the roomserver through the public APIs.

**Comment by babolivier** [comment]
Claiming this one 🙂

**Comment by erikjohnston** [comment]
Where were you planning on moving it?

**Comment by babolivier** [comment]
I'm thinking of either moving it to the client API or creating a new component.

**Comment by erikjohnston** [comment]
Ok, I was messing around with refactoring the components so if you do create a new component it might be worth waiting for my stuff to land (it should make things a lot nicer!)

**Comment by babolivier** [comment]
Oh, I'll wait for your stuff then 🙂

**Comment by erikjohnston** [comment]
(FTR, #384 is what I was doing)

**Comment by neilalexander** [comment]
Don't think this is relevant anymore.
