### ISSUE TITLE
Mautrix Google Chat Bridge Aggressive Join Behaviour after Appservice Refactor

### ISSUE THREAD

**Issue by timaeos** [matrix-org/dendrite#2691]
### Background information

- **Dendrite version or git SHA**: 0.9.6
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **`go version`**: 1.18.5
- **Client used (if applicable)**: Element Desktop

### Description

 - **What** is the problem: Mautrix Google Chat Appservice Bridge joins all active channels of a whitelisted user based on the user's events
 - **Who** is affected: whitelisted users of the appservice
 - **How** is this bug manifesting: Google Chat Appservice Bridge bot will join every channel that a user shows activity in
 - **When** did this first appear: Post 0.9.6 Upgrade (after Appservice Refactoring)

### Steps to reproduce

- Install the Appservice Bridge for Mautrix Google Chat 
- Whitelist a user to use the App service
- Upgrade Dendrite to 0.9.6
- Message in non-google chat portal rooms with the user client

Previously, the appservice would only join portal rooms that it would create but now that it is monitoring all NATS streams for activity, it is seeing activity from the user OR room ID and attempting to join the room that has that activity. It does this for every event it receives as long as the event is from a whitelisted user. This could be a bug in the bot itself, however this is not how the bot behaved prior to the appservice refactoring. Perhaps it should be checking for User ID and Room ID when sending events?

below are some of the logs of the app service. Dendrite doesn't show any errors.
```
Sep 01 15:46:02 hermes mautrix-googlechat[203061]: [2022-09-01 20:46:02,301] [DEBUG@mau.mx] Received Matrix event $xNY92Zs8ZtH8dTSTDlxdx-voHIN0A3mKVdpogy3WbPs from @timaeos:matrix.nexaeos.io in !0fmC9WTUK8f4WBOk:matrix.nexaeos.io
Sep 01 15:46:02 hermes mautrix-googlechat[203061]: [2022-09-01 20:46:02,307] [DEBUG@mau.as.api.bot] req #2063: POST https://matrix.nexaeos.io/_matrix/client/v3/join/%210fmC9WTUK8f4WBOk%3Amatrix.nexaeos.io?user_id=@nexaeosgooglechat:matrix.nexaeos.io {}
```
In reviewing the refactoring, I'm not sure why it's resulting in this aggressive join behaviour for any event created by a whitelisted user. 
Again, this might be a bug in the appservice itself but it only started after the refactor.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by S7evinK** [comment]
Please reopen if this still happens with 350a5e5
