### ISSUE TITLE
Implement appservice login

### ISSUE THREAD

**Issue by tulir** [matrix-org/dendrite#2723]
Required for end-to-bridge encryption in most bridges

https://spec.matrix.org/v1.3/client-server-api/#appservice-login (also mentioned on https://spec.matrix.org/v1.3/application-service-api/#server-admin-style-permissions)

**Comment by vijfhoek** [comment]
I've been working on this, and managed to get it working. Code still needs some work, but I've got mautrix-telegram working in an end-to-end encrypted room.

Will be touching up the code soon, after which it'll be ready for review 

![image](https://user-images.githubusercontent.com/345785/211128376-0b66162d-a335-4995-9b13-1975f272e809.png)

**Comment by jjj333-p** [comment]
Hi, so the pr related to this issue seems to be closed, however this issue is still open, and according to my experience trying to set up a bridge with e2ee on dendrite its still not fixed. 

Has this spec been implemented and I'm just stupid? Is it hidden behind a msc flag? Thanks.

**Comment by jjj333-p** [comment]
Never mind, i am dumb. The new pr is https://github.com/matrix-org/dendrite/pull/2936 and it is still open.

**Comment by spaetz** [comment]
https://github.com/matrix-org/dendrite/pull/3078 has been merged, so this can arguably be closed?

**Comment by S7evinK** [comment]
Absolutely!
