### ISSUE TITLE
Does Dendrite support the new Element Call multi-party instead of Jitsi?

### ISSUE THREAD

**Issue by jittygitty** [matrix-org/dendrite#2747]
**Description:**
Does Dendrite currently support "Element Call" option for multi-party calls instead of Jitsi? If not, and its only supported with Synapse, can support be added soon?

For reference see:
https://github.com/vector-im/element-call
https://github.com/matrix-org/matrix-react-sdk/pull/9267
example, in src/SdkConfig.ts they added "element_call:"
```
jitsi: {
        preferred_domain: "meet.element.io",
    },
    element_call: {
        url: "https://call.element.io",
    },
```

https://github.com/vector-im/element-web/issues/22964
Feature based on:
https://github.com/matrix-org/matrix-spec-proposals/blob/matthew/group-voip/proposals/3401-group-voip.md
https://github.com/matrix-org/matrix-js-sdk/pull/1902
thx!

**Comment by spaetz** [comment]
Why don't you try it out yourself? I successfully joined "new-style" video rooms hosted on my dendrite server. Afaik, there is nothing special the server needs to do, they are just widgets.

**Comment by jittygitty** [comment]
@spaetz I was hoping someone who already installed their own call server beat me to 'trying/testing' so I could postpone installing my call server until I know it works.

I think in your case you're not running your own "call server"? But maybe it doesn't matter, I guess I assumed it may work when using official call-server that talks to their synapse federation etc but might have issues on private installed call-server.

I just been busy, still on Dendrite 0.9.3 since didn't get chance upgrade, soon as I get a breather I'll upgrade Dendrite and install element-call and see how it goes.

**Comment by kegsay** [comment]
Apparently, yes, it does.
