### ISSUE TITLE
dendrite tries and fails to fetch its own keys

### ISSUE THREAD

**Issue by ashkitten** [matrix-org/dendrite#2751]
### Background information

- **Dendrite version or git SHA**: e45ba35e979f2f8af1e75f5f16158973b790436b
- **Monolith or Polylith?**: monolith
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: no
- **`go version`**: 1.18
- **Client used (if applicable)**: n/a

### Description

this showed up in the logs while trying to join a room:
```
Sep 29 19:24:11 xenia dendrite-monolith-server[1034867]: time="2022-09-29T19:24:11.913667350Z" level=error msg="Failed to fetch key for server" context=missing error="Post \"matrix://nyrina.link/_matrix/key/v2/query\": context deadline exceeded" fetcher=DirectKeyFetcher
Sep 29 19:24:11 xenia dendrite-monolith-server[1034867]: time="2022-09-29T19:24:11.913732990Z" level=warning msg="Failed to retrieve any keys" context=missing fetcher=DirectKeyFetcher
```

**Comment by devonh** [comment]
Fixed in #3126
