### ISSUE TITLE
dendrite always sends outbound m.presence to every server in every room it's in

### ISSUE THREAD

**Issue by ashkitten** [matrix-org/dendrite#2752]
from a cursory skim through the code, it seems like this happens because of this line:
https://github.com/matrix-org/dendrite/blob/175f65407a7f684753334022e66b8209f3db7396/federationapi/consumers/presence.go#L99

the `federationsender_joined_hosts` table used in that query has information about what rooms other servers share with us, but not about which of our users are in those rooms, which i assume is why this shortcut of sending to all known servers is used.

my dendrite instance has:
- a few "real" matrix users, one of whom is joined to #dendrite:matrix.org
- about 50 bridged discord users (the rooms they're in are only federated to 2 other servers)

due to this bug, i'm sending presence updates every few seconds to 566 distinct servers because of this one user being joined to a large room. after joining #dendrite:matrix.org, my server's load average went up from ~0.2 to ~5.6 (presumably just from presence events!)

**Comment by S7evinK** [comment]
Do you mind giving the [s7evink/presencejoinedhosts](https://github.com/matrix-org/dendrite/compare/main...s7evink/presencejoinedhosts) branch a try?
