### ISSUE TITLE
Error building v0.10.1:  IsUniqueConstraintViolationErr redeclared in this block

### ISSUE THREAD

**Issue by zoenglinghou** [matrix-org/dendrite#2754]
### Background information

- **Dendrite version or git SHA**: v0.10.1
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **`go version`**: `1.18.6 linux/amd64`
- **Client used (if applicable)**:

### Description

 - **What** is the problem: Error during compilation
 - **Who** is affected: not sure
 - **How** is this bug manifesting:
 ```
$ ./build.sh
...
github.com/matrix-org/dendrite/internal/sqlutil
# github.com/matrix-org/dendrite/internal/sqlutil
internal/sqlutil/unique_constraint.go:26:6: IsUniqueConstraintViolationErr redeclared in this block
	internal/sqlutil/postgres.go:23:6: other declaration of IsUniqueConstraintViolationErr
```
 - **When** did this first appear: at compilation time

### Steps to reproduce

- I downloaded the tar ball and decompressed to `/opt/dendrite/src`
- I executed command `./build.sh` as user `dendrite`
- Error message for compilation

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by S7evinK** [comment]
`postgres.go` was renamed in #2712, so this seems to be some files from earlier tar balls. Deleting the file should solve the issue.

**Comment by zoenglinghou** [comment]
@S7evinK could be... I might have used Ansible wrongly. Will let you know how it 
Thank you in advance

**Comment by zoenglinghou** [comment]
Yep, that's my problem for not cleaning up the old source files. closing
