### ISSUE TITLE
Federation: Add query room alias API endpoint

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/dendrite#277]
Implement the server portion of: `GET /_matrix/federation/v1/query/directory?room_alias=...`

See e.g. https://github.com/matrix-org/dendrite/blob/bcf58fad84bf53b6a6cf13a8d11bd46d82cc3bab/src/github.com/matrix-org/dendrite/clientapi/readers/directory.go#L31-L90 for how to query the room server for directory mappings

**Comment by rschulman** [comment]
Claiming this feature.

**Comment by erikjohnston** [comment]
Done in #338
