### ISSUE TITLE
Docker Hub "latest" tag broken

### ISSUE THREAD

**Issue by abdulocracy** [matrix-org/dendrite#2774]
It seems there has been an accidental push to the Docker Hub "latest" tag with only an arm build:
![image](https://user-images.githubusercontent.com/25480267/194509492-3f3ea285-b0ba-4163-af9b-0832fa8c1a79.png)
There hasn't been a release and this update wasn't done by the bot, so I'm assuming it was accidental. I ended up with a broken Compose deployment which tracks "latest".

**Comment by neilalexander** [comment]
Looks to have been an accidental push on my part and has since been fixed by the bot, so will close.
