### ISSUE TITLE
create-account not functioning

### ISSUE THREAD

**Issue by k1ngdmk** [matrix-org/dendrite#2786]
### Background information

- **Dendrite version or git SHA**: Dendrite 0.10.2
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: yes docker-compose
- **`go version`**: docker
- **Client used (if applicable)**: n/a

### Description

- **What** is the problem: Users can register through a client without a problem, however docker exec create-account does not function. The script runs, asks for password, will fail if I input wrong URL / path to dendrite.yaml.. but the user does not actually get created (verifying via postgres cli). Output says 'Created account' with no accessToken listed.
INFO[0003] Created account: abc (AccessToken: )

- **Who** is affected: Me as admin
- **How** is this bug manifesting: When attempting to run create-account from docker exec
- **When** did this first appear: Previously running the 9/30/22 image and saw the same issue. Upgraded to latest as of 10/7/22 and same issue seen. User creation via client app (Element) works fine.

### Steps to reproduce

- Docker-compose using :latest image tag (image version from 10/7/22
- Execute create-account.sh via docker exec './bin/create-account -config /path/to/dendrite.yaml -username USERNAME -url https://localhost:8448'
- Login to postgres bash and check account-accounts table.

As per https://matrix-org.github.io/dendrite/administration/createusers this should be the right command. Command seems to work fine but doesn't actually create the user.
<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by S7evinK** [comment]
I've just made a [change](https://github.com/matrix-org/dendrite/commit/83c9dde219440e0d730d63d2d65fc9eaaea64762) to main returning an error if we fail to read the response body. If I'm seeing right, that's the only place where we didn't check the returned error, which could cause this behavior.

**Comment by kegsay** [comment]
I think we also now assert this works in Docker in the upgrade tests right @S7evinK ? If so, we can close this.

**Comment by S7evinK** [comment]
Yep, it's tested in CI now.
Neil also added some more [verbose logging,](https://github.com/matrix-org/dendrite/commit/6f000e980155d6651b01c9b4dbdb316e9f501a45) so closing this. If it still happens, let us know.
