### ISSUE TITLE
Add /voip/turnServer endpoint

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/dendrite#279]
See: https://github.com/matrix-org/synapse/blob/6c1bb1601e43c89637ae5bd8720c255646ca8141/synapse/rest/client/v1/voip.py#L26-L64

This involves adding some config options and doing some HMACing

**Comment by anoadragon453** [comment]
Will take this if nobody else wants it.

**Comment by t3chguy** [comment]
This has now been merged
