### ISSUE TITLE
Dendrite panics when there is no space left on device

### ISSUE THREAD

**Issue by rakoo** [matrix-org/dendrite#2796]
### Background information
- **Dendrite version or git SHA**: 0.10.1 (installed from yunohost: the exact version is 0.10.1~ynh1
- **Monolith or Polylith?**: monolith
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: no
- **`go version`**:  1.15
- **Client used (if applicable)**: issue is on server side

### Description

- **What** is the problem: Dendrite panics when there is no space left on device
- **Who** is affected: every user
- **How** is this bug manifesting: The server exits
- **When** did this first appear: I haven't had a full disk before, so I don't know when the error first appeared

### Steps to reproduce

- Fill the disk
- The server exits

I'm not sure what should really happen when the disk is full though. You can't store anything so it seems logical that messages can't get across, so maybe this issue is not relevant but I thought it might be an interesting edge case 

Logs available here: https://paste.yunohost.org/duxafecase

**Comment by fantashley** [comment]
@rakoo I ended up opening a PR to address this in NATS Server based on the stack trace in your logs. Once that fix gets merged and released, this issue should be fixed by updating the nats dependency in go.mod!

**Comment by rakoo** [comment]
For some reason I didn't receive the notification. Thanks for that, it's amazing !

(And also thanks for dendrite, it does have some rough edges but it's nice to have a server that scales down !)

**Comment by fantashley** [comment]
@rakoo no worries, you're welcome! 😊 I'm just a random contributor so no need to thank me for Dendrite itself 😄

**Comment by S7evinK** [comment]
This should now be fixed since [v0.10.6](https://github.com/matrix-org/dendrite/releases/tag/v0.10.6) (NATS was updated to [2.9.4](https://github.com/nats-io/nats-server/releases/tag/v2.9.4), which contains @fantashley fix)
Panics might still occur, since Dendrite still tries to write to Postgres/SQLite and panics to avoid further inconsistencies in the database.
