### ISSUE TITLE
Complement test failure on restricted room remote-join tests (with room version 8)

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/dendrite#2801]
In complement, currently, the `TestRestrictedRoomsRemoteJoinFailOver`, which tests if servers perform failover when they do not have permission to authorize a restricted room join, fails on Dendrite.

I couldn't find an appropriate issue to note here, to track inside the complement repository, so this is that issue.

[This](https://github.com/matrix-org/complement/blob/086fa4bf8f2099198e2f8e6e96cd52da6ce4bbe5/tests/restricted_rooms_test.go#L355) is the relevant line in the Complement repository.

Additionally, I found `TestRestrictedRoomsRemoteJoinLocalUser`, which performs the same test, only that it'll "choose wisely" and perform a remote join, even if there's a local user. The relevant line is found [here](https://github.com/matrix-org/complement/blob/086fa4bf8f2099198e2f8e6e96cd52da6ce4bbe5/tests/restricted_rooms_test.go#L228).

**Comment by kegsay** [comment]
This is tracked insofar that it's skipped clearly in CI:
```
🚧 TestRestrictedRoomsRemoteJoinFailOver (0s)
```
We do not need an issue for every single skipped or unimplemented test.

**Comment by ShadowJonathan** [comment]
These issues exist to track spec compliance

**Comment by kegsay** [comment]
We will be aware of these issues when we see skipped complement tests in CI and/or EXPECTED FAIL tests in sytest. Having an issue for every single skipped/failing test is just annoying. It adds noise to the issue tracker, with zero clear benefit. Worse still, when the test does eventually pass, people tend to forget to update and close the issue - they are often unaware such an issue even exists. Having the tracking inside CI (AWSY or Complement runs) is a much better way to track progress, which automatically updates.
