### ISSUE TITLE
New member presence is not given through `/sync` after join

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/dendrite#2803]
Encountered this while clearing the following sytest (and Complement test): [`Existing members see new members' presence`](https://github.com/matrix-org/complement/blob/6c31e8dd4e04fc12e9b3a7aa5553d80b42092cf8/tests/csapi/rooms_members_local_test.go#L38)

The closest issue to missing presence functionality is https://github.com/matrix-org/dendrite/issues/1324, however, that already pertains to another part of skipped complement tests.

https://github.com/matrix-org/dendrite/issues/602 mentions that the "presence module" has landed in 0.8, however, https://github.com/matrix-org/dendrite/pull/1879 has closed without any mention of a follow-up PR or commit to the codebase.

The above test still fails on Dendrite `0.10.3`

**Comment by S7evinK** [comment]
This seems to be passing in Sytest as of 07bfb791ca616bd3a4aa96691b74c96146d59d90 ([CI](https://github.com/matrix-org/dendrite/actions/runs/3265256479/jobs/5367270587#step:7:121))
For reference, presence was added in #2312

**Comment by ShadowJonathan** [comment]
I can confirm that with [matrix-org/complement@`502127d` (#516)](https://github.com/matrix-org/complement/pull/516/commits/502127d47fa0a7f6ad02a42973aba7fed9bb2346) dendrite now exhibits the following behaviour;

When alice syncs _after_ bob has set presence, bob's presence is not propagated when bob joins a room with alice.

However, if bob sets a presence _after_ alice starts syncing (for the first time), his presence is propagated to alice when bob joins a room.

This behaviour seems to be introduced by https://github.com/matrix-org/dendrite/commit/07bfb791ca616bd3a4aa96691b74c96146d59d90, or a likewise patch, so please double-check if this behaviour wasn't inadvertently introduced.
