### ISSUE TITLE
Users getting deleted

### ISSUE THREAD

**Issue by MaximilianGaedig** [matrix-org/dendrite#2808]
### Background information

- **Dendrite version or git SHA**: 3aa92efaa3e814ad0596fc5fc174a2e43124dcf5
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: Yes
- **`go version`**: The one in the container
- **Client used (if applicable)**: --

### Description

- **What** is the problem: All users are getting deleted from the database
- **Who** is affected: Probably every user of which the server is using the latest commit
- **How** is this bug manifesting: Cannot log in
- **When** did this first appear: Probably after watchtower upgraded me to the latest commit

### Steps to reproduce

- have a server which is one commit behind the latest
- update to the latest commit

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

I'd expect users not to get deleted.
Latest is referring to 3aa92efaa3e814ad0596fc5fc174a2e43124dcf5 which I suspect the issue came from.
Logs are clear, sorry for this small amount of info, this is all I have.
I assume the migration from a previous version to the new one created this issue.

**Comment by neilalexander** [comment]
Can you please confirm **exactly** what you did, i.e. did you try to go from `main` back to the release builds or did you stay on `main` in all tested cases?

The nature of the database migration means that once you go past that commit, you can't go back to before it. The migration also doesn't actually affect the table contents at all, they are all `ALTER ... RENAME` statements.

**Comment by MaximilianGaedig** [comment]
I just updated and stayed on that, that's when the issue occurred.

**Comment by MaximilianGaedig** [comment]
Probably something outside of dendrite caused the issue (watchtower), it must have updated to main then to latest for some reason.
