### ISSUE TITLE
Ability to use S3 buckets (or similar) for object/media storage

### ISSUE THREAD

**Issue by ThatOneCalculator** [matrix-org/dendrite#2813]
**Description:**

My VPS doesnt have a lot of storage, and being able to offload media to my S3 bucket would be extremely useful

**Comment by S7evinK** [comment]
Right now there would be [matrix-media-repo](https://github.com/turt2live/matrix-media-repo), but I haven't tested this with Dendrite.

**Comment by kegsay** [comment]
We have no plans to support or maintain this built in. Use matrix-media-repo if you need this.
