### ISSUE TITLE
Unable to use voice calling

### ISSUE THREAD

**Issue by keytime211** [matrix-org/dendrite#2835]
Background information:
Monolith
Postgres
Running Docker

Description:
I used the home server to build it, but I can't use the voice call function.
When I use the voice call feature, he keeps showing up in the connection, but there is no sound and I can't talk.
At the beginning of the period, it was thought that the problem was caused by the server time zone, but the problem still persisted after changing to the correct time zone
Tried to configure TURN server and the problem persists.
No relevant configuration was found in the configuration documentation.
I don't know where the problem is, no exception was found in the docker log.

`time="2022-10-27T08:44:42.318308117Z" level=info msg="Sent event to roomserver" event_id="$xxxxxxxxxxxxxxx" req.id=xxxxxx req.method=PUT req.path="/_matrix/client/r0/rooms/!xxxxx:xxxx.xx:xxx/send/m.room.encrypted/xxxxx.20" room_id="!xxxx:xx.xxxx:xxx" room_version=9 user_id="@xxxxxxxxx"`
`time="2022-10-27T08:44:42.787193200Z" level=info msg="Sent event to roomserver" event_id="$E3gu1-xxxxxxxxxxxx" req.id=xxxxxxxxx req.method=PUT req.path="/_matrix/client/r0/rooms/!xxxxxxx:xxxxxxz:xxxx/send/m.room.encrypted/xxxxxxxx.xx" room_id="!xxxxxx:xxx.xx:xx" room_version=9 user_id="@xxxxxxxxxxxxxx"`

Does Monolith itself have a TURN server service?
Or how should I configure it to realize the voice call function

**Comment by rigzba21** [comment]
I believe that Dendrite does not implement a TURN server service, and you would likely need to run a setup similar to the [configuring a `coturn` TURN server with Synapse docs.](https://matrix-org.github.io/synapse/latest/turn-howto.html#configuration)

**Comment by keytime211** [comment]
> 我相信 Dendrite 没有 TURN 服务器配置[文档服务，您可能需要运行类似于 Synapse ](https://matrix-org.github.io/synapse/latest/turn-howto.html#configuration)[TURN 服务器的设置。`coturn`](https://matrix-org.github.io/synapse/latest/turn-howto.html#configuration)

Thanks a lot, I have solved this problem.
When looking at the documentation, I found that I did not open the UDP port to the firewall to cause this problem. Now I can connect and use it normally.
