### ISSUE TITLE
Permission denied and get panic while dendrite trying to write it in /var/ folder on docker container.

### ISSUE THREAD

**Issue by nakoo** [matrix-org/dendrite#2862]
### Background information

- **Dendrite version or git SHA**: v0.10.7
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: Docker
- **`go version`**: -
- **Client used (if applicable)**: Element

### Description

- **What** is the problem: Getting permission deny error message while dendrite trying to write it in `/var/` directory. Using `/var` direcitory as docker volume is very common thing in Docker. [compose.yaml](https://github.com/matrix-org/dendrite/blob/main/build/docker/docker-compose.monolith.yml) also recommends to do so.
- **Who** is affected: Who run dendrite server on docker
- **How** is this bug manifesting:
```bash
Error writing to logfile: open /var/log/dendrite/Monolith.log: permission denied
time="2022-11-04T20:38:55.703616343Z" level=panic msg="failed to create full text" error="open /var/dendrite/searchindex/index_meta.json: permission denied"
time="2022-11-04T20:38:55.703199780Z" level=info msg="Dendrite version 0.10.7"
panic: (*logrus.Entry) 0x40004d36c0

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0x40004d3650, 0x0, {0x40005845c0, 0x1a})
   github.com/sirupsen/logrus@v1.9.0/entry.go:260 +0x4a0
github.com/sirupsen/logrus.(*Entry).Log(0x40004d3650, 0x0, {0x4000558e48?, 0x66ee8?, 0x20418c8?})
   github.com/sirupsen/logrus@v1.9.0/entry.go:304 +0x60
github.com/sirupsen/logrus.(*Entry).Panic(...)
   github.com/sirupsen/logrus@v1.9.0/entry.go:342
github.com/MFAshby/stdemuxerhook.(*StdDemuxerHook).Fire(0x40005899e0?, 0x40004d3570)
   github.com/MFAshby/stdemuxerhook@v1.0.0/stdemuxerhook.go:58 +0x144
github.com/sirupsen/logrus.LevelHooks.Fire(0x4000558f98?, 0x558f68?, 0x4000000004?)
   github.com/sirupsen/logrus@v1.9.0/hooks.go:28 +0x94
github.com/sirupsen/logrus.(*Entry).fireHooks(0x40004d3570)
   github.com/sirupsen/logrus@v1.9.0/entry.go:280 +0x1cc
github.com/sirupsen/logrus.(*Entry).log(0x40004d3500, 0x0, {0x40005845a0, 0x1a})
   github.com/sirupsen/logrus@v1.9.0/entry.go:242 +0x3b0
github.com/sirupsen/logrus.(*Entry).Log(0x40004d3500, 0x0, {0x4000559268?, 0x0?, 0x0?})
   github.com/sirupsen/logrus@v1.9.0/entry.go:304 +0x60
github.com/sirupsen/logrus.(*Entry).Logf(0x40004d3500, 0x0, {0x135f630?, 0x11586c0?}, {0x0?, 0x2?, 0x1?})
   github.com/sirupsen/logrus@v1.9.0/entry.go:349 +0x88
github.com/sirupsen/logrus.(*Entry).Panicf(...)
   github.com/sirupsen/logrus@v1.9.0/entry.go:387
github.com/matrix-org/dendrite/setup/base.NewBaseDendrite(0x40004c0000, {0x133db53, 0x8}, {0x4000559cf8, 0x0, 0x10bbdc?})
   github.com/matrix-org/dendrite/setup/base/base.go:160 +0x3f4
main.main()
   github.com/matrix-org/dendrite/cmd/dendrite-monolith-server/main.go:69 +0x340
```
- **When** did this first appear: After updating v0.10.7. This issue didn't happen on previous version (v0.10.6)

### Steps to reproduce

- update to v0.10.7
- run dendrite server on docker
- panic (can't run)

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by neilalexander** [comment]
I've rebuilt the images, please try pulling again.

**Comment by nakoo** [comment]
I tested it now and it works as expected. Thank you for reverting the change. I know this gives some security benefit, but for the user perspective, it's hard to manage. To make it work, I had to mount all necessary folders to docker volume, and use alpine image to chown those docker volumes. I couldn't find proper workaround other than this.

**Comment by S7evinK** [comment]
This seems to be resolved now.
For future reference: This was caused by changing the user inside docker and not taking into account existing setups using the old user.
