### ISSUE TITLE
Add auth to /rooms/{roomID}/state... APIs

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/dendrite#287]
The API also needs to handle the case of the user having left the room, where we should then return the state of the room at that point as per: https://matrix.org/docs/spec/client_server/r0.2.0.html#get-matrix-client-r0-rooms-roomid-state

**Comment by MohitKS5** [comment]
To implement this we need to store `eventStateSnapshotNID` at the point when user leaves the room somewhat like `roomId: last state` for each room he joins and then query the State snapshot at that NId from the api whenever the request to `/state` is sent. And all this after we get `eventContent.membership (join | invite | leave | ban | kick)` of the user. Am I going ryt?

**Comment by MohitKS5** [comment]
@erikjohnston

**Comment by prateek2211** [comment]
I would like to work on this

**Comment by Kegsay** [comment]
We now do this for single `/state/{type}/{key}` requests since https://github.com/matrix-org/dendrite/pull/1222 - it should be easy enough to extend this for `/state`

**Comment by Kegsay** [comment]
@neilalexander I think you do this now for `/state` too? :D Can we close?

**Comment by neilalexander** [comment]
Yep, we can indeed!
