### ISSUE TITLE
Can I custom could messaging to send notification

### ISSUE THREAD

**Issue by Modificator** [matrix-org/dendrite#2883]
**Description:**
Usually, we can not connect Google Service,  can not receive FCM.
So, I wanna api or web hook to use other notification service.
Thanks.

**Comment by spaetz** [comment]
I use ntfy.sh as a push server without problems. dendrite does not necessarily rely on Google services...

**Comment by S7evinK** [comment]
Like mentioned, Dendrite doesn't really care which push gateway is getting informed, it's the client setting up the push gateway to use. (Not sure if you can override the push gateway in Element Android, though)

**Comment by spaetz** [comment]
Yes you can. Android element works well with ntfy.sh, for example.
