### ISSUE TITLE
Can't use other languages for full text search

### ISSUE THREAD

**Issue by Anulo2** [matrix-org/dendrite#2886]
### Background information

- Dendrite 0.10.1
- Monolith
- Postgres
- Docker

### Description

- When enabling full text search with languages different from engilsh it throws the following error:
`level=panic msg="failed to create full text" error="no analyzer with name or type 'it' registered"`
I've attemped with the following languages: it, de

### Steps to reproduce

- Run dendrite monolith with full search enabled in the dendrite.yaml with the language param set to "it"
<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by S7evinK** [comment]
This was fixed in Dendrite [0.10.2](https://github.com/matrix-org/dendrite/releases/tag/v0.10.2), so updating to [0.10.7](https://github.com/matrix-org/dendrite/releases/tag/v0.10.7) should fix this issue.
