### ISSUE TITLE
Cannot find a user to include in a chat room

### ISSUE THREAD

**Issue by Juha-Park-TII-SSRC** [matrix-org/dendrite#2895]
### Background information

- **Dendrite version or git SHA**: 0.10.8
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: SQLite3
- **Running in Docker?**: No
- **`go version`**: 1.19
- **Client used (if applicable)**: Element-desktop

### Description

- **What** is the problem: Cannot search of any user to include into chat room.
- **Who** is affected: Everybody to use dendrite with pinecone.
- **How** is this bug manifesting: Erros in the log saying "WARN[2022-11-30T07:42:05.764548000Z] bulkFetchUserDirectoriesFromServers: failed to query hs  context=missing error="Get \"http://c613f8f078d7bc8d0a540fbf6fd02b6475babe33012189262b178837522b5e00/_matrix/p2p/profiles\": loopback dial" hs=c613f8f078d7bc8d0a540fbf6fd02b6475babe33012189262b178837522b5e00"
- **When** did this first appear: It happens since dendrite v.0.9.2

### Steps to reproduce

- Prepare 2 computers which are in the same subnetwork.
- Run dendrite servers which uses pine-cone for P2P chat in each computer
- Check each dendrite server found out the other dendrite server
- Create a user account with element-desktop in each computer(Ex. User1 and User2)
- One user account(Ex. User1) create a chat room which is public
- The user account(Ex. User1) searches of the other user account(Ex. User2) in order to invite him into the chat room.
- The room creator(Ex. User1) cannot search of anyone(Ex. User2).

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->
The user account should be able to search of other user account but that is not possible since dendrite 0.9.2 with pine-cone
I attached the generated log from dendrite when I type a letter for other user account after creating a public chat room.

**Comment by kegsay** [comment]
Dupe https://github.com/matrix-org/dendrite/issues/2704
