### ISSUE TITLE
[Feature]  Make Nats JetStream stream replicas configurable

### ISSUE THREAD

**Issue by pcmid** [matrix-org/dendrite#2908]
**Description:**
When the nodes in the nats cluster are restarted, in order to ensure 0 downtime as much as possible, we should set the tream replication factor to a value greater than 1. Currently all of the streams are hardcoded to default to 1 replica and we want to allow setting to a larger value in the configuration.

**Comment by kegsay** [comment]
We don't have any plans to support this at this time. When we properly support polylith and external NATS then we will revisit this, but for now this isn't a configuration we want users to run.
