### ISSUE TITLE
Signing in with uppercase username breaks device list updates

### ISSUE THREAD

**Issue by nico-famedly** [matrix-org/dendrite#2914]
### Background information

- **Dendrite version or git SHA**: 0.10.8+ed497aa
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: sqlite
- **Running in Docker?**: yes
- **`go version`**:
- **Client used (if applicable)**: famedlysdk, but shouldn't matter

### Description

- **What** is the problem: If I sign in using `Bob` instead of `bob`, I get a device list update for `@Bob:localhost` instead of `@bob:localhost` with only one entry
- **Who** is affected: Uhhh, everyone who uses an uppercase username to sign in?
- **How** is this bug manifesting: Wrong device lists, that break e2ee
- **When** did this first appear:

### Steps to reproduce

- curl -fS -XPOST -d '{"username":"bob", "password":"Something", "inhibit_login":true, "auth": {"type":"m.login.dummy"}}' "http://$IP_ADDRESS/_matrix/client/r0/register"
- then login using Bob as the identifier for the user
- login succeeds
- If you share an encrypted room with bob, you will get a device list update for `@Bob:servername` instead of `@bob:servername`

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->
I would expect device lists to always use the exact mxid instead of the casing from /login.

Logs:

```
# Normal login using "bob"

Updating device keys for {@bob:famedlysdk.test: []}

Response {@bob:famedlysdk.test: {pnv71Ijt: Instance of 'MatrixDeviceKeys'}}

# Login using "Bob"

[Matrix] Successfully connected as Bob with http://127.0.0.1

Updating device keys for {@Bob:famedlysdk.test: []}

Response {@Bob:famedlysdk.test: {2Cfqnc6M: Instance of 'MatrixDeviceKeys'}}
```

Notice how the latter does not include the devices form "bob" and uses the wrong mxid in the response.

**Comment by bones-was-here** [comment]
How are you able to log in with an uppercase char?

I still patch the source to support very old accounts https://github.com/matrix-org/dendrite/issues/2073#issuecomment-1047934258

**Comment by deepbluev7** [comment]
@bones-was-here I just passed "Bob" as the login username and it worked.
