### ISSUE TITLE
Federated backfill broken for medium/large sized rooms since v0.10.8

### ISSUE THREAD

**Issue by z411** [matrix-org/dendrite#2923]
### Background information

- **Dendrite version or git SHA**: v0.10.8
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **`go version`**: 1.19.3
- **Client used (if applicable)**: Element 1.11.17

### Description

- **What** is the problem: Newly joined remote rooms don't backfill the history, they just show "You can't see earlier messages". It seems to work for smaller rooms (less than 100 events) but I'm not sure if that's the cause.
- **Who** is affected: Dendrite clients joining remote Synapse rooms
- **How** is this bug manifesting: The room fails to backfill after first join, can't see history. Logs don't display erorrs or wanings, just "backfilled 0 events".
- **When** did this first appear: Since v0.10.8, main as of today affected as well

### Steps to reproduce

- Try to join a remote room hosted a Synapse homeserver (preferably with a longer than 100 message history)
- After join, backfilling won't work. It'll just display "You can't see earlier messages" instead of showing the room history.

When Dendrite attempts the backfill request, the remote Synapse server appears to log the backfill events in its log, but the Dendrite server just shows the following in the log: 

`level=info msg="backfilled 0 events"`

In a smaller room, though, it works fine:

`level=info msg="backfilled 77 events"`

In v0.10.7 and v0.10.6 (versions I tested) everything works as expected, with the backfill appearing in the client and the Dendrite log showing the following, even with very large and old rooms:

`level=info msg="backfilled 100 events"`

In all said rooms there are only local users of said homeservers.

I can't see any warnings or errors related to this so if there are other ways to debug the issue I'd be glad to provide more information.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

### Notes

I say "federated" because I only tried joining remote rooms, but I don't know if this also happens with local rooms.

**Comment by bones-was-here** [comment]
I can reproduce this.

**Comment by dead10ck** [comment]
This is also happening for me.

**Comment by dead10ck** [comment]
I can confirm that this fix worked on my own Dendrite instance. Thanks so much!
