### ISSUE TITLE
Support listening on Unix socket

### ISSUE THREAD

**Issue by Saklad5** [matrix-org/dendrite#2924]
Dendrite currently only supports listening on TCP ports, one for HTTP and one for HTTPS. Since it is already designed with reverse proxies in mind, it would be much more helpful to support listening on a Unix domain socket.

Unix domain sockets are much simpler and efficient, particularly with regards to access control: configuring them to only be usable by desired users (e.g. nginx) allows connections to remain secure from other users on the server without requiring TLS or other complications like listening on the loopback interface does.

This also has the obvious benefit of not having to keep track of arbitrary ports and addresses.

When implementing this, it is vital that permissions for the socket are configurable: if anyone can access it, it is only marginally better than a loopback address.

**Comment by S7evinK** [comment]
Fixed with #2974
