### ISSUE TITLE
Implement FastCGI support

### ISSUE THREAD

**Issue by Saklad5** [matrix-org/dendrite#2925]
FastCGI allows for much more efficient communication between a reverse proxy and a backend server. As Dendrite is expected to be used with a reverse proxy, it may be worth implementing that protocol.

It would be best to implement this over a Unix domain socket, as described in #2924. That combination is extremely common among software used with reverse proxies, as it offers exceptional efficiency, simplicity, and (assuming separate users and strict filesystem permissions) security.

**Comment by kegsay** [comment]
We have no plans to support this currently. Bottlenecks in the server at present aren't due to the protocol used from reverse proxy to Dendrite.
