### ISSUE TITLE
getProfile failed

### ISSUE THREAD

**Issue by MelBourbon** [matrix-org/dendrite#2937]
### Background information
- **Dendrite version or git SHA**: 0.10.8
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **`go version`**: go1.18.1 linux/amd64
- **Client used (if applicable)**: app.element.io

### Description

- **What** is the problem: Not possible to search for "known" user on other matrix server
- **Who** is affected: All users
- **How** is this bug manifesting: When searching for other user no result is shown and error log is created
- **When** did this first appear: Fresh install

### Steps to reproduce
Log into account with element and search for user on other server which you know that it is existing to establish private chat. Other user is not shown.

### Log (real domain was exchanged with "domain.com" and user which was searched with "user"):
```
ERRO[2023-01-11T22:15:04.724306862Z] getProfile failed  ... msg=Failed to GET JSON (hostname \"tchncs.de\" path \"/_matrix/federation/v1/query/profile\") code=401 wrapped=M_UNAUTHORIZED: Failed to find any key to satisfy: _FetchKeyRequest(server_name='domain.com', minimum_valid_until_ts=1673475304499, key_ids=['ed25519:LNyFeY'])" req.id=RgXiSloJtt9c req.method=GET req.path="/_matrix/client/r0/profile/@user:tchncs.de"
```

**Comment by S7evinK** [comment]
Can you check if your domain successfully passes the [federation tester](https://federationtester.matrix.org/)? The error suggests there might be something wrong.

**Comment by MelBourbon** [comment]
Yes, federation test was passed but issue was still existing. This issue was existing if I tried to run dendrite on the main domain or with delegation. Issue was resolved after running it only on subdomain. So it is related to my nginx conf, not directly with dendrite. So I will close for now.
