### ISSUE TITLE
m.homeserver should be an URL instead of a hostname

### ISSUE THREAD

**Issue by clandmeter** [matrix-org/dendrite#2951]
The dendrite documentation and sample configuration are unclear about its content.
Adding just a hostname will prevent some clients (almost all of them)  from working.
The solution here is to use an URL instead of just a hostname.

https://github.com/matrix-org/dendrite/blob/5b73592f5a4dddf64184fcbe33f4c1835c656480/dendrite-sample.monolith.yaml#L72

**Comment by spaetz** [comment]
More specifically, line 73 provides the wrong example of `  # e.g. localhost:443`, which should be `https://localhost` to provide a correct example.

**Comment by S7evinK** [comment]
Going to be fixed with #2953

**Comment by S7evinK** [comment]
Oh.. Also, looks like a similar [issue](https://github.com/matrix-org/dendrite/issues/2941) exists, going to close this one
