### ISSUE TITLE
Images not being loaded by my homeserver and messages aren't synchronizing anymore either

### ISSUE THREAD

**Issue by theparappanon** [matrix-org/dendrite#2954]
### Background information

- **Dendrite version or git SHA**:  0.11.0
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **`go version`**: 1.19.5
- **Client used (if applicable)**: Nheko and Fluffychat

### Description

- **What** is the problem: I can log into my Matrix account and even join chats, but no messages are updated, nor images load. 
- **Who** is affected: Myself, and likely everyone else in my homeserver.
- **How** is this bug manifesting: I can send messages in chats, but others' messages do not load. Images as a whole, whether avatars, stickers or other uploaded media do not show up. When I join a room I do seem to join, but no messages show up.
When I check through logs with journalctl, I find out that when the server tries to fetch image files, it ends up causing errors.
- **When** did this first appear: The image issue started like last week, just a few days after updating to 0.11.1 from 0.10.8 in fact, but today it's finally completely broke down.

### Steps to reproduce

- I updated from the stable release zip for 0.10.8 to the 0.11.0 branch of the git repository which I cloned.
- I moved my secret key and dendrite.yaml file, which I soon modified to change the media_store path's location from being inside the dendrite folder to directly in the home folder itself so I could make upgrading easier. I had already put Jetstream's  location to be directly in the matrix user's home folder from the beginning so I didn't need to edit that.
- After that, I compiled the new version of Dendrite to /usr/bin/local and started running it.
- However, even though the inability to cache or load other people's messages issue started creeping up gradually (it could be a Postgres problem), it was the images which started disappearing first, then the ability to load messages went away today.

Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data).

When I use journalctl -fu dendrite, my log ends up full of messages similar to this:

``` Jan 28 01:52:48 vmi1151718.myhomeserver.org dendrite-monolith-server[6716]: time="2023-01-28T00:52:48.043158039Z"
``` level=error msg="r.fetchRemoteFileAndStoreMetadata: failed to fetch remote file"
``` MediaID=367fcc30d277492a432794513f59ab8609b554cb Origin=othermatrix.server error="file with media ID
`` `\"367fcc30d277492a432794513f59ab8609b554cb\" could not be downloaded from othermatrix.server " req.id=GoF4VpraqPA3
``` req.method=GET req.path=/_matrix/media/v3/download/othermatrix.server/367fcc30d277492a432794513f59ab8609b554cb

**Comment by theparappanon** [comment]
Strangely enough, it seems that the images that disappeared were all images that were loaded by my server 7 weeks or earlier ago. I've changed my account's avatar and there was absolutely no issue going on with that.
Maybe it could have to do with Dendrite's cache (which I've set to 256mb) and the default key validity period lasting for 7 days in dendrite.yaml?

**Comment by leafee98** [comment]
Have you moved the old media_store content to the new place? And how about the file permission?

**Comment by theparappanon** [comment]
Yeah, I did move the old media_store directory before upgrading from v0.10.8 to v.0.11.0.
As for the file permissions,  media_store is owned by the same user I use to run dendrite and has drwxr-x--- as its file permissions.

**Comment by theparappanon** [comment]
I finally found out the reason behind this... it was literally just a typo in the base_path section of the media API configuration in my dendrite.yaml file.
