### ISSUE TITLE
Deduplicate identical filters

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/dendrite#298]
i.e. porting functionality of https://github.com/matrix-org/synapse/pull/2219 to dendrite.

This can either be done as in the PR by comparing the filter dicts, or by using the hash of a filter as the ID

**Comment by anoadragon453** [comment]
Any input on which layer this should be done at? Whether it's where `accounts.Database.PutFilter` ([link](https://github.com/matrix-org/dendrite/blob/b7cfc2e057439334e3ddfa69cebff653f3114d00/src/github.com/matrix-org/dendrite/clientapi/routing/filter.go#L114)) is called from, inside `accounts.Database.PutFilter` ([link](https://github.com/matrix-org/dendrite/blob/b7cfc2e057439334e3ddfa69cebff653f3114d00/src/github.com/matrix-org/dendrite/clientapi/auth/storage/accounts/storage.go#L333)) itself, or in the method PutFilter calls, `insertFilter` ([link](https://github.com/matrix-org/dendrite/blob/b7cfc2e057439334e3ddfa69cebff653f3114d00/src/github.com/matrix-org/dendrite/clientapi/auth/storage/accounts/filter_table.go#L70))?

I'm thinking `accounts.Database.PutFilter` itself, so the check only needs to be done once, while keeping `insertFilter` always doing what it says on the tin.

**Comment by anoadragon453** [comment]
Presumably we wouldn't even need to hash, we can just check whether the filter's text and user's localpart is already a part of a row in the database, and refuse to insert if so.
