### ISSUE TITLE
README instructions reference -monolith

### ISSUE THREAD

**Issue by jimt** [matrix-org/dendrite#2991]
### Background information

- **Dendrite version or git SHA**: f1ccfcf1504c27cbaaecbc28ec26299d785d2695
- **SQLite3 or Postgres?**:
- **Running in Docker?**:
- **`go version`**:
- **Client used (if applicable)**:

### Description

- **What** is the problem:
  sample installation instructions refer to `-monolith` versions of files that no longer exist

- **Who** is affected:
  users installing a test instance for the first time
- **How** is this bug manifesting:
  - `We recommend running in Monolith mode` in [L16](https://github.com/matrix-org/dendrite/blame/main/README.md#L16)
  - `dendrite-sample.monolith.yaml` in [L74](https://github.com/matrix-org/dendrite/blame/main/README.md#L74) appears to be `dendrite-sample.yaml` now.
  - `./bin/dendrite-monolith-server` in [L77](https://github.com/matrix-org/dendrite/blame/main/README.md#L77) is presumably just `./bin/dendrite` now.

- **When** did this first appear:

**Comment by robinwesterik** [comment]
#2994 Aims to solve this issue. I have just deployed my home server with these new instructions.

**Comment by S7evinK** [comment]
Solved with #2994
