### ISSUE TITLE
Handle duplicate kafka/naffka messages

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/dendrite#300]
Since we only persist the partition offset after we've processed the message it's possible for dendrite services to receive the last message from kafka again if it died at the right/wrong point.

Currently e.g. federation sender doesn't handle this (causing #290)

Two options:
1. Ensure we handle duplicate messages
2. Persist the results of processing the messages atomically with the offsets

**Comment by erikjohnston** [comment]
> Persist the results of processing the messages atomically with the offsets

This is probably the better option, but its probably going to be quite faffy to actually code due to having to figure out how to atomically persist things without pushing processing into the database layer and using DB transactions

**Comment by neilalexander** [comment]
We're NATS now.
