### ISSUE TITLE
PerformPublish failed

### ISSUE THREAD

**Issue by mwnu** [matrix-org/dendrite#3003]
- **SQLite3 or Postgres?**:Postgres
- **Running in Docker?**:Yes
- **What** is the problem:Newly created rooms cannot be published to the room directory under the domain name, and rooms that were created and published a year ago cannot be unpublished.
- **The server log error message**: There is no unique or exclusion constraint matching the ON CONFLICT specification.

**Comment by S7evinK** [comment]
Which version are you on? This should be fixed in v0.11.1, or since https://github.com/matrix-org/dendrite/commit/4738fe656fc0975b5faa4fcdf6c11a776b9563a0
