### ISSUE TITLE
Support for MongoDB

### ISSUE THREAD

**Issue by lmauromb** [matrix-org/dendrite#3005]
**Description:**

Hi folks, 

I'm currently experimenting with switching the database to MongoDB and use it as an alternative solution for Dendrite. So, I wanted to ask if this would be something that you see value and can be contributed back to the upstream repository.

**Comment by S7evinK** [comment]
Hi and sorry for the late reply.
We currently don't have intentions to add yet another database type to Dendrite, as it would add a huge maintenance burden on us. You can have a look at our contributing [guidelines](https://matrix-org.github.io/dendrite/development/contributing#contribution-types) for things we're likely to accept.

**Comment by lmauromb** [comment]
hey @S7evinK thanks for sharing your guidelines and understood!!
