### ISSUE TITLE
Replace `gorilla/mux`

### ISSUE THREAD

**Issue by S7evinK** [matrix-org/dendrite#3017]
Since [gorilla/mux](https://github.com/gorilla/mux) is archived and not actively maintained, we should replace it with a different router/mux.

Possible replacements:
- https://github.com/julienschmidt/httprouter
- https://github.com/go-chi/chi
- https://github.com/labstack/echo
- other?

**Comment by joy4eg** [comment]
I would recommend considering also https://github.com/gofiber/fiber

**Comment by S7evinK** [comment]
We've decided to go with https://github.com/julienschmidt/httprouter, as we don't need many of the features provided by other routers.

**Comment by S7evinK** [comment]
https://gorilla.github.io/blog/2023-07-17-project-status-update/
Given this, closing.
