### ISSUE TITLE
Don't leak goroutines waiting for notifier in syncserver

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/dendrite#303]
When we receive a sync request we spawn off a goroutine that blocks until there are new events for a user. These could quickly stack up for users that don't have much activity happening, as we time the requests out.

**Comment by richvdh** [comment]
https://github.com/matrix-org/dendrite/blob/119a8a2876a823bacaca9040882bfe9603a8cb67/src/github.com/matrix-org/dendrite/syncapi/sync/requestpool.go#L125

**Comment by richvdh** [comment]
presumably fixing this requires wiring WaitForEvents into the request context in some way, such that it can be cancelled when the context is cancelled.

**Comment by erikjohnston** [comment]
Fixed in #311
