### ISSUE TITLE
FR: GRPC

### ISSUE THREAD

**Issue by gattytto** [matrix-org/dendrite#3036]
[follow up](https://github.com/matrix-org/dendrite/pull/158#discussion_r127173760) this could be a little easier if gapic is embraced for client-side libs as in [1: bazel's workspace](https://github.com/googleapis/googleapis/blob/master/WORKSPACE), [2: bzl repository](https://github.com/googleapis/googleapis/blob/master/repository_rules.bzl), and [3: generators](https://github.com/googleapis/gapic-generator-python)(with due tweaks in templates). 

this allows also for a couple bash scripts to generate protobuf messages code, server-side grpc code and stubs in various languages (more for server-side as there's new plug-ins coming out very often :3 ) like dart and scala

bazel takes great care of the build environment for different platforms and takes generators straight from their github repos, builds and runs them.

**Comment by kegsay** [comment]
We don't have internal APIs anymore, so this issue isn't relevant for us.
