### ISSUE TITLE
federation.LookupRoomAlias failed...Failed to find any key to satisfy: _FetchKeyRequest

### ISSUE THREAD

**Issue by sg-qwt** [matrix-org/dendrite#3041]
### Background information

- **Dendrite version or git SHA**:  0.11.1
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No 
- **Client used (if applicable)**: element web

Error: federation.LookupRoomAlias failed...code=401 wrapped=M_UNAUTHORIZED: Failed to find any key to satisfy: _FetchKeyRequest

### Description
This is a very weird issue I encountered on a fresh install yesterday. 

After fresh setup, I successfully passed https://federationtester.matrix.org/ without any issue. But I cannot join any room because of the `federation.LookupRoomAlias failed...Failed to find any key to satisfy: _FetchKeyRequest` error messages.

My initial Nginx reverse relevant bit is here:
```
      "/_matrix" = {
        proxyPass = "http://localhost:8008";
      };
```

I then tried lots of things, then I realized if I changed the reverse proxy as below, then suddenly the error message goes away.
```
      "/_matrix" = {
        proxyPass = "http://[::1]:8008";
      };
```
That's the only diff between what's working and not working.

Note both configs are passing all https://federationtester.matrix.org/ tests without issue. But only the below version works. And I don't recall having issues using localhost as reverse proxy for other services.

My questions are:
1. Is this a Nginx thing or Dendrite thing this case? I misconfigured Nginx on the first one?
2. Why I'm able to pass https://federationtester.matrix.org/ on the first case though in reality it failed to join any room?

**Comment by bones-was-here** [comment]
Although most systems have `localhost` resolving to 127.0.0.1 and ::1 this isn't guaranteed to exist or be configured correctly.  Even if it is configured correctly, it's possible for a service to listen only on (for example) ::1 and not 127.0.0.1 so if (for example) the reverse proxy decides to try 127.0.0.1 first and give up if that doesn't work, the connection can fail "randomly".

Personally I use a unix socket instead whenever possible (which is supported in Dendrite 0.12.0) and if that's not supported I will specify the configured listen IP in the proxy config instead of `localhost`.

**Comment by spaetz** [comment]
Not sure if dendrite listens on ipv6 by default, so this is one of those things where it depends on your systems what localhost resolves to (ipv4 or ipv6). So, this is one of those configuration things where one just needs to be sure that there is an impedance match between IPV4 and IPV6...

**Comment by sg-qwt** [comment]
My vps has pretty standard dual stack network. And the hosts file has default content as below:
```
127.0.0.1 localhost
::1 localhost
```
nslookup gave me 127.0.0.1 for localhost. So I believe there's an impedance match between IPV4 and IPV6 which dendrite listens on ipv6 while reverse proxy tried 127.0.0.1 as explained above. Though it's failing consistently this case, not
 randomly.

Thanks for the advice and help. I guess I'll give unix socket a try in newer 0.12.0. Pls feel free to close this issue if nobody has other comments.
