### ISSUE TITLE
Dendrite is unable to access postgresql database

### ISSUE THREAD

**Issue by emmatebibyte** [matrix-org/dendrite#3053]
### Background information

- **Dendrite version or git SHA**: `0.12.0+74dc5468`
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **`go version`**: `go version go1.20.2 linux/amd64`
- **Client used (if applicable)**:

### Description

- **What** is the problem:
When I run it, dendrite is unable to connect to the postgresql database.
- **Who** is affected:
Server admin
- **How** is this bug manifesting:
```
$ bin/dendrite -config dendrite.yaml
INFO[2023-04-09T23:54:18.859871578Z] Dendrite version 0.12.0+74dc5468             
DEBU[2023-04-09T23:54:18.860043540Z] Setting DB connection limits                  conn_max_lifetime=-1s data_source_name="postgresql://localhost/dendrite?sslmode=disable" max_idle_conns=5 max_open_conns=90
PANI[2023-04-09T23:54:18.860132090Z] Failed to set up global database connections  error="failed to find maximum connections: parse \"postgresql://dendrite:[password]@localhost/dendrite?sslmode=disable\": net/url: invalid userinfo"
panic: (*logrus.Entry) 0xc0001d0bd0

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc0001d0b60, 0x0, {0xc000136a20, 0x2c})
	github.com/sirupsen/logrus@v1.9.0/entry.go:260 +0x4d6
github.com/sirupsen/logrus.(*Entry).Log(0xc0001d0b60, 0x0, {0xc000190eb0?, 0x10c1bd7?, 0x0?})
	github.com/sirupsen/logrus@v1.9.0/entry.go:304 +0x4f
github.com/sirupsen/logrus.(*Entry).Panic(...)
	github.com/sirupsen/logrus@v1.9.0/entry.go:342
github.com/MFAshby/stdemuxerhook.(*StdDemuxerHook).Fire(0x0?, 0xc0001d0a80)
	github.com/MFAshby/stdemuxerhook@v1.0.0/stdemuxerhook.go:58 +0x19e
github.com/sirupsen/logrus.LevelHooks.Fire(0xc000190ff0?, 0x190fc0?, 0x4?)
	github.com/sirupsen/logrus@v1.9.0/hooks.go:28 +0x7a
github.com/sirupsen/logrus.(*Entry).fireHooks(0xc0001d0a80)
	github.com/sirupsen/logrus@v1.9.0/entry.go:280 +0x1f0
github.com/sirupsen/logrus.(*Entry).log(0xc0001d0a10, 0x0, {0xc0001369f0, 0x2c})
	github.com/sirupsen/logrus@v1.9.0/entry.go:242 +0x3c5
github.com/sirupsen/logrus.(*Entry).Log(0xc0001d0a10, 0x0, {0xc000191488?, 0x15bd820?, 0xc000134ba0?})
	github.com/sirupsen/logrus@v1.9.0/entry.go:304 +0x4f
github.com/sirupsen/logrus.(*Entry).Panic(...)
	github.com/sirupsen/logrus@v1.9.0/entry.go:342
github.com/matrix-org/dendrite/setup/base.NewBaseDendrite(0xc0000ac000, {0xc000191cb0, 0x0, 0x17afd9f?})
	github.com/matrix-org/dendrite/setup/base/base.go:180 +0x855
main.main()
	github.com/matrix-org/dendrite/cmd/dendrite/main.go:67 +0x329
```
- **When** did this first appear:
Upon following [these instructions](https://matrix-org.github.io/dendrite/installation).

### Steps to reproduce

- Follow the instructions at the official docs for building and installing dendrite
- Experience the issue

<!--
Describe how what happens differs from what you expected.

The program should have access to the database.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by spaetz** [comment]
You failed to write your specific database connection string. You do need to adapt it to suit your host setup .

**Comment by emmatebibyte** [comment]
What needs to change about it? I have a dendrite role/user in postgresql that has access to the appropriate tables, and the password has been checked countless times.

**Comment by S7evinK** [comment]
Wild guess would be some special character in your password, which making `net/url` unable to parse `username:password` correctly.

**Comment by spaetz** [comment]
Did not know this. Does the password need to be urlencoded in general? (Makes sense when you think about it)

**Comment by matslarson** [comment]
It’s usually easier to sidestep the issue by using an env var or other reference rather than trying to encode weird characters directly in the connection string

**Comment by kegsay** [comment]
You can use alternative formats for connection strings. I would suggest using key-values as per https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING - either way this is a support issue more than a bug, closing this.
