### ISSUE TITLE
Nginx configuration example in README.md not found

### ISSUE THREAD

**Issue by taylorzhancher** [matrix-org/dendrite#3094]
Quoting from the repository readme:
> Also recommended are:
>
>    A PostgreSQL database engine, which will perform better than SQLite with many users and/or larger rooms
>    A reverse proxy server, such as nginx, configured [like this sample](https://github.com/matrix-org/dendrite/blob/master/docs/nginx/monolith-sample.conf)

The link in "like this sample" does not work anymore (404 page not found). 

Not sure if this is the right template to open. Thought I'd raised it anyways since I came across it. I have little to no background in the technology so correct me if I am wrong.
Here's a possible example perhaps? copying from https://landchad.net/dendrite/
```
server {
        server_name example.org;

        listen 80;
        listen [::]:80;

        listen 443 ssl http2 default_server;
        listen [::]:443 ssl http2 default_server;

        listen 8448 ssl http2 default_server;
        listen [::]:8448 ssl http2 default_server;

        location ~* ^(\/_matrix|\/_synapse|\/_client) {
                proxy_pass http://localhost:8008;
                proxy_set_header X-Forwarded-For $remote_addr;
                client_max_body_size 50M;
        }

        # These sections are required for client and federation discovery
        # (AKA: Client Well-Known URI)
        location /.well-known/matrix/client {
                return 200 '{"m.homeserver": {"base_url": "https://example.org"}}';
                default_type application/json;
                add_header Access-Control-Allow-Origin *;
        }

        location /.well-known/matrix/server {
                return 200 '{"m.server": "example.org:443"}';
                default_type application/json;
                add_header Access-Control-Allow-Origin *;
        }
}
```

**Comment by taylorzhancher** [comment]
I found a relevant document in your repo and created a commit based on that. 
Let me know if this is desired or off the mark.

**Comment by S7evinK** [comment]
Solved with https://github.com/matrix-org/dendrite/pull/3107
