### ISSUE TITLE
Publish current dendrite-monolith container images with version tags

### ISSUE THREAD

**Issue by varac** [matrix-org/dendrite#3122]
**Description:**

Latest versioned tag on [dendrite-monolith container images](https://github.com/matrix-org/dendrite/pkgs/container/dendrite-monolith)
is still `v0.12.0`, the [related 0.12.0 release](https://github.com/matrix-org/dendrite/releases/tag/v0.12.0) is already from March 13.
I see the `main` image tag is update frequently, but for stability it's important to have versioned tags.
Please ensure to push container images together with every release (Github actions ?). Thanks !

**Comment by S7evinK** [comment]
We [already](https://github.com/matrix-org/dendrite/blob/main/.github/workflows/docker.yml#L70-L85) do, but the latest release has been some time ago, yeah.
We're likely to have a new release in the next few days, though. :)

**Comment by varac** [comment]
@S7evinK Good to know that it *should* work automatically, but in fact it didn't for the last 3 releases (0.12.1 - 0.12.3).
Did somebody investigate the reason for this ? It would be good to fix this *before* next release. Thanks !

**Comment by S7evinK** [comment]
Those weren't releases for Dendrite itself, those were for the Helm chart. (it only changed something for the chart itself, so no regular release needed)

**Comment by S7evinK** [comment]
Closing, CI still creates versioned docker images - https://github.com/matrix-org/dendrite/pkgs/container/dendrite-monolith/105836856?tag=v0.13.0
