### ISSUE TITLE
Can't accept or decline direct message invite

### ISSUE THREAD

**Issue by wangwillian0** [matrix-org/dendrite#3123]
Trying to accept invite:
> level=error msg="Failed to join room" error="1 : InputRoomEvents auth failed: InputRoomEventsResponse: eventauth: \"@...\" is not allowed to change their membership from \"leave\" to \"join\" as join rule \"invite\" forbids it" room_id="!..." servers="[...]" user_id="@..."

Rejecting invite:
> level=error msg="Failed to leave room" error="user \"@...\" is not joined to the room (membership is \"leave\")" room_id="!..." user_id="@..."

This happens with rooms created by bridges (mainly [discord](https://github.com/mautrix/discord)).

Possibly related: https://github.com/matrix-org/dendrite/issues/1760

**Comment by S7evinK** [comment]
https://github.com/matrix-org/dendrite/pull/3231 https://github.com/matrix-org/dendrite/pull/3243
Probably fixed by those, closing for now. If it still happens, happy to re-open.
