### ISSUE TITLE
Go 1.21 (Quic)

### ISSUE THREAD

**Issue by gonzalo-** [matrix-org/dendrite#3128]
### Background information

- **Dendrite version or git SHA**: 0.12.0
- **Monolith or Polylith?**: any
- **SQLite3 or Postgres?**: any
- **Running in Docker?**: No
- **`go version`**: 1.21
- **Client used (if applicable)**: Any

### Description
- **What** is the problem: The las version will not build with Go 1.21
- **Who** is affected: From now on with Go >=1.21
- **How** is this bug manifesting: Trying to build Dendrite againsts Go 1.21
- **When** did this first appear: With the release of Go 1.21

### Steps to reproduce
Try to build Dendrite v0.12.0 or less over Go 1.21:

```
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.32.0/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration
```

Cheers.-

**Comment by S7evinK** [comment]
Solved by https://github.com/matrix-org/dendrite/pull/3174
