### ISSUE TITLE
Spaces don't really work with a fresh install

### ISSUE THREAD

**Issue by lauralani** [matrix-org/dendrite#3165]
### Background information

- **Dendrite version or git SHA**: matrixdotorg/dendrite-monolith:v0.13.1
- **SQLite3 or Postgres?**: postgres 15
- **Running in Docker?**: yes 
- **`go version`**: - 
- **Client used (if applicable)**: Element 1.11.37 & FluffyChat 1.12.0

### Description

- **What** is the problem: Spaces that are **not on my Instance** don't work or don't work enough to be of any use.
- **Who** is affected: probably all users on my Instance lila.network
- **How** is this bug manifesting:
Element: When trying to join public spaces, the list of rooms can't be fetched. I therefore also can't join any rooms.  
FluffyChat: When trying to add spaces, the app tells me "Unrecognized request".
Debug logs don't show any weird errors (at least for me, i just started with matrix)
- **When** did this first appear: Since setting up the instance with v0.13.1 yesterday

### Steps to reproduce

- open Element or FluffyChat
- try to join spaces (i tested it with `#codeberg-space:matrix.org` and `#nerdberg:nerdberg.de` 
- for Element: See the join screen, click join, see that the room list is not displaying with an error:
<img width="955" alt="image" src="https://github.com/matrix-org/dendrite/assets/6391042/16db35cf-1e20-4426-bec1-e5ce7da41288">

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->
I don't really see any relevant logs with debug logging turned on. The only odd log line is the following:
```
dendrite-dendrite-1  | time="2023-08-02T06:09:23.430054766Z" level=debug msg="Responding to sync since client gave up or timeout was reached" device_id=n-oLIY9e limit=20 req.id=QN51cSIiiVUW req.method=GET req.path=/_matrix/client/r0/sync since=s211_0_30_0_0_171_174_56_0 timeout=30s user_id="@lauralani:lila.network"
```
I dont know if that's in any way relevant.

Federation seems to work as expected, i can chat without any problems with people on other instances. The federation checker also says all is good.

Thanks in advance.

**Comment by kir68k** [comment]
Same here using 0.13.1, although a private space hosted on my instance doesn't work either. My dendrite binary is compiled from source, but I don't think that should matter.
I can't find anything in my logs as well.

**Comment by kir68k** [comment]
> Though @kir68k since you said no spaces work, still work a check if the MSC is enabled.

I had the MSC disabled, enabling it made spaces on my instance work properly, as well as spaces on remote instances. Thanks.

**Comment by lauralani** [comment]
@swedgwood that seems to have fixed it!  
I can use spaces now with fluffychat, I have to check some more tho :) thanks!

**Comment by swedgwood** [comment]
Glad to know this resolved it for both of you! I'll close this issue now but feel free to reopen it if the issue persists :)
