### ISSUE TITLE
dendrite     | time="2023-08-04T01:25:43.172632547Z" level=panic msg="failed to connect to federation sender db" error="failed to find maximum connections: pq: password authentication failed for user \"dendrite\""

### ISSUE THREAD

**Issue by lazyzyf** [matrix-org/dendrite#3166]
### Background information

- **Dendrite version or git SHA**:
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: yes
- **`go version`**: 
- **Client used (if applicable)**: no

### Description

- **What** is the problem:  dendrite     | time="2023-08-04T01:25:43.172632547Z" level=panic msg="failed to connect to federation sender db" error="failed to find maximum connections: pq: password authentication failed for user \"dendrite\""
- **Who** is affected:
- **How** is this bug manifesting:
- **When** did this first appear:

### Steps to reproduce

- list the steps
- that reproduce the bug
- using hyphens as bullet points

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by S7evinK** [comment]
Error message already states what's wrong.
