### ISSUE TITLE
helm: dendrite helm chart containing versions > 0.12.3 is not published

### ISSUE THREAD

**Issue by Ramblurr** [matrix-org/dendrite#3176]
### Background information

- **Dendrite version or git SHA**: 0.12.3
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: k8s w/ helm
- **`go version`**: n/a
- **Client used (if applicable)**: n/a

### Description

- **What** is the problem: Dendrite 0.13.1 (and 0.13.0) are released, but not available via the helm chart.
- **Who** is affected: Helm chart users
- **How** is this bug manifesting: Helm users cannot upgrade to dendrite > 0.12.3
- **When** did this first appear: Sometime after 0.12.3.

### Steps to reproduce

```
curl https://matrix-org.github.io/dendrite/index.yaml
```

notice:
1. `generated: "2023-05-02T16:29:48.253970683Z"`
2. latest version is `version: 0.12.3`

However if you look at:

https://github.com/matrix-org/dendrite/blob/gh-pages/docs/index.yaml

You can see it was modified only a few weeks ago and has 0.13.1 available.

**Comment by S7evinK** [comment]
No idea why CI didn't run for this, should be published now.
