### ISSUE TITLE
go 1.21 support

### ISSUE THREAD

**Issue by jostreff** [matrix-org/dendrite#3178]
It will be great to made dendrite compatible with go 1.21. 
Some of components like quic-go are already updated by his developers to work with newest go version.

**Comment by S7evinK** [comment]
Dendrite should be able to be built with 1.21.0 now - pineconde/quic-go were updated. (also no issue compiling in Docker using `golang:1.21-alpine`)

**Comment by zhanghua000** [comment]
I think the maintainers may create a new release for people who want to build this package with newer go. It is 0.13.1 in release and it is released on July.
