### ISSUE TITLE
Bridged profile avatars are not redownloaded/reuploaded after purging the media database or deleting the media files

### ISSUE THREAD

**Issue by Xinayder** [matrix-org/dendrite#3179]
### Background information

- **Dendrite version or git SHA**:  v0.13.1
- **SQLite3 or Postgres?**: Postgres 15
- **Running in Docker?**: No
- **`go version`**: 1.20.2
- **Client used (if applicable)**: Element

### Description

- **What** is the problem: Avatars from bridged users are still pointing to old URLs and MXIDs even after deleting the media files and purging the mediaapi database, falling back to the default text initials avatar
- **Who** is affected: Clients
- **How** is this bug manifesting: 
- **When** did this first appear: After deleting the Dendrite media folder on the server

### Steps to reproduce

- Delete the media folder used by Dendrite
- Restart Dendrite
- Avatars will now be missing and Dendrite won't redownload them. (expected, as the media files no longer exist)
- Purge the mediaapi_media_repository table
- Restart Dendrite
- Avatars will still be missing

I run a local Matrix instance using Dendrite and I host a few Mautrix bridges for Instagram, Messenger and WhatsApp. If I understood correctly, the profiles are created locally on the homeserver, but after deleting the media folder, the avatars are not found, which is expected. However, even after deleting the mediaapi table, the avatars are still pointing to files that no longer exist. 

The only way avatars get updated is if the social media profile updates their avatar on the respective social media.

Dendrite should try to redownload the avatars if they point to nonexistent media files.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by S7evinK** [comment]
Closing, as this is not an issue with Dendrite.
There is no "remote" we could re-download the avatars from, nor do we have a way to signal the bridge that we've "lost" the avatar so it can be uploaded again.

For others having the same issue - forcing the bridge to re-upload the avatars seems to work - https://github.com/mautrix/whatsapp/issues/644#issuecomment-1678937057
