### ISSUE TITLE
Do something about invalid well-known names

### ISSUE THREAD

**Issue by Elara6331** [matrix-org/dendrite#3180]
**Description:**

The comments above `well_known_client_name` and `well_known_server_name` in the sample config have `localhost:443` as an example. This leads to people using things like `matrix.example.com:443` as their client/server names. That works for Element, Nheko, and some others, but many clients, including Fluffychat, NeoChat, Fractal, and Cinny require a scheme to be part of the name or they fail to connect. This appears to be based on the following sentence in the matrix spec:

> Parse it as a URL. If it is not a URL, then `FAIL_ERROR`.

which can be found at https://spec.matrix.org/v1.7/client-server-api/#well-known-uri

Either the examples should be changed to `https://localhost:443` and a warning or error logged if the name is invalid, or Dendrite should automatically add the scheme if it doesn't exist.

**Comment by S7evinK** [comment]
https://github.com/matrix-org/dendrite/blob/1c4ec67bb6897859617fea263c658142a694e26d/dendrite-sample.yaml#L68-L73

Looks fine to me?
We could still check for a prefix here and log a warning if it's missing.

**Comment by Elara6331** [comment]
Yeah, that looks fine. Looks like I had an old version of the sample config. That line was changed 3 months ago. I do think it'd be useful to log a warning because it took me a while to figure out what was wrong there.

**Comment by S7evinK** [comment]
We're a bit more radical now than just logging a warning, we're failing to start up if `well_known_client_name` is not formatted in a proper way.
