### ISSUE TITLE
Failed to change notification setting on clients using Dendrite servers

### ISSUE THREAD

**Issue by jahway603** [matrix-org/dendrite#3183]
### Background information

- **Dendrite version or git SHA**: both servers running Dendrite 0.13.1
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: 1 server no & other server unknown
- **`go version`**: go version go1.18.1 linux/amd64
- **Client used (if applicable)**: Element & Schildichat

### Description

- **What** is the problem: In both Matrix clients tested, I can enter the room #pinetime:matrix.org but if I attempt to change the notifications from "All messages" to either "Mentions & Keywords only" or "None", I then receive the following error messages and it will not change notifications in that room. I have also duplicated this if I join a completely new room on either Dendrite server and then attempt the same behaviour.
![Screenshot_20230814-080238](https://github.com/matrix-org/dendrite/assets/64485701/3b90dcca-00d4-4714-bfc5-dc59f913570d)
![Screenshot_20230814-082423](https://github.com/matrix-org/dendrite/assets/64485701/3c52227b-c456-4ef8-9ab3-70021de15982)

- **Who** is affected: Every client using a Dendrite Matrix server
- **How** is this bug manifesting: Unsure, but I have been able to reproduce it. The captcha is broken on dendrite.matrix.org as I attempted earlier to create an account on there to also test this issue.
- **When** did this first appear: I only noticed it last week when I attempted to toggle notifications in #pinetime:matrix.org and then I recieved these error messages.t

### Steps to reproduce

- Be on a client on a Dendrite server. This issue does not occur if a client is using a Synapse server, which I have already tested.
- Join #pinetime:matrix.org
![Screenshot_20230815-115820](https://github.com/matrix-org/dendrite/assets/64485701/6e2dfae7-24d6-4a41-b9f8-0855dfdb09e9)
- Attempt to change the notifications from "All messages" to either "Mentions & Keywords only" or "None".
- Receive either an error message of "push rule ID not found" or "missing actions"
- Then file this issue as I don't know what else to do to fix this

### Describe how what happens differs from what you expected.
- Follow the same Steps to reproduce on a client using a Synapse server and this issue will not occur.

**Comment by bahur142** [comment]
Hello

I can reproduce this case.
Latest Dendrite 0.13.1, Go version go1.20.7

**Comment by jahway603** [comment]
This is still occurring with latest Dendrite 0.13.2 with Go version go1.20.

**Comment by jahway603** [comment]
This is still occurring with latest Dendrite 0.13.3 built using Go version go1.20.8.

**Comment by ryester19** [comment]
Also able to reproduce on 0.13.3
