### ISSUE TITLE
Go minimum requirement bumped to 1.20

### ISSUE THREAD

**Issue by spaetz** [matrix-org/dendrite#3184]
Commit fa6c7ba45671c8fbf13cb7ba456355a04941b535 by @devonh seems to have bumped the minumum go requirement to 1.20. With 1.19 I get
```
../go/pkg/mod/github.com/quic-go/quic-go@v0.37.4/internal/qtls/go_oldversion.go:5:13: cannot use "The version of quic-go you're using can't be built using outdated Go versions. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built using outdated Go...) as int value in variable declaration
note: module requires Go 1.20
```

Given that 1.20 is not available in Debian testing yet (not to talk about stable), is this really intended? If yes, the README needs to be updated which currently states: `To build Dendrite, you will need Go 1.18 or later.`

**Comment by jahway603** [comment]
Created PR https://github.com/matrix-org/dendrite/pull/3194 to resolve this issue. I had an older version of go and have to update it to 1.20 with this latest dendrite release.

**Comment by jahway603** [comment]
@spaetz , Dendrite [Release 0.13.3](https://github.com/matrix-org/dendrite/releases/tag/v0.13.3) now has an updated README to reflect the newer version of go 1.20+, so this issue is now resolved.

**Comment by spaetz** [comment]
Thanks
