### ISSUE TITLE
Hardware and system requirements?

### ISSUE THREAD

**Issue by gwerbin** [matrix-org/dendrite#321]
Hi Matrix.org team!

First of all, THANK YOU for the Matrix protocol and Riot. I'm really excited for Matrix to take off and I'm happy to see you guys are working on a better home server.

So, what will the hardware and system requirements be for Dendrite? As in, RAM, CPU, operating system, etc. And will ARM be supported, or will it be x86-only? I know the project is far from finished, but some early visibility on this would be nice.

It would be great if Dendrite could run on a Raspberry Pi (or Banana Pi, Orange Pi, ODROID, BeagleBone, Pine, etc.) which IMO would really help federation take off since those boards are so cheap and are within the financial and technical reach of casual hobbyists. It would also be nice if it could run on the lowest-tier Linode/DigitalOcean/Vultr instances, for similar reasons.

I should also throw in another major thank-you for even mentioning hardware requirements in the first place in the Synapse docs. It seems a lot of server-side projects neglect this kind of documentation, and it makes it difficult to know what's possible for those of us with limited hardware budgets.

**Comment by t3chguy** [comment]
@gwerbin I am about to test it on a Pi3, the supported platforms are anything that supports kaffka (if you want to use kaffka), postgres and Go can compile to

**Comment by erikjohnston** [comment]
First of all: thanks for the thanks! It's appreciated! 

It would be great if dendrite worked on smaller machines, and certainly we've tried to ensure it'll be easy by being able to run dendrite as a single binary without kafka. However, I don't really have much of an idea what the hardware requirements will end up being at the moment; the primary concern at the moment is to get dendrite up and running without much focus on the end requirements.

Once we've got things into a state where Dendrite is usable I think we should definitely do some tests and document the minimum requirements. Until then lets close this.

@t3chguy would be great if you shared your experiences here once you've had a chance to try it

**Comment by erikjohnston** [comment]
(I've opened #324 to track adding requirements to the readme)

**Comment by t3chguy** [comment]
So a Dendrite thats attempting to federate (and failing) is using about 100% of a single RPi3 core, only about 100-200MB RAM
I could not get it to federate with a big room *yet*

**Comment by t3chguy** [comment]
its settled down now, if I get it to federate I'll graph it

**Comment by beomusxyz** [comment]
> its settled down now, if I get it to federate I'll graph it

any news on the federation?
