### ISSUE TITLE
Failed to fetch helm chart

### ISSUE THREAD

**Issue by mike-pisman** [matrix-org/dendrite#3217]
Hi,

Sorry if I am doing something wrong, but I cannot figure out how to install the helm chart:
```console
$ helm install dendrite dendrite/dendrite -n matrix
Error: INSTALLATION FAILED: failed to fetch https://matrix-org.github.io/dendrite/dendrite-0.13.4.tgz : 404 Not Found
```
The helm repository shows:
```console
$ helm search repo dendrite
NAME             	CHART VERSION	APP VERSION	DESCRIPTION      
dendrite/dendrite	0.13.4       	0.13.3     	Dendrite Matrix Homeserver
```

Versions:
helm version: `v3.12.2` 
GoVersion: `1.20.7`
Kubernetes version : `v1.28.1`

**Comment by mike-pisman** [comment]
Well, until solution is posted, the workaround is to download archive from the release page and install chart from the file:
`helm install -f values.yaml dendrite ./dendrite-0.13.4.tgz`

**Comment by S7evinK** [comment]
Doesn't look like you did something wrong.
Updating the chart-releaser-action seems to also pulled in a "bug". afaict, it will always use `--packages-with-index`, even though it shouldn't. This now resulted in `dendrite-0.13.4.tgz` being pushed to the `gh-pages` branch and the `index.yaml` not pointing to the package in the release.

**Comment by mike-pisman** [comment]
> [helm/chart-releaser-action#163](https://github.com/helm/chart-releaser-action/pull/163) should fix it for the future, I think.

Thank you, hopefully this will resolve the issue with the action. I will keep this one open for now, at least until they pull your changes.

**Comment by wrenix** [comment]
#3220 should solve it in the current state.

**Comment by S7evinK** [comment]
Since https://github.com/helm/chart-releaser-action/pull/172 was merged, closing this, going to update CI on the next release.
