### ISSUE TITLE
deadlock in postgres connection pooling

### ISSUE THREAD

**Issue by bones-was-here** [matrix-org/dendrite#3230]
### Background information

- **Dendrite version or git SHA**: 0.13.3+b341a66
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: no
- **`go version`**: 1.21
- **Client used (if applicable)**: element web

### Description

- **What** is the problem: Dendrite becomes mostly unresponsive while spamming errors
- **Who** is affected: all users and federation
- **How** is this bug manifesting: max allowed db connections are open but all are idle
- **When** did this first appear: when reducing `max_open_conns` on a machine with limited resources

### Steps to reproduce

- reduce the `max_open_conns` below the default, I don't know how low it needs to be but I saw it fail at 36 on a lightly loaded homeserver, not sure if a smaller number causes it to fail sooner
- at some point (might take a few days) it stops responding, element web says [Offline]

I've seen this failure twice recently, don't think it ever happened at the old default of `max_open_conns: 100`.  
It might be able to fail at the current default of 90 if the load is high enough.  

The log had thousands of messages like `level=error msg="userAPI.QueryAccessToken failed" error="context canceled"`  
and `level=info msg="Error authenticating request" error="context canceled"`  
and none of the usual messages about useful work happening.  
Dendrite had exactly the max of 36 connections to postgres open, and all were idle according to postgres.  
CPU load was very low.  I believe the workload on the homeserver was minimal when it failed, 36 maximum should have been far more postgres workers than it could have needed.  

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by S7evinK** [comment]
iirc, this didn't happen again after some recent changes, right?

**Comment by bones-was-here** [comment]
Yeah I don't seem to be able to reproduce it any more, Dendrite been reliable since 699f5ca8c1f73ff7e4b70f0f9273ffcb1c195cdc or maybe ee73a90aea8349e2695ce555ac868bbf45c11d02 with settings that previously would fail and require a restart.
