### ISSUE TITLE
nats  2.10 upgrade

### ISSUE THREAD

**Issue by gedw99** [matrix-org/dendrite#3246]
There's new features in NATS 2.10 that make it now possible to even manage the distribution of the client application instances between those partitions (exactly like a Kafka consumer group).

You can do deterministic distribution of the messages in a stream over a number of consuming client application using the subject mapping functionality, which can now be part of the stream definition itself in 2.10

**Comment by S7evinK** [comment]
Do you have a link to said feature? Unable to find it.
