### ISSUE TITLE
Helm Chart PVC does not allow for multiple replicas or configuration changes

### ISSUE THREAD

**Issue by metalsp0rk** [matrix-org/dendrite#3258]
### Background information

- **Dendrite version or git SHA**: 317b101
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: Kubernetes
- **`go version`**: 
- **Client used (if applicable)**: N/A

### Description

- **What** is the problem: The PVC configuration for the Helm chart dendrite deployment is set to ReadWriteOnce, which prevents multiple replicas to be spun up, and additionally prevents the create -> terminate lifecycle pattern when upgrading.
- **Who** is affected: Anyone using the Helm chart.
- **How** is this bug manifesting: When attempting to upgrade the server or change configuration
- **When** did this first appear: After making a configuration change

### Steps to reproduce

- deploy the Dendrite Helm chart
- make a configuration change
- the kubernetes control plane will then attempt to deploy a second pod, which gets stuck in containerCreating, causing a bad state, that requires the uninstallation of the helm chart and manual clean up of resources on the cluster.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org, @s7evink:matrix.org or @devonh:one.ems.host
with a link to the respective Github issue, thanks!
-->
I would expect multiple pods to be able to be launched simultaneously, but currently the PVC configuration prevents this.  
I would be happy to submit a PR to address the change in the helm chart if a change is welcomed in this area.

**Comment by wrenix** [comment]
You chould change the updateStrategy to `type: Recreate` to solve your problem on change config ...

An setup to change the PVC to ReadWriteMany is possible (but no good idea like to change to StatefulSet with VolumneTemplate).
dendrite does not support to be run multiple times, see: #2975
