### ISSUE TITLE
Unable to Connect Dendrite Homeserver in Element 

### ISSUE THREAD

**Issue by SmolPatches** [matrix-org/dendrite#3264]
### Background information

- **Dendrite@7863a40**:
- **Postgres DB**
- **Running in Docker**:
- **`go version` - whatever is used in default config**:
- **Client used (if applicable)**:
Local Element Client on MacOSX

### Description
- **What** : *Element cannot find my local home server*:
- **Who**: I hosted one on *Gentoo homelab* and one on my *local machine(MacOSX)*, neither works.
- **How** run docker yaml file and try to connect in Element client.
- **When** did this first appear: I noticed it today.

### Steps to reproduce

- Docker steps to [install](https://matrix-org.github.io/dendrite/installation/docker/install) Dendrite,
```
mkdir -p ./config
docker run --rm --entrypoint="/usr/bin/generate-keys" \
  -v $(pwd)/config:/mnt \
  matrixdotorg/dendrite-monolith:latest \
  -private-key /mnt/matrix_key.pem
```
```
mkdir -p ./config
docker run --rm --entrypoint="/bin/sh" \
  -v $(pwd)/config:/mnt \
  matrixdotorg/dendrite-monolith:latest \
  -c "/usr/bin/generate-config \
    -dir /var/dendrite/ \
    -db postgres://dendrite:itsasecret@postgres/dendrite?sslmode=disable \
    -server YourDomainHere > /mnt/dendrite.yaml"
```
``` wget https://github.com/matrix-org/dendrite/blob/main/build/docker/docker-compose.yml ```
```docker-compose -f docker-compose.yml up``` on Mac 
```docker compose up ``` on Gentoo
- Open Mac Element Client
- Choose a home server
 - Typing in localhost:8008 or 127.0.0.1:8008 or PRIVATE_IP:8008
 Leads to, ```Homeserver URL does not appear to be a valid matrix homeserver```
 **Note**, since I am running this locally, I left the domain as the preset YourDomainHere.
<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org, @s7evink:matrix.org or @devonh:one.ems.host
with a link to the respective Github issue, thanks!
-->

**Comment by S7evinK** [comment]
Did you specify the protocol to use? e.g. `http://localhost:8008`? Element Web doesn't add that automatically when entering the address manually.

**Comment by SmolPatches** [comment]
> Did you specify the protocol to use? e.g. `http://localhost:8008`? Element Web doesn't add that automatically when entering the address manually.

Yep it works, I feel silly for not trying that lol.

**Comment by S7evinK** [comment]
Glad it works now!
