### ISSUE TITLE
General Dendrite relationship to Pinecone?

### ISSUE THREAD

**Issue by lonnietc** [matrix-org/dendrite#3265]
Hello,

I am just now exploring the Matrix ecosystem and understand that Pinecone is the routing process that the network uses, but I am unclear as to what its relationship is to Dendrite.

Is Dendrite the actual P2P node server that uses Pinecone?

I have read something that Dendrite is the Golang new version to Synapse which I think was in Rust, but also am trying to get a feel for how all of these come together to make the P2P Matrix system.

Any clarification would be greatly appreciated.
Thanks

**Comment by kegsay** [comment]
Pinecone is an overlay network and has no dependency on Matrix. Dendrite uses Pinecone to support P2P Matrix.
