### ISSUE TITLE
Auto accept invites

### ISSUE THREAD

**Issue by recht** [matrix-org/dendrite#3268]
It would be nice to be able to configure invite auto accept. Synapse has a module for this (https://github.com/matrix-org/synapse-auto-accept-invite), something similar would be very useful in Dendrite.

**Comment by jjj333-p** [comment]
what would this be used for? most sdks have auto accept abilities. autojoin is rather dangerous to implement randomly as well.

**Comment by S7evinK** [comment]
Given this is a module for Synapse and not in the spec - closing this.
