### ISSUE TITLE
Can't federate with matrix.org, can federate with everyone else

### ISSUE THREAD

**Issue by TheStranjer** [matrix-org/dendrite#3279]
### Background information

- **Dendrite version or git SHA**: `fd11e65a9d113839177f9f7a32af328a0292b195`
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: No
- **go version**: `go version go1.19.8 linux/amd64`
- **Client used (if applicable)**:

### Description

- **What** is the problem: Will federate with every instance except `matrix.org`, which insists the requests sent use an invalid signature:
```
122023-12-04 01:05:48,310 - synapse.federation.transport.server._base - 312 - WARNING - PUT-830024a3de2d9830-SJC - authenticate_request failed: 401: Invalid signature for server [iddqd.chat](http://iddqd.chat/) with key ed25519:4nSjL2: Unable to verify signature for [iddqd.chat](http://iddqd.chat/): <class 'nacl.exceptions.BadSignatureError'> Signature was forged or corrupt
2023-12-04 01:05:48,310 - synapse.http.server - 124 - INFO - PUT-830024a3de2d9830-SJC - <XForwardedForRequest at 0x7ffb382a0320 method='PUT' uri='/_matrix/federation/v1/send/1701607934603-6' clientproto='HTTP/1.1' site='15102'> SynapseError: 401 - Invalid signature for server [iddqd.chat](http://iddqd.chat/) with key ed25519:4nSjL2: Unable to verify signature for [iddqd.chat](http://iddqd.chat/): <class 'nacl.exceptions.BadSignatureError'> Signature was forged or corrupt
```
But other instances don't have this problem.

- **Who** is affected: `matrix.org`
- **How** is this bug manifesting: Messages from `iddqd.chat` do not federate to `matrix.org`, but do federate elsewhere
- **When** did this first appear: ~1wk ago

### Steps to reproduce
1. Send message on `iddqd.chat`
2. Verify that it arrives elsewhere like `bolha.chat` and on `matrix.org`
3. Notice that it arrives at the former but not the latter

**Comment by viviicat** [comment]
might be related to these upstream patches?
https://github.com/matrix-org/gomatrixserverlib/commit/2aa58908de15bf46cca37a3a89aed5c4bfd32611
https://github.com/matrix-org/gomatrixserverlib/commit/41497b7563eb4a7416f72427580aa786ef768cfe

**Comment by TheStranjer** [comment]
Yup. As far as I'm aware, this has been fixed. Thanks for your time.
