### ISSUE TITLE
federation issues and "This server is using an older version of Matrix. Upgrade to Matrix v1.5 to use Element without errors."

### ISSUE THREAD

**Issue by r3k2** [matrix-org/dendrite#3304]
Updated to last stable git version of dendrite mid december
version: v0. 13.15 https://github.com/matrix-org/dendrite/releases/tag/v0.13.5

People is reporting they can't see msgs from matrix.org or even other homeservers (this was working last month just fine ) 
since all the report from my users, at least 6 of them for the last 2 weeks I decided to log using element ( I use iamb and gomuks )
and the first weird thing I notice is :
```
This server is using an older version of Matrix. Upgrade to Matrix v1.5 to use Element without errors.
```
I have checked postgresql I see no errors
I need to enable debug for dendrite since the regular stdout I see no errors neither
posting this now so I do not forget, since I work a lot and always push things, and then I end up forgetting and my users keep asking me to fix this.

- The server does use ipv6 and ipv4
- latest git stable version https://github.com/matrix-org/dendrite/releases/tag/v0.13.5 
- everyone in our homeserver can talk to each other just fine, sometimes I see msg's from other homeservers but for example in the #rust channel that is super active the last one I got was from Sunday, I find that very weird...

Hopefully this is a known issue and has a fast fix/workaround.
let me know what other info people will need when I enable this weekend debug ( I have a lot of work now ) I will post the results as well.
is possible we are block? how can we check that? 

[edit] msgs work from our homeserver to matrix.org is the other way around, I had family members write to me and friends on matrix.org and I never got their msg's since Sunday. I saw them because I used my matrix.org test account and can see matrix.hispagatos.org msgs on matrix.org but not the other way around :( 
[edit2] this is what I get to stdout
```
[root@matrix ~]# journalctl -fu dendrite
Jan 16 19:41:05 matrix systemd[1]: Started Dendrite (Matrix Homeserver).
Jan 16 20:38:45 matrix dendrite[437]: 2024/01/16 20:38:45 Transport: unhandled response frame type *http.http2UnknownFrame
```
thats about it

**Comment by idanoo** [comment]
![image](https://github.com/matrix-org/dendrite/assets/9691551/0a144578-6ae1-4749-b7d1-3ce35d529114)

Also got this opening Element after upgrading client today.

**Comment by ekbaker7** [comment]
Having the same issue using the docker version of dendrite, and taking the image down and restarting to get latest actually made my instance completely unreachable by Element.

**Comment by Mic92** [comment]
How can I check what Matrix version a server supports?

**Comment by Mic92** [comment]
This got introduced in

```
Element version: 1.11.54
Crypto version: Olm 3.2.15
```

Element 1.11.53 is still fine.

**Comment by tommie** [comment]
> How can I check what Matrix version a server supports?

And the Dendrite source agrees: https://github.com/matrix-org/dendrite/blob/dae1ef2e46b332d67f1729c3d1a2ffe3910aa3aa/clientapi/routing/routing.go#L149

Only up to v1.2 announced.

**Comment by S7evinK** [comment]
The Matrix 1.5 thingy was a [change](https://github.com/matrix-org/matrix-js-sdk/pull/3970) in the matrix-js-sdk, and unfortunately totally went past us and now we are here.

As for the federation issue, are you able to update to latest main? This would contain #3288 which likely fixes a few issues with incoming events.

**Comment by tommie** [comment]
Related context: conduit-rs announces up to v1.4, so that'll also trigger the warning: https://gitlab.com/famedly/conduit/-/blob/next/src/api/client_server/unversioned.rs?ref_type=heads#L28

Suggesting Synapse is the only(?) server that is not causing warnings in Element right now.

**Comment by r3k2** [comment]
@S7evinK I just updated to main, and now I can't even see msg's from people in our own homeserver? :cry:  do I need to delete jetstream or something? maybe is trying to work on all the late msg's and getting stuck?

**Comment by r3k2** [comment]
@S7evinK to late, I was getting spam like 200 msg a sec from that same msg regarding user real-changeling so had to stop and do how we used to do when we first added jetstream, and deleted the folder ( we do not mind if we lose old msg's) now seems like the spam has stop, also have removed the MSC for the config and that is gone... local msg's are working good again, not sure about federation so far is not, going to let it sit for 1-2 hours. Regarding that msg about 8m for jetstream how can we fix/improve that?

**Comment by S7evinK** [comment]
Unsure about the 8MB warning, we used to pump quite a bit of data (iirc, 20MB+) through Kafka before switching to JetStream, not sure how this looks at the moment. But this shouldn't be a problem.

And if matrix.org is receiving your messages, I don't think your server is blocked or anything.

**Comment by TruncatedDinoSour** [comment]
same here, https://matrix.ari.lt/
looking forward to the fix

**Comment by r3k2** [comment]
@S7evinK I just check on the federation test thing, as domain hispagatos.org as usuall and says is having issues... we have not changed anything in our side in years regarding this, did we change the way we point a domain to a home server? our homeserver is matrix.hispagatos.org but our matrix domain is hispagatos.org 
https://matrix.hispagatos.org/_matrix/federation/v1/version  <--- this works but..
https://federationtester.matrix.org/#hispagatos.org   this has a warning and a red issue ... like is not changing it to matrix.hispagatos.org like it used to ? I remember we used to have it the very old way with cname 
```	
_matrix._tcp.hispagatos.org
	SRV 	
10 0 443 matrix.hispagatos.org
	1h
```
and also on the nginx server.. 
going to check the wiki see if I still have it configure right. Posting in case something changed regarding this.

**Comment by S7evinK** [comment]
Right, so: both well-known files should be served on https://hispagatos.org instead of https://matrix.hispagatos.org

If you **need** to use SRV records, hispagatos.org needs a valid TLS certificate. (this is not recommended, though).

So my course of action would be:
- Move the `.well-known` files to be served at
  - https://hispagatos.org/.well-known/matrix/client
  - https://hispagatos.org/.well-known/matrix/server
- Check the federation tester
  -  if `server name/.well-known result contains explicit port number: no SRV lookup done` in the results, you're good for the next step
- Remove the SRV record

**Comment by r3k2** [comment]
ok wait this rings a bell know! @S7evinK  so hispagatos.org our blog where I also have those .well-known was down because of a DDOS attack for the whole week last week... and now they have some broken git pages ..... this now does make sense because... is the only thing really that has happened between last week and this week since it was working 100% fine.
let me see what I can do regarding sr.ht

**Comment by S7evinK** [comment]
Going to close this here, as there is currently nothing we can do - it is already reported to the Element Web team.
In the mean time, you can use https://riots.im and specifically https://riots.im/1.11.53/ to connect to Dendrite.

**Comment by 65a** [comment]
This appears to be fixed in element nightly now

**Comment by tommie** [comment]
Nice. Here's the "partial revert": https://github.com/matrix-org/matrix-js-sdk/pull/4014
