### ISSUE TITLE
account reactivation

### ISSUE THREAD

**Issue by TruncatedDinoSour** [matrix-org/dendrite#3309]
**Description:**

synapse has account reactivation, but i don't think dendrite has that, would be a useful feature, esp rn as i'm sorta in need of it xD

**Comment by spaetz** [comment]
You can poke the user_account table and reactivate directly there....

**Comment by TruncatedDinoSour** [comment]
> You can poke the user_account table and reactivate directly there....

yeah but thts very uh
hacky

**Comment by jjj333-p** [comment]
i mean deactivation only exists by either poking the db or logging in as the user and using the user endpoint, so like of course it wont exist. 

also imo it shouldnt be added but thats just my personal take

**Comment by TruncatedDinoSour** [comment]
> i mean deactivation only exists by either poking the db or logging in as the user and using the user endpoint, so like of course it wont exist.
> 
> also imo it shouldnt be added but thats just my personal take

synapse has it and i think itd come in handy when u need it
https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html

**Comment by S7evinK** [comment]
Given `/deactivate` doesn't just set a flag in Dendrite but also removes the user from every room they were in, I'm not sure this is something we currently want to implement.
