### ISSUE TITLE
How to use email or mobile phone number to register and login?

### ISSUE THREAD

**Issue by zoujiaqing** [matrix-org/dendrite#3318]
Email and phone number are the most common registration and login methods.
How to get Dendrite to support them?

**Comment by jjj333-p** [comment]
Currently not supported. 

Also reminder that this isnt a support forum, you'll likely get better help in #dendrite:matrix.org

**Comment by TruncatedDinoSour** [comment]
> Currently not supported.

but honestly it should be a thing, email is easy, but for phone maybe you could use like twillio api

**Comment by niebloomj** [comment]
I think we can close this issue

**Comment by jjj333-p** [comment]
or add a [feature request] tag or something

**Comment by S7evinK** [comment]
Dupe of https://github.com/matrix-org/dendrite/issues/3260 (probably some others, just doing some cleanup)
And well, currently not implemented.
