### ISSUE TITLE
Display Name of newly created user is replaced with the first person tries to communicate with them.

### ISSUE THREAD

**Issue by lil5** [matrix-org/dendrite#3324]
### Background information

- **Dendrite version or git SHA**:
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: Yes
- **`go version`**: 
- **Client used (if applicable)**:

### Description

- **What** is the problem:
Display Name of newly created user is replaced with the first person tries to communicate with them.
- **Who** is affected:
Any new user this is generated from the cmd
On top of that this new user will be set as admin, even if the `-admin` flag is _not_ used
- **How** is this bug manifesting:
The shared_secret_registration is shown as a device. 
- **When** did this first appear:
After running `/_synapse/admin/v1/register` with a loggedin access token

https://github.com/matrix-org/dendrite/assets/17646836/aa1575d9-20db-4f16-b345-a35aa5037be4

### Steps to reproduce

1. Create a first user 1 using the cli register command with the username `override`
2. Login user 1 in a client like Element
3. Create a second user 2 using the cli register command with the username `user`
4. With user 1 in Element chat with user 2
5. Before sending a chat the displayname of user 2 is `user`
6. Send a message to user 2
7. The displayname of user 2 changes to `override` _This should not happen_, user 2 is also suddenly an admin.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org, @s7evink:matrix.org or @devonh:one.ems.host
with a link to the respective Github issue, thanks!
-->

**Comment by S7evinK** [comment]
I'm assuming you mean "room admin", right? That's the correct behavior when creating DMs.

**Comment by lil5** [comment]
Ah right, the wording is naturally confusing, but I guess that more an issue to take up with the client devs, nevertheless 3326 will fix the main issue.
