### ISSUE TITLE
Option to disable encryption for local DMs

### ISSUE THREAD

**Issue by alex9434** [matrix-org/dendrite#3351]
**Description:**

I suggest to enable a setting in dendrite.yaml to have all DMs between users on the local server unencrypted by default. DMs to users on other servers should be encrypted by default.

Rationale: Chats between local users are only stored on the local server and therefore can be protected on the server level. Encryption adds unnecessary overhead (e.g. using multiple devices) and also makes it impossible to audit/document chats for companies.

**Comment by alex9434** [comment]
But Dendrite would be the best to understand whether this is a DM between two local users. The client does not know whether the user is local or via federation. To be clear, my proposal would not be to show in the UI the chat is encrypted while in reality it is not. Instead I suggest a configuration setting (e.g. overwrite encryption request for local DMs) that converts a request from a client to create an unencrypted DM if both users are local on the server. The client would then show that the DM is unencrypted.

**Comment by 0x00cl** [comment]
This doesn't make much sense. End-to-end encryption makes sure only the sender and the reciever can write/read messages. So not even your homeserver should read/modify your messages. That isn't unnecessary overhead.

Also from my understanding this is not a server related option.

**Comment by S7evinK** [comment]
Sorry, but this is something we'll not implement.
