### ISSUE TITLE
Support Go versions for longer

### ISSUE THREAD

**Issue by Dreamsorcerer** [matrix-org/dendrite#3367]
Could we maintain support for older versions of Go for a little longer in future?
At a minimum, I think Dendrite should run on the version included in the latest Debian stable and Ubuntu LTS releases (which today, would mean 1.19+).

**Comment by S7evinK** [comment]
imo, we shouldn't maintain "old" Go versions as long as possible.

Go is easy to install manually. Even my Raspberry Pi Zero is on 1.22.2 now, by manually installing it (without using too much shell witchcraft). (Distribution had 1.17.6 in the repos..)

Bumping go to 1.21 seems sensible to me.

**Comment by Dreamsorcerer** [comment]
We're only talking about last 3 years of versions, similar that anybody would expect for a Python application.

However, if I understand correctly, Go is only needed to build the binaries, not to run them. In which case, it would make sense to just build them locally on a newer release and them copy the results to the server. If I'm right, then I think it's fine to close this (though maybe clarify that in the install instructions).

**Comment by S7evinK** [comment]
That's correct, you can compile Dendrite on a different machine and copy it over to the server.
Alternatively, you can manually install Go in any version as described [here](https://go.dev/doc/install)
