### ISSUE TITLE
Helm chart not being updated

### ISSUE THREAD

**Issue by pat-s** [matrix-org/dendrite#3392]
Latest release on https://matrix-org.github.io/dendrite/index.yaml is 0.13.5 whereas the latest `version` in https://github.com/matrix-org/dendrite/blob/main/helm/dendrite/README.md is 0.14.0

**Comment by aleksasiriski** [comment]
+1 for this

**Comment by S7evinK** [comment]
This should now be solved (again). https://github.com/matrix-org/dendrite/pull/3429
Thanks @Arkaniad !
