### ISSUE TITLE
Is Dendrite being actively developed? 

### ISSUE THREAD

**Issue by K1D77A** [matrix-org/dendrite#3413]
Hi, just a quick question.
Is Dendrite still being actively developed? 

Thanks.

**Comment by S7evinK** [comment]
Development is currently best effort, since Dendrite is in maintenance mode. This may change in the (hopefully) near future.

Other than that, if I find the time and will to work on it, I'll do.

**Comment by 2Belette** [comment]
Thanks @S7evinK , would you be able to elaborate a little bit more on that ? I may have missed an important news so, I always had thought that Dendrite would be the future and replace eventually Matrix.. many thanks

**Comment by S7evinK** [comment]
https://matrix.org/blog/2023/12/25/the-matrix-holiday-update-2023/

> The other major change is that we’ve had no choice but pause development on the majority of the core team’s next-generation Matrix projects. We had high hopes of being able to secure dedicated funding for [Third Room](https://matrix.org/blog/2023/12/25/the-matrix-holiday-update-2023/thirdroom.io) (especially after the awesome [Tech Preview 2: Creator Update](https://matrix.org/blog/2023/06/07/introducing-third-room-tp-2-the-creator-update/) in June), but the interested parties did not come through, and the team has now disbanded. Meanwhile, P2P Matrix and Low Bandwidth Matrix is on hiatus until there’s dedicated funding - and Account Portability work is also temporarily paused in favour of commercial Element work, despite the fantastic progress made recently with Pseudo IDs ([MSC4014](https://github.com/matrix-org/matrix-spec-proposals/pull/4014)) and Cryptographic identifiers ([MSC4080](https://github.com/matrix-org/matrix-spec-proposals/pull/4080)). Given P2P Matrix and Account Portability were the main projects driving Dendrite development recently, this may also cause a slow-down in Dendrite development, although Dendrite itself will still be maintained.
