### ISSUE TITLE
Federation authenticated media endpoints have invalid multipart response

### ISSUE THREAD

**Issue by Benjamin-L** [matrix-org/dendrite#3414]
### Background information

- **Dendrite version or git SHA**: `0.13.7+7a4ef24`
- **SQLite3 or Postgres?**: unknown (not my server)
- **Running in Docker?**: unknown
- **`go version`**: unknown
- **Client used (if applicable)**: Grapevine `b4fecbc51719a33d09be1e76d55ae0eec11fb71a` (over federation API)

### Description

The [multipart spec](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html) states that every encapsulation boundary in the body should be preceded by a CRLF. Instead, dendrite's response to the federation auth media download endpoint has the `--` of the first boundary starting directly at the beginning of the body, with no CRLF.

Ruma expects a preceding CRLF [here](https://github.com/ruma/ruma/blob/14d7415f0d80aadf425c2384c0f348d1c03527c8/crates/ruma-federation-api/src/authenticated_media.rs#L172) when parsing the response. As a result, homeserver implementations using ruma are unable to fetch media from dendrite servers over the authed media endpoints. This affects grapevine, and likely also affects conduwuit although I have not tested it.

<details>
<summary>relevant text from RFC 1341</summary>

> Note that the encapsulation boundary must occur at the beginning of a line, i.e., following a CRLF, and that that initial CRLF is considered to be part of the encapsulation boundary rather than part of the preceding part. The boundary must be followed immediately either by another CRLF and the header fields for the next part, or by two CRLFs, in which case there are no header fields for the next part (and it is therefore assumed to be of Content-Type text/plain).

> NOTE: The CRLF preceding the encapsulation line is considered part of the boundary so that it is possible to have a part that does not end with a CRLF (line break). Body parts that must be considered to end with line breaks, therefore, should have two CRLFs preceding the encapsulation line, the first of which is part of the preceding body part, and the second of which is part of the encapsulation boundary.

> The requirement that the encapsulation boundary begins with a CRLF implies that the body of a multipart entity must itself begin with a CRLF before the first encapsulation line -- that is, if the "preamble" area is not used, the entity headers must be followed by TWO CRLFs. This is indeed how such entities should be composed. A tolerant mail reading program, however, may interpret a body of type multipart that begins with an encapsulation line NOT initiated by a CRLF as also being an encapsulation boundary, but a compliant mail sending program must not generate such entities. 
</details>

### Steps to reproduce

 - issue a `/_matrix/federation/v1/media/download/:mediaid` request to a dendrite server
 - inspect the response body. Every multipart boundary should start with a CRLF. Instead, the first boundary begins immediately.

**Comment by CobaltCause** [comment]
Seems like this is actually a bug in Go's standard library. It actually used to include a leading CRLF but was changed ~13 years ago as a workaround for a bug in a different program: <https://codereview.appspot.com/4635063#msg4>.

**Comment by S7evinK** [comment]
This might be a problem in Ruma, the [Spec](https://spec.matrix.org/v1.11/server-server-api/#get_matrixfederationv1mediadownloadmediaid) wants RFC 2046 for the boundary. (Yea, the MSC linked to RFC 1341, which may had different "rules" for boundaries)

The [multipart package](https://pkg.go.dev/mime/multipart), which Dendrite uses, implements RFC 2046.

**Comment by Benjamin-L** [comment]
@S7evinK Good catch! RFC 2046 seems to have similar text stating that boundaries must be preceded by a CRLF though. On page 19:

> The boundary delimiter MUST occur at the beginning of a line, i.e.,
> following a CRLF, and the initial CRLF is considered to be attached
> to the boundary delimiter line rather than part of the preceding
> part.  The boundary may be followed by zero or more characters of
> linear whitespace. It is then terminated by either another CRLF and
> the header fields for the next part, or by two CRLFs, in which case
> there are no header fields for the next part.  If no Content-Type
> field is present it is assumed to be "message/rfc822" in a
> "multipart/digest" and "text/plain" otherwise.
> 
> NOTE:  The CRLF preceding the boundary delimiter line is conceptually
> attached to the boundary so that it is possible to have a part that
> does not end with a CRLF (line  break).  Body parts that must be
> considered to end with line breaks, therefore, must have two CRLFs
> preceding the boundary delimiter line, the first of which is part of
> the preceding body part, and the second of which is part of the
> encapsulation boundary.

I haven't read the whole thing in detail, it's definitely possible that I'm missing something. It would be at least somewhat surprising this was a bug sitting in the go standard library for 13 years without anybody else noticing it.

**Comment by Benjamin-L** [comment]
Oh fun. I agree with your reading that the BNF clearly states the first CRLF is not required unless there is a preamble. That seems to conflict with the earlier text in the RFC to me, but either way the next step is to change ruma to be more permissive.
