### ISSUE TITLE
Authenticated media requests don't seem to work at all?

### ISSUE THREAD

**Issue by Lunaphied** [matrix-org/dendrite#3420]
### Background information

- **Dendrite version or git SHA**: 0.13.7
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**:  No
- **`go version`**: Irrelevant/unknown (using as packaged from Nixpkgs)
- **Client used (if applicable)**: Cinny/Element

### Description

- **What** is the problem: Media requests to servers that only support authenticated media requests (like matrix.org itself) always 404
- **Who** is affected: Everyone using Dendrite
- **How** is this bug manifesting: Log messages about failed media requests
- **When** did this first appear: Recently, likely when matrix.org disabled unauthenticated fetch

### Steps to reproduce

- Start an encrypted DM with someone from Matrix.org
- Have them send an image
- Observe error

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org, @s7evink:matrix.org or @devonh:one.ems.host
with a link to the respective Github issue, thanks!
-->
```log
Sep 10 18:08:41 homura dendrite[14339]: time="2024-09-11T00:08:41.576265018Z" level=error msg="r.fetchRemoteFileAndStoreMetadata: failed to fetch remote file" MediaID=redacted Origin=matrix.org error="File with media ID \"redacted\" does not exist on matrix.org" req.id=KiQCE521bkpb req.method=GET req.path=/_matrix/media/v3/download/matrix.org/redacted
```
all redacteds are the same ID.

**Comment by viviicat** [comment]
Looking at the history, this might be because they have not made a release with that functionality yet? I believe it was added in August in #3397 

Tomorrow I'm going to try with a more recent build to see if that resolves it.

**Comment by viviicat** [comment]
Yeah, running from a main build resolved my issue.

**Comment by S7evinK** [comment]
Also keep in mind that you need a client that supports authed media through the unstable feature announced in `/versions`, as we do not have support for Matrix v1.11 yet.

**Comment by McSinyx** [comment]
What clients would work then?

**Comment by S7evinK** [comment]
AFAIK, FluffyChat and nheko either use the unstable feature, or just try the new endpoints and use them.

**Comment by Lunaphied** [comment]
> Looking at the history, this might be because they have not made a release with that functionality yet? I believe it was added in August in #3397

Ah looks like my quick peruse and search of the sources and PRs missed this, thank you! Manually bumping my package to use the latest sources seems to address the issue so the solution for this should be as simple as cutting a new release of dendrite

**Comment by S7evinK** [comment]
#3431 was merged, so hopefully some/all of this was fixed, if not, feel free to re-open.
