### ISSUE TITLE
Need a way to enable debug logging

### ISSUE THREAD

**Issue by richvdh** [matrix-org/dendrite#346]
We could do with a way of configuring dendrite to enable debug logs. Presumably via an env var, like LOG_DIR?

While we're at it, perhaps we could get rid of the separate error/warn/info logs. I'm not a fan of having three logfiles to check.

**Comment by anoadragon453** [comment]
The way I've seen it done in other projects is you'll have different levels of logging, where each has its own place in a hierarchy, and in a config file you can specify which level and above that you'd like printed to the logs.

Then each line of logging would be prefixed with its level. Developers may want maximum logging, whereas users may only want errors and above.

An example of levels from [matrix-appservice-discord](https://github.com/Half-Shot/matrix-appservice-discord/blob/7a1c27a3f47962b46468190fabbf8ab09e9ef5a2/config/config.sample.yaml#L14):

```
logging:
   level: "warn" #silly, verbose, info, http, warn, error
```

**Comment by erikjohnston** [comment]
As a tangential thought: it would be nice to figure out how we can have different [logrus hooks](https://github.com/sirupsen/logrus#hooks), e.g. I was playing with putting dendrite logs into logstash. Right now I need to edit the code.

**Comment by ElyKar** [comment]
My thoughts on this are the same as anoa: the logging level is set in a config file, individual lines are prefixed by the level.
In the case of dendrite, the possibilities should match logrus's levels: debug, info, warn, error, fatal and panic.

Breaking this down a little bit (though there's not much) :
 - Add a logging.level to the configuration
 - Also, change the configuration of the directory from the LOG_DIR env var to a logging.path parameter (mixing two ways of configuring logs seems off, and this is the only env var required for configuring dendrite) 
- Modify the library github.com/matrix-org/dugong to accomodate the changes

For supporting various logrus hooks, I have no idea how to do it apart from implementing them one by one. Though, a few of them may be interesting to have (journald, syslog, Logstash, ...).

**Comment by Kegsay** [comment]
I agree with @deedubs on this. We don't have any real users on Dendrite yet, so it's easy to remove, and I really don't want to be supporting log stuff. Spin it up in docker and export stdout to a central logging location.

The ability to configure logging landed in https://github.com/matrix-org/dendrite/pull/379 - this issue is no longer relevant.
