### ISSUE TITLE
Application Services

### ISSUE THREAD

**Issue by turt2live** [matrix-org/dendrite#358]
[![bounty](https://api.bountysource.com/badge/issue?issue_id=52019596)](https://www.bountysource.com/issues/52019596-application-services)

Currently this is under phase 4 for dendrite, however I'd certainly like to see it in an earlier phase. This includes:
* Loading application service configurations
* The application service API
* Supporting application services on the various client endpoints

An incredibly nice to have feature of this would also be documentation on how this API works.

**Comment by anoadragon453** [comment]
To break the tasks down a bit further:

* Allow application services to register users in their namepsaces defined in the config files.
* Look at each event and figure out if it should be sent to the AS, if so do that (this requires batching requests up).
* Make the APIs support the way that AS's interact with the API, which is use a master access token and specify a `user_id=` param.

[Application Services API docs](https://matrix.org/docs/spec/application_service/unstable.html)

**Comment by anoadragon453** [comment]
In terms of users, Application Services specifically:

* Register for a namespace which is a regex pattern which their user's usernames matches. They can say whether they have exclusive rights to their namespace or not.
* They can register a password-less user as long as the username lies within their namespace.
* They can then call any API endpoint masquerading as that user with `/path?access_token=$token&user_id=$userid`.

**Comment by turt2live** [comment]
Just for tracking purposes, here's the PR progress so far:
* https://github.com/matrix-org/dendrite/pull/377 - Parse and load the config files
* https://github.com/matrix-org/dendrite/pull/390 - Appservice users can be registered
* https://github.com/matrix-org/dendrite/pull/392 - Fix a bug related to registrations on homeservers with no appservices

If I'm not mistaken, what's left to do is:
* [ ] Support the `?user_id` query parameter for appservice access tokens
* [ ] Sending events to the appservice (`/transactions` route)
* [ ] Sending room alias query requests to the appservice
* [ ] Sending user query requests to the appservice
* [ ] 3pid support (although for the purposes of the bounty, I'm okay with ignoring this part)
* [ ] Testing the whole thing to see if it works :) 

Thanks for your amazing progress so far on this @anoadragon453! It's looking pretty good, and I'm really excited to see it implemented.

**Comment by turt2live** [comment]
More for tracking purposes:
* Milestone: https://github.com/matrix-org/dendrite/milestone/3
* Send events: https://github.com/matrix-org/dendrite/issues/450 (PR: https://github.com/matrix-org/dendrite/pull/477)
* https://github.com/matrix-org/dendrite/issues/452 - GET /rooms/alias
* https://github.com/matrix-org/dendrite/issues/453 - GET /users/userId
* https://github.com/matrix-org/dendrite/issues/456 - Timestamp massaging
* https://github.com/matrix-org/dendrite/issues/457 - GET /app/r0/user?uri=encoded (I think this is 3pid related?)
* https://github.com/matrix-org/dendrite/issues/460 - GET /app/r0/alias?uri=encoded (I think this is 3pid related?)
* https://github.com/matrix-org/dendrite/issues/451 - Validation on exclusive rooms
* https://github.com/matrix-org/dendrite/issues/468 - Validation to ensure the appservice is actually in the room
* https://github.com/matrix-org/dendrite/issues/469 - Identity masquerading
* https://github.com/matrix-org/dendrite/issues/471 - Misc additional registration options

**Comment by Half-Shot** [comment]
Modulo #468 being verified as fixed, I don't know if this issue is very useful going forwards. All the basic AS features have landed and we can track the thirdparty endpoints / misc things as issues.

Any votes for keeping this open?

**Comment by turt2live** [comment]
yea, I think this is done enough. Is there someone who is able to accept the bounty or should I get it moved to another issue? (not sure how many people are involved, and whether it would count as conflict of interest/non-compete)

**Comment by Half-Shot** [comment]
I think the PRs have come over several years, some of which have since been broken and unbroken. Suggest you move the bounty, unless I am forgetting someone (please ping loudly).
