### ISSUE TITLE
Fix up Room Server races

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/dendrite#375]
Currently the room server assumes that it is processing one event at a time for a room. If this is not true then the output room events kafka stream ends up with incorrect state deltas.

For now this is fixed by adding a mutex to process one event at a time, but it should be eminently tractable to safely process multiple events concurrently.

**Comment by anoadragon453** [comment]
Removing this from the bot milestone as the data is currently correct, it could just be done in a more elegant way.

**Comment by Kegsay** [comment]
Superced by #547
