### ISSUE TITLE
Implement fallback web registration

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#398]
**Spec URI:** https://matrix.org/docs/spec/client_server/r0.3.0.html#fallback

**Phase:** 3-5

Allow a fallback web page for a client to complete various registration stages when they may not be able to do so themselves (i.e. Google ReCaptcha).

**Summary:**
- [x] Implement a new endpoint in [clientapi/routing.go](https://github.com/matrix-org/dendrite/blob/master/src/github.com/matrix-org/dendrite/clientapi/routing/routing.go)
- [x] Serve HTML pages depending on auth type in request URI

**Comment by Trion129** [comment]
Can I can take this issue? Need to get my hands on dendrite code now :)

**Comment by anoadragon453** [comment]
Sure! It's a bit high level though, but feel free to create a branch and start working towards it. More issues coming very soon!

**Comment by Cnly** [comment]
Closed by #405. Support for the recaptcha auth type is added there, and there seems to be no other types to implement for now.
