### ISSUE TITLE
Registration: "completed" is initially returned as null

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#399]
**Spec URL**: https://matrix.org/docs/spec/client_server/r0.3.0.html#post-matrix-client-r0-register

**Phase:** 1

As part of the response from `/register`, a `completed` array is returned specifying what registration stages have been completed so far by the client. If a client has not completed any stages (which is always the case initially), the server should send back `"completed"` with an empty array (`[]`). Instead, it sends back `"completed": null`.

This is where we add items to the completed array:

https://github.com/matrix-org/dendrite/blob/139cb7a01e1c391d0828c2d78182c39059b3a0fa/src/github.com/matrix-org/dendrite/clientapi/routing/register.go#L427-L481

If no auth type is specified, `completed` never has anything added to it. We need to initialize it to an empty array (or slice in Go terms) somewhere, probably before we add stuff to it.

## Request

Use a REST API Client such as [RESTClient](https://addons.mozilla.org/en-US/firefox/addon/restclient/) or [Postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop). 

```
# POST _matrix/client/r0/register

Body: {}
```

## Expected Response Body

```
{
  "flows": [{
    "stages": ["m.login.recaptcha"]
  }],
  "completed": [],
  "params": {
    "m.login.recaptcha": {
      "public_key": "6LdL3i8UAAAAAAxwztdHt348YLXFcA6vx0JRkRge"
    }
  },
  "session": "b32ORZ6ubv8YErtX3sV0h6oA"
}
```

## Given Response Body

```
{
  "flows": [{
    "stages": ["m.login.recaptcha"]
  }],
  "completed": null, # Wrong
  "params": {
    "m.login.recaptcha": {
      "public_key": "6LdL3i8UAAAAAAxwztdHt348YLXFcA6vx0JRkRge"
    }
  },
  "session": "b32ORZ6ubv8YErtX3sV0h6oA"
}
```

**Summary:**

- [ ] Ensure that an empty array `[]` is returned instead of `null`.

**Comment by APwhitehat** [comment]
@anoadragon453 Could you specify the steps to reproduce this ?

**Comment by anoadragon453** [comment]
@APwhitehat I've updated with instructions for reproducing and where we handle the registration code. Let me know if you need anything else :)
