### ISSUE TITLE
Implement whoami endpoint

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#404]
**Spec URL:** https://matrix.org/docs/spec/client_server/r0.3.0.html#get-matrix-client-r0-account-whoami

**Phase:** 2

**Difficulty:** Easy

We receive an access token, and with that we return the user_id connected to that access token.

**Summary:**

- [ ] Create endpoint for GET `/account/whoami` in [routing.go](https://github.com/matrix-org/dendrite/blob/master/src/github.com/matrix-org/dendrite/clientapi/routing/routing.go)
- [ ] Return the correct user_id for the given access token. If no correct token was found, return `M_UNKNOWN_TOKEN`
- [ ] Create test case(s) for `/account/whoami` with correct and incorrect access tokens.

**Comment by turt2live** [comment]
(and make sure it works with appservices 😇 )

**Comment by anoadragon453** [comment]
@turt2live Thanks! You think the spec would mention them :P

**Comment by turt2live** [comment]
I wrote that spec, so that's more of an oversight on my part :(

/me scribbles unintelligible words on his todo list

**Comment by anoadragon453** [comment]
@turt2live matrix-org/matrix-doc#1135 ;)

**Comment by richvdh** [comment]
>  Ensure this endpoint works with Application Services. App services pass in ?user_id= as part of the request, so just need to hand this back.

This is true for most endpoints (and supporting it is not necessarily 'Easy'). We should probably have a separate bug to track it?

**Comment by anoadragon453** [comment]
@richvdh Good point, I'll move it out.

**Comment by anoadragon453** [comment]
Actually I'm pretty sure it's just tracked under #358.
