### ISSUE TITLE
Account: Implement Password Change API Endpoint

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#407]
**Spec URL:** https://matrix.org/docs/spec/client_server/r0.3.0.html#post-matrix-client-r0-account-password

**Phase:** 1

**Difficulty:** Medium

This endpoint allows users to reset their passwords. Learn how to authenticate with endpoints [here](https://github.com/anoadragon453/dendrite/wiki/How-to-Test-with-Authentication-to-the-Client-Server-API)!

This issue has been rated Medium due to having to authenticate via the [User-Interactive Authentication API](https://matrix.org/docs/spec/client_server/r0.3.0.html#user-interactive-authentication-api). Theoretically, as we already handle such requests in register.go: https://github.com/matrix-org/dendrite/blob/139cb7a01e1c391d0828c2d78182c39059b3a0fa/src/github.com/matrix-org/dendrite/clientapi/routing/register.go#L404-L482

One should be able to just pass on requests to the `handleRegistrationFlow` method. However, this may end up requiring some refactoring, as that method also handles registering a new user, which is not necessary in this case.

Details on how to test/reproduce this endpoint are below.

## Request

Use a REST API Client such as [RESTClient](https://addons.mozilla.org/en-US/firefox/addon/restclient/) or [Postman](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop).

```
# POST _matrix/client/r0/account/password
Header: N/A
Body: {}
```

See the above **Spec URL** for how the server should properly respond. A `200 OK` with an empty body means the password was changed successfully.

**Summary:**

- [ ] Create a new endpoint in [routing.go](https://github.com/matrix-org/dendrite/blob/master/src/github.com/matrix-org/dendrite/clientapi/routing/routing.go) for `/account/password`.
- [ ] Implement `/account/password` in a new `password.go` file in [clientapi/routing](https://github.com/matrix-org/dendrite/tree/master/src/github.com/matrix-org/dendrite/clientapi/routing).
- [ ] Allow ability to authenticate through [User Interactive Auth API](https://matrix.org/docs/spec/client_server/r0.3.0.html#user-interactive-authentication-api) or existing token.
- [ ] Create integration test(s) for creating a user and changing their password.

**Comment by MohitKS5** [comment]
can I take this?
My plan
- [ ] add `updatePassword` sql query in [accounts_table](https://github.com/matrix-org/dendrite/blob/master/src/github.com/matrix-org/dendrite/clientapi/auth/storage/accounts/accounts_table.go)
- [ ] add a `update password` function in [accounts/storage](https://github.com/matrix-org/dendrite/blob/master/src/github.com/matrix-org/dendrite/clientapi/auth/storage/accounts/storage.go)
- [ ] use `handleregistration` flow same as it is except for modifying `completeRegistration` function to 
   say `changePassword` in new `routing/password.go`
- [ ] adding endpoint to [routing.go](https://github.com/matrix-org/dendrite/blob/master/src/github.com/matrix-org/dendrite/clientapi/routing/routing.go)

**Comment by anoadragon453** [comment]
@MohitKS5 Of course! And that plan sounds good. Don't forget the tests ;)

**Comment by MohitKS5** [comment]
I coded whatever I could but now I am stuck. I think the issue has some prerequisites. Some queries/problems - 
* Only two of `loginAuth` types match between [Client Api](https://matrix.org/docs/spec/client_server/r0.3.0.html#id133) and code [logintypes.go](https://github.com/matrix-org/dendrite/blob/master/src/github.com/matrix-org/dendrite/clientapi/auth/authtypes/logintypes.go).
* If its not implemented in register then no point in using in `password.go`.
* Can't find any reference to `LoginTypeSharedSecret`. Perhaps its login by password
need to work on register I guess :P

**Comment by anoadragon453** [comment]
> Only two of loginAuth types match between Client Api specSheet and code logintypes.go.

This is true, feel free to add some if they are missing :)

> If its not implemented in register then no point in using in password.go.

You and I chatted by splitting off the UIAA into it's own file, so I think this one should be answered.

> Can't find any reference to LoginTypeSharedSecret. Perhaps its login by password
will send a PR after generating tests

Probably not implemented then, I wouldn't worry about that for now.

> need `whoami` endpoint to get currentUser.

That's just for the client, we should never call any of the endpoints ourselves. In the [whoami PR by APwhitehat](https://github.com/matrix-org/dendrite/pull/411#discussion_r172122385) I brought up how to extract the access token from the Header in the request, which you can then use to get the user information via `getDeviceByAccessToken` which returns an object with the following type: https://github.com/matrix-org/dendrite/blob/bad701c703cb97c8352fea671e506f47c063a91c/src/github.com/matrix-org/dendrite/clientapi/auth/authtypes/device.go#L18-L25

With that you can use the UserID to call a database function defined in [storage/accounts](https://github.com/matrix-org/dendrite/tree/bad701c703cb97c8352fea671e506f47c063a91c/src/github.com/matrix-org/dendrite/clientapi/auth/storage/accounts) that actually updates the password to a hash of the new one.

> I am assuming derieved Registration flows updating password flows will be same. Is it okay ?

That's fine for now yeah, in the future we'll add a config option for custom flows for changing a password, but if UIAA is stuck into it's own file and just accepts a list it should be relatively painless to add in the different flows in the future.

**Comment by MohitKS5** [comment]
well.. I said about whaomi endpoint because I thought there are no functions currently to implement it thats why its pending but I see everything is defined  to get user from access token. Nobody just implemented it in a wrapper `whaomi.go`. My bad.
and loginTypeSharedSecret is implemented in register. Just that there is nothing relating it in specSheet.
thanks for responding.

**Comment by suvidsahay** [comment]
Can we still work on this issue??

**Comment by anoadragon453** [comment]
@suvidsahay Sure, feel free.

**Comment by suvidsahay** [comment]
I have a query for login type sharedsecret, if we are using [this](https://github.com/matrix-org/dendrite/blob/05e1ae8745725245ee3b85a588000b0d26bae96c/clientapi/routing/register.go#L917) algorithm to generate MAC , what should be the passowrd provided? The new password or the old password?

**Comment by anoadragon453** [comment]
@suvidsahay If I get what you're saying: old password, as this is verifying that you know the old password before you set a new one.

**Comment by suvidsahay** [comment]
Okay I will continue by considering that the old passwordwould be required to generate the MAC.

**Comment by Kegsay** [comment]
Related sytests:
```
    × After changing password, can't log in with old password
    × After changing password, can log in with new password
    × After changing password, existing session still works
    × After changing password, a different session no longer works by default
    × After changing password, different sessions can optionally be kept
```

**Comment by Kegsay** [comment]
https://github.com/matrix-org/dendrite/pull/1397
