### ISSUE TITLE
.../device/{deviceID} fails if device is found

### ISSUE THREAD

**Issue by MohitKS5** [matrix-org/dendrite#416]
The bug resides in [devices_table.go](https://github.com/matrix-org/dendrite/blob/master/src/github.com/matrix-org/dendrite/clientapi/auth/storage/devices/devices_table.go#L177)
```golang
func (s *devicesStatements) selectDeviceByID(
	ctx context.Context, localpart, deviceID string,
) (*authtypes.Device, error) {
	var dev authtypes.Device
	var created int64
	stmt := s.selectDeviceByIDStmt
	err := stmt.QueryRowContext(ctx, localpart, deviceID).Scan(&created)
	if err == nil {
		dev.ID = deviceID
		dev.UserID = makeUserID(localpart, s.serverName)
	}
	return &dev, err
}
```
The Scan is passed with `int64` pointer. While it is supposed to contain as many members as columns in the row. It throws an error whenever a device is **found.**

**Comment by ptman** [comment]
Right, sorry. Seems I broke this between #313 and #319.

**Comment by ptman** [comment]
https://github.com/matrix-org/dendrite/commit/608eb3ed96c5cb4932c28afdc1bd350bd49764ea ?

**Comment by anoadragon453** [comment]
This still fails with the following:

```
ERRO[2018-05-24T10:34:31.934366910Z] request failed                                error="sql: Scan error on column index 0: converting driver.Value type <nil> (\"<nil>\") to a int64: invalid syntax" req.id=W25ueLhlXoi9 req.method=GET req.path=/_matrix/client/r0/devices/M1rmvB_7
```

**Comment by ptman** [comment]
Great, you managed to fix this before I had time to react. Carry on!
