### ISSUE TITLE
Any plan to replace Kafka?

### ISSUE THREAD

**Issue by koalalorenzo** [matrix-org/dendrite#439]
Any plan to replace Kafka with something different? For example, what about NATS?

**Comment by julian-goldsmith** [comment]
What would the benefits of that be?  I wouldn't think the authors of Dendrite would want to throw a grenade in the middle of everything right now.

**Comment by ara4n** [comment]
we already provide an alternative to kafka called naffka when building dendrite as a single binary; the append-only log engine is designed to be modular. so: yes :)

**Comment by koalalorenzo** [comment]
What a short answer!
I meant to replace it with something different, as when I have Kafka I have to keep running an heavy with a lot of components, while with NATS I don’t.

The answer of Kafka vs Nafka is too short. You shouldn’t have closed this ticket!!! :-(

**Comment by joeblew99** [comment]
@ara4n Have you seen Lift Bridge ? Its a NATS system that has the same semantics as Kafka.
Its looking very good.


Where is naffka btw ?
