### ISSUE TITLE
keyBlock is nil

### ISSUE THREAD

**Issue by cking** [matrix-org/dendrite#442]
Hi, I'm getting the following error:

`Invalid config file: keyBlock is nil`

Basically I am reusing the Caddy fetched Let's Encrypt SSL certificates. I can `cat` the file using the same user account and `openssl` can read it without any problem too

**Comment by l2dy** [comment]
Note that two keys are required with HTTPS: https://github.com/matrix-org/dendrite/blob/b72ed3e38c33d9a31eb9dd3441a599e13ee75c4b/INSTALL.md#crypto-key-generation
The TLS certificate and key should be passed via `--tls-cert` and `--tls-key` options.

**Comment by anoadragon453** [comment]
@cking can you verify what exact command you're using to start dendrite?

**Comment by anoadragon453** [comment]
Closing due to staleness. Feel free to reopen if the problem persists.
