### ISSUE TITLE
AppServices: GET /_matrix/app/r0/user?uri={url_encoded_uri}

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#457]
**Spec:** https://matrix.org/docs/spec/application_service/unstable.html#user-ids

This endpoint takes an encoded URI (such as `tel://123.1234`) that represents an appservice user, and returns the complete Matrix ID on the homeserver (`@_tel_1231234:matrix.org`) which can then be used to contact them directly.

**Comment by rederekt** [comment]
I'll take this one! The spec link mentions multiple input URI types, including:
- MSISDNs (tel)
- Email addresses (mailto)
- IRC nicks (irc - https://tools.ietf.org/html/draft-butcher-irc-url-04)
- XMPP (XEP-0032)
- SIP URIs (RFC 3261)

Are there any others I should account for? I may have to handle these on a case-by-case basis, so I just want to make sure.

**Comment by Kegsay** [comment]
We've deprioritised appservices, and we don't need an issue for each and every missing feature in Dendrite, so closing this for now.
