### ISSUE TITLE
Maintenance: Set up coverage tracking and a roadmap

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#458]
We need:

* ~~Some sort of test coverage tracking. https://coveralls.io seems like a good candidate.~~ Not worth the hassle of hooking SyTest up to at the moment.
* A public Roadmap in the README.md that's kept more up to date than the spreadsheet.
* Godoc?

**Comment by ara4n** [comment]
i’d much rather we kept the spreadsheet up to date than created a new source of truth...

**Comment by anoadragon453** [comment]
The Roadmap was decided on during the meeting with Erik and Neil, mostly because we tended to forget about the spreadsheet. Something right in the Readme (ala https://github.com/half-shot/matrix-appservice-discord) would be difficult to forget about.

But yes, if we have one we shouldn't have the other.

**Comment by anoadragon453** [comment]
We're gonna go for the spreadsheet since it's already familiar to everyone.

Time to update it!

**Comment by neilisfragile** [comment]
For clarity, the plan is that the spreadsheet remains the source of truth at an overall project level, then we use github issues for finer grained immediate workflow and delivery. So @anoadragon453 will create some issues that are grouped in a phase 1 milestone and update the spreadsheet to be truth. As he makes progress through the issues, then spreadsheet can be updated.
