### ISSUE TITLE
AppServices: GET /_matrix/app/r0/alias?uri={url_encoded_uri}

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#460]
**Spec:** https://matrix.org/docs/spec/application_service/unstable.html#room-aliases

This endpoint takes an encoded URI (such as `irc://irc.freenode.net:6667/newcomers`) that represents an external room hosted by an application service, and returns a room alias on the homeserver (`#_freenode_#newcomers:matrix.org`) which can then be used to interact with that external room.

**Comment by Kegsay** [comment]
We've deprioritised appservices, and we don't need an issue for each and every missing feature in Dendrite, so closing this for now.
