### ISSUE TITLE
Prometheus: Don't expose /metrics to the internet by default

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#461]
Currently the `/metrics` endpoint for each component (and the monolith) exposes a `/metrics` endpoint which allows to view and gather various statistics about a Dendrite server.

Ideally this would not be public by default. There are of course multiple ways to solve this, however one of the simplest would be to just expose the endpoint on a separate port (i.e. `http://localhost:7870`), which people can then choose to forward or not.

The only real con to this is we're now exposing double the ports we used to (in the case of non-monolith mode), but this really isn't the end of the world.

**Comment by anoadragon453** [comment]
`/metrics` is indeed enabled by default and there doesn't seem to be a config flag for it.

**Comment by ptman** [comment]
Looking from the prometheus side, I think basic auth for /metrics would be very handy and easy to configure. At least easier than TLS Client Certs. But an on/off switch (or empty listen address) could work just as well.

**Comment by Kegsay** [comment]
This got done.
