### ISSUE TITLE
ClientAPI: POST /_matrix/client/r0/delete_devices

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#463]
**Spec:** https://matrix.org/docs/spec/client_server/unstable.html#post-matrix-client-r0-delete-devices

**Phase**: 2

Need to add an endpoint in the client-api router:

https://github.com/matrix-org/dendrite/blob/c2380485991f0aba55381da5f6bc8b7ba40296dc/src/github.com/matrix-org/dendrite/clientapi/routing/routing.go#L358-L376

And then a method for deleting devices in `device.go`: https://github.com/matrix-org/dendrite/blob/master/src/github.com/matrix-org/dendrite/clientapi/routing/device.go

**Comment by APwhitehat** [comment]
Breakdown of what's required:
- Take a look at [dendrite/clientapi/auth/storage/devices/storage.go](https://github.com/matrix-org/dendrite/blob/master/src/github.com/matrix-org/dendrite/clientapi/auth/storage/devices/storage.go#L144), we'll use the function `RemoveDevice `.
- Then create a (http request) handler function [here](https://github.com/matrix-org/dendrite/blob/master/src/github.com/matrix-org/dendrite/clientapi/routing/device.go),  which takes a request of type [spec](https://matrix.org/docs/spec/client_server/unstable.html#post-matrix-client-r0-delete-devices).
- Then add the handler to [routing](https://github.com/matrix-org/dendrite/blob/master/src/github.com/matrix-org/dendrite/clientapi/routing/routing.go#L377) at path `/delete_devices`.

Note: Feel free to bug us at [#dendrite-dev:matrix.org](https://riot.im/app/#/room/#dendrite-dev:matrix.org).

**Comment by t3chguy** [comment]
I'd argue that there should be another storage method for deleting all devices, it should be parallelised at the database instead of done sequentially/parallelised at the app level

**Comment by APwhitehat** [comment]
@t3chguy I'm sorry, I don't understand.
pq supports parallel queries ? is there a speedup if we parallelise at the app level ?

(I looked and found that they do in fact support parallel read, but that's in version 10. Interesting though)

**Comment by t3chguy** [comment]
I'm saying it'd be best if we ran a `DELETE... WHERE X IN (...) ` rather than N queries

**Comment by APwhitehat** [comment]
True, we should be using a bulk query for this.

**Comment by t3chguy** [comment]
The prepared stmt means we would have to either use pq ANY or stmt each amount of args inside the `IN (?,?,?,...) ` the latter of which is infeasible

**Comment by t3chguy** [comment]
it was concluded that a single prepared stmt with `= ANY(?::varchar[])` was best from some testing

**Comment by t3chguy** [comment]
This uses U-I auth so not really a good first issue :(
