### ISSUE TITLE
AppServices: Identity Assertion aka ?user_id={user_id}

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#469]
**Spec:** https://matrix.org/docs/spec/application_service/unstable.html#identity-assertion

Application Services are able to call the client-server API while masquerading as one of the users they control.

This has already been partially implemented in https://github.com/matrix-org/dendrite/pull/427

**Comment by Kegsay** [comment]
We've deprioritised appservices, and we don't need an issue for each and every missing feature in Dendrite, so closing this for now.
