### ISSUE TITLE
AppServices: Implement Synapse-supported registration config options

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#471]
Once matrix-org/matrix-doc#1259 is closed and these options are properly spec'd, they will need to be added in Dendrite.

Essentially, these are:

- [x] Ability to have a null `url` field
- [ ] Namespace `group_id` field (need to figure out how synapse handles this)
- [ ] Rate limited option (to be implemented once general rate limit support is implemented)
- [ ] Supported protocols option (used in 3PE lookup)

Edit: Options have been added to the config in #478, but their functionality is still not implemented.

**Comment by kegsay** [comment]
Groups were subsequently removed from the spec. We generally do not like issues which are blanket "implement feature X" - we rely on Are We Synapse Yet? to expose areas which are unimplemented in an automated fashion.
