### ISSUE TITLE
Registration: Prevent duplicate registration on same session ID

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#472]
At the moment it's possible to register users over and over again by completing the last step of the User-Interactive Auth flow again and again.

To fix this we need to remove the session ID from the DB once the user has completed registration.

Edit: Turns out what Synapse does in this case is generate a new device for each subsequent request. Of course this requires keeping track of session IDs even after the user has registered. We should probably remain backwards compatible, but this is more overhead. Needs some discussion.

**Comment by babolivier** [comment]
Related: https://github.com/matrix-org/dendrite/issues/644

**Comment by Kegsay** [comment]
What does the spec say?

**Comment by S7evinK** [comment]
Right now, if a user registers with the same session again, they get the result of the previous `/register` call, making `/register` idempotent. (There's also a passing Sytest for this: `registration is idempotent, with username specified`)
So closing this.
