### ISSUE TITLE
Use NOT NULL in DB tables' TEXT fields

### ISSUE THREAD

**Issue by APwhitehat** [matrix-org/dendrite#473]
Can we disallow NULL fields ? (or use Scan with sql.NULLable types)

`password_hash` & `appservice_id` if NULL would throw a sql Scan error [here](https://github.com/matrix-org/dendrite/blob/master/src/github.com/matrix-org/dendrite/clientapi/auth/storage/accounts/accounts_table.go#L109).

Currently we store "" instead of NULL in most tables, which is not NULL.

**Comment by kegsay** [comment]
It depends, as sometimes we care about `''` vs `NULL`, other times we do not. Either way, it's specific to the feature/area, we cannot make blanket rules here.
