### ISSUE TITLE
[federation] Add event auth endpoint

### ISSUE THREAD

**Issue by APwhitehat** [matrix-org/dendrite#482]
endpoint: GET and POST [/_matrix/federation/v1/event_auth/{roomID}/{eventID}](https://matrix.org/docs/spec/server_server/unstable#get-matrix-federation-v1-event-auth-roomid-eventid).

Phase: 1 (still incomplete ?)

ref: https://github.com/matrix-org/synapse/blob/master/synapse/federation/federation_server.py#L342
 https://github.com/matrix-org/synapse/blob/master/synapse/handlers/federation.py#L935

**Comment by APwhitehat** [comment]
_self note_: This is fairly straightforward after #485 is merged.

**Comment by sudsj** [comment]
Hi, I would like to work on this issue.:)

**Comment by APwhitehat** [comment]
Fixed in #905, I believe. @Kegsay ?

**Comment by Kegsay** [comment]
Yep
