### ISSUE TITLE
[federation] Querying Keys Through Another Server

### ISSUE THREAD

**Issue by APwhitehat** [matrix-org/dendrite#483]
spec: https://matrix.org/docs/spec/server_server/unstable.html#querying-keys-through-another-server

Phase: 3

For this api, federation component needs to send a /_matrix/key/v2/server/ request to another HS, sign the response with it's own key, then return the response.

**Comment by anoadragon453** [comment]
Duplicate of https://github.com/matrix-org/dendrite/issues/650
