### ISSUE TITLE
Trim room alias when receiving a directory request

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#489]
Some clients **cough** Riot **cough** won't always trim strings when they send them to you. So if you request to join a room "#happy:matrix.org ", the request will fail because there's a space in there.

Easy fix, just need to trim vars["roomAlias"] here:

https://github.com/matrix-org/dendrite/blob/78440083dfc8f522e55f11f0fce0f3ea4a103f0b/src/github.com/matrix-org/dendrite/clientapi/routing/routing.go#L140-L145

**Comment by t3chguy** [comment]
This has been deemed a Riot bug and handling this server-side would be in breach of spec

**Comment by anoadragon453** [comment]
Forgot this issue still existed. Thanks @t3chguy
