### ISSUE TITLE
[federation] Implement stream_id for users' device updates

### ISSUE THREAD

**Issue by APwhitehat** [matrix-org/dendrite#493]
After #498 we have basic get user_devices in place.
` GET /_matrix/federation/v1/query/user_devices/{user_id}`

Expected Response: 
```js
{
    "stream_id": string,
    "devices": []device
}
```
We still don't implement `stream_id`.
Figure out how to do this.

**Comment by erikjohnston** [comment]
The stream_id stuff is to allow servers to be subscribed to users' device updates. This works by servers sending any update to devices to other servers who have users which share a room with the device's user. This allows remote servers to get live updates about device changes (which is important for e2e) without constantly having to query the local server. This API basically allows remote servers to "resync", i.e. get the list of all the user's devices.

**Comment by Kegsay** [comment]
We do this now.
