### ISSUE TITLE
[Idea] Registration option for not sending old events

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#497]
The AS `age` field is considered fairly useless at the moment. The only usecase found so far for it is preventing old events (+1 week) from being sent from the homeserver to the AS.

If we added an AS registration option, say `max_event_age`, that wouldn't send events if they were over a certain age then we could get rid of this field for application services.

**Comment by Kegsay** [comment]
This isn't part of the spec, and realistically I don't see us getting around to this anytime soon. I don't think this is the best place for this, try `matrix-doc`.
