### ISSUE TITLE
Flatbuffer binary encoding?

### ISSUE THREAD

**Issue by AndrewJDR** [matrix-org/dendrite#51]
Once dendrite gets further along, would a flatbuffer binary encoding for the matrix events be considered?

I experimented with encoding the existing json schema as binary using flatbuffers, and it did appear to work alright for `m.room.member_example.json`. I presume it would be fine for other messages, and that the flatbuffers schemas could be automatically generated with a tool from the matrix-spec repo (Meaning potentially no need to maintain a separate binary protocol specification). I published my test here - https://github.com/matrix-hacks/matrix-flatbuffers

... I believe this would allow clients and servers to completely ditch the need for json parsing/encoding which relieves clients of a lot of their code size and complexity, while increasing message handling performance significantly -- all relevant for minimal/embedded clients written in C and other low level languages.

Flatbuffers already has language bindings for Go (and python and C++ and many others).

**Comment by AndrewJDR** [comment]
Also, if there's a more appropriate place to discuss this please let me know. I tried on #matrix-dev but it gets quickly lost in the scrollback before any devs get a chance to see it.

**Comment by ara4n** [comment]
the right place is probably the spec - matrix-org/matrix-doc. the dendrite folks are fairly singlehandedly focused on the dendrite impl itself. now, if only github let you move issues between projects...

**Comment by AndrewJDR** [comment]
Thanks @ara4n, I'm going to close this and open an issue over at matrix-doc.
