### ISSUE TITLE
Make sytest's federation tests pass 

### ISSUE THREAD

**Issue by APwhitehat** [matrix-org/dendrite#519]
- [x] 00prepare.pl
- [x] 01keys.pl (notary server not implemented)
- [x] 10query-profile.pl (remote profile query not implemented)
- [x] 11query-directory.pl
- [x] 30room-join.pl
- [x] 31room-send.pl (we don't support /events, deprecated)
- [ ] 32room-getevent.pl
- [ ] 33room-get-missing-events.pl
- [ ] 34room-backfill.pl
- [ ] 35room-invite.pl
- [ ] 36-state.pl
- [ ] 37public-rooms.pl
- [ ] 40devicelists.pl
- [ ] 41power-levels.pl

At least the ones which are supposed to be implemented by dendrite

**Comment by Kegsay** [comment]
I don't mind having a "are-we-synapse-ready-yet?" issue to track parity with Synapse, but I do object to having lots of issues for this. Please keep issues Specific, Measurable, Achievable/Actionable, Realistic, and Time-Bounded.
