### ISSUE TITLE
[discussion] Decide who handles http Bad Method

### ISSUE THREAD

**Issue by APwhitehat** [matrix-org/dendrite#523]
This code is never reached.
https://github.com/matrix-org/dendrite/blob/af08eea46df38117738c56df4b2b3717c5211248/src/github.com/matrix-org/dendrite/clientapi/routing/profile.go#L38-L43

Gorilla mux internally offers handling Bad method, which we should promote.
But we don't have control over what body is returned.

**Comment by anoadragon453** [comment]
Yeah, the whole point is to return a `404` because that request type + endpoint doesn't exist.

We should just remove that type check.

**Comment by Cnly** [comment]
+1 for removal. I removed one of this in #726 while I was wondering why it existed. But there are still other occurrences in the codebase.

**Comment by anoadragon453** [comment]
Fixed by https://github.com/matrix-org/dendrite/pull/747
