### ISSUE TITLE
[Discussion] Refactor LogThenError to just take context

### ISSUE THREAD

**Issue by APwhitehat** [matrix-org/dendrite#536]
https://github.com/matrix-org/dendrite/blob/142fbcde218f55f50ed74d16b7e58faabc6697f6/src/github.com/matrix-org/dendrite/clientapi/httputil/httputil.go#L41-L47

My argument in favor is that it will help sanitize many function by not passing the request.
This is speacially the case in federation where httpReq should not passed.

**Comment by anoadragon453** [comment]
Sure, that seems reasonable.

**Comment by erikjohnston** [comment]
I will note though that the idea is that only functions that take the request object should return HTTP responses. In the past there have been bits of dendrite that have used http responses as an error parameter, we found that this leads to quite brittle and complicated code.

c.f. [code style](https://github.com/matrix-org/dendrite/blob/master/CODE_STYLE.md#http-error-handling) on HTTP error handling

**Comment by APwhitehat** [comment]
I got you.
Though we are actually using `*util.JSONResponse` as an error response at several places.
Is that acceptable ?

**Comment by erikjohnston** [comment]
I think most of the time those same functions take in the request object, so should be fine. Basically, its fine if the function is "processing the request", but less fine if the function is, say, doing a subset of work.
