### ISSUE TITLE
Add test config for AS component

### ISSUE THREAD

**Issue by APwhitehat** [matrix-org/dendrite#558]
https://github.com/matrix-org/dendrite/blob/68131ca7a37bded8a00f745cb71fa538d26746e9/src/github.com/matrix-org/dendrite/common/config/config_test.go#L57-L61

**Comment by anoadragon453** [comment]
It's presumed that it was just forgotten about, and OK to update.

**Comment by babolivier** [comment]
Given the related PR has been merged, I suppose it's OK to close this issue. Please reopen if I was wrong.

**Comment by APwhitehat** [comment]
I see `as_api` is still not present. Not sure about what else should be there.
Maybe I should rename this issue to just point out AS api.
Hopefully while fixing it, we'll realise if something else is missing.

**Comment by babolivier** [comment]
Roger that, thanks!
