### ISSUE TITLE
Improve/rectify code comments for clientapi membership storage

### ISSUE THREAD

**Issue by APwhitehat** [matrix-org/dendrite#560]
here https://github.com/matrix-org/dendrite/blob/38965ef5e224cec7ca98dc54e6de18266f907591/src/github.com/matrix-org/dendrite/clientapi/auth/storage/accounts/membership_table.go#L25-L27

here https://github.com/matrix-org/dendrite/blob/38965ef5e224cec7ca98dc54e6de18266f907591/src/github.com/matrix-org/dendrite/clientapi/auth/storage/accounts/storage.go#L145-L150

We also need to take a look at other membership function comments in the above file `storage.go`.

**Comment by APwhitehat** [comment]
Feels like an good exercise for someone looking to read & understand the code base.
Do feel free to ask your queries on https://matrix.to/#/!FyQrGcOoVamcLcvdob:matrix.org

**Comment by rederekt** [comment]
Should be fixed by #566

**Comment by APwhitehat** [comment]
Fixed by #566
