### ISSUE TITLE
Dendrite does not limit postgres connections

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#564]
While testing massive parallel registration today it was found that Dendrite can end up hitting postgres' connection limit and drop DB queries.

```
Error registering: msg=Failed to POST JSON to /_matrix/client/r0/register code=500 wrapped=M_UNKNOWN: failed to create account: pq: remaining connection slots are reserved for non-replication superuser connections
```

Connections should be limited and queued if we hit the limit. The limit is on postgres' side rather than Dendrite's.

**Comment by Kegsay** [comment]
This is literally just passing through a config option for `sql.DB`.`SetMaxOpenConns`

**Comment by tomasji** [comment]
Hi, I tried to add Db connection configuration, please have a look at the pull request
https://github.com/matrix-org/dendrite/pull/980
