### ISSUE TITLE
TypingEvent should be replaced by gomatrixserverlib.Event ?

### ISSUE THREAD

**Issue by APwhitehat** [matrix-org/dendrite#569]
https://github.com/matrix-org/dendrite/blob/1165b49da78f4e4c92e9cbd5f5a633528a304068/src/github.com/matrix-org/dendrite/typingserver/api/output.go#L21-L26

We should probably have an gomatrixserverlib.Event instead. Thoughts ?

**Comment by anoadragon453** [comment]
Yep, I went through the same thing with ApplicationServiceEvent. Saves having to keep two things in sync.
