### ISSUE TITLE
Improve backfilling and get_missing_events on the federation end

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#586]
As of https://github.com/matrix-org/dendrite/pull/585, dendrite uses [BFS](https://en.wikipedia.org/wiki/Breadth-first_search) to generate its response to a request on the `/backfill` federation endpoint. This should be changed to make it use something more efficient.

**Comment by babolivier** [comment]
ftr we also use it for `/get_missing_events` since it's the same function that handles events retrieval for both endpoints.

**Comment by Kegsay** [comment]
> use something more efficient.

What did you have in mind @babolivier ?

**Comment by babolivier** [comment]
So this issue was a consequence of a discussion I had with @erikjohnston, who said that there should be more efficient algos out there to process events here, but I don't think he mentioned any in particular. Though some time later I noticed that the spec seems to somewhat mandate BFS for the [`/get_missing_events`](https://matrix.org/docs/spec/server_server/latest#post-matrix-federation-v1-get-missing-events-roomid) endpoint.

**Comment by Kegsay** [comment]
Righto, closing this then.
