### ISSUE TITLE
Implement the media repository APIs

### ISSUE THREAD

**Issue by NegativeMjark** [matrix-org/dendrite#59]
The media repository component handles `/_matrix/media/v1/` API requests from local clients and remote servers. It can create thumbnails for common image formats like JPEG, GIF and PNG.

See [Component-Design](https://github.com/matrix-org/dendrite/wiki/Component-Design) for general guidelines for writing a component.

 * [ ] Handle `/_matrix/media/v1/upload` requests
    * [x] Store the content. Decide whether to use a local fs, or something else to store the content.
    * [ ] Authenticate the user. Decide whether to use postgres, or an internal API, or a timebound macaroon to check the access token.
    * Maybe look at https://github.com/erikjohnston/gotest/tree/test
 * [x] Handle `/_matrix/media/v1/download/...` requests
 * [x] Handle `/_matrix/media/v1/thumbnail/...` requests
    * Maybe look at https://github.com/illicitonion/thumbnailer
 * [ ] Handle `/_matrix/media/v1/preview_url/...` requests
 * [ ] Think about sharding for the media repository.
 * [ ] Think about replication for the media repository.

**Comment by NegativeMjark** [comment]
> @NegativeMjark should this be /v1 or /r0?

It looks like the JS client uses v1 for this.

https://github.com/matrix-org/matrix-js-sdk/blob/master/src/content-repo.js#L50

**Comment by superdump** [comment]
@ara4n @NegativeMjark - the spec says `/r0`, if that clarifies anything.

**Comment by superdump** [comment]
This will be steadily appearing on https://github.com/matrix-org/dendrite/tree/rob/media-upload

As of the time of writing I have just uploaded my first file. Needs polish but it's alive! 😄

**Comment by superdump** [comment]
I can now download files too. Working on clean up and refactoring.

**Comment by superdump** [comment]
A bunch more refactoring and clean up happened. The skeleton (cli, configuration, types, upload/download stubs) has been merged. Upload and db code is in #124.

**Comment by superdump** [comment]
Upload has been merged #124. Download of local files has been merged #125. Download of remote files is under review #126.

**Comment by superdump** [comment]
Upload/download/thumbnailing now done aside from integration tests.

**Comment by Kegsay** [comment]
So what's left on this issue? Can you please update the [google doc](https://docs.google.com/spreadsheets/d/1tkMNpIpPjvuDJWjPFbw_xzNzOHBA-Hp50Rkpcr43xTw/edit#gid=0) with your progress.

**Comment by superdump** [comment]
Tests landed. This is 'done' for now.
