### ISSUE TITLE
docker-compose setup doesn't work if binaries have been built by anything else than docker-compose up

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#596]
It appears that the `docker-compose` setup is broken right now if binaries are built outside of a `docker-compose up` process. This means that removing the `./bin` directory then running `docker-compose up ...` seems to work (might need some tweaks in the configuration though), but running `gb build` then `docker compose up ...` will result in errors such as `./docker/services/monolith.sh: line 5: ./bin/dendrite-monolith-server: No such file or directory`.

For the record, binaries seems to be mounted correctly, as shown in one of my test runs in which I edited the script to do some extra logging:

```
brendan@Noah:~/Documents/matrix/dendrite/docker (babolivier/playground*)$ sudo docker-compose up client_api 
dendrite_postgres is up-to-date
Starting dendrite_room_server ... done
Starting dendrite_client_api  ... done
Attaching to dendrite_client_api
dendrite_client_api     | + ls -lisha /build/bin/dendrite-client-api-server
dendrite_client_api     | 4023896  14344 -rwxr-xr-x    1 root     root       14.0M Dec 17 13:05 /build/bin/dendrite-client-api-server
dendrite_client_api     | + /build/bin/dendrite-client-api-server --config=dendrite.yaml
dendrite_client_api     | ./docker/services/client-api.sh: line 8: /build/bin/dendrite-client-api-server: No such file or directory
dendrite_client_api exited with code 127
brendan@Noah:~/Documents/matrix/dendrite/docker (babolivier/playground*)$ sudo docker-compose up monolith

**Comment by ataul443** [comment]
I am working on it. @babolivier

**Comment by ayushjn20** [comment]
Hey @babolivier @ataul443 
I have also tried setting up with `sudo docker-compose -f docker/docker-compose.yml up ...` and is getting the same issue. Besides the issue mentioned above, I am getting two more errors,

1.
```
dendrite_client_api     | writing new private key to 'server.key'
dendrite_client_api     | server.key: Permission denied
```

2.
```
FATAL: command "build" failed: copyfile: mkdirall: mkdir /build/pkg: permission denied
```
Can someone give some insights on these too?

**Comment by Cnly** [comment]
I also ran into this problem and I think the error messages were really confusing. I tried to fix things and then I found this issue! I saw that @ataul443 has been working on it but it's been some time, so I opened my PR #598 and maybe that could provide a fix for now. I'm not a Docker expert, so I'd also like to know if there's a better solution :)
