### ISSUE TITLE
Option to use TravisR's Media Repo Implementation

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#597]
https://github.com/turt2live/matrix-media-repo

Travis' media repo allows for deduplication and simultaneous use by multiple homeserver instances at once.

Not sure what would currently be required to get it up and running with the current codebase, but seeing as it essentially just works as a key-value store, it shouldn't be too difficult to communicate with it.

Whether there would be much overhead over using http instead of Kafka needs to be determined.

**Comment by turt2live** [comment]
> Whether there would be much overhead over using http instead of Kafka needs to be determined.

Worth noting that my mental agenda for the repo includes alternative transports for more efficient communication with the homeservers it represents. Stuff like hooking into synapse's replication and dendrite's Kafka stuff is not off the table.

**Comment by Kegsay** [comment]
Closing this as this is not really a dendrite issue, it's a matrix-media-repo issue to support dendrite. We have enough open issues.
