### ISSUE TITLE
Implement OpenID module

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#599]
- [ ] Implement [POST /_matrix/client/r0/user/{userId}/openid/request_token](https://matrix.org/docs/spec/client_server/r0.4.0.html#post-matrix-client-r0-user-userid-openid-request-token)
- [ ] Implement [GET /_matrix/federation/v1/openid/userinfo](https://matrix.org/docs/spec/server_server/unstable.html#get-matrix-federation-v1-openid-userinfo)

**Comment by Kegsay** [comment]
Sytests:
```
    × Can generate a openid access_token that can be exchanged for information about a user
    × Invalid openid access tokens are rejected
    × Requests to userinfo without access tokens are rejected
```

**Comment by jakehemmerle** [comment]
Starting work on this!

**Comment by BruceMacD** [comment]
I'll review Jake's previous work here and finish this off.
