### ISSUE TITLE
Implement ignoring specific users

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#600]
- [ ] Implement special case for [m.ignored_user_list](https://matrix.org/docs/spec/client_server/r0.4.0.html#m-ignored-user-list) account data type

**Comment by abhishekkumar2718** [comment]
Correct me on this - Ignored users are sent as a map with usernames as key and user_ids as values. Since the usernames can be changed, we will have to use user_ids anyway.

Can we change this in the specification to send a list of user_ids instead? It seems more intuitive to me.

**Comment by prateek2211** [comment]
I would like to work on this

**Comment by Kegsay** [comment]
Sytests:
```
    × Ignore user in existing room
    × Ignore invite in full sync
    × Ignore invite in incremental sync
```

**Comment by kegsay** [comment]
https://github.com/matrix-org/dendrite/pull/2329
