### ISSUE TITLE
Fix database errors

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#601]
Currently, we have two occurrences of `sql: expected x destination arguments in Scan, not y` runtime errors popping up:

- [x] one when querying the CS API's `GET /devices` endpoint
- [ ] one in the syncapi's `rowsToStreamEvents` function

Both should be quite trivial to fix as the former should be pretty straightforward and the latter on require a small bit of refactoring.

**Comment by DrGlitchMX** [comment]
I would gladly take this on, and I actually have a fix for `GET /devices` ready.
Should I wait for submission until the bug in `rowsToStreamEvents` is also fixed?

**Comment by Kegsay** [comment]
The syncapi one is still an issue:
```
	// TODO: The session_id and transaction_id blanks are here because otherwise
	// the rowsToStreamEvents expects there to be exactly five columns. We need to
	// figure out if these really need to be in the DB, and if so, we need a
	// better permanent fix for this. - neilalexander, 2 Jan 2020
```
