### ISSUE TITLE
Implement /initialSync endpoints

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#604]
- [ ] Implement [GET /_matrix/client/r0/initialSync](https://matrix.org/docs/spec/client_server/r0.4.0.html#get-matrix-client-r0-initialsync)
- [ ] Implement [GET /_matrix/client/r0/rooms/{roomId}/initialSync](https://matrix.org/docs/spec/client_server/r0.4.0.html#get-matrix-client-r0-rooms-roomid-initialsync)

Even though these endpoints are marked as deprecated, they're still widely used in tests all around our projects (sytest, riot tests, etc.) so it might be a good thing to implement them at some point, if they still exist then.

**Comment by anoadragon453** [comment]
Probably a case of updating the tests.

**Comment by Kegsay** [comment]
We have no intention to implement this and have been updating sytest to not use deprecated endpoints.
