### ISSUE TITLE
Implement read receipts

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#608]
- [ ] Implement [m.receipt](https://matrix.org/docs/spec/client_server/r0.4.0.html#m-receipt)
- [ ] Implement [POST /_matrix/client/r0/rooms/{roomId}/receipt/{receiptType}/{eventId}](https://matrix.org/docs/spec/client_server/r0.4.0.html#post-matrix-client-r0-rooms-roomid-receipt-receipttype-eventid)
- [ ] Implement read receipt in [/sync](https://matrix.org/docs/spec/client_server/r0.4.0.html#get-matrix-client-r0-sync)

I'd suggest giving https://matrix.org/docs/spec/client_server/r0.4.0.html#id99 a good read before starting working on this one.

**Comment by Kegsay** [comment]
Sytests:
```
    × POST /rooms/:room_id/receipt can create receipts
    × Read receipts are sent as events
    × Receipts must be m.read

    × Outbound federation sends receipts
    × Inbound federation rejects receipts from wrong remote

    × Read receipts appear in initial v2 /sync
    × New read receipts appear in incremental v2 /sync
```

**Comment by S7evinK** [comment]
I'd like to give this a try, if there's nobody else already working on it.

**Comment by S7evinK** [comment]
```
× Read receipts are sent as events
```

Isn't necessary, since its a test on a [deprecated](https://matrix.org/docs/spec/client_server/r0.6.1#deprecated-get-matrix-client-r0-events) endpoint
