### ISSUE TITLE
Add insecure test mode

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#609]
Sytest needs to be able to set an insecure mode in Dendrite's configuration in which it doesn't check the validity of SSL certificates. This include:

- [ ] not checking certificates when querying application services
- [ ] not checking certificates when querying identity servers

This should be pretty straightforward, as it only needs to configure HTTP clients to skip this check if the test mode is enabled.

I labeled it with the clientapi and appservices components because I don't think we have any of these calls made outside of these components, but I could be wrong about it.

**Comment by Quarkstar** [comment]
I would like to work on this.
And I have a problem with this function in `appservice/api/query.go`
```go
func NewAppServiceQueryAPIHTTP(
	appserviceURL string,
	httpClient *http.Client,
) AppServiceQueryAPI {
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	return &httpAppServiceQueryAPI{appserviceURL, httpClient}
}
```
It seems that I need to add a new parameter like 'test flag' to decide whether to skip the SSL verify.
Is there a better way to deal with it without changing parameters?

**Comment by frzifus** [comment]
@Quarkstar you could extend this pr. https://github.com/matrix-org/dendrite/pull/823

**Comment by Kegsay** [comment]
The opposite is true, we don't verify SSL certs by default over federation, which is a separate issue.
