### ISSUE TITLE
Implement GET /events

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#612]
- [ ] Implement [GET /_matrix/client/r0/events](https://matrix.org/docs/spec/client_server/r0.4.0.html#get-matrix-client-r0-events)

Even though this endpoint is marked as deprecated, it's still widely used in tests all around our projects (sytest, riot tests, etc.) so it might be a good thing to implement it at some point, if it still exist then.

**Comment by anoadragon453** [comment]
Sounds like the tests just need to be updated.

**Comment by Kegsay** [comment]
We don't plan to implement this endpoint, and instead will convert sytests to use /sync
