### ISSUE TITLE
Handle trailing slashes at the end of paths

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#613]
The HTTP routers Dendrite uses see `/foo/bar` and `/foo/bar/` as two different routes. We'd ideally not want that, because Synapse and sytest sometimes add trailing slashes at the end of paths even though the specs doesn't use any.

This might require a bit of research but should be quite straightforward.

**Comment by turt2live** [comment]
note that synapse is also picky about slashes, which may result in a fun time debugging if not considered carefully: https://github.com/matrix-org/synapse/issues/3622

**Comment by brunnre8** [comment]
He, but I guess that doesn't mean that we can't "fix" it in dendrite does it? That just means that one also has to do the work in synapse if I understand correctly?

I mean, the core team needs to make the decision whether trailing slashes are significant or not. Then this can be implemented one way or the other.

**Comment by turt2live** [comment]
It should absolutely be fixed in Dendrite - that's a great thing to do. Just giving a head's up that going the other direction (Dendrite -> Synapse) is picky as well.

I'd hope that everyone agrees that trailing slashes are supposed to be insignificant.

**Comment by brunnre8** [comment]
>I'd hope that everyone agrees that trailing slashes are supposed to be insignificant.

Oh boy, I just read a few blog posts / forum threads and people have *very* strong opinions about that.

Seems that there are strong voices against doing it in a REST interface.

Then again, I personally don't care either way so just tell me what to do and I'll happily do it :wink:

**Comment by babolivier** [comment]
> I could have a look if you'd like?

If you have some time and motivation to look into this, feel free to do so! :)

> Which endpoints do you want to handle in this way? All of them, including prometheus? Just the synapse ones in /api/... ?

Ideally every endpoint managed by Dendrite, though we only really care about the public endpoints under `/_matrix`.

**Comment by anoadragon453** [comment]
I am up for removing all trailing slashes from all requests before passing them to handler functions, if that's possible.

Afaik no query parameters would have trailing slashes that would be worse off if they were chopped off.

**Comment by babolivier** [comment]
Well the issue is that it's `gorilla/mux` that does the matching: if you register a handler on a path without a trailing slash at the end then hit that path with a trailing slash the router will respond with a `404` code without passing the request to any of your handlers. We could do a very ugly thing and register two handlers for every path, one with a trailing slash and one without, but I'd like to avoid that as much as possible. We should look for another way to do it, if that's possible.

**Comment by anoadragon453** [comment]
https://godoc.org/github.com/gorilla/mux#Router.StrictSlash ?

**Comment by babolivier** [comment]
As mentioned above, this doesn't fit our use case.

Possible ways to do this:

1. find a way to register some kind of middleware to catch the requests and remove any trailing slash from the URL
2. PR a "ignore trailing slash" feature to `gorilla/mux`

After irl discussions with @anoadragon453, we're likely going to go with option 2.

**Comment by brunnre8** [comment]
there's actually a nice blog post here https://natedenlinger.com/dealing-with-trailing-slashes-on-requesturi-in-go-with-mux/

**Comment by SUMUKHA-PK** [comment]
So its not option 2? Can I work on option 1?

**Comment by NJnisarg** [comment]
This issue seems to be still not resolved yet. Can I give it a shot?
I looked at the comment thread on this issue and seems like the article: [https://natedenlinger.com/dealing-with-trailing-slashes-on-requesturi-in-go-with-mux/](https://natedenlinger.com/dealing-with-trailing-slashes-on-requesturi-in-go-with-mux/)
might work. I was thinking of writing a middleware along the lines the common.WrapHandlerInCORS that simply drops the trailing slashes.

Correct me if my thinking path is wrong. I am new to dendrite and golang as well. Thanks!

**Comment by anoadragon453** [comment]
We need to do a comprehensive review of all the spec'd endpoints, but I believe Dendrite shouldn't just assume an endpoint with a trailing slash is the same as one without. For instance, there are some endpoints where a trailing slash means you're providing an empty path parameter: https://github.com/matrix-org/matrix-doc/issues/1916

As far as I can tell there shouldn't be any instances where we would want to handle an endpoint with and without a trailing slash as the exact same functionality, other than possibly keeping backwards compatibility with older Synapse versions that sent trailing slashes when they shouldn't have: https://github.com/matrix-org/synapse/pull/4935 https://github.com/matrix-org/synapse/pull/4840

**Comment by Kegsay** [comment]
This happened, including weird fixes with `SkipClean` and `UseEncodedPath`. Related sytests (specifically with `/rooms/{roomID}/state/{eventType}/`  now pass.

**Comment by princebillyGK** [comment]
`var Router = mux.NewRouter().StrictSlash(true)`

**Comment by nxvinh222** [comment]
> `var Router = mux.NewRouter().StrictSlash(true)` Just use this line of code instead of a regular router.

this doesn't work with prefix path
