### ISSUE TITLE
Investigate latencies between components

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#619]
For instance, when sytest sends a new state event, it expects it to be present in `/state` responses as soon as the event sending request responds, which isn't the case.

The most probable explanation is that communication between components, even in a monolithic setup, isn't instantaneous because using kafka/naffka introduces some level of latency. We need to make sure that's what's happening, then figure out how to improve it.

**Comment by babolivier** [comment]
Hah. I encountered some occurrences of this during my testing, will try to hunt them down at some point and PR fixes to sytest.

Even though, it might be good to investigate on that at some point to have a clear understanding of what latencies we might have in monolithic mode (since these are pretty obvious in a multi-component setup but not always with a monolith).

**Comment by anoadragon453** [comment]
I've fixed up a few tests that were running into this issue: https://github.com/matrix-org/sytest/pull/631 It does indeed allow dendrite to pass more tests.

So, investigation succeeded. If we find more tests of the same nature then we can just apply the same fix.
