### ISSUE TITLE
Implement event redaction

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#620]
- [ ] Implement [m.room.redaction](https://matrix.org/docs/spec/client_server/r0.4.0.html#m-room-redaction)
- [ ] Implement [PUT /_matrix/client/r0/rooms/{roomId}/redact/{eventId}/{txnId}](https://matrix.org/docs/spec/client_server/r0.4.0.html#put-matrix-client-r0-rooms-roomid-redact-eventid-txnid)

We already handle redacted event so this shouldn't be too hard.

**Comment by anoadragon453** [comment]
Keep in mind this is affected by room versions, particularly room v3.

**Comment by Kegsay** [comment]
Landed in https://github.com/matrix-org/dendrite/pull/1189 🎉
