### ISSUE TITLE
Implement GET /messages

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#624]
- [ ] Implement [GET /_matrix/client/r0/rooms/{roomId}/messages](https://matrix.org/docs/spec/client_server/r0.4.0.html#get-matrix-client-r0-rooms-roomid-messages)

Currently implementing this in the syncapi component because of pagination. We might want to move it elsewhere in the future.

**Comment by babolivier** [comment]
Open PR is #591

**Comment by Kegsay** [comment]
This was merged but is buggy over federation, which I'm currently working on.
