### ISSUE TITLE
Implement public rooms directory over federation

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#626]
- [ ] Implement [GET /_matrix/federation/v1/publicRooms](https://matrix.org/docs/spec/server_server/unstable.html#get-matrix-federation-v1-publicrooms)

This should be quite straightforward since the logic already lives within the publicroomsapi component.

**Comment by Kegsay** [comment]
This was done was https://github.com/matrix-org/dendrite/pull/923 got merged
