### ISSUE TITLE
Media API: Media metadata (hash, size…) aren't stored in db for media fetched remotely

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#629]

**Comment by Kegsay** [comment]
Looking at the code, we do. @neilalexander do you concur?

**Comment by Kegsay** [comment]
Specifically https://github.com/matrix-org/dendrite/blob/master/mediaapi/routing/download.go#L625 sets fields for the metadata then `db.StoreMediaMetadata` is called.

**Comment by neilalexander** [comment]
Yes, I believe we do.
