### ISSUE TITLE
Use hs_token as access_token when talking to appservice

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#632]
When querying an application service, homeservers should auth themselves by providing the `hs_token` configured in the application service's config file as an access token.

This is fairly simple as it only requires appending `?access_token=...` to every request sent to an application service.

**Comment by MohitKS5** [comment]
Isn't this already done in both the [room alias](https://github.com/matrix-org/dendrite/blob/master/appservice/query/query.go#L64) and [user id exists](https://github.com/matrix-org/dendrite/blob/master/appservice/query/query.go#L132) endpoints ? 
Or I have misunderstood something ?

**Comment by prateek2211** [comment]
@MohitKS5 [This](https://github.com/matrix-org/dendrite/blob/master/appservice/api/query.go#L120) makes http request to the homeserver component corresponding to appservice and not AppService, so it doesn't require any access_token.

**Comment by prateek2211** [comment]
However, I guess this needs an hs_token
https://github.com/matrix-org/dendrite/blob/0352f250b85721580055f4ba1321c2dda11f0b97/appservice/workers/transaction_scheduler.go#L207
