### ISSUE TITLE
/sync "limit" parameter sends down the $limit oldest events instead of the $limit latest ones

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#634]

**Comment by serra-allgood** [comment]
I'll try to tackle this one

**Comment by serra-allgood** [comment]
Been pouring through the code related to this for the past couple of days (the code base looks so much better now imo, btw!), and I'm not sure if this is still an issue?

**Comment by serra-allgood** [comment]
I've been having considerable difficulty debugging this and it's time to admit that I don't know enough to do so. Please consider this issue available to other contributors.

**Comment by dryairship** [comment]
Hey @anoadragon453 @babolivier I would like to work on this issue. As I can see [here](https://github.com/matrix-org/dendrite/blob/5741235833489d2769c72c24f1b5d93abe9d21ed/syncapi/sync/request.go#L61) limit is currently not being read from the request. Should I first fix this?

**Comment by prateek2211** [comment]
I would like to work on this

**Comment by Kegsay** [comment]
Is this actually an issue? The next sync will fetch slightly more recent account events until eventually it is up-to-date. By skipping older events don't we run the risk of not telling clients all their account data?

**Comment by prateek2211** [comment]
@Kegsay  shouldn't this query produce latest $LIMIT events?
https://github.com/matrix-org/dendrite/blob/0352f250b85721580055f4ba1321c2dda11f0b97/syncapi/storage/postgres/output_room_events_table.go#L89

So, I guess events are already sent as latest ones

**Comment by Kegsay** [comment]
I don't see this as an issue at present - reopen if this is reproducible.
