### ISSUE TITLE
Implement "full_state" query parameter for /sync

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#637]
When `/sync` is called with the `full_state` query parameter, the response should include the complete state of every room the user is in.

**Comment by Cnly** [comment]
This should not be hard to implement. One possible way to do this is we respect [`syncReq.wantFullState`](https://github.com/matrix-org/dendrite/blob/master/syncapi/sync/request.go#L42) so we 1. [return](https://github.com/matrix-org/dendrite/blob/master/syncapi/sync/requestpool.go#L69) from `/sync` immediately and 2. use a zero `fromPos` for [`getStateDeltas`](https://github.com/matrix-org/dendrite/blob/fd4ea78dbfcc9d2c98709f2170e593bff258e0ca/syncapi/storage/syncserver.go#L251).

**Comment by Kegsay** [comment]
Failing sytest, hence reopening:
```
    × A full_state incremental update returns all state
```

**Comment by DavidSpenler** [comment]
I can work on this.

**Comment by DavidSpenler** [comment]
This test is already passing. Should probably close the issue.

**Comment by kegsay** [comment]
Right you are!
