### ISSUE TITLE
Move the error log interface to `common`

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/dendrite#64]
This interface https://github.com/matrix-org/dendrite/blob/da0fffcc19f58df7f21d45016c0768ce2a39d093/src/github.com/matrix-org/dendrite/roomserver/input/consumer.go#L21 should be in `/common`. The intent here is that we will log errors using logrus and/or **send errors to kafka** so we can easily consume errors that occur across many different processes.

**Comment by NegativeMjark** [comment]
The `ErrorLogger` interface doesn't exist anymore as of #161
