### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#640]
- [ ] Use custom error types to differentiate errors throughout the code base (as well as allow us to use different behaviours according to the type of the error). This can be an interesting resource: https://evilmartians.com/chronicles/errors-in-go-from-denial-to-acceptance
- [ ] Process errors from gomatrixserverlib and gomatrix correctly so that we don't respond 500 instead of e.g. 403, 404, etc.
- [ ] Process errors from requests to remote servers (federation, appservice) so that we don't respond 500 instead of e.g. 403, 404, etc.

**Comment by Cnly** [comment]
Note that some places in gomatrixserverlib are already using the [`NotAllowed`](https://github.com/matrix-org/gomatrixserverlib/blob/929828872b51e6733166553d6b1a20155b6ab829/eventauth.go#L303) error, but not sure if Dendrite has made full use of this distinguishment yet.

**Comment by ptman** [comment]
I've found this a nice pattern for simple errors. Much nicer than `var ErrFooBar = errors.New(...)`: https://dave.cheney.net/2016/04/07/constant-errors

**Comment by shyam-patel-kira** [comment]
Is anyone working on this issue right now..??

**Comment by Pac23** [comment]
> Is anyone working on this issue right now..??

i am

**Comment by lpar** [comment]
> Process errors from gomatrixserverlib and gomatrix correctly so that we don't respond 500 instead of e.g. 403, 404, etc.

Might I suggest adopting RFC 7807?

Also, I've been looking at this problem for my own applications, and came up with [lpar/problem](https://github.com/lpar/problem) as an approach for making it easier to handle.

**Comment by Kegsay** [comment]
We're a lot better at this now, with internal APIs exposing their own error types and GMSL having more thorough error types. There's always room for improvement though so it's hard to know at what point this issue can be closed, so I'm deciding now.
