### ISSUE TITLE
Implement missing room creation features

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#643]
- [ ] Implement setting the room's canonical alias
- [ ] Implement setting an alias for the room
- [ ] Implement inviting other users in the room (with `is_direct` flag if applicable)

**Comment by anoadragon453** [comment]
This seem to all currently be possible.

"PUT /directory/room/:room_alias creates alias" will be possible when https://github.com/matrix-org/dendrite/issues/659 is implemented.

**Comment by Cnly** [comment]
@anoadragon453 I wonder if that's accurate? We still have plenty of TODOs in the code:

https://github.com/matrix-org/dendrite/blob/067b87506357c996fd6ddb11271db9469ad4ce80/clientapi/routing/createroom.go#L199-L201

https://github.com/matrix-org/dendrite/blob/067b87506357c996fd6ddb11271db9469ad4ce80/clientapi/routing/createroom.go#L246-L255
