### ISSUE TITLE
Implement missing registration features

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#644]
- [ ] Save/reuse session parameters
- [ ] Remove old sessions. Need to do so on a session-specific timeout.
- [ ] Use device ID in request to create device if present
- [x] "Enable registration" config flag
- [ ] Guest account upgrading

**Comment by anstue** [comment]
There is already a `registration_disabled` flag which is used accordingly in code. I guess we can check that box.

**Comment by Kegsay** [comment]
This issue has too many disparate bits in it, closing for more concrete issues.
