### ISSUE TITLE
Implement appservice room directories

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#646]
- [ ] Implement [PUT /_matrix/client/r0/directory/list/appservice/{networkId}/{roomId}](https://matrix.org/docs/spec/application_service/r0.1.0.html#put-matrix-client-r0-directory-list-appservice-networkid-roomid)

**Comment by Kegsay** [comment]
We've deprioritised appservices, and we don't need an issue for each and every missing feature in Dendrite, so closing this for now.
