### ISSUE TITLE
There seems to be some kind of race when sending an event to an application service

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#647]
Something seems to change the value of a worker's `EventsReady` variable, causing it to wait endlessly for new events when there's actually some events to process. Reproducible through sytest's `Accesing an AS-hosted room alias asks the AS server` test.

**Comment by Kegsay** [comment]
There was an issue whereby the AS component was sharing a DB with another component (clientapi) and using the same partition offsets which could cause races. For now, we're treating ASes as unimplemented so it falls to the cutting room floor along with other unimplemented features: we don't need an issue per missing feature.
