### ISSUE TITLE
Implement user directory

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#649]
This might need its own component like publicroomsapi does, though its logic is simpler so I'm not that sure about it.

- [ ] Implement [POST /_matrix/client/r0/user_directory/search](https://matrix.org/docs/spec/client_server/r0.4.0.html#post-matrix-client-r0-user-directory-search)

**Comment by anoadragon453** [comment]
Probably wouldn't hurt to put it in its own dedicated component since matrix.org sees a large amount of traffic from user searches, and taking load off roomserver is probably a good idea.

**Comment by PrivyDG** [comment]
maybe GAIA from blockstack project would be suitables for such. https://github.com/blockstack/gaia . Only problem is that GAIA  is not written in  GOLANG but their have have couple go projects and libs

**Comment by anoadragon453** [comment]
That would require a change to the [Matrix spec](https://matrix.org/docs/spec) which Dendrite is currently implementing.

I agree that decentralizing the user directory more is a good idea though. One could even use something like https://zeronet.io, which has the concept of user accounts and search.

Would need some PoW scheme though to dissuade Sybil attacks.

**Comment by PrivyDG** [comment]
well Gaia is very impressive since it does not sacrifice speed, does not depend on a crypto currency, support delegations already which would be very useful for matrix.I like the fact it does allow the users to select where his data would be hosted. 
![gaia](https://user-images.githubusercontent.com/48634491/61579521-08dcfd80-aad4-11e9-8ad4-889864657e7e.png)

**Comment by anstue** [comment]
Anyone implementing this issue? Otherwise I grab it ;)

**Comment by anoadragon453** [comment]
> Anyone implementing this issue? Otherwise I grab it ;)

Not to my knowledge!
