### ISSUE TITLE
Implement remote key retrieval

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#650]
- [ ] Implement [GET /_matrix/key/v2/query/{serverName}/{keyId}](https://matrix.org/docs/spec/server_server/unstable.html#get-matrix-key-v2-query-servername-keyid)

**Comment by anoadragon453** [comment]
Partially implemented in https://github.com/matrix-org/dendrite/pull/530

**Comment by anoadragon453** [comment]
This is deprecated as we're deprecating perspectives from the protocol.

**Comment by Cnly** [comment]
And it seems Dendrite already has the preferable behaviour? https://github.com/matrix-org/dendrite/blob/33a13925417612b032c1cbbb8ee62eb053faa5f8/federationapi/routing/routing.go#L61-L66

**Comment by neilalexander** [comment]
This is done by #975 - Dendrite has both direct and perspective key fetching now.
