### ISSUE TITLE
Implement E2EE key management

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#652]
- [ ] Implement [POST /_matrix/client/r0/keys/upload](https://matrix.org/docs/spec/client_server/r0.4.0.html#post-matrix-client-r0-keys-upload)
- [ ] Implement [POST /_matrix/client/r0/keys/query](https://matrix.org/docs/spec/client_server/r0.4.0.html#post-matrix-client-r0-keys-query)
- [ ] Implement [POST /_matrix/client/r0/keys/claim](https://matrix.org/docs/spec/client_server/r0.4.0.html#post-matrix-client-r0-keys-claim)
- [ ] Implement [GET /_matrix/client/r0/keys/changes](https://matrix.org/docs/spec/client_server/r0.4.0.html#get-matrix-client-r0-keys-changes)

I labeled this under the clientapi component, but it might require a dedicated one.

**Comment by SUMUKHA-PK** [comment]
Open PR : https://github.com/matrix-org/dendrite/pull/530

I'm slowly getting into this rn. Will take a while :D

**Comment by Kegsay** [comment]
We do this now.
