### ISSUE TITLE
Implement read markers

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#653]
- [ ] Implement [m.fully_read](https://matrix.org/docs/spec/client_server/r0.4.0.html#m-fully-read) account data type
- [ ] Implement [POST /_matrix/client/r0/rooms/{roomId}/read_markers](https://matrix.org/docs/spec/client_server/r0.4.0.html#post-matrix-client-r0-rooms-roomid-read-markers)

**Comment by Kegsay** [comment]
Sytests:
```
    × Read markers appear in incremental v2 /sync
    × Read markers appear in initial v2 /sync
    × Read markers can be updated
```
