### ISSUE TITLE
Implement missing device management features

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#655]
- [ ] Implement [DELETE /_matrix/client/r0/devices/{deviceId}](https://matrix.org/docs/spec/client_server/r0.4.0.html#delete-matrix-client-r0-devices-deviceid)
- [ ] Implement [POST /_matrix/client/r0/delete_devices](https://matrix.org/docs/spec/client_server/r0.4.0.html#post-matrix-client-r0-delete-devices) - already tracked in https://github.com/matrix-org/dendrite/issues/463

**Comment by Kegsay** [comment]
We landed both of these now.
