### ISSUE TITLE
Investigate updating account data

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#656]
Updating account data should update the content in DB for the couple `(type, room)` and also update its stream position to the most recent value.
It seems like this is not the case currently (or at least it isn't done correctly), and needs deeper investigation.

**Comment by Kegsay** [comment]
If this was an issue, it isn't now:
```
    ✓ Can add account data
    ✓ Can add account data to room
    ✓ Can get account data without syncing
    ✓ Can get room account data without syncing
    ✓ Latest account data appears in v2 /sync
    ✓ New account data appears in incremental v2 /sync
```
