### ISSUE TITLE
Implement room tagging

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#657]
- [x] Implement [m.tag](https://matrix.org/docs/spec/client_server/r0.4.0.html#m-tag) account data type
- [x] Implement [GET /_matrix/client/r0/user/{userId}/rooms/{roomId}/tags](https://matrix.org/docs/spec/client_server/r0.4.0.html#get-matrix-client-r0-user-userid-rooms-roomid-tags)
- [x] Implement [PUT /_matrix/client/r0/user/{userId}/rooms/{roomId}/tags/{tag}](https://matrix.org/docs/spec/client_server/r0.4.0.html#put-matrix-client-r0-user-userid-rooms-roomid-tags-tag)
- [x] Implement [DELETE /_matrix/client/r0/user/{userId}/rooms/{roomId}/tags/{tag}](https://matrix.org/docs/spec/client_server/r0.4.0.html#delete-matrix-client-r0-user-userid-rooms-roomid-tags-tag)

**Comment by SUMUKHA-PK** [comment]
I'm almost done in implementing room tagging, Ill send out a PR within a couple of days.

**Comment by Cnly** [comment]
Closed by #694.
