### ISSUE TITLE
Implement room versioning

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#658]
Currently this isn't described in the specs. Let's make this wait till then.

---

It is now described here: https://matrix.org/docs/spec/#id5 ~anoa

**Comment by Cnly** [comment]
Possibly related: https://github.com/matrix-org/dendrite/issues/660

**Comment by anoadragon453** [comment]
This is something we should have for the bot milestone, such that bots can interact in later room versions (v1 currently has vulns).
