### ISSUE TITLE
Implement /sendToDevice

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#664]
Spec: https://matrix.org/docs/spec/client_server/r0.4.0.html#put-matrix-client-r0-sendtodevice-eventtype-txnid

**Comment by SUMUKHA-PK** [comment]
Issue #530 seems to have this. 
Currently a little rusty, but will try to complete this :)

**Comment by Kegsay** [comment]
@neilalexander this is done now right?

**Comment by neilalexander** [comment]
@Kegsay Local send-to-device is done, federated isn't yet. We can probably rename the issue.

**Comment by Kegsay** [comment]
New one please, closing this.
