### ISSUE TITLE
GET /state... as banned should get the room’s state as it was when banned

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#665]

**Comment by prateek2211** [comment]
I would like to work on this

**Comment by Kegsay** [comment]
The endpoint `GET /_matrix/client/r0/rooms/{roomId}/state/{eventType}/{stateKey}` states:
> Looks up the contents of a state event in a room. If the user is joined to the room then the state is taken from the current state of the room. If the user has left the room then the state is taken from the state of the room when they left.

However, it appears if you are banned then it will just 403 you as per the sytest `Remote banned user is kicked and may not rejoin until unbanned` which, upon banning a user tightloops on:
```perl
         repeat_until_true {
            matrix_get_room_state( $banned_user, $room_id,
               type      => "m.room.member",
               state_key => $banned_user->user_id,
            )->main::check_http_code(
               403 => "ok",
               200 => "redo",
            );
         };
```

The source code in Synapse also seems to suggest it is 403ing given it calls `check_user_in_room_or_world_readable`first when `get_room_data` is called, and that throws.

It's unclear what the correct behaviour is: the spec or synapse.
