### ISSUE TITLE
Implement E2E encryption

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#667]
See https://matrix.org/docs/spec/client_server/r0.4.0.html#end-to-end-encryption

Includes #652 

Might need a dedicated component.

**Comment by babolivier** [comment]
FTR there's a PR about this, we might want to have a look at it: https://github.com/matrix-org/dendrite/pull/530

**Comment by Kegsay** [comment]
Work on this is basically complete now, enough for this not to be an open issue anyway.
