### ISSUE TITLE
Implement single event retrieval

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#671]
Full specs: https://matrix.org/docs/spec/client_server/r0.4.0.html#get-matrix-client-r0-rooms-roomid-event-eventid

**Comment by vaithak** [comment]
Hi @babolivier , I would like to work on this as my first issue. 
Can you guide me with this ?

**Comment by Azanul** [comment]
@babolivier I just have to write the code to GET an event and print status 200 if successful and 404 if not? also, what does "Requires auth: Yes" mean?

**Comment by anoadragon453** [comment]
`Requires auth` means that authentication via an access token is required to use this endpoint. Dendrite has a simple wrapper function for this though, so should need to worry about implementing any auth stuff.

**Comment by anoadragon453** [comment]
However you will need to check that the user requesting this event is allowed to request it. They must be in the room for one.

**Comment by anoadragon453** [comment]
Might also be useful to look at the relevant Synapse code: https://github.com/matrix-org/synapse/blob/d731b75c7bcada708f1acbb83e2521da6a7d97a9/synapse/rest/client/v1/room.py#L525-L544

**Comment by Azanul** [comment]
In the link given by babolivier, the example request seems a bit off as in place of room_id there is event_id.

**Comment by anoadragon453** [comment]
@Azanul Not sure I see the same thing you do. A room ID is the one that begins with !
