### ISSUE TITLE
Implement event auth querying over federation

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#674]
- [ ] Implement [GET /_matrix/federation/v1/event_auth/{roomId}/{eventId}](https://matrix.org/docs/spec/server_server/unstable.html#get-matrix-federation-v1-event-auth-roomid-eventid) - tracked in https://github.com/matrix-org/dendrite/issues/482
- [ ] Implement [POST /_matrix/federation/v1/query_auth/{roomId}/{eventId}](https://matrix.org/docs/spec/server_server/unstable.html#post-matrix-federation-v1-query-auth-roomid-eventid)

**Comment by anoadragon453** [comment]
Closing in favor of #482 and https://github.com/matrix-org/dendrite/issues/757
