### ISSUE TITLE
Allow application services to change the profile of their ghost users

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#675]
This means that if we get a profile update request and it's both done with an AS's token, and is for a user that's within the users namespace of the AS requesting it, we should allow it.

**Comment by SUMUKHA-PK** [comment]
Okay, so this is what Ive understood till now, please do correct me if Im wrong before I proceed to my implementation.

Profile update requests are : `SetAvatarURL` and `SetDisplayName`
We must check whether the AS returns a positive response in `appService.UserIDExists` and then proceed to "return" `SetAvatarURL` and `SetDisplayName` on request by client to the `clientapi`

**Comment by suvidsahay** [comment]
May I take this issue?

**Comment by jaywink** [comment]
This already seems to work but only for users created by the appservice. Made PR #1672 to ensure appservices can update profile of any user in their namespace, this could be closed I believe if that is merged.
