### ISSUE TITLE
Run sytest in CI

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#676]
Running sytest in Dendrite's CI would be tremendous, and also the ultimate integration test suite.

In order to do that, we must find a way to configure it so it doesn't run all of the tests, since Dendrite doesn't aim at passing them all currently. @anoadragon453 opened a PR allowing a HS to specify what tests should pass, which is a good starting point: https://github.com/matrix-org/sytest/pull/452

Checklist for better status tracking:

- [ ] Allow a HS to tell sytest which tests to run and which tests not to run
- [ ] Configure Dendrite's CI to setup and run sytest for every pull request

**Comment by anoadragon453** [comment]
Erik has mentioned that it would probably be best to run this in CircleCI. Synapse currently uses Docker images to achieve that. Will look into it.

**Comment by babolivier** [comment]
ftr I'm also in favor of using CircleCI instead of Travis.

**Comment by anoadragon453** [comment]
Fixed in #704
