### ISSUE TITLE
Figure out roomserver sharding

### ISSUE THREAD

**Issue by babolivier** [matrix-org/dendrite#677]
We might want to shard the roomserver, we should think about how we want to do that.

**Comment by anoadragon453** [comment]
Adding this to Bot Hosting as it's something we probably want to figure out in the short-term as it's an architectural design choice.

**Comment by Kegsay** [comment]
I'd like to extend the HTTP API tests to include sharded tests when we actually land support for it. @neilalexander and I will need to probably have an irl discussion about sharding to work out a plan of attack.

**Comment by kegsay** [comment]
This has gone sufficiently low priority enough that this isn't worth having open. We know we need this already.
