### ISSUE TITLE
Move to go mods instead of gb

### ISSUE THREAD

**Issue by serra-allgood** [matrix-org/dendrite#700]
Go mods is the modern and officially supported method for vendor package versioning and building outside GOPATH. For VS Code with the golang extension devs, gb does not seem to integrate with the tools used by the extension, severely limiting the IDE capabilities of VS Code (code completion, lookup, etc). Additionally, the official site for [gb](getgb.io) seems to be offline due to domain registration issues. For these reasons, I think it's worthwhile to change the vendor management strategy to go mods.

As a new contributor to the project, this is an issue I'd like to take up if there is agreement on moving forward.

**Comment by babolivier** [comment]
Hey, and thanks for taking the time to file this issue!
Work on this has already been started by community member @rbns in https://github.com/matrix-org/dendrite/pull/594, however we currently lack the bandwidth to look at this kind of issues :/
This should hopefully be solved soon. Sorry for the inconvenience :/

**Comment by serra-allgood** [comment]
Oh cool! I'll just base off that branch for the time being :)

**Comment by babolivier** [comment]
With #594 now merged, we can safely close this issue :)

**Comment by babolivier** [comment]
Related: #703
