### ISSUE TITLE
invites_table.go should probably CREATE SEQUENCE IF NOT EXISTS syncapi_stream_id

### ISSUE THREAD

**Issue by Cnly** [matrix-org/dendrite#723]
It looks like [invites_table.go](https://github.com/matrix-org/dendrite/blob/master/syncapi/storage/invites_table.go#L11) should also have the `CREATE SEQUENCE` line as in other data tables sharing `syncapi_stream_id` e.g. https://github.com/matrix-org/dendrite/blob/master/syncapi/storage/account_data_table.go#L28.

**Comment by neilalexander** [comment]
The `syncapi_stream_id` sequence will already exist due to one of the other two statements which create it (which is probably already one too many):
```
$ git grep syncapi_stream_id | grep CREATE
syncapi/storage/postgres/account_data_table.go:CREATE SEQUENCE IF NOT EXISTS syncapi_stream_id;
syncapi/storage/postgres/output_room_events_table.go:CREATE SEQUENCE IF NOT EXISTS syncapi_stream_id;
```
I'm not sure if there is any benefit in adding another statement which will end up being ignored due to the sequence already existing.

**Comment by Kegsay** [comment]
Having the clarity that is depends on the sequence existing could be nice, though a pain if we ever want to update it.

**Comment by Kegsay** [comment]
Negated by https://github.com/matrix-org/dendrite/issues/963
