### ISSUE TITLE
Repeated membership requests cause Dendrite to send multiple membership events

### ISSUE THREAD

**Issue by Cnly** [matrix-org/dendrite#724]
Replayed calls of `/rooms/{roomID}/join` and `/join/{roomIdOrAlias}` seem to cause Dendrite to send multiple `"membership": "join"` events to the room joined, while Synapse seems to ignore the redundant calls.

Events of other membership types have not been tested yet, but may also be problematic.

**Comment by suvidsahay** [comment]
May I know what exactly we need to do in this?

**Comment by neilalexander** [comment]
This is fixed by #1001.
