### ISSUE TITLE
"Didn't call Close on UserStreamListener" log messages when syncing

### ISSUE THREAD

**Issue by Cnly** [matrix-org/dendrite#725]
When clients are normally syncing, there will be "Didn't call Close on UserStreamListener" messages in Dendrite's log. This comes from the [finalizer set](https://github.com/matrix-org/dendrite/blob/master/syncapi/sync/userstream.go#L77) for `UserStreamListener` instances. However, it seems that `Close()` has been correctly called in a [`defer` statement](https://github.com/matrix-org/dendrite/blob/master/syncapi/sync/requestpool.go#L87); it should be just that the finalizer is run right before that.

**Comment by anoadragon453** [comment]
I'd be slightly tempted to just remove the warning, as it seems in some situations it may be unavoidable.

**Comment by Cnly** [comment]
So you mean removing the warning but leaving the finalizer there? That sounds plausible.

**Comment by suvidsahay** [comment]
I want to work on this issue. Is anyone working on it?

**Comment by Kegsay** [comment]
All yours

**Comment by suvidsahay** [comment]
For what I think is that removing the warning is the only solution cause the UserStreamListener will be closed at the end of the [OnIncomingSyncRequest](https://github.com/matrix-org/dendrite/blob/5a1a1ded1b5d8387f89e3d586729d175c1f1a1d0/syncapi/sync/requestpool.go#L46) method.

**Comment by Kegsay** [comment]
Then go ahead :)

**Comment by Cnly** [comment]
Closing as it's fixed.
