### ISSUE TITLE
Explicitly add govet to the list of golangci-lint linters

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#733]
`govet` is enabled by default in [golangci-lint](https://github.com/golangci/golangci-lint/#supported-linters), but we should be explicit about it in the config file.

It may also be nice to add all other default linters to the list as well. Heads up that we're on a quite old version of golangci-lint as well (which is probably a good idea to update).

**Comment by progmatic-99** [comment]
Are you still working on this?
Should govet & others be added to codeql-analysis.yml??

**Comment by anoadragon453** [comment]
@progmatic-99 Err, I don't think we support [CodeQL](https://securitylab.github.com/tools/codeql) currently.

This issue is literally just adding `govet` to [this list](https://github.com/matrix-org/dendrite/blob/f5869daaab2b8135415f4ae5b2d61ac8c3037a9d/.golangci.yml#L181).
