### ISSUE TITLE
Dendrite should honor the bounds on integers

### ISSUE THREAD

**Issue by lucavb** [matrix-org/dendrite#749]
The Matrix spec uses JSON which supports full precision for integers only within the range `[-(2^53 - 1), 2^53 - 1]`. Subsequently numbers need to be in this range, including power levels. I did not find any mentions of the bounds in the dendrite code base. Should Dendrite attempt to share a m.room.power_levels event with Synapse with numbers outside of this range, a split state would occur. 

[Source](https://matrix.org/docs/spec/appendices#canonical-json)

**Comment by anoadragon453** [comment]
Indeed there does not seem to be any bounds on power levels. People have used this against Synapse users as a DoS attack before (mobile apps get scared at big power levels), so we should definitely solve this.

**Comment by Kegsay** [comment]
This got fixed when we added v6 support in https://github.com/matrix-org/gomatrixserverlib/pull/201
