### ISSUE TITLE
Support the new "identifier" login parameter

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#750]
Spec: https://matrix.org/docs/spec/client_server/unstable#post-matrix-client-r0-login

The login API has a new `identifier` field which deprecates the `user` and `address` fields.

**Comment by MohitKS5** [comment]
Assuming 3PID endpoint remains for now (to be depreciated as per spec), It requires

-  Define identifier struct , preferably in login.go as at this point only login endpoint uses that.
-  In /login handler , go over [interface types](https://matrix.org/docs/spec/client_server/unstable#identifier-types)
    - extract user from identifier in m.id.user
    - send back not-implemented for others

**Comment by Kegsay** [comment]
https://github.com/matrix-org/dendrite/pull/825 added this
