### ISSUE TITLE
Transaction IDs in transaction cache have global scope

### ISSUE THREAD

**Issue by Cnly** [matrix-org/dendrite#756]
Currently a transaction cache is [implemented](https://github.com/matrix-org/dendrite/blob/master/clientapi/routing/sendevent.go#L53) for request idempotency, however the transactions cached are only associated with their IDs regardless of the senders' access tokens. So if a transaction ID is used by more than one user before the cache expires, only one among these requests will actually have effect.

From the [spec](https://matrix.org/docs/spec/client_server/r0.5.0#api-standards):

> The scope of a transaction identifier is a particular access token.

**Comment by Cnly** [comment]
A straightforward fix seems to be using an `(accessToken, txnID)` tuple as the transaction cache key.

By the way it looks like roomserver uses a `(deviceID, txnID)` tuple for idempotency which may not be the same as using an `(accessToken, txnID)`: If the user logs into a new session but with a previously seen device ID, there might be problems.

**Comment by anoadragon453** [comment]
> By the way it looks like roomserver uses a `(deviceID, txnID)` tuple for idempotency which may not be the same as using an `(accessToken, txnID)`: If the user logs into a new session but with a previously seen device ID, there might be problems.

Have filed an issue for this at https://github.com/matrix-org/dendrite/issues/776
