### ISSUE TITLE
Implement /query_auth

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#757]
Spec entry: https://matrix.org/docs/spec/server_server/unstable.html#post-matrix-federation-v1-query-auth-roomid-eventid

Related: https://github.com/matrix-org/dendrite/issues/482

**Comment by Trion129** [comment]
I would like to implement a federation API. If this is not a high priority issue, I can work on it.

**Comment by Cnly** [comment]
@Trion129 I think you can certainly take it. Thanks!

**Comment by prateek2211** [comment]
I would like to work on this.

**Comment by clokep** [comment]
It is currently under proposal to remove this endpoint, see matrix-org/matrix-doc#2451.

**Comment by clokep** [comment]
This was officially removed from the spec. I'm going to close this.
