### ISSUE TITLE
Implement a basic version of /event_auth and /query_auth

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#758]
These endpoints aren't required in full for basic federation to work. We may just need to fill out the endpoints and have them return happy error codes without any content.

Individual tracking issues: https://github.com/matrix-org/dendrite/issues/482, https://github.com/matrix-org/dendrite/issues/757

**Comment by clokep** [comment]
Looks like event_auth was implemented and query_auth is no more so this can be closed I believe.
