### ISSUE TITLE
Require verified certificates for federation (MSC1711)

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#760]
[MSC1711](https://github.com/matrix-org/matrix-doc/pull/1711) states that federation connections must only be made to homeservers that have a valid X.509 (SSL) certificate. The specification [states this](https://matrix.org/docs/spec/server_server/r0.1.2#resolving-server-names) as well, thus Dendrite must enforce it.

**Comment by JorikSchellekens** [comment]
Should this be optional (opt out) for deployments using reverse proxy's or something unspeakable?

**Comment by JorikSchellekens** [comment]
Will we support this: ["Servers can additionally skip the certificate validation for a given whitelist of domains or netmasks for the purposes of testing or in networks where verification is done elsewhere, such as with .onion addresses"](https://matrix.org/docs/spec/server_server/r0.1.2#resolving-server-names)
