### ISSUE TITLE
Automatic ACME registration for federation certificates 

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#761]
Synapse has [a nifty feature](https://github.com/matrix-org/synapse/blob/master/docs/ACME.md) where it will retrieve Let's Encrypt certificates for federation purposes on first start, and continue to renew them as the homeserver continuously runs. This makes setting up valid certifications on federation simple, and would be a nice feature for Dendrite to have as well.

**Comment by ptman** [comment]
Synapse ACME support was removed. Caddy can easily front dendrite and get certs automatically. But it's also quite easy to get with e.g. https://github.com/caddyserver/certmagic

**Comment by anoadragon453** [comment]
Synapse's ACME support was removed due to no upstream library being available to support it. It's possible that support would have continued in Synapse otherwise.

**Comment by ptman** [comment]
Sure, I should've mentioned that. But there are libraries for golang.

**Comment by tombh** [comment]
I got auto SSL certs working with Caddy. Really quite straightforward once Caddy itself is set up. Then the Dendrite config in `Caddyfile` is just something like:
```
https://example.com:8448 {
  # No need to run Dendrite with SSL options, Caddy will automatically manage SSL
  reverse_proxy localhost:8008
}
```

**Comment by kegsay** [comment]
We don't have the bandwidth to add or maintain this.
