### ISSUE TITLE
Create constants for membership types in common

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#765]
There's lots of uses of `"join"`, `"leave"`, `"ban"` etc all over the codebase. It'd be a pain and kind of scary to change if `"leave"` were changed to `"part"` for instance.

We should consolidate these into constants in `common/` somewhere.

**Comment by Cnly** [comment]
We should just https://github.com/matrix-org/gomatrixserverlib/issues/97.

**Comment by Cnly** [comment]
Closed by https://github.com/matrix-org/gomatrixserverlib/pull/136.
