### ISSUE TITLE
Dendrite shouldn't try to unmarshal the request body for /leave

### ISSUE THREAD

**Issue by Cnly** [matrix-org/dendrite#767]
[`/rooms/:roomID/leave`](https://matrix.org/docs/spec/client_server/r0.5.0#post-matrix-client-r0-rooms-roomid-leave) accepts an empty request body, but Dendrite [tries](https://github.com/matrix-org/dendrite/blob/d21a2fb152143b2ce7600213abe18013519ccedf/clientapi/routing/membership.go#L49) to unmarshal it anyway.

**Comment by yozamacs** [comment]
I would like to work on this....would it be okay to start with adding a basic test for that case? I see there aren't many tests in that directory

**Comment by Cnly** [comment]
@yozamacs Sure, you can take it, and feel free to help add more tests. Currently we use [SyTest](https://github.com/matrix-org/sytest) to test Dendrite as a whole, but finer, language-specific tests are surely good to have! You can also join us in [#dendrite-dev:matrix.org](https://matrix.to/#/#dendrite-dev:matrix.org) if you want to discuss or ask more.

**Comment by yozamacs** [comment]
I did some work on this in https://github.com/matrix-org/dendrite/pull/790. Let me know if that was the direction you wanted to go in

**Comment by anoadragon453** [comment]
@babolivier and I are arguing over what's considered spec compliant here. Whether Unmarshalling even if there's an empty body is spec compliant or not. We'll get back to you.

**Comment by yozamacs** [comment]
great, thanks!

**Comment by anoadragon453** [comment]
So here we are getting back to you :)

Neither the Matrix Spec nor HTTP define whether a `POST` request need contain a body with content. We're going to be opinionated an require this. Therefore the rule should be:

if the content is `nil`, return a `400 M_NOT_JSON`, otherwise attempt to unmarshal.

**Comment by yozamacs** [comment]
@anoadragon453 I'll get on it, thanks!!

**Comment by Kegsay** [comment]
> if the content is nil, return a 400 M_NOT_JSON, otherwise attempt to unmarshal.

What does this even mean? A literal body with the text `null` or `nil`? Because `req.Body` will always be defined even if it's empty.

**Comment by Kegsay** [comment]
https://github.com/matrix-org/dendrite/pull/839#issuecomment-632027384
