### ISSUE TITLE
S3 for mediaapi

### ISSUE THREAD

**Issue by samlabs821** [matrix-org/dendrite#775]
I was looking for code how dendrite store files, mediaApi to be precise. Is it possible to add some kind of S3 api instead of storing files locally? Is there any status or plans for adding this option in future?

**Comment by anoadragon453** [comment]
Not currently any plans, but certainly something we'd consider for the future.

It's worth noting that https://github.com/turt2live/matrix-media-repo/ can be combined with dendrite and do this today though.

**Comment by HelderFSFerreira** [comment]
Can I start working on this or it will be offloaded?

**Comment by Kegsay** [comment]
No plans to add S3 support.
