### ISSUE TITLE
Docker image naming convention

### ISSUE THREAD

**Issue by feffes** [matrix-org/dendrite#806]
I couldn't find this anywhere, so I thought we might as well discuss it here.

# What naming conventions should the docker images use?
Some options:
* matrixdotorg/dendrite-\<service-name\>:\<tag\>
* matrixdotorg/dendrite:\<service-name\>-\<tag\>
* dendrite/\<service-name\>:\<tag\>

**Comment by anoadragon453** [comment]
Hm, my guess would be `matrixdotorg/dendrite-<service-name>:<tag>`, and then just `matrixdotorg/dendrite:<tag>` for the monolith, but there might be other conventions out there.

@hawkowl, do you have any input here?

**Comment by Maescool** [comment]
What commonly is done on docker hub (what I see) 
is `matrixdotorg/dendrite:<service-name>-<tag>`
The reasoning is that then all the information and things are in one place.
and in case of `:latest` we could put the monolith as well as for `:monolith-latest`

So that gets my vote.

**Comment by Kegsay** [comment]
Let's keep it at `matrixdotorg/dendrite-<service-name>:<tag>` please. The service is not a version or variant or encapsulating OS information, it's a completely different binary. E.g
```
matrixdotorg/dendrite-monolith:1.2.3-alpine
matrixdotorg/dendrite-monolith:1.2
matrixdotorg/dendrite-roomserver:1.9.3
```

**Comment by Kegsay** [comment]
We ended up with `matrixdotorg/dendrite:<service-name>-<tag>` e.g:
 - `matrixdotorg/dendrite:clientapi`
 - `matrixdotorg/dendrite:monolith`
