### ISSUE TITLE
Update the sarama lib to be compatible with the latest kafka

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/dendrite#815]
Sarama, the Kafka library for go, will need an update as the current version we're using does not work with the latest Kafka version.

Naffka's sarama lib apparently also needs to be updated.

This may also be a good time to see what their dependencies need updating as we haven't done so for so long.

**Comment by Kegsay** [comment]
What version was the breaking change? i.e. what is the max version Dendrite supports?

**Comment by neilalexander** [comment]
This was done by #856.
