### ISSUE TITLE
Use http.Client instead of http.DefaultClient

### ISSUE THREAD

**Issue by S7evinK** [matrix-org/dendrite#820]
Currently there are several places (eg [query.go](https://github.com/matrix-org/dendrite/blob/5eb63f1d1eafae0111d46def5cf5bf431d2e8169/federationsender/api/query.go#L64)) where http.DefaultClient is used, which doesn't come with a timeout. This could cause unwanted locks.

**Comment by frzifus** [comment]
Oh, u're right. We should make the timeout configurable via a flag?
```shell
roomserver/api/alias.go:// If httpClient is nil then it uses the http.DefaultClient
roomserver/api/alias.go:		httpClient = http.DefaultClient
roomserver/api/query.go:// If httpClient is nil then it uses the http.DefaultClient
roomserver/api/query.go:		httpClient = http.DefaultClient
roomserver/api/input.go:// If httpClient is nil then it uses the http.DefaultClient
roomserver/api/input.go:		httpClient = http.DefaultClient
federationsender/api/query.go:// If httpClient is nil then it uses the http.DefaultClient
federationsender/api/query.go:		httpClient = http.DefaultClient
appservice/api/query.go:// If httpClient is nil then it uses http.DefaultClient
appservice/api/query.go:		httpClient = http.DefaultClient
clientapi/threepid/invites.go:	resp, err := http.DefaultClient.Do(req.WithContext(ctx))
clientapi/threepid/invites.go:	resp, err := http.DefaultClient.Do(req.WithContext(ctx))
clientapi/threepid/threepid.go:	resp, err := http.DefaultClient.Do(req.WithContext(ctx))
typingserver/api/input.go:		httpClient = http.DefaultClient
```

**Comment by S7evinK** [comment]
Either a flag or a config entry, not sure what's the better solution to this.
A flag would require a new parameter to all functions using the default client, while a config entry is already passed to the functions.

Creating a new httpClient and passing it to the functions is, in my opinion, the best idea. 
Instead of passing nil, we would pass the newly created httpClient (with timeout):
https://github.com/matrix-org/dendrite/blob/145921f2071660af7d8e1ea2ea015949a0b03c59/common/basecomponent/base.go#L88-L90 (among others)

**Comment by frzifus** [comment]
uff. y, sounds good :+1:

**Comment by frzifus** [comment]
couldn't really sleep. So I added a proposal.
