### ISSUE TITLE
Don't overwrite global err before return

### ISSUE THREAD

**Issue by APwhitehat** [matrix-org/dendrite#846]
https://github.com/matrix-org/dendrite/blob/74827428bd3e11faab65f12204449c1b9469b0ae/mediaapi/fileutils/fileutils.go#L115

I realised that if we change the value of `err` in a defer statement, we are effectively overwriting the result of `tmpFile.Close()` to `err` which could be non-nil. This behaviour is triggered only for named return values.

> For instance, if the deferred function is a function literal and the surrounding function has named result parameters that are in scope within the literal, the deferred function may access and modify the result parameters before they are returned. If the deferred function has any return values, they are discarded when the function completes.

ref: https://golang.org/ref/spec#Defer_statements

Fix for this issue should also look for any other instances of this issue around the codebase.
e.g. 
https://github.com/matrix-org/dendrite/blob/9a56cf8439304540d0cdae18b30df82962c065cb/common/test/config.go#L145-L148

**Comment by prateek2211** [comment]
@APwhitehat  would `e:=tempfile.close(); if err==nil{ err=e }` go well?

**Comment by frzifus** [comment]
here it depends on which golang version we want to remain compatible with. Since version 1.13 we could wrap the err.
SEE: https://blog.golang.org/go1.13-errors

in another case we could also combine both errors in one message using `fmt`. Like you said before, only if an error occurs.
https://golang.org/pkg/fmt/#Errorf

**Comment by neilalexander** [comment]
As an FYI, we are now targeting only Go 1.13 or later therefore we can use the 1.13 error wrapping.

**Comment by DantrazTrev** [comment]
Can I work on this issue?

**Comment by oz** [comment]
@neilalexander you can't combine two unrelated errors with the `%w` of `Errorf` though, or can you?

Uber's [multierr](https://godoc.org/go.uber.org/multierr) could make sense here ; the simplest I could come up to avoid losing an error is a little verbose (even for Go)...

```go
defer (func() {
	closeError := tmpFile.Close()
	if err == nil {
		err = closeError
		return
	}
	if closeError == nil {
		return
	}
	err = fmt.Errorf("%w\n%s", err, closeError)
})()
```

... times all the similar defers in the code.

**Comment by oliverpool** [comment]
Usually one only cares about the first error.

A possible solution would be a helper function:
```go
func checkErr(err *error, fn func() error) {
	if e := fn(); e != nil && *err == nil {
		*err = e
	}
}
```

Usage:
```go
defer checkErr(&err, tmpFile.Close)
```

Playground: https://play.golang.org/p/MB4mIgfoXP8
