### ISSUE TITLE
Don't allow users to update m.push_rules type data through /account_data/<type> api

### ISSUE THREAD

**Issue by prateek2211** [matrix-org/dendrite#887]

**Comment by Kegsay** [comment]
Link to relevant spec/synapse behaviour?

**Comment by prateek2211** [comment]
The content for m.push_rule event is stored in account data in dendrite. There's a seperate API for push rules. Thus we might not want to change its content through account_data API.
Synapse does not give push rules content through account data nor does it allows its modification through it
