### ISSUE TITLE
General arch: data propagation

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/dendrite#893]
Draw up the arrows for topic consumer/producers AND internal APIs.
 - Do they make sense? 
 - Can we cut them down anywhere? 
 - Then write it up with justifications for each arrow.

**Comment by gedw99** [comment]
The implementation uses Kafka it seems.

I would be interested in adding. NATS / liftbridge solution as well. So 100% golang.

**Comment by Kegsay** [comment]
We already use https://github.com/matrix-org/naffka for when we run in monolith mode, which is 100% golang. That's not the point of this issue.
