### ISSUE TITLE
Remove pointless interfaces in roomserver

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/dendrite#894]
We have lots of interfaces in roomserver. If there is only 1 concrete impl, then we should not have an interface. If there are >1 impl, then we should.

**Comment by prateek2211** [comment]
@Kegsay The only interface that has one implementation is https://github.com/matrix-org/dendrite/blob/c2bd0b97b34c9040325bf31c5c4a2a06579239d9/roomserver/state/state.go#L48

But I guess in future if we have higher version state resolution algos, it will have more implementations.
So, probably there's no need to remove interface rn.

**Comment by Kegsay** [comment]
Not sure how you checked this, but off the top of my head, room server has:
 - `RoomserverAliasAPI` with the only concrete one of `httpRoomserverAliasAPI`
 - `RoomserverInputAPI` with the only concrete one of `httpRoomserverInputAPI`
 - etc...

**Comment by prateek2211** [comment]
According to me ,another implementation of `RoomserverAliasAPI` is https://github.com/matrix-org/dendrite/blob/c019ad708669a4c269072bea933f0a520a78ca7c/roomserver/alias/alias.go#L56
For `RoomserverInputAPI`, it is https://github.com/matrix-org/dendrite/blob/ec38783192dd551718902719c8446c6cc3942dfa/roomserver/input/input.go#L31

Am I doing something wrong in here?

**Comment by Kegsay** [comment]
Ahh, no I don't think you are. I'll take over this issue for now, as clearly I'm not seeing something. Thanks for pointing this out!
