### ISSUE TITLE
Add a Key Server

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/dendrite#895]
Motivation: We have multiple microservices touching the same database (keydb), creating an implicit dependency which breaks the isolation that we have with microservices.

We should have a Key Server to store keys for servers:
 - Allows us to have internal APIs rather than lots of components all opening database connections to the keydb directly
 - Allows us to have a kafka topic to notify key changes, expiries etc
 - Let's keep E2EE device keys out of this though because we will probably want to implement E2EE stuff as a separate server

**Comment by prateek2211** [comment]
I'm up for it

**Comment by Kegsay** [comment]
#1032 added a stub for this.
