### ISSUE TITLE
Use %w everywhere

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/dendrite#896]
Using `%w` will be a good start.

**Comment by dotwaffle** [comment]
By `errors.Wrap` I assume you mean using `github.com/pkg/errors` and the `Wrap()` method there? Since Go 1.13, the accepted way of wrapping errors is to use `fmt.Printf("something: %w", err)` as shown on the [Golang blog](https://blog.golang.org/go1.13-errors).

**Comment by Kegsay** [comment]
Sorry, I actually mean `%w` - will update issue.

**Comment by abbyck** [comment]
There are some instances of using %q as a format verb.

for eg: in https://github.com/matrix-org/dendrite/blob/master/mediaapi/fileutils/fileutils.go#L52

`if err != nil {
		return "", fmt.Errorf("Unable to construct filePath: %q", err)
	}
`
I suppose quoted errors are for a purpose. So, I think we should not need to update that to this new verb?

**Comment by Kegsay** [comment]
Use `%w` in all cases where the param is an `error` type please, including that line.

**Comment by abbyck** [comment]
Updated all cases where the param is of type error.
