### ISSUE TITLE
Refactor directory structure

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/dendrite#897]
Top level folders should be:
 - Services/components themselves
 - An "internal" folder for all of the other mess e.g common, which should be broken up further.
 - A "docs" folder that contains design, install, wiring, P2P
 - A "build" folder that contains "scripts", "docker" and other things

Remove `/hooks`: We cannot rely on outside contributors running pre-commit hooks, and we have CI to enforce stuff so let’s just use it.

Not a good first issue because it requires all contributors to be in lockstep or else we risk conflicts.

**Comment by Kegsay** [comment]
Once I've merged in as many outstanding PRs as possible I'll go ahead and do this. cc @neilalexander

**Comment by neilalexander** [comment]
We may also need to make some tweaks in the pipelines.

**Comment by Kegsay** [comment]
Right, I feel we're basically ready to do this. Most PRs outstanding are small tweaks. We've already started doing some of this. I'll sync with you @neilalexander then make the changes, which are:
 - An "internal" folder for all of the other mess e.g common, which should be broken up further.
 - A "build" folder that contains "scripts", "docker" and other things.
