### ISSUE TITLE
Client API: mutex on (user_id, room_id)

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/dendrite#903]
We should be able to make some guarantees about message ordering from a single client, insofar that if you send 1,2,3,4,5 it should be in the DAG as 1,2,3,4,5 without forks *created by your own messages*. We can do this by locking for a given room/user tuple, which assumes we don't run multiple client APIs which aren't sticky on the user.

This may be a cause of SyTest flakiness, as it rapidly sends events.

**Comment by prateek2211** [comment]
I am not clear about what issues says, but as far as I understood, there shouldn't be race between goroutines sending events to roomserver . So for that wouldn't adding lock and unlock inside send messages routines work ?

**Comment by anandv96** [comment]
Hello, I would like to work on this issue. I'm also unsure of what exactly needs to be done. I understand that with messages being sent very rapidly, there is a possibility that a newer message would be entered into the room than an older one.

Like @prateek2211 mentioned, shouldn't this be addressed at the place where the clientAPI sends the messages to the roomserver? (maybe in clientapi/producers/roomserver.go?)

**Comment by Kegsay** [comment]
Yup

**Comment by Kegsay** [comment]
Related: https://github.com/matrix-org/dendrite/issues/547 which has a mutex per room on the roomserver.
