### ISSUE TITLE
MediaAPI: Handle allow_remote query param in download endpoint

### ISSUE THREAD

**Issue by prateek2211** [matrix-org/dendrite#935]
Add support for `allow_remote` in [GET /_matrix/media/r0/download/{serverName}/{mediaId}](https://matrix.org/docs/spec/client_server/r0.5.0#id435)

**Comment by behouba** [comment]
Correct me if I am wrong @prateek2211  but this seems to be already added. The code bellow is from `makeDownloadAPI` function in `routing` package of `mediaapi`
```
// For the purposes of loop avoidance, we will return a 404 if allow_remote is set to
// false in the query string and the target server name isn't our own.
// https://github.com/matrix-org/matrix-doc/pull/1265
if allowRemote := req.URL.Query().Get("allow_remote"); strings.ToLower(allowRemote) == "false" {
	if serverName != cfg.Matrix.ServerName {
		w.WriteHeader(http.StatusNotFound)
		return
	}
}
```

**Comment by S7evinK** [comment]
As mentioned, already implemented.
