### ISSUE TITLE
MediaAPI: Temp files not deleted on error

### ISSUE THREAD

**Issue by prateek2211** [matrix-org/dendrite#944]
Even the function is called to remove temp file https://github.com/matrix-org/dendrite/blob/05e1ae8745725245ee3b85a588000b0d26bae96c/mediaapi/routing/upload.go#L117

but `tmpDir` is empty since this line is never reached
https://github.com/matrix-org/dendrite/blob/05e1ae8745725245ee3b85a588000b0d26bae96c/mediaapi/fileutils/fileutils.go#L136

**Comment by prateek2211** [comment]
@Kegsay On discovering the error, we don't misuse `path`. So how about replacing `tmpDir` with `path` here:
https://github.com/matrix-org/dendrite/blob/05e1ae8745725245ee3b85a588000b0d26bae96c/mediaapi/fileutils/fileutils.go#L111

**Comment by Kegsay** [comment]
Both the current impl (if it cleaned up the dir) and the proposed impl are valid, however unfortunately the function level docs for `WriteTempFile` are not detailed enough to state what the intended behaviour is in the case where `err` is returned.

Given `:117`, it seems to suggest that "if there was an error, you should still clean up the tmp directory" was the intended behaviour, but as you point out it doesn't work. I would rather change the contract of this function to be "if there was an error, you don't need to do anything" as making it the caller's responsibility to clean up the innards of `WriteTempFile` feels like a bad API shape.

**Comment by Kegsay** [comment]
https://github.com/matrix-org/dendrite/pull/1343
