### ISSUE TITLE
Caching needed around room version queries

### ISSUE THREAD

**Issue by neilalexander** [matrix-org/dendrite#946]
Currently there are a fair few places where we perform a `QueryRoomVersionForRoom` a number of times (e.g. when handling incoming PDUs) and we don't cache the results even temporarily. This means that handling 6 events in a transaction for one room still hits the query API 6 times. It was decided not to cache prematurely but this is a prime candidate of somewhere it would be good to do so.

We may also want to explore being able to use a shared cache in monolith mode for this, since room versions are something we hit a lot across different components.

**Comment by Kegsay** [comment]
This is done now right?

**Comment by neilalexander** [comment]
Yep, done by #976.
