### ISSUE TITLE
Flakey: FAILURE Test #296: /joined_rooms returns only joined rooms

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/dendrite#969]
This endpoint is implemented in clientapi but entries are only removed when receiving messages from the roomserver. The perl test just does `Promise.all(invite,join,leave)` on 3 rooms then immediately hits `/joined_rooms` so sometimes that isn't enough time for the leave to go clientapi -> roomserver -> clientapi.

**Comment by suvidsahay** [comment]
The reason for the failure provided by SyTest was `Timed out waiting for test at ./run-tests.pl line 745.`.
So increasing the timeout did the job for me and the test passed. 
So will increasing the timeout suffice for this issue?

**Comment by neilalexander** [comment]
Out of curiosity, what did you increase the timeout to?

**Comment by suvidsahay** [comment]
Although I don't know what was the significance of `$loop->delay_future( after => $test->timeout // 10 )`, I changed it to `after => 60`.
So yeah I increased the timeout to 60 seconds.

**Comment by Kegsay** [comment]
#1099 to track.
